# Connect Git with  Colab

In [1]:
# --- always get latest repo state in Colab ---
import os, sys, subprocess

REPO_URL  = "https://github.com/Wmeesena/Safe_Start.git"
REPO_ROOT = "/content/Safe_Start"     # repo root
WORKDIR   = os.path.join(REPO_ROOT, "MAGIC")
BRANCH    = "main"

def run(cmd):
    print("$", " ".join(cmd))
    subprocess.run(cmd, check=True)

if not os.path.isdir(REPO_ROOT):
    run(["git", "clone", "--depth", "1", "--branch", BRANCH, REPO_URL, REPO_ROOT])
else:
    run(["git", "-C", REPO_ROOT, "fetch", "origin"])
    run(["git", "-C", REPO_ROOT, "checkout", BRANCH])
    run(["git", "-C", REPO_ROOT, "reset", "--hard", f"origin/{BRANCH}"])


# Set working dir and import path
os.chdir(WORKDIR if os.path.isdir(WORKDIR) else REPO_ROOT)
if REPO_ROOT not in sys.path:
    sys.path.append(REPO_ROOT)

print("CWD:", os.getcwd())
!git -C {REPO_ROOT} rev-parse --abbrev-ref HEAD
!git -C {REPO_ROOT} rev-parse HEAD

# installs
%pip install -q ucimlrepo

$ git clone --depth 1 --branch main https://github.com/Wmeesena/Safe_Start.git /content/Safe_Start
CWD: /content/Safe_Start/MAGIC
main
ea7685864f7b73dfc4fbda4d45c37b6b2ee1da33

# Setup

In [11]:
from ucimlrepo import fetch_ucirepo
import pandas as pd
import numpy as np
import torch
from src.models.mlp import MLP
import torch.nn as nn
import torch.optim as optim
from pprint import pprint
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier, export_text
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from src.train import pretrain,  joint_train, train_all, fit_dt, _rare_event_margin_binary
from src.eval import evaluate_avg_accuracy, evaluate_robust, eval_one, eval_all, print_last_bias_mlp
from src.utils import pct, pct_ci
from src.plots import plot_loss_multi, plot_all_loss
from src.data import load_magic_data

# %load_ext autoreload
# %autoreload 2

# Data

In [ ]:
# Hyperparameters for checking on local
SIGMA = 10.0
SAMPLES_EVAL = 1
SAMPLES_TRAIN = 1
GAMMA = 1000.
NUM_EPOCHS = 1
NUM_EPOCHS_PRE = 1
SAFE_BIAS = 1.0

In [3]:
# Hyperparameters for running on colab
SIGMA = 2.
SAMPLES_EVAL = 500000
SAMPLES_TRAIN = 100000
GAMMA = 10000.
NUM_EPOCHS = 100
NUM_EPOCHS_PRE = 400
SAFE_BIAS = 1.0
BATCH_SIZE = 1024

In [4]:
X_train, y_train, X_test, y_test = load_magic_data()

In [5]:
unique, counts = np.unique(y_train, return_counts=True)
print("Train class balance:", dict(zip(unique, counts)))
unique, counts = np.unique(y_test, return_counts=True)
print("Test  class balance:", dict(zip(unique, counts)))

Train class balance: {np.float32(0.0): np.int64(4879), np.float32(1.0): np.int64(9121)}
Test  class balance: {np.float32(0.0): np.int64(1809), np.float32(1.0): np.int64(3211)}

# Pretrain

In [6]:
# init_model = MLP(input_size=X_train.shape[1]).to(device)

In [7]:
device = "cuda" if torch.cuda.is_available() else "cpu"
model = MLP(input_size=X_train.shape[1]).to(device)
pre_model = pretrain(X_train,y_train, model, num_epochs=NUM_EPOCHS_PRE)
init_model = MLP(input_size=X_train.shape[1]).to(device)
# pre_model = init_model.to(device)

Epochs:   0%|          | 0/400 [00:00<?, ?it/s]

In [8]:
_ = eval_one(
    pre_model, X_test, y_test,
    sigma=SIGMA, SAMPLES_EVAL=SAMPLES_EVAL,
    J_chunk=5000,        # <= keep m small
    N_chunk=512,      # <= keep B small
    B=300             # <= lighter bootstrap
)

print("--------------")

check_eval = eval_one(
    init_model, X_test, y_test,
    sigma=SIGMA, SAMPLES_EVAL=SAMPLES_EVAL,
    J_chunk=5000,        # <= keep m small
    N_chunk=512,      # <= keep B small
    B=300             # <= lighter bootstrap
)

Accuracy: 85.76%  (CI 95%: [84.76%, 86.70%])
Robust Accuracy: 64.09520%  (CI 95%: [63.67906%, 64.58444%])
Conditional Robust Accuracy: 67.60729%  (CI 95%: [67.20278%, 67.98547%])
--------------
Accuracy: 35.44%  (CI 95%: [34.13%, 36.77%])
Robust Accuracy: 35.51556%  (CI 95%: [34.05934%, 36.66263%])
Conditional Robust Accuracy: 99.54191%  (CI 95%: [99.36518%, 99.70904%])

In [ ]:
check_eval

{'acc': 0.6396414342629482,
 'acc_ci': (0.6262580236311578, 0.6528112846049933),
 'RA': 0.6396414637565613,
 'RA_ci': (0.6284860557768924, 0.6540986055776893),
 'CRA': 1.0,
 'CRA_ci': (1.0, 1.0)}

In [ ]:
print_last_bias_mlp(pre_model)

fc_last.bias shape: (1,)
[0.8822072148323059]

# Check Data Topology: Random Forest

One single split can lead to $73\%$ accuracy.

In [ ]:
# # 1) Decision stump (single split)
# acc1, stump = fit_dt("Decision stump (max_depth=1)",X_train,y_train,X_test,y_test,  max_depth=1)

# # quick confusion matrix for the stump
# cm = confusion_matrix(y_test, stump.predict(X_test))
# print("\nConfusion matrix (stump):")
# pprint(cm)

# Training

In [ ]:
configs = [ ("naive", "sgd") ,("safe", "sgd") ]
# configs = [ ("naive", "sgd") ,("safe", "sgd"), ("safe_neg", "sgd")  ]

results = train_all(X_train, y_train,init_model, 50, GAMMA, SAMPLES_TRAIN, SIGMA, configs = configs , SAFE_BIAS=15.0, lr=1e-4, batch_size = BATCH_SIZE )

Training naive with sgd...

Epochs:   0%|          | 0/50 [00:00<?, ?it/s]

/content/Safe_Start/MAGIC/src/train.py:205: UserWarning: Converting a tensor with requires_grad=True to a scalar may lead to unexpected behavior.
Consider using tensor.detach() first. (Triggered internally at /pytorch/torch/csrc/autograd/generated/python_variable_methods.cpp:836.)
  tot += float(loss)

[epoch 000000001] loss=3.406518391 | avg=2.964139802 | rare=0.000044238
[epoch 000000002] loss=3.779818569 | avg=2.492668101 | rare=0.000128715
[epoch 000000003] loss=6.993132404 | avg=6.357631070 | rare=0.000063550
[epoch 000000004] loss=6.662218128 | avg=6.662218128 | rare=0.000000000
[epoch 000000005] loss=5.642273630 | avg=5.642273630 | rare=0.000000000
[epoch 000000006] loss=4.812971967 | avg=4.809049674 | rare=0.000000392
[epoch 000000007] loss=4.364204747 | avg=4.355257307 | rare=0.000000895
[epoch 000000008] loss=3.808245642 | avg=3.808245642 | rare=0.000000000
[epoch 000000009] loss=3.177459989 | avg=3.149572543 | rare=0.000002789
[epoch 000000010] loss=2.455324582 | avg=2.203847442 | rare=0.000025148
[epoch 000000011] loss=2.543512080 | avg=1.486042555 | rare=0.000105747
[epoch 000000012] loss=2.054206048 | avg=1.373502289 | rare=0.000068070
[epoch 000000013] loss=1.688348225 | avg=1.288392280 | rare=0.000039996
[epoch 000000014] loss=2.132234871 | avg=0.962539630 | rare=0.000116970
[epoch 000000015] loss=1.551230120 | avg=0.809152271 | rare=0.000074208
[epoch 000000016] loss=3.251170695 | avg=1.226050219 | rare=0.000202512
[epoch 000000017] loss=3.279364833 | avg=1.180497221 | rare=0.000209887
[epoch 000000018] loss=4.974626643 | avg=1.230995012 | rare=0.000374363
[epoch 000000019] loss=3.975944868 | avg=1.448422279 | rare=0.000252752
[epoch 000000020] loss=5.655225822 | avg=1.203657704 | rare=0.000445157
[epoch 000000021] loss=4.574272828 | avg=1.313440715 | rare=0.000326083
[epoch 000000022] loss=5.792628365 | avg=1.098708766 | rare=0.000469392
[epoch 000000023] loss=4.044280784 | avg=0.891547241 | rare=0.000315273
[epoch 000000024] loss=3.113822571 | avg=1.207026558 | rare=0.000190680
[epoch 000000025] loss=4.276949567 | avg=0.757563744 | rare=0.000351939
[epoch 000000026] loss=4.648065652 | avg=0.827298748 | rare=0.000382077
[epoch 000000027] loss=3.950744961 | avg=0.853141516 | rare=0.000309760
[epoch 000000028] loss=2.594386050 | avg=0.678922049 | rare=0.000191546
[epoch 000000029] loss=1.644792531 | avg=0.636276539 | rare=0.000100852
[epoch 000000030] loss=2.721122776 | avg=0.596849527 | rare=0.000212427
[epoch 000000031] loss=1.624607461 | avg=0.928455523 | rare=0.000069615
[epoch 000000032] loss=2.147888609 | avg=0.757916506 | rare=0.000138997
[epoch 000000033] loss=3.392857671 | avg=0.581816971 | rare=0.000281104
[epoch 000000034] loss=2.537696217 | avg=0.551957616 | rare=0.000198574
[epoch 000000035] loss=1.848499281 | avg=0.550037301 | rare=0.000129846
[epoch 000000036] loss=1.921847982 | avg=0.535943942 | rare=0.000138590
[epoch 000000037] loss=1.823309830 | avg=0.526739887 | rare=0.000129657
[epoch 000000038] loss=1.608047528 | avg=0.532409097 | rare=0.000107564
[epoch 000000039] loss=1.443588874 | avg=0.536341599 | rare=0.000090725
[epoch 000000040] loss=1.399424106 | avg=0.533636363 | rare=0.000086579
[epoch 000000041] loss=1.683855764 | avg=0.525772325 | rare=0.000115808
[epoch 000000042] loss=1.629454775 | avg=0.535568127 | rare=0.000109389
[epoch 000000043] loss=1.489941512 | avg=0.517652226 | rare=0.000097229
[epoch 000000044] loss=1.808141308 | avg=0.553856822 | rare=0.000125428
[epoch 000000045] loss=1.426601274 | avg=0.517723107 | rare=0.000090888
[epoch 000000046] loss=1.459336715 | avg=0.520520412 | rare=0.000093882
[epoch 000000047] loss=1.420286127 | avg=0.514374418 | rare=0.000090591
[epoch 000000048] loss=1.003558780 | avg=0.521230206 | rare=0.000048233
[epoch 000000049] loss=1.100458831 | avg=0.521493069 | rare=0.000057897
[epoch 000000050] loss=1.367876849 | avg=0.536543050 | rare=0.000083133

Training safe with sgd...

Epochs:   0%|          | 0/50 [00:00<?, ?it/s]

[epoch 000000001] loss=4.124058196 | avg=4.041633095 | rare=0.000008243
[epoch 000000002] loss=4.011532954 | avg=3.907372952 | rare=0.000010416
[epoch 000000003] loss=3.992051448 | avg=3.631528582 | rare=0.000036052
[epoch 000000004] loss=3.820091554 | avg=3.556080750 | rare=0.000026401
[epoch 000000005] loss=3.982036574 | avg=3.921862585 | rare=0.000006017
[epoch 000000006] loss=3.290013824 | avg=3.080773405 | rare=0.000020924
[epoch 000000007] loss=3.438288331 | avg=3.170738459 | rare=0.000026755
[epoch 000000008] loss=4.906540539 | avg=1.825292681 | rare=0.000308125
[epoch 000000009] loss=5.070024763 | avg=4.971174785 | rare=0.000009885
[epoch 000000010] loss=5.892185960 | avg=3.583717312 | rare=0.000230847
[epoch 000000011] loss=8.932778597 | avg=3.166949630 | rare=0.000576583
[epoch 000000012] loss=5.991465364 | avg=3.009144051 | rare=0.000298232
[epoch 000000013] loss=6.877034443 | avg=3.783792377 | rare=0.000309324
[epoch 000000014] loss=9.087747744 | avg=3.796126332 | rare=0.000529162
[epoch 000000015] loss=11.367262040 | avg=2.731126257 | rare=0.000863614
[epoch 000000016] loss=7.436792816 | avg=3.377877065 | rare=0.000405892
[epoch 000000017] loss=13.517478739 | avg=3.408295461 | rare=0.001010918
[epoch 000000018] loss=13.491332838 | avg=3.400846907 | rare=0.001009049
[epoch 000000019] loss=15.479833262 | avg=3.621288163 | rare=0.001185854
[epoch 000000020] loss=9.536645447 | avg=2.995986479 | rare=0.000654066
[epoch 000000021] loss=5.334926179 | avg=2.938010148 | rare=0.000239692
[epoch 000000022] loss=10.603024636 | avg=2.829069972 | rare=0.000777395
[epoch 000000023] loss=5.593237298 | avg=3.313935569 | rare=0.000227930
[epoch 000000024] loss=9.593264427 | avg=2.725016696 | rare=0.000686825
[epoch 000000025] loss=4.468393905 | avg=3.106447015 | rare=0.000136195
[epoch 000000026] loss=7.208192144 | avg=2.609605823 | rare=0.000459859
[epoch 000000027] loss=9.510125603 | avg=2.686501333 | rare=0.000682362
[epoch 000000028] loss=8.381843533 | avg=3.595830441 | rare=0.000478601
[epoch 000000029] loss=9.396144424 | avg=2.861018947 | rare=0.000653513
[epoch 000000030] loss=8.059159023 | avg=2.636708626 | rare=0.000542245
[epoch 000000031] loss=7.362619690 | avg=3.289177792 | rare=0.000407344
[epoch 000000032] loss=12.287643211 | avg=2.358913600 | rare=0.000992873
[epoch 000000033] loss=13.226529070 | avg=3.934467614 | rare=0.000929206
[epoch 000000034] loss=17.425079107 | avg=3.190936616 | rare=0.001423414
[epoch 000000035] loss=10.849970256 | avg=3.466817941 | rare=0.000738315
[epoch 000000036] loss=9.277413028 | avg=3.115443213 | rare=0.000616197
[epoch 000000037] loss=14.511671952 | avg=2.596311705 | rare=0.001191536
[epoch 000000038] loss=20.205161231 | avg=2.363768203 | rare=0.001784139
[epoch 000000039] loss=5.187943033 | avg=3.553690451 | rare=0.000163425
[epoch 000000040] loss=15.449910947 | avg=3.179584231 | rare=0.001227033
[epoch 000000041] loss=9.315676757 | avg=2.369588554 | rare=0.000694609
[epoch 000000042] loss=10.494576437 | avg=2.182225270 | rare=0.000831235
[epoch 000000043] loss=11.606570039 | avg=3.060677239 | rare=0.000854589
[epoch 000000044] loss=17.855447258 | avg=3.742501514 | rare=0.001411295
[epoch 000000045] loss=11.471470049 | avg=4.889677933 | rare=0.000658179
[epoch 000000046] loss=6.115054812 | avg=4.501651611 | rare=0.000161340
[epoch 000000047] loss=27.833475556 | avg=3.670925975 | rare=0.002416255
[epoch 000000048] loss=7.092325517 | avg=6.695075580 | rare=0.000039725
[epoch 000000049] loss=7.378664460 | avg=5.984855209 | rare=0.000139381
[epoch 000000050] loss=16.463508947 | avg=4.811421309 | rare=0.001165209

In [ ]:
configs = [ ("safe_neg", "sgd")  ]
# configs = [ ("naive", "sgd") ,("safe", "sgd"), ("safe_neg", "sgd")  ]

results = train_all(X_train, y_train,pre_model, 50, GAMMA, SAMPLES_TRAIN, SIGMA, configs = configs , SAFE_BIAS=5.0, lr=1e-7, batch_size = BATCH_SIZE )

In [ ]:
NUM_EPOCHS = 100
SAMPLES_EVAL = 500000

lrs = [1e-1, 1e-2, 1e-3,1e-4, 1e-5, 1e-6]
configs = [ ("naive", "sgd") ,("safe", "sgd")  ]
final_results = {}
for lr in lrs:
    print(f"#################lr: {lr}#############################")
    configs_result = {}
    # result_init = train_all(X_train, y_train,init_model, NUM_EPOCHS, GAMMA, SAMPLES_TRAIN, SIGMA, configs = [ ("naive", "sgd") ] , SAFE_BIAS=15.0, lr=lr, batch_size = BATCH_SIZE )
    # configs_result[("init_naive", "sgd")] = eval_one(
    #                                       result_init[("naive", "sgd")][0], X_test, y_test,
    #                                       sigma=SIGMA, SAMPLES_EVAL=SAMPLES_EVAL,
    #                                       J_chunk=5000,        # <= keep m small
    #                                       N_chunk=512,      # <= keep B small
    #                                       B=300             # <= lighter bootstrap
    #                                   )
    results = train_all(X_train, y_train,pre_model, NUM_EPOCHS, GAMMA, SAMPLES_TRAIN, SIGMA, configs = configs , SAFE_BIAS=15.0, lr=lr, batch_size = BATCH_SIZE )

    for config in configs:
        configs_result[config] = eval_one(
                                          results[config][0], X_test, y_test,
                                          sigma=SIGMA, SAMPLES_EVAL=SAMPLES_EVAL,
                                          J_chunk=5000,        # <= keep m small
                                          N_chunk=512,      # <= keep B small
                                          B=300             # <= lighter bootstrap
                                      )
    final_results[lr] = configs_result

#################lr: 0.1#############################

Training naive with sgd...

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

[epoch 000000001] loss=36697.019252232 | avg=0.263567181 | rare=3.669675503
[epoch 000000002] loss=36609.113560268 | avg=0.264090906 | rare=3.660884976
[epoch 000000003] loss=nan | avg=nan | rare=nan
[epoch 000000004] loss=nan | avg=nan | rare=nan
[epoch 000000005] loss=nan | avg=nan | rare=nan
[epoch 000000006] loss=nan | avg=nan | rare=nan
[epoch 000000007] loss=nan | avg=nan | rare=nan
[epoch 000000008] loss=nan | avg=nan | rare=nan
[epoch 000000009] loss=nan | avg=nan | rare=nan
[epoch 000000010] loss=nan | avg=nan | rare=nan
[epoch 000000011] loss=nan | avg=nan | rare=nan
[epoch 000000012] loss=nan | avg=nan | rare=nan
[epoch 000000013] loss=nan | avg=nan | rare=nan
[epoch 000000014] loss=nan | avg=nan | rare=nan
[epoch 000000015] loss=nan | avg=nan | rare=nan
[epoch 000000016] loss=nan | avg=nan | rare=nan
[epoch 000000017] loss=nan | avg=nan | rare=nan
[epoch 000000018] loss=nan | avg=nan | rare=nan
[epoch 000000019] loss=nan | avg=nan | rare=nan
[epoch 000000020] loss=nan | avg=nan | rare=nan
[epoch 000000021] loss=nan | avg=nan | rare=nan
[epoch 000000022] loss=nan | avg=nan | rare=nan
[epoch 000000023] loss=nan | avg=nan | rare=nan
[epoch 000000024] loss=nan | avg=nan | rare=nan
[epoch 000000025] loss=nan | avg=nan | rare=nan
[epoch 000000026] loss=nan | avg=nan | rare=nan
[epoch 000000027] loss=nan | avg=nan | rare=nan
[epoch 000000028] loss=nan | avg=nan | rare=nan
[epoch 000000029] loss=nan | avg=nan | rare=nan
[epoch 000000030] loss=nan | avg=nan | rare=nan
[epoch 000000031] loss=nan | avg=nan | rare=nan
[epoch 000000032] loss=nan | avg=nan | rare=nan
[epoch 000000033] loss=nan | avg=nan | rare=nan
[epoch 000000034] loss=nan | avg=nan | rare=nan
[epoch 000000035] loss=nan | avg=nan | rare=nan
[epoch 000000036] loss=nan | avg=nan | rare=nan
[epoch 000000037] loss=nan | avg=nan | rare=nan
[epoch 000000038] loss=nan | avg=nan | rare=nan
[epoch 000000039] loss=nan | avg=nan | rare=nan
[epoch 000000040] loss=nan | avg=nan | rare=nan
[epoch 000000041] loss=nan | avg=nan | rare=nan
[epoch 000000042] loss=nan | avg=nan | rare=nan
[epoch 000000043] loss=nan | avg=nan | rare=nan
[epoch 000000044] loss=nan | avg=nan | rare=nan
[epoch 000000045] loss=nan | avg=nan | rare=nan
[epoch 000000046] loss=nan | avg=nan | rare=nan
[epoch 000000047] loss=nan | avg=nan | rare=nan
[epoch 000000048] loss=nan | avg=nan | rare=nan
[epoch 000000049] loss=nan | avg=nan | rare=nan
[epoch 000000050] loss=nan | avg=nan | rare=nan
[epoch 000000051] loss=nan | avg=nan | rare=nan
[epoch 000000052] loss=nan | avg=nan | rare=nan
[epoch 000000053] loss=nan | avg=nan | rare=nan
[epoch 000000054] loss=nan | avg=nan | rare=nan
[epoch 000000055] loss=nan | avg=nan | rare=nan
[epoch 000000056] loss=nan | avg=nan | rare=nan
[epoch 000000057] loss=nan | avg=nan | rare=nan
[epoch 000000058] loss=nan | avg=nan | rare=nan
[epoch 000000059] loss=nan | avg=nan | rare=nan
[epoch 000000060] loss=nan | avg=nan | rare=nan
[epoch 000000061] loss=nan | avg=nan | rare=nan
[epoch 000000062] loss=nan | avg=nan | rare=nan
[epoch 000000063] loss=nan | avg=nan | rare=nan
[epoch 000000064] loss=nan | avg=nan | rare=nan
[epoch 000000065] loss=nan | avg=nan | rare=nan
[epoch 000000066] loss=nan | avg=nan | rare=nan
[epoch 000000067] loss=nan | avg=nan | rare=nan
[epoch 000000068] loss=nan | avg=nan | rare=nan
[epoch 000000069] loss=nan | avg=nan | rare=nan
[epoch 000000070] loss=nan | avg=nan | rare=nan
[epoch 000000071] loss=nan | avg=nan | rare=nan
[epoch 000000072] loss=nan | avg=nan | rare=nan
[epoch 000000073] loss=nan | avg=nan | rare=nan
[epoch 000000074] loss=nan | avg=nan | rare=nan
[epoch 000000075] loss=nan | avg=nan | rare=nan
[epoch 000000076] loss=nan | avg=nan | rare=nan
[epoch 000000077] loss=nan | avg=nan | rare=nan
[epoch 000000078] loss=nan | avg=nan | rare=nan
[epoch 000000079] loss=nan | avg=nan | rare=nan
[epoch 000000080] loss=nan | avg=nan | rare=nan
[epoch 000000081] loss=nan | avg=nan | rare=nan
[epoch 000000082] loss=nan | avg=nan | rare=nan
[epoch 000000083] loss=nan | avg=nan | rare=nan
[epoch 000000084] loss=nan | avg=nan | rare=nan
[epoch 000000085] loss=nan | avg=nan | rare=nan
[epoch 000000086] loss=nan | avg=nan | rare=nan
[epoch 000000087] loss=nan | avg=nan | rare=nan
[epoch 000000088] loss=nan | avg=nan | rare=nan
[epoch 000000089] loss=nan | avg=nan | rare=nan
[epoch 000000090] loss=nan | avg=nan | rare=nan
[epoch 000000091] loss=nan | avg=nan | rare=nan
[epoch 000000092] loss=nan | avg=nan | rare=nan
[epoch 000000093] loss=nan | avg=nan | rare=nan
[epoch 000000094] loss=nan | avg=nan | rare=nan
[epoch 000000095] loss=nan | avg=nan | rare=nan
[epoch 000000096] loss=nan | avg=nan | rare=nan
[epoch 000000097] loss=nan | avg=nan | rare=nan
[epoch 000000098] loss=nan | avg=nan | rare=nan
[epoch 000000099] loss=nan | avg=nan | rare=nan
[epoch 000000100] loss=nan | avg=nan | rare=nan

Training safe with sgd...

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

[epoch 000000001] loss=3860.957676479 | avg=3.283441186 | rare=0.385767424
[epoch 000000002] loss=3857.097726004 | avg=3.295365265 | rare=0.385380238
[epoch 000000003] loss=nan | avg=nan | rare=nan
[epoch 000000004] loss=nan | avg=nan | rare=nan
[epoch 000000005] loss=nan | avg=nan | rare=nan
[epoch 000000006] loss=nan | avg=nan | rare=nan
[epoch 000000007] loss=nan | avg=nan | rare=nan
[epoch 000000008] loss=nan | avg=nan | rare=nan
[epoch 000000009] loss=nan | avg=nan | rare=nan
[epoch 000000010] loss=nan | avg=nan | rare=nan
[epoch 000000011] loss=nan | avg=nan | rare=nan
[epoch 000000012] loss=nan | avg=nan | rare=nan
[epoch 000000013] loss=nan | avg=nan | rare=nan
[epoch 000000014] loss=nan | avg=nan | rare=nan
[epoch 000000015] loss=nan | avg=nan | rare=nan
[epoch 000000016] loss=nan | avg=nan | rare=nan
[epoch 000000017] loss=nan | avg=nan | rare=nan
[epoch 000000018] loss=nan | avg=nan | rare=nan
[epoch 000000019] loss=nan | avg=nan | rare=nan
[epoch 000000020] loss=nan | avg=nan | rare=nan
[epoch 000000021] loss=nan | avg=nan | rare=nan
[epoch 000000022] loss=nan | avg=nan | rare=nan
[epoch 000000023] loss=nan | avg=nan | rare=nan
[epoch 000000024] loss=nan | avg=nan | rare=nan
[epoch 000000025] loss=nan | avg=nan | rare=nan
[epoch 000000026] loss=nan | avg=nan | rare=nan
[epoch 000000027] loss=nan | avg=nan | rare=nan
[epoch 000000028] loss=nan | avg=nan | rare=nan
[epoch 000000029] loss=nan | avg=nan | rare=nan
[epoch 000000030] loss=nan | avg=nan | rare=nan
[epoch 000000031] loss=nan | avg=nan | rare=nan
[epoch 000000032] loss=nan | avg=nan | rare=nan
[epoch 000000033] loss=nan | avg=nan | rare=nan
[epoch 000000034] loss=nan | avg=nan | rare=nan
[epoch 000000035] loss=nan | avg=nan | rare=nan
[epoch 000000036] loss=nan | avg=nan | rare=nan
[epoch 000000037] loss=nan | avg=nan | rare=nan
[epoch 000000038] loss=nan | avg=nan | rare=nan
[epoch 000000039] loss=nan | avg=nan | rare=nan
[epoch 000000040] loss=nan | avg=nan | rare=nan
[epoch 000000041] loss=nan | avg=nan | rare=nan
[epoch 000000042] loss=nan | avg=nan | rare=nan
[epoch 000000043] loss=nan | avg=nan | rare=nan
[epoch 000000044] loss=nan | avg=nan | rare=nan
[epoch 000000045] loss=nan | avg=nan | rare=nan
[epoch 000000046] loss=nan | avg=nan | rare=nan
[epoch 000000047] loss=nan | avg=nan | rare=nan
[epoch 000000048] loss=nan | avg=nan | rare=nan
[epoch 000000049] loss=nan | avg=nan | rare=nan
[epoch 000000050] loss=nan | avg=nan | rare=nan
[epoch 000000051] loss=nan | avg=nan | rare=nan
[epoch 000000052] loss=nan | avg=nan | rare=nan
[epoch 000000053] loss=nan | avg=nan | rare=nan
[epoch 000000054] loss=nan | avg=nan | rare=nan
[epoch 000000055] loss=nan | avg=nan | rare=nan
[epoch 000000056] loss=nan | avg=nan | rare=nan
[epoch 000000057] loss=nan | avg=nan | rare=nan
[epoch 000000058] loss=nan | avg=nan | rare=nan
[epoch 000000059] loss=nan | avg=nan | rare=nan
[epoch 000000060] loss=nan | avg=nan | rare=nan
[epoch 000000061] loss=nan | avg=nan | rare=nan
[epoch 000000062] loss=nan | avg=nan | rare=nan
[epoch 000000063] loss=nan | avg=nan | rare=nan
[epoch 000000064] loss=nan | avg=nan | rare=nan
[epoch 000000065] loss=nan | avg=nan | rare=nan
[epoch 000000066] loss=nan | avg=nan | rare=nan
[epoch 000000067] loss=nan | avg=nan | rare=nan
[epoch 000000068] loss=nan | avg=nan | rare=nan
[epoch 000000069] loss=nan | avg=nan | rare=nan
[epoch 000000070] loss=nan | avg=nan | rare=nan
[epoch 000000071] loss=nan | avg=nan | rare=nan
[epoch 000000072] loss=nan | avg=nan | rare=nan
[epoch 000000073] loss=nan | avg=nan | rare=nan
[epoch 000000074] loss=nan | avg=nan | rare=nan
[epoch 000000075] loss=nan | avg=nan | rare=nan
[epoch 000000076] loss=nan | avg=nan | rare=nan
[epoch 000000077] loss=nan | avg=nan | rare=nan
[epoch 000000078] loss=nan | avg=nan | rare=nan
[epoch 000000079] loss=nan | avg=nan | rare=nan
[epoch 000000080] loss=nan | avg=nan | rare=nan
[epoch 000000081] loss=nan | avg=nan | rare=nan
[epoch 000000082] loss=nan | avg=nan | rare=nan
[epoch 000000083] loss=nan | avg=nan | rare=nan
[epoch 000000084] loss=nan | avg=nan | rare=nan
[epoch 000000085] loss=nan | avg=nan | rare=nan
[epoch 000000086] loss=nan | avg=nan | rare=nan
[epoch 000000087] loss=nan | avg=nan | rare=nan
[epoch 000000088] loss=nan | avg=nan | rare=nan
[epoch 000000089] loss=nan | avg=nan | rare=nan
[epoch 000000090] loss=nan | avg=nan | rare=nan
[epoch 000000091] loss=nan | avg=nan | rare=nan
[epoch 000000092] loss=nan | avg=nan | rare=nan
[epoch 000000093] loss=nan | avg=nan | rare=nan
[epoch 000000094] loss=nan | avg=nan | rare=nan
[epoch 000000095] loss=nan | avg=nan | rare=nan
[epoch 000000096] loss=nan | avg=nan | rare=nan
[epoch 000000097] loss=nan | avg=nan | rare=nan
[epoch 000000098] loss=nan | avg=nan | rare=nan
[epoch 000000099] loss=nan | avg=nan | rare=nan
[epoch 000000100] loss=nan | avg=nan | rare=nan
Accuracy: 63.96%  (CI 95%: [62.63%, 65.28%])
Robust Accuracy: 63.96415%  (CI 95%: [62.84861%, 65.40986%])
Conditional Robust Accuracy: 100.00000%  (CI 95%: [100.00000%, 100.00000%])
Accuracy: 63.96%  (CI 95%: [62.63%, 65.28%])
Robust Accuracy: 63.96415%  (CI 95%: [62.84861%, 65.40986%])
Conditional Robust Accuracy: 100.00000%  (CI 95%: [100.00000%, 100.00000%])
#################lr: 0.01#############################

Training naive with sgd...

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

[epoch 000000001] loss=36697.019252232 | avg=0.263567181 | rare=3.669675503
[epoch 000000002] loss=36609.113560268 | avg=0.264090906 | rare=3.660884976
[epoch 000000003] loss=nan | avg=nan | rare=nan
[epoch 000000004] loss=nan | avg=nan | rare=nan
[epoch 000000005] loss=nan | avg=nan | rare=nan
[epoch 000000006] loss=nan | avg=nan | rare=nan
[epoch 000000007] loss=nan | avg=nan | rare=nan
[epoch 000000008] loss=nan | avg=nan | rare=nan
[epoch 000000009] loss=nan | avg=nan | rare=nan
[epoch 000000010] loss=nan | avg=nan | rare=nan
[epoch 000000011] loss=nan | avg=nan | rare=nan
[epoch 000000012] loss=nan | avg=nan | rare=nan
[epoch 000000013] loss=nan | avg=nan | rare=nan
[epoch 000000014] loss=nan | avg=nan | rare=nan
[epoch 000000015] loss=nan | avg=nan | rare=nan
[epoch 000000016] loss=nan | avg=nan | rare=nan
[epoch 000000017] loss=nan | avg=nan | rare=nan
[epoch 000000018] loss=nan | avg=nan | rare=nan
[epoch 000000019] loss=nan | avg=nan | rare=nan
[epoch 000000020] loss=nan | avg=nan | rare=nan
[epoch 000000021] loss=nan | avg=nan | rare=nan
[epoch 000000022] loss=nan | avg=nan | rare=nan
[epoch 000000023] loss=nan | avg=nan | rare=nan
[epoch 000000024] loss=nan | avg=nan | rare=nan
[epoch 000000025] loss=nan | avg=nan | rare=nan
[epoch 000000026] loss=nan | avg=nan | rare=nan
[epoch 000000027] loss=nan | avg=nan | rare=nan
[epoch 000000028] loss=nan | avg=nan | rare=nan
[epoch 000000029] loss=nan | avg=nan | rare=nan
[epoch 000000030] loss=nan | avg=nan | rare=nan
[epoch 000000031] loss=nan | avg=nan | rare=nan
[epoch 000000032] loss=nan | avg=nan | rare=nan
[epoch 000000033] loss=nan | avg=nan | rare=nan
[epoch 000000034] loss=nan | avg=nan | rare=nan
[epoch 000000035] loss=nan | avg=nan | rare=nan
[epoch 000000036] loss=nan | avg=nan | rare=nan
[epoch 000000037] loss=nan | avg=nan | rare=nan
[epoch 000000038] loss=nan | avg=nan | rare=nan
[epoch 000000039] loss=nan | avg=nan | rare=nan
[epoch 000000040] loss=nan | avg=nan | rare=nan
[epoch 000000041] loss=nan | avg=nan | rare=nan
[epoch 000000042] loss=nan | avg=nan | rare=nan
[epoch 000000043] loss=nan | avg=nan | rare=nan
[epoch 000000044] loss=nan | avg=nan | rare=nan
[epoch 000000045] loss=nan | avg=nan | rare=nan
[epoch 000000046] loss=nan | avg=nan | rare=nan
[epoch 000000047] loss=nan | avg=nan | rare=nan
[epoch 000000048] loss=nan | avg=nan | rare=nan
[epoch 000000049] loss=nan | avg=nan | rare=nan
[epoch 000000050] loss=nan | avg=nan | rare=nan
[epoch 000000051] loss=nan | avg=nan | rare=nan
[epoch 000000052] loss=nan | avg=nan | rare=nan
[epoch 000000053] loss=nan | avg=nan | rare=nan
[epoch 000000054] loss=nan | avg=nan | rare=nan
[epoch 000000055] loss=nan | avg=nan | rare=nan
[epoch 000000056] loss=nan | avg=nan | rare=nan
[epoch 000000057] loss=nan | avg=nan | rare=nan
[epoch 000000058] loss=nan | avg=nan | rare=nan
[epoch 000000059] loss=nan | avg=nan | rare=nan
[epoch 000000060] loss=nan | avg=nan | rare=nan
[epoch 000000061] loss=nan | avg=nan | rare=nan
[epoch 000000062] loss=nan | avg=nan | rare=nan
[epoch 000000063] loss=nan | avg=nan | rare=nan
[epoch 000000064] loss=nan | avg=nan | rare=nan
[epoch 000000065] loss=nan | avg=nan | rare=nan
[epoch 000000066] loss=nan | avg=nan | rare=nan
[epoch 000000067] loss=nan | avg=nan | rare=nan
[epoch 000000068] loss=nan | avg=nan | rare=nan
[epoch 000000069] loss=nan | avg=nan | rare=nan
[epoch 000000070] loss=nan | avg=nan | rare=nan
[epoch 000000071] loss=nan | avg=nan | rare=nan
[epoch 000000072] loss=nan | avg=nan | rare=nan
[epoch 000000073] loss=nan | avg=nan | rare=nan
[epoch 000000074] loss=nan | avg=nan | rare=nan
[epoch 000000075] loss=nan | avg=nan | rare=nan
[epoch 000000076] loss=nan | avg=nan | rare=nan
[epoch 000000077] loss=nan | avg=nan | rare=nan
[epoch 000000078] loss=nan | avg=nan | rare=nan
[epoch 000000079] loss=nan | avg=nan | rare=nan
[epoch 000000080] loss=nan | avg=nan | rare=nan
[epoch 000000081] loss=nan | avg=nan | rare=nan
[epoch 000000082] loss=nan | avg=nan | rare=nan
[epoch 000000083] loss=nan | avg=nan | rare=nan
[epoch 000000084] loss=nan | avg=nan | rare=nan
[epoch 000000085] loss=nan | avg=nan | rare=nan
[epoch 000000086] loss=nan | avg=nan | rare=nan
[epoch 000000087] loss=nan | avg=nan | rare=nan
[epoch 000000088] loss=nan | avg=nan | rare=nan
[epoch 000000089] loss=nan | avg=nan | rare=nan
[epoch 000000090] loss=nan | avg=nan | rare=nan
[epoch 000000091] loss=nan | avg=nan | rare=nan
[epoch 000000092] loss=nan | avg=nan | rare=nan
[epoch 000000093] loss=nan | avg=nan | rare=nan
[epoch 000000094] loss=nan | avg=nan | rare=nan
[epoch 000000095] loss=nan | avg=nan | rare=nan
[epoch 000000096] loss=nan | avg=nan | rare=nan
[epoch 000000097] loss=nan | avg=nan | rare=nan
[epoch 000000098] loss=nan | avg=nan | rare=nan
[epoch 000000099] loss=nan | avg=nan | rare=nan
[epoch 000000100] loss=nan | avg=nan | rare=nan

Training safe with sgd...

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

[epoch 000000001] loss=3860.957676479 | avg=3.283441186 | rare=0.385767424
[epoch 000000002] loss=3857.097726004 | avg=3.295365265 | rare=0.385380238
[epoch 000000003] loss=nan | avg=nan | rare=nan
[epoch 000000004] loss=nan | avg=nan | rare=nan
[epoch 000000005] loss=nan | avg=nan | rare=nan
[epoch 000000006] loss=nan | avg=nan | rare=nan
[epoch 000000007] loss=nan | avg=nan | rare=nan
[epoch 000000008] loss=nan | avg=nan | rare=nan
[epoch 000000009] loss=nan | avg=nan | rare=nan
[epoch 000000010] loss=nan | avg=nan | rare=nan
[epoch 000000011] loss=nan | avg=nan | rare=nan
[epoch 000000012] loss=nan | avg=nan | rare=nan
[epoch 000000013] loss=nan | avg=nan | rare=nan
[epoch 000000014] loss=nan | avg=nan | rare=nan
[epoch 000000015] loss=nan | avg=nan | rare=nan
[epoch 000000016] loss=nan | avg=nan | rare=nan
[epoch 000000017] loss=nan | avg=nan | rare=nan
[epoch 000000018] loss=nan | avg=nan | rare=nan
[epoch 000000019] loss=nan | avg=nan | rare=nan
[epoch 000000020] loss=nan | avg=nan | rare=nan
[epoch 000000021] loss=nan | avg=nan | rare=nan
[epoch 000000022] loss=nan | avg=nan | rare=nan
[epoch 000000023] loss=nan | avg=nan | rare=nan
[epoch 000000024] loss=nan | avg=nan | rare=nan
[epoch 000000025] loss=nan | avg=nan | rare=nan
[epoch 000000026] loss=nan | avg=nan | rare=nan
[epoch 000000027] loss=nan | avg=nan | rare=nan
[epoch 000000028] loss=nan | avg=nan | rare=nan
[epoch 000000029] loss=nan | avg=nan | rare=nan
[epoch 000000030] loss=nan | avg=nan | rare=nan
[epoch 000000031] loss=nan | avg=nan | rare=nan
[epoch 000000032] loss=nan | avg=nan | rare=nan
[epoch 000000033] loss=nan | avg=nan | rare=nan
[epoch 000000034] loss=nan | avg=nan | rare=nan
[epoch 000000035] loss=nan | avg=nan | rare=nan
[epoch 000000036] loss=nan | avg=nan | rare=nan
[epoch 000000037] loss=nan | avg=nan | rare=nan
[epoch 000000038] loss=nan | avg=nan | rare=nan
[epoch 000000039] loss=nan | avg=nan | rare=nan
[epoch 000000040] loss=nan | avg=nan | rare=nan
[epoch 000000041] loss=nan | avg=nan | rare=nan
[epoch 000000042] loss=nan | avg=nan | rare=nan
[epoch 000000043] loss=nan | avg=nan | rare=nan
[epoch 000000044] loss=nan | avg=nan | rare=nan
[epoch 000000045] loss=nan | avg=nan | rare=nan
[epoch 000000046] loss=nan | avg=nan | rare=nan
[epoch 000000047] loss=nan | avg=nan | rare=nan
[epoch 000000048] loss=nan | avg=nan | rare=nan
[epoch 000000049] loss=nan | avg=nan | rare=nan
[epoch 000000050] loss=nan | avg=nan | rare=nan
[epoch 000000051] loss=nan | avg=nan | rare=nan
[epoch 000000052] loss=nan | avg=nan | rare=nan
[epoch 000000053] loss=nan | avg=nan | rare=nan
[epoch 000000054] loss=nan | avg=nan | rare=nan
[epoch 000000055] loss=nan | avg=nan | rare=nan
[epoch 000000056] loss=nan | avg=nan | rare=nan
[epoch 000000057] loss=nan | avg=nan | rare=nan
[epoch 000000058] loss=nan | avg=nan | rare=nan
[epoch 000000059] loss=nan | avg=nan | rare=nan
[epoch 000000060] loss=nan | avg=nan | rare=nan
[epoch 000000061] loss=nan | avg=nan | rare=nan
[epoch 000000062] loss=nan | avg=nan | rare=nan
[epoch 000000063] loss=nan | avg=nan | rare=nan
[epoch 000000064] loss=nan | avg=nan | rare=nan
[epoch 000000065] loss=nan | avg=nan | rare=nan
[epoch 000000066] loss=nan | avg=nan | rare=nan
[epoch 000000067] loss=nan | avg=nan | rare=nan
[epoch 000000068] loss=nan | avg=nan | rare=nan
[epoch 000000069] loss=nan | avg=nan | rare=nan
[epoch 000000070] loss=nan | avg=nan | rare=nan
[epoch 000000071] loss=nan | avg=nan | rare=nan
[epoch 000000072] loss=nan | avg=nan | rare=nan
[epoch 000000073] loss=nan | avg=nan | rare=nan
[epoch 000000074] loss=nan | avg=nan | rare=nan
[epoch 000000075] loss=nan | avg=nan | rare=nan
[epoch 000000076] loss=nan | avg=nan | rare=nan
[epoch 000000077] loss=nan | avg=nan | rare=nan
[epoch 000000078] loss=nan | avg=nan | rare=nan
[epoch 000000079] loss=nan | avg=nan | rare=nan
[epoch 000000080] loss=nan | avg=nan | rare=nan
[epoch 000000081] loss=nan | avg=nan | rare=nan
[epoch 000000082] loss=nan | avg=nan | rare=nan
[epoch 000000083] loss=nan | avg=nan | rare=nan
[epoch 000000084] loss=nan | avg=nan | rare=nan
[epoch 000000085] loss=nan | avg=nan | rare=nan
[epoch 000000086] loss=nan | avg=nan | rare=nan
[epoch 000000087] loss=nan | avg=nan | rare=nan
[epoch 000000088] loss=nan | avg=nan | rare=nan
[epoch 000000089] loss=nan | avg=nan | rare=nan
[epoch 000000090] loss=nan | avg=nan | rare=nan
[epoch 000000091] loss=nan | avg=nan | rare=nan
[epoch 000000092] loss=nan | avg=nan | rare=nan
[epoch 000000093] loss=nan | avg=nan | rare=nan
[epoch 000000094] loss=nan | avg=nan | rare=nan
[epoch 000000095] loss=nan | avg=nan | rare=nan
[epoch 000000096] loss=nan | avg=nan | rare=nan
[epoch 000000097] loss=nan | avg=nan | rare=nan
[epoch 000000098] loss=nan | avg=nan | rare=nan
[epoch 000000099] loss=nan | avg=nan | rare=nan
[epoch 000000100] loss=nan | avg=nan | rare=nan
Accuracy: 63.96%  (CI 95%: [62.63%, 65.28%])
Robust Accuracy: 63.96415%  (CI 95%: [62.84861%, 65.40986%])
Conditional Robust Accuracy: 100.00000%  (CI 95%: [100.00000%, 100.00000%])
Accuracy: 63.96%  (CI 95%: [62.63%, 65.28%])
Robust Accuracy: 63.96415%  (CI 95%: [62.84861%, 65.40986%])
Conditional Robust Accuracy: 100.00000%  (CI 95%: [100.00000%, 100.00000%])
#################lr: 0.001#############################

Training naive with sgd...

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

[epoch 000000001] loss=36697.019252232 | avg=0.263567181 | rare=3.669675503
[epoch 000000002] loss=36609.113560268 | avg=0.264090906 | rare=3.660884976
[epoch 000000003] loss=nan | avg=nan | rare=nan
[epoch 000000004] loss=nan | avg=nan | rare=nan
[epoch 000000005] loss=nan | avg=nan | rare=nan
[epoch 000000006] loss=nan | avg=nan | rare=nan
[epoch 000000007] loss=nan | avg=nan | rare=nan
[epoch 000000008] loss=nan | avg=nan | rare=nan
[epoch 000000009] loss=nan | avg=nan | rare=nan
[epoch 000000010] loss=nan | avg=nan | rare=nan
[epoch 000000011] loss=nan | avg=nan | rare=nan
[epoch 000000012] loss=nan | avg=nan | rare=nan
[epoch 000000013] loss=nan | avg=nan | rare=nan
[epoch 000000014] loss=nan | avg=nan | rare=nan
[epoch 000000015] loss=nan | avg=nan | rare=nan
[epoch 000000016] loss=nan | avg=nan | rare=nan
[epoch 000000017] loss=nan | avg=nan | rare=nan
[epoch 000000018] loss=nan | avg=nan | rare=nan
[epoch 000000019] loss=nan | avg=nan | rare=nan
[epoch 000000020] loss=nan | avg=nan | rare=nan
[epoch 000000021] loss=nan | avg=nan | rare=nan
[epoch 000000022] loss=nan | avg=nan | rare=nan
[epoch 000000023] loss=nan | avg=nan | rare=nan
[epoch 000000024] loss=nan | avg=nan | rare=nan
[epoch 000000025] loss=nan | avg=nan | rare=nan
[epoch 000000026] loss=nan | avg=nan | rare=nan
[epoch 000000027] loss=nan | avg=nan | rare=nan
[epoch 000000028] loss=nan | avg=nan | rare=nan
[epoch 000000029] loss=nan | avg=nan | rare=nan
[epoch 000000030] loss=nan | avg=nan | rare=nan
[epoch 000000031] loss=nan | avg=nan | rare=nan
[epoch 000000032] loss=nan | avg=nan | rare=nan
[epoch 000000033] loss=nan | avg=nan | rare=nan
[epoch 000000034] loss=nan | avg=nan | rare=nan
[epoch 000000035] loss=nan | avg=nan | rare=nan
[epoch 000000036] loss=nan | avg=nan | rare=nan
[epoch 000000037] loss=nan | avg=nan | rare=nan
[epoch 000000038] loss=nan | avg=nan | rare=nan
[epoch 000000039] loss=nan | avg=nan | rare=nan
[epoch 000000040] loss=nan | avg=nan | rare=nan
[epoch 000000041] loss=nan | avg=nan | rare=nan
[epoch 000000042] loss=nan | avg=nan | rare=nan
[epoch 000000043] loss=nan | avg=nan | rare=nan
[epoch 000000044] loss=nan | avg=nan | rare=nan
[epoch 000000045] loss=nan | avg=nan | rare=nan
[epoch 000000046] loss=nan | avg=nan | rare=nan
[epoch 000000047] loss=nan | avg=nan | rare=nan
[epoch 000000048] loss=nan | avg=nan | rare=nan
[epoch 000000049] loss=nan | avg=nan | rare=nan
[epoch 000000050] loss=nan | avg=nan | rare=nan
[epoch 000000051] loss=nan | avg=nan | rare=nan
[epoch 000000052] loss=nan | avg=nan | rare=nan
[epoch 000000053] loss=nan | avg=nan | rare=nan
[epoch 000000054] loss=nan | avg=nan | rare=nan
[epoch 000000055] loss=nan | avg=nan | rare=nan
[epoch 000000056] loss=nan | avg=nan | rare=nan
[epoch 000000057] loss=nan | avg=nan | rare=nan
[epoch 000000058] loss=nan | avg=nan | rare=nan
[epoch 000000059] loss=nan | avg=nan | rare=nan
[epoch 000000060] loss=nan | avg=nan | rare=nan
[epoch 000000061] loss=nan | avg=nan | rare=nan
[epoch 000000062] loss=nan | avg=nan | rare=nan
[epoch 000000063] loss=nan | avg=nan | rare=nan
[epoch 000000064] loss=nan | avg=nan | rare=nan
[epoch 000000065] loss=nan | avg=nan | rare=nan
[epoch 000000066] loss=nan | avg=nan | rare=nan
[epoch 000000067] loss=nan | avg=nan | rare=nan
[epoch 000000068] loss=nan | avg=nan | rare=nan
[epoch 000000069] loss=nan | avg=nan | rare=nan
[epoch 000000070] loss=nan | avg=nan | rare=nan
[epoch 000000071] loss=nan | avg=nan | rare=nan
[epoch 000000072] loss=nan | avg=nan | rare=nan
[epoch 000000073] loss=nan | avg=nan | rare=nan
[epoch 000000074] loss=nan | avg=nan | rare=nan
[epoch 000000075] loss=nan | avg=nan | rare=nan
[epoch 000000076] loss=nan | avg=nan | rare=nan
[epoch 000000077] loss=nan | avg=nan | rare=nan
[epoch 000000078] loss=nan | avg=nan | rare=nan
[epoch 000000079] loss=nan | avg=nan | rare=nan
[epoch 000000080] loss=nan | avg=nan | rare=nan
[epoch 000000081] loss=nan | avg=nan | rare=nan
[epoch 000000082] loss=nan | avg=nan | rare=nan
[epoch 000000083] loss=nan | avg=nan | rare=nan
[epoch 000000084] loss=nan | avg=nan | rare=nan
[epoch 000000085] loss=nan | avg=nan | rare=nan
[epoch 000000086] loss=nan | avg=nan | rare=nan
[epoch 000000087] loss=nan | avg=nan | rare=nan
[epoch 000000088] loss=nan | avg=nan | rare=nan
[epoch 000000089] loss=nan | avg=nan | rare=nan
[epoch 000000090] loss=nan | avg=nan | rare=nan
[epoch 000000091] loss=nan | avg=nan | rare=nan
[epoch 000000092] loss=nan | avg=nan | rare=nan
[epoch 000000093] loss=nan | avg=nan | rare=nan
[epoch 000000094] loss=nan | avg=nan | rare=nan
[epoch 000000095] loss=nan | avg=nan | rare=nan
[epoch 000000096] loss=nan | avg=nan | rare=nan
[epoch 000000097] loss=nan | avg=nan | rare=nan
[epoch 000000098] loss=nan | avg=nan | rare=nan
[epoch 000000099] loss=nan | avg=nan | rare=nan
[epoch 000000100] loss=nan | avg=nan | rare=nan

Training safe with sgd...

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

[epoch 000000001] loss=3860.957676479 | avg=3.283441186 | rare=0.385767424
[epoch 000000002] loss=3857.097726004 | avg=3.295365265 | rare=0.385380238
[epoch 000000003] loss=nan | avg=nan | rare=nan
[epoch 000000004] loss=nan | avg=nan | rare=nan
[epoch 000000005] loss=nan | avg=nan | rare=nan
[epoch 000000006] loss=nan | avg=nan | rare=nan
[epoch 000000007] loss=nan | avg=nan | rare=nan
[epoch 000000008] loss=nan | avg=nan | rare=nan
[epoch 000000009] loss=nan | avg=nan | rare=nan
[epoch 000000010] loss=nan | avg=nan | rare=nan
[epoch 000000011] loss=nan | avg=nan | rare=nan
[epoch 000000012] loss=nan | avg=nan | rare=nan
[epoch 000000013] loss=nan | avg=nan | rare=nan
[epoch 000000014] loss=nan | avg=nan | rare=nan
[epoch 000000015] loss=nan | avg=nan | rare=nan
[epoch 000000016] loss=nan | avg=nan | rare=nan
[epoch 000000017] loss=nan | avg=nan | rare=nan
[epoch 000000018] loss=nan | avg=nan | rare=nan
[epoch 000000019] loss=nan | avg=nan | rare=nan
[epoch 000000020] loss=nan | avg=nan | rare=nan
[epoch 000000021] loss=nan | avg=nan | rare=nan
[epoch 000000022] loss=nan | avg=nan | rare=nan
[epoch 000000023] loss=nan | avg=nan | rare=nan
[epoch 000000024] loss=nan | avg=nan | rare=nan
[epoch 000000025] loss=nan | avg=nan | rare=nan
[epoch 000000026] loss=nan | avg=nan | rare=nan
[epoch 000000027] loss=nan | avg=nan | rare=nan
[epoch 000000028] loss=nan | avg=nan | rare=nan
[epoch 000000029] loss=nan | avg=nan | rare=nan
[epoch 000000030] loss=nan | avg=nan | rare=nan
[epoch 000000031] loss=nan | avg=nan | rare=nan
[epoch 000000032] loss=nan | avg=nan | rare=nan
[epoch 000000033] loss=nan | avg=nan | rare=nan
[epoch 000000034] loss=nan | avg=nan | rare=nan
[epoch 000000035] loss=nan | avg=nan | rare=nan
[epoch 000000036] loss=nan | avg=nan | rare=nan
[epoch 000000037] loss=nan | avg=nan | rare=nan
[epoch 000000038] loss=nan | avg=nan | rare=nan
[epoch 000000039] loss=nan | avg=nan | rare=nan
[epoch 000000040] loss=nan | avg=nan | rare=nan
[epoch 000000041] loss=nan | avg=nan | rare=nan
[epoch 000000042] loss=nan | avg=nan | rare=nan
[epoch 000000043] loss=nan | avg=nan | rare=nan
[epoch 000000044] loss=nan | avg=nan | rare=nan
[epoch 000000045] loss=nan | avg=nan | rare=nan
[epoch 000000046] loss=nan | avg=nan | rare=nan
[epoch 000000047] loss=nan | avg=nan | rare=nan
[epoch 000000048] loss=nan | avg=nan | rare=nan
[epoch 000000049] loss=nan | avg=nan | rare=nan
[epoch 000000050] loss=nan | avg=nan | rare=nan
[epoch 000000051] loss=nan | avg=nan | rare=nan
[epoch 000000052] loss=nan | avg=nan | rare=nan
[epoch 000000053] loss=nan | avg=nan | rare=nan
[epoch 000000054] loss=nan | avg=nan | rare=nan
[epoch 000000055] loss=nan | avg=nan | rare=nan
[epoch 000000056] loss=nan | avg=nan | rare=nan
[epoch 000000057] loss=nan | avg=nan | rare=nan
[epoch 000000058] loss=nan | avg=nan | rare=nan
[epoch 000000059] loss=nan | avg=nan | rare=nan
[epoch 000000060] loss=nan | avg=nan | rare=nan
[epoch 000000061] loss=nan | avg=nan | rare=nan
[epoch 000000062] loss=nan | avg=nan | rare=nan
[epoch 000000063] loss=nan | avg=nan | rare=nan
[epoch 000000064] loss=nan | avg=nan | rare=nan
[epoch 000000065] loss=nan | avg=nan | rare=nan
[epoch 000000066] loss=nan | avg=nan | rare=nan
[epoch 000000067] loss=nan | avg=nan | rare=nan
[epoch 000000068] loss=nan | avg=nan | rare=nan
[epoch 000000069] loss=nan | avg=nan | rare=nan
[epoch 000000070] loss=nan | avg=nan | rare=nan
[epoch 000000071] loss=nan | avg=nan | rare=nan
[epoch 000000072] loss=nan | avg=nan | rare=nan
[epoch 000000073] loss=nan | avg=nan | rare=nan
[epoch 000000074] loss=nan | avg=nan | rare=nan
[epoch 000000075] loss=nan | avg=nan | rare=nan
[epoch 000000076] loss=nan | avg=nan | rare=nan
[epoch 000000077] loss=nan | avg=nan | rare=nan
[epoch 000000078] loss=nan | avg=nan | rare=nan
[epoch 000000079] loss=nan | avg=nan | rare=nan
[epoch 000000080] loss=nan | avg=nan | rare=nan
[epoch 000000081] loss=nan | avg=nan | rare=nan
[epoch 000000082] loss=nan | avg=nan | rare=nan
[epoch 000000083] loss=nan | avg=nan | rare=nan
[epoch 000000084] loss=nan | avg=nan | rare=nan
[epoch 000000085] loss=nan | avg=nan | rare=nan
[epoch 000000086] loss=nan | avg=nan | rare=nan
[epoch 000000087] loss=nan | avg=nan | rare=nan
[epoch 000000088] loss=nan | avg=nan | rare=nan
[epoch 000000089] loss=nan | avg=nan | rare=nan
[epoch 000000090] loss=nan | avg=nan | rare=nan
[epoch 000000091] loss=nan | avg=nan | rare=nan
[epoch 000000092] loss=nan | avg=nan | rare=nan
[epoch 000000093] loss=nan | avg=nan | rare=nan
[epoch 000000094] loss=nan | avg=nan | rare=nan
[epoch 000000095] loss=nan | avg=nan | rare=nan
[epoch 000000096] loss=nan | avg=nan | rare=nan
[epoch 000000097] loss=nan | avg=nan | rare=nan
[epoch 000000098] loss=nan | avg=nan | rare=nan
[epoch 000000099] loss=nan | avg=nan | rare=nan
[epoch 000000100] loss=nan | avg=nan | rare=nan
Accuracy: 63.96%  (CI 95%: [62.63%, 65.28%])
Robust Accuracy: 63.96415%  (CI 95%: [62.84861%, 65.40986%])
Conditional Robust Accuracy: 100.00000%  (CI 95%: [100.00000%, 100.00000%])
Accuracy: 63.96%  (CI 95%: [62.63%, 65.28%])
Robust Accuracy: 63.96415%  (CI 95%: [62.84861%, 65.40986%])
Conditional Robust Accuracy: 100.00000%  (CI 95%: [100.00000%, 100.00000%])
#################lr: 0.0001#############################

Training naive with sgd...

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

[epoch 000000001] loss=36697.019252232 | avg=0.263567181 | rare=3.669675503
[epoch 000000002] loss=36609.113560268 | avg=0.264090906 | rare=3.660884976
[epoch 000000003] loss=nan | avg=nan | rare=nan
[epoch 000000004] loss=1.146082963 | avg=1.146082963 | rare=0.000000000
[epoch 000000005] loss=1.109187637 | avg=1.109187637 | rare=0.000000000
[epoch 000000006] loss=1.098987162 | avg=1.098987162 | rare=0.000000000
[epoch 000000007] loss=1.048764846 | avg=1.048764846 | rare=0.000000000
[epoch 000000008] loss=1.035859947 | avg=1.035859947 | rare=0.000000000
[epoch 000000009] loss=1.056189358 | avg=1.056189358 | rare=0.000000000
[epoch 000000010] loss=1.000800094 | avg=1.000800094 | rare=0.000000000
[epoch 000000011] loss=0.989782329 | avg=0.989782329 | rare=0.000000000
[epoch 000000012] loss=0.963086635 | avg=0.963086635 | rare=0.000000000
[epoch 000000013] loss=0.948030902 | avg=0.948030902 | rare=0.000000000
[epoch 000000014] loss=0.934782420 | avg=0.934782420 | rare=0.000000000
[epoch 000000015] loss=0.925343645 | avg=0.925343645 | rare=0.000000000
[epoch 000000016] loss=0.922498277 | avg=0.922498277 | rare=0.000000000
[epoch 000000017] loss=0.916461919 | avg=0.916461919 | rare=0.000000000
[epoch 000000018] loss=0.910243196 | avg=0.910243196 | rare=0.000000000
[epoch 000000019] loss=0.908344009 | avg=0.908344009 | rare=0.000000000
[epoch 000000020] loss=0.902924465 | avg=0.902924465 | rare=0.000000000
[epoch 000000021] loss=0.925541835 | avg=0.925541835 | rare=0.000000000
[epoch 000000022] loss=0.894507306 | avg=0.894507306 | rare=0.000000000
[epoch 000000023] loss=0.890543478 | avg=0.890543478 | rare=0.000000000
[epoch 000000024] loss=0.887008054 | avg=0.887008054 | rare=0.000000000
[epoch 000000025] loss=0.883974561 | avg=0.883974561 | rare=0.000000000
[epoch 000000026] loss=0.881286919 | avg=0.881286919 | rare=0.000000000
[epoch 000000027] loss=0.881369982 | avg=0.881369982 | rare=0.000000000
[epoch 000000028] loss=0.873476054 | avg=0.873476054 | rare=0.000000000
[epoch 000000029] loss=0.870240062 | avg=0.870240062 | rare=0.000000000
[epoch 000000030] loss=0.866120564 | avg=0.866120564 | rare=0.000000000
[epoch 000000031] loss=0.862348080 | avg=0.862348080 | rare=0.000000000
[epoch 000000032] loss=0.859485017 | avg=0.859485017 | rare=0.000000000
[epoch 000000033] loss=0.854002991 | avg=0.854002991 | rare=0.000000000
[epoch 000000034] loss=0.852706628 | avg=0.852706628 | rare=0.000000000
[epoch 000000035] loss=0.857281353 | avg=0.857281353 | rare=0.000000000
[epoch 000000036] loss=0.849564727 | avg=0.849564727 | rare=0.000000000
[epoch 000000037] loss=0.848265546 | avg=0.848265546 | rare=0.000000000
[epoch 000000038] loss=0.853230851 | avg=0.853230851 | rare=0.000000000
[epoch 000000039] loss=0.844088571 | avg=0.844088571 | rare=0.000000000
[epoch 000000040] loss=0.842281529 | avg=0.842281529 | rare=0.000000000
[epoch 000000041] loss=0.839224866 | avg=0.839224866 | rare=0.000000000
[epoch 000000042] loss=0.842057530 | avg=0.842057530 | rare=0.000000000
[epoch 000000043] loss=0.835690430 | avg=0.835690430 | rare=0.000000000
[epoch 000000044] loss=0.835044763 | avg=0.835044763 | rare=0.000000000
[epoch 000000045] loss=0.835472256 | avg=0.835472256 | rare=0.000000000
[epoch 000000046] loss=0.833484071 | avg=0.833484071 | rare=0.000000000
[epoch 000000047] loss=0.831704655 | avg=0.831704655 | rare=0.000000000
[epoch 000000048] loss=0.832135899 | avg=0.832135899 | rare=0.000000000
[epoch 000000049] loss=0.831335813 | avg=0.831335813 | rare=0.000000000
[epoch 000000050] loss=0.844447166 | avg=0.844447166 | rare=0.000000000
[epoch 000000051] loss=0.843858106 | avg=0.843858106 | rare=0.000000000
[epoch 000000052] loss=0.827279159 | avg=0.827279159 | rare=0.000000000
[epoch 000000053] loss=0.828505103 | avg=0.828505103 | rare=0.000000000
[epoch 000000054] loss=0.827244708 | avg=0.827244708 | rare=0.000000000
[epoch 000000055] loss=0.826623878 | avg=0.826623878 | rare=0.000000000
[epoch 000000056] loss=0.825328869 | avg=0.825328869 | rare=0.000000000
[epoch 000000057] loss=0.823701684 | avg=0.823701684 | rare=0.000000000
[epoch 000000058] loss=0.829934295 | avg=0.829934295 | rare=0.000000000
[epoch 000000059] loss=0.822650748 | avg=0.822650748 | rare=0.000000000
[epoch 000000060] loss=0.822926036 | avg=0.822926036 | rare=0.000000000
[epoch 000000061] loss=0.822901125 | avg=0.822901125 | rare=0.000000000
[epoch 000000062] loss=0.820430138 | avg=0.820430138 | rare=0.000000000
[epoch 000000063] loss=0.820328483 | avg=0.820328483 | rare=0.000000000
[epoch 000000064] loss=0.820676880 | avg=0.820676880 | rare=0.000000000
[epoch 000000065] loss=0.820581338 | avg=0.820581338 | rare=0.000000000
[epoch 000000066] loss=0.819450370 | avg=0.819450370 | rare=0.000000000
[epoch 000000067] loss=0.818362853 | avg=0.818362853 | rare=0.000000000
[epoch 000000068] loss=0.817068624 | avg=0.817068624 | rare=0.000000000
[epoch 000000069] loss=0.817605640 | avg=0.817605640 | rare=0.000000000
[epoch 000000070] loss=0.821166562 | avg=0.821166562 | rare=0.000000000
[epoch 000000071] loss=0.818675756 | avg=0.818675756 | rare=0.000000000
[epoch 000000072] loss=0.816058823 | avg=0.816058823 | rare=0.000000000
[epoch 000000073] loss=0.817732066 | avg=0.817732066 | rare=0.000000000
[epoch 000000074] loss=0.816631500 | avg=0.816631500 | rare=0.000000000
[epoch 000000075] loss=0.814142002 | avg=0.814142002 | rare=0.000000000
[epoch 000000076] loss=0.813843795 | avg=0.813843795 | rare=0.000000000
[epoch 000000077] loss=0.814739487 | avg=0.814739487 | rare=0.000000000
[epoch 000000078] loss=0.813988341 | avg=0.813988341 | rare=0.000000000
[epoch 000000079] loss=0.814408962 | avg=0.814408962 | rare=0.000000000
[epoch 000000080] loss=0.811664151 | avg=0.811664151 | rare=0.000000000
[epoch 000000081] loss=0.830167055 | avg=0.830167055 | rare=0.000000000
[epoch 000000082] loss=0.813550749 | avg=0.813550749 | rare=0.000000000
[epoch 000000083] loss=0.812517979 | avg=0.812517979 | rare=0.000000000
[epoch 000000084] loss=0.812012753 | avg=0.812012753 | rare=0.000000000
[epoch 000000085] loss=0.812380735 | avg=0.812380735 | rare=0.000000000
[epoch 000000086] loss=0.811160777 | avg=0.811160777 | rare=0.000000000
[epoch 000000087] loss=0.809576524 | avg=0.809576524 | rare=0.000000000
[epoch 000000088] loss=0.809982202 | avg=0.809982202 | rare=0.000000000
[epoch 000000089] loss=0.810283874 | avg=0.810283874 | rare=0.000000000
[epoch 000000090] loss=0.809130119 | avg=0.809130119 | rare=0.000000000
[epoch 000000091] loss=0.809899577 | avg=0.809899577 | rare=0.000000000
[epoch 000000092] loss=0.808341682 | avg=0.808341682 | rare=0.000000000
[epoch 000000093] loss=0.807217526 | avg=0.807217526 | rare=0.000000000
[epoch 000000094] loss=0.808356877 | avg=0.808356877 | rare=0.000000000
[epoch 000000095] loss=0.807094906 | avg=0.807094906 | rare=0.000000000
[epoch 000000096] loss=0.806760682 | avg=0.806760682 | rare=0.000000000
[epoch 000000097] loss=0.807280592 | avg=0.807280592 | rare=0.000000000
[epoch 000000098] loss=0.807073976 | avg=0.807073976 | rare=0.000000000
[epoch 000000099] loss=0.806873815 | avg=0.806873815 | rare=0.000000000
[epoch 000000100] loss=0.805835443 | avg=0.805835443 | rare=0.000000000

Training safe with sgd...

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

[epoch 000000001] loss=3860.957676479 | avg=3.283441186 | rare=0.385767424
[epoch 000000002] loss=3857.097726004 | avg=3.295365265 | rare=0.385380238
[epoch 000000003] loss=3565.289431981 | avg=2194.159514155 | rare=0.137112991
[epoch 000000004] loss=2162.626652309 | avg=2157.520412990 | rare=0.000510624
[epoch 000000005] loss=110.326365335 | avg=109.151454653 | rare=0.000117491
[epoch 000000006] loss=40.467800430 | avg=40.291306743 | rare=0.000017649
[epoch 000000007] loss=635.165730289 | avg=635.016977498 | rare=0.000014875
[epoch 000000008] loss=5.896726472 | avg=5.896726472 | rare=0.000000000
[epoch 000000009] loss=5.673220498 | avg=5.673220498 | rare=0.000000000
[epoch 000000010] loss=5.543571200 | avg=5.543571200 | rare=0.000000000
[epoch 000000011] loss=5.468909638 | avg=5.468909638 | rare=0.000000000
[epoch 000000012] loss=5.438717263 | avg=5.438717263 | rare=0.000000000
[epoch 000000013] loss=5.404137748 | avg=5.404137748 | rare=0.000000000
[epoch 000000014] loss=5.372319358 | avg=5.372319358 | rare=0.000000000
[epoch 000000015] loss=5.353096758 | avg=5.353096758 | rare=0.000000000
[epoch 000000016] loss=5.359955413 | avg=5.359955413 | rare=0.000000000
[epoch 000000017] loss=5.354839359 | avg=5.354839359 | rare=0.000000000
[epoch 000000018] loss=5.336923327 | avg=5.336923327 | rare=0.000000000
[epoch 000000019] loss=5.343497276 | avg=5.343497276 | rare=0.000000000
[epoch 000000020] loss=5.320041725 | avg=5.320041725 | rare=0.000000000
[epoch 000000021] loss=5.326985495 | avg=5.326985495 | rare=0.000000000
[epoch 000000022] loss=5.312630892 | avg=5.312630892 | rare=0.000000000
[epoch 000000023] loss=5.312558310 | avg=5.312558310 | rare=0.000000000
[epoch 000000024] loss=5.301214116 | avg=5.301214116 | rare=0.000000000
[epoch 000000025] loss=5.301080295 | avg=5.301080295 | rare=0.000000000
[epoch 000000026] loss=5.303517682 | avg=5.303517682 | rare=0.000000000
[epoch 000000027] loss=5.288422278 | avg=5.288422278 | rare=0.000000000
[epoch 000000028] loss=5.293152400 | avg=5.293152400 | rare=0.000000000
[epoch 000000029] loss=5.291982480 | avg=5.291982480 | rare=0.000000000
[epoch 000000030] loss=5.285687413 | avg=5.285687413 | rare=0.000000000
[epoch 000000031] loss=5.274344240 | avg=5.274344240 | rare=0.000000000
[epoch 000000032] loss=5.284485340 | avg=5.284485340 | rare=0.000000000
[epoch 000000033] loss=5.261713845 | avg=5.261713845 | rare=0.000000000
[epoch 000000034] loss=5.270317759 | avg=5.270317759 | rare=0.000000000
[epoch 000000035] loss=5.281088897 | avg=5.281088897 | rare=0.000000000
[epoch 000000036] loss=5.275715930 | avg=5.275715930 | rare=0.000000000
[epoch 000000037] loss=5.286441258 | avg=5.286441258 | rare=0.000000000
[epoch 000000038] loss=5.269856623 | avg=5.269856623 | rare=0.000000000
[epoch 000000039] loss=5.273805993 | avg=5.273805993 | rare=0.000000000
[epoch 000000040] loss=5.272716897 | avg=5.272716897 | rare=0.000000000
[epoch 000000041] loss=5.257551261 | avg=5.257551261 | rare=0.000000000
[epoch 000000042] loss=5.274382080 | avg=5.274382080 | rare=0.000000000
[epoch 000000043] loss=5.254272291 | avg=5.254272291 | rare=0.000000000
[epoch 000000044] loss=5.258159569 | avg=5.258159569 | rare=0.000000000
[epoch 000000045] loss=5.269092458 | avg=5.269092458 | rare=0.000000000
[epoch 000000046] loss=5.261519466 | avg=5.261519466 | rare=0.000000000
[epoch 000000047] loss=5.252256870 | avg=5.252256870 | rare=0.000000000
[epoch 000000048] loss=5.266482694 | avg=5.266482694 | rare=0.000000000
[epoch 000000049] loss=5.264830112 | avg=5.264830112 | rare=0.000000000
[epoch 000000050] loss=5.260128498 | avg=5.260128498 | rare=0.000000000
[epoch 000000051] loss=5.262087618 | avg=5.262087618 | rare=0.000000000
[epoch 000000052] loss=5.250516244 | avg=5.250516244 | rare=0.000000000
[epoch 000000053] loss=5.265499558 | avg=5.265499558 | rare=0.000000000
[epoch 000000054] loss=5.260562795 | avg=5.260562795 | rare=0.000000000
[epoch 000000055] loss=5.261806556 | avg=5.261806556 | rare=0.000000000
[epoch 000000056] loss=5.255772114 | avg=5.255772114 | rare=0.000000000
[epoch 000000057] loss=5.247789724 | avg=5.247789724 | rare=0.000000000
[epoch 000000058] loss=5.255370719 | avg=5.255370719 | rare=0.000000000
[epoch 000000059] loss=5.250509637 | avg=5.250509637 | rare=0.000000000
[epoch 000000060] loss=5.259959664 | avg=5.259959664 | rare=0.000000000
[epoch 000000061] loss=5.264527048 | avg=5.264527048 | rare=0.000000000
[epoch 000000062] loss=5.249109302 | avg=5.249109302 | rare=0.000000000
[epoch 000000063] loss=5.254163640 | avg=5.254163640 | rare=0.000000000
[epoch 000000064] loss=5.262091058 | avg=5.262091058 | rare=0.000000000
[epoch 000000065] loss=5.266069957 | avg=5.266069957 | rare=0.000000000
[epoch 000000066] loss=5.259094988 | avg=5.259094988 | rare=0.000000000
[epoch 000000067] loss=5.251599210 | avg=5.251599210 | rare=0.000000000
[epoch 000000068] loss=5.244917904 | avg=5.244917904 | rare=0.000000000
[epoch 000000069] loss=5.255098173 | avg=5.255098173 | rare=0.000000000
[epoch 000000070] loss=5.245888403 | avg=5.245888403 | rare=0.000000000
[epoch 000000071] loss=5.268199035 | avg=5.268199035 | rare=0.000000000
[epoch 000000072] loss=5.247884512 | avg=5.247884512 | rare=0.000000000
[epoch 000000073] loss=5.259878669 | avg=5.259878669 | rare=0.000000000
[epoch 000000074] loss=5.260760239 | avg=5.260760239 | rare=0.000000000
[epoch 000000075] loss=5.240549496 | avg=5.240549496 | rare=0.000000000
[epoch 000000076] loss=5.240740844 | avg=5.240740844 | rare=0.000000000
[epoch 000000077] loss=5.250657558 | avg=5.250657558 | rare=0.000000000
[epoch 000000078] loss=5.246823004 | avg=5.246823004 | rare=0.000000000
[epoch 000000079] loss=5.255642857 | avg=5.255642857 | rare=0.000000000
[epoch 000000080] loss=5.234340225 | avg=5.234340225 | rare=0.000000000
[epoch 000000081] loss=5.246237278 | avg=5.246237278 | rare=0.000000000
[epoch 000000082] loss=5.256162439 | avg=5.256162439 | rare=0.000000000
[epoch 000000083] loss=5.251742227 | avg=5.251742227 | rare=0.000000000
[epoch 000000084] loss=5.249356100 | avg=5.249356100 | rare=0.000000000
[epoch 000000085] loss=5.255876848 | avg=5.255876848 | rare=0.000000000
[epoch 000000086] loss=5.247186422 | avg=5.247186422 | rare=0.000000000
[epoch 000000087] loss=5.237926858 | avg=5.237926858 | rare=0.000000000
[epoch 000000088] loss=5.244862250 | avg=5.244862250 | rare=0.000000000
[epoch 000000089] loss=5.251469919 | avg=5.251469919 | rare=0.000000000
[epoch 000000090] loss=5.242510114 | avg=5.242510114 | rare=0.000000000
[epoch 000000091] loss=5.248389312 | avg=5.248389312 | rare=0.000000000
[epoch 000000092] loss=5.237973247 | avg=5.237973247 | rare=0.000000000
[epoch 000000093] loss=5.234708207 | avg=5.234708207 | rare=0.000000000
[epoch 000000094] loss=5.246316535 | avg=5.246316535 | rare=0.000000000
[epoch 000000095] loss=5.236902339 | avg=5.236902339 | rare=0.000000000
[epoch 000000096] loss=5.237418175 | avg=5.237418175 | rare=0.000000000
[epoch 000000097] loss=5.242649930 | avg=5.242649930 | rare=0.000000000
[epoch 000000098] loss=5.243013757 | avg=5.243013757 | rare=0.000000000
[epoch 000000099] loss=5.242361648 | avg=5.242361648 | rare=0.000000000
[epoch 000000100] loss=5.234985045 | avg=5.234985045 | rare=0.000000000
Accuracy: 63.96%  (CI 95%: [62.63%, 65.28%])
Robust Accuracy: 63.96415%  (CI 95%: [62.84861%, 65.40986%])
Conditional Robust Accuracy: 100.00000%  (CI 95%: [100.00000%, 100.00000%])
Accuracy: 63.96%  (CI 95%: [62.63%, 65.28%])
Robust Accuracy: 63.96415%  (CI 95%: [62.84861%, 65.40986%])
Conditional Robust Accuracy: 100.00000%  (CI 95%: [100.00000%, 100.00000%])
#################lr: 1e-05#############################

Training naive with sgd...

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

[epoch 000000001] loss=36697.019252232 | avg=0.263567181 | rare=3.669675503
[epoch 000000002] loss=36609.113560268 | avg=0.264090906 | rare=3.660884976
[epoch 000000003] loss=18634.239889962 | avg=291.350616844 | rare=1.834288955
[epoch 000000004] loss=509.991481236 | avg=509.991481236 | rare=0.000000000
[epoch 000000005] loss=440.646730695 | avg=440.646730695 | rare=0.000000000
[epoch 000000006] loss=380.526059832 | avg=380.526059832 | rare=0.000000000
[epoch 000000007] loss=324.104267665 | avg=324.104267665 | rare=0.000000000
[epoch 000000008] loss=270.008882795 | avg=270.008882795 | rare=0.000000000
[epoch 000000009] loss=220.271204267 | avg=220.271204267 | rare=0.000000000
[epoch 000000010] loss=174.608232771 | avg=174.608232771 | rare=0.000000000
[epoch 000000011] loss=137.650057111 | avg=137.650057111 | rare=0.000000000
[epoch 000000012] loss=107.531453814 | avg=107.531453814 | rare=0.000000000
[epoch 000000013] loss=85.898755210 | avg=85.898755210 | rare=0.000000000
[epoch 000000014] loss=68.560223443 | avg=68.560223443 | rare=0.000000000
[epoch 000000015] loss=53.166268485 | avg=53.145481110 | rare=0.000002079
[epoch 000000016] loss=41.824052266 | avg=40.780037744 | rare=0.000104401
[epoch 000000017] loss=35.105740275 | avg=34.035634313 | rare=0.000107011
[epoch 000000018] loss=29.435751779 | avg=27.935064861 | rare=0.000150069
[epoch 000000019] loss=43.541306768 | avg=19.902843612 | rare=0.002363846
[epoch 000000020] loss=158.699853080 | avg=45.407356739 | rare=0.011329249
[epoch 000000021] loss=57.585318974 | avg=55.474551610 | rare=0.000211077
[epoch 000000022] loss=49.366745540 | avg=48.996464321 | rare=0.000037028
[epoch 000000023] loss=42.441428321 | avg=42.134355545 | rare=0.000030707
[epoch 000000024] loss=37.152899878 | avg=36.010271617 | rare=0.000114263
[epoch 000000025] loss=31.745749746 | avg=30.868124962 | rare=0.000087762
[epoch 000000026] loss=28.235583578 | avg=27.338897296 | rare=0.000089669
[epoch 000000027] loss=25.491136960 | avg=24.548497200 | rare=0.000094264
[epoch 000000028] loss=22.738234384 | avg=21.874776840 | rare=0.000086346
[epoch 000000029] loss=20.334269932 | avg=19.672786440 | rare=0.000066148
[epoch 000000030] loss=17.896969591 | avg=16.920118809 | rare=0.000097685
[epoch 000000031] loss=16.060101032 | avg=15.424490724 | rare=0.000063561
[epoch 000000032] loss=14.467363562 | avg=13.485498224 | rare=0.000098187
[epoch 000000033] loss=13.639622211 | avg=12.810885498 | rare=0.000082874
[epoch 000000034] loss=12.412163189 | avg=11.703768390 | rare=0.000070839
[epoch 000000035] loss=11.276914324 | avg=10.074754374 | rare=0.000120216
[epoch 000000036] loss=10.153052602 | avg=9.269978932 | rare=0.000088307
[epoch 000000037] loss=9.440019982 | avg=8.039685215 | rare=0.000140033
[epoch 000000038] loss=8.330240829 | avg=7.519946030 | rare=0.000081029
[epoch 000000039] loss=7.080411366 | avg=6.139202050 | rare=0.000094121
[epoch 000000040] loss=5.821045024 | avg=5.116946357 | rare=0.000070410
[epoch 000000041] loss=5.389061213 | avg=4.579730647 | rare=0.000080933
[epoch 000000042] loss=4.539854084 | avg=4.000971624 | rare=0.000053888
[epoch 000000043] loss=8.362997566 | avg=2.746912548 | rare=0.000561609
[epoch 000000044] loss=11.758955445 | avg=3.190046144 | rare=0.000856891
[epoch 000000045] loss=6.111848422 | avg=5.801767622 | rare=0.000031008
[epoch 000000046] loss=5.362038919 | avg=5.246216229 | rare=0.000011582
[epoch 000000047] loss=4.694395508 | avg=4.560735192 | rare=0.000013366
[epoch 000000048] loss=4.089856693 | avg=3.965606179 | rare=0.000012425
[epoch 000000049] loss=3.482051066 | avg=3.395972116 | rare=0.000008608
[epoch 000000050] loss=2.928553394 | avg=2.763757893 | rare=0.000016480
[epoch 000000051] loss=2.337467458 | avg=2.244998779 | rare=0.000009247
[epoch 000000052] loss=1.795118281 | avg=1.677036217 | rare=0.000011808
[epoch 000000053] loss=1.302511947 | avg=1.202479099 | rare=0.000010003
[epoch 000000054] loss=0.933068275 | avg=0.862470056 | rare=0.000007060
[epoch 000000055] loss=0.761205401 | avg=0.690106473 | rare=0.000007110
[epoch 000000056] loss=2.699542092 | avg=1.459181654 | rare=0.000124036
[epoch 000000057] loss=6.401917270 | avg=3.134786708 | rare=0.000326713
[epoch 000000058] loss=3.038613711 | avg=2.289238734 | rare=0.000074937
[epoch 000000059] loss=1.828171364 | avg=1.770554551 | rare=0.000005762
[epoch 000000060] loss=1.323271198 | avg=1.269494099 | rare=0.000005378
[epoch 000000061] loss=0.979397970 | avg=0.876744036 | rare=0.000010265
[epoch 000000062] loss=0.792661846 | avg=0.702539218 | rare=0.000009012
[epoch 000000063] loss=0.700613175 | avg=0.660674853 | rare=0.000003994
[epoch 000000064] loss=0.679324354 | avg=0.646073857 | rare=0.000003325
[epoch 000000065] loss=8.920568321 | avg=8.617595434 | rare=0.000030297
[epoch 000000066] loss=9.961653505 | avg=9.961653505 | rare=0.000000000
[epoch 000000067] loss=9.062085629 | avg=9.062085629 | rare=0.000000000
[epoch 000000068] loss=8.250512804 | avg=8.250512804 | rare=0.000000000
[epoch 000000069] loss=7.530301707 | avg=7.530301707 | rare=0.000000000
[epoch 000000070] loss=6.837142195 | avg=6.837142195 | rare=0.000000000
[epoch 000000071] loss=6.252276931 | avg=6.252276931 | rare=0.000000000
[epoch 000000072] loss=5.655001674 | avg=5.655001674 | rare=0.000000000
[epoch 000000073] loss=5.149743898 | avg=5.149743898 | rare=0.000000000
[epoch 000000074] loss=4.674719368 | avg=4.674719368 | rare=0.000000000
[epoch 000000075] loss=4.215158973 | avg=4.215158973 | rare=0.000000000
[epoch 000000076] loss=3.807034561 | avg=3.807034390 | rare=0.000000000
[epoch 000000077] loss=3.437052011 | avg=3.437049764 | rare=0.000000000
[epoch 000000078] loss=3.080929296 | avg=3.080893040 | rare=0.000000004
[epoch 000000079] loss=2.758168050 | avg=2.758117795 | rare=0.000000005
[epoch 000000080] loss=2.442407336 | avg=2.442252857 | rare=0.000000015
[epoch 000000081] loss=2.159099400 | avg=2.158824044 | rare=0.000000028
[epoch 000000082] loss=1.894225385 | avg=1.893822449 | rare=0.000000040
[epoch 000000083] loss=1.640265763 | avg=1.639487701 | rare=0.000000078
[epoch 000000084] loss=1.407176750 | avg=1.405945684 | rare=0.000000123
[epoch 000000085] loss=1.199887718 | avg=1.197074882 | rare=0.000000281
[epoch 000000086] loss=1.018148699 | avg=1.015955674 | rare=0.000000219
[epoch 000000087] loss=0.877879381 | avg=0.870245218 | rare=0.000000763
[epoch 000000088] loss=0.780168793 | avg=0.772403130 | rare=0.000000777
[epoch 000000089] loss=0.718958382 | avg=0.709746033 | rare=0.000000921
[epoch 000000090] loss=0.684224589 | avg=0.673826188 | rare=0.000001040
[epoch 000000091] loss=0.667019171 | avg=0.656210320 | rare=0.000001081
[epoch 000000092] loss=0.657608049 | avg=0.646130898 | rare=0.000001148
[epoch 000000093] loss=3.336332223 | avg=1.062625315 | rare=0.000227371
[epoch 000000094] loss=0.815508025 | avg=0.811572377 | rare=0.000000394
[epoch 000000095] loss=0.744344911 | avg=0.737781273 | rare=0.000000656
[epoch 000000096] loss=0.700819118 | avg=0.692654886 | rare=0.000000816
[epoch 000000097] loss=0.675714621 | avg=0.667193911 | rare=0.000000852
[epoch 000000098] loss=0.662146709 | avg=0.653514411 | rare=0.000000863
[epoch 000000099] loss=0.655103943 | avg=0.645092734 | rare=0.000001001
[epoch 000000100] loss=6.089908566 | avg=4.929738381 | rare=0.000116017

Training safe with sgd...

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

[epoch 000000001] loss=3860.957676479 | avg=3.283441186 | rare=0.385767424
[epoch 000000002] loss=3857.097726004 | avg=3.295365265 | rare=0.385380238
[epoch 000000003] loss=2907.330540248 | avg=420.704998425 | rare=0.248662551
[epoch 000000004] loss=655.149993896 | avg=655.149993896 | rare=0.000000000
[epoch 000000005] loss=589.545758929 | avg=589.545758929 | rare=0.000000000
[epoch 000000006] loss=535.648921422 | avg=535.648921422 | rare=0.000000000
[epoch 000000007] loss=486.941759382 | avg=486.941759382 | rare=0.000000000
[epoch 000000008] loss=443.750377110 | avg=443.750377110 | rare=0.000000000
[epoch 000000009] loss=408.755990165 | avg=408.755990165 | rare=0.000000000
[epoch 000000010] loss=377.385962350 | avg=377.385962350 | rare=0.000000000
[epoch 000000011] loss=347.670277187 | avg=347.670277187 | rare=0.000000000
[epoch 000000012] loss=320.763185774 | avg=320.763185774 | rare=0.000000000
[epoch 000000013] loss=305.258215768 | avg=294.139225551 | rare=0.001111899
[epoch 000000014] loss=290.495536804 | avg=256.073544094 | rare=0.003442199
[epoch 000000015] loss=493.901547023 | avg=166.280930383 | rare=0.032762062
[epoch 000000016] loss=505.187886919 | avg=255.669755118 | rare=0.024951814
[epoch 000000017] loss=414.319684710 | avg=327.379783630 | rare=0.008693990
[epoch 000000018] loss=422.894045149 | avg=167.860711234 | rare=0.025503334
[epoch 000000019] loss=777.616849627 | avg=109.440951211 | rare=0.066817590
[epoch 000000020] loss=288.499335153 | avg=92.685090746 | rare=0.019581424
[epoch 000000021] loss=328.806316921 | avg=77.285982949 | rare=0.025152034
[epoch 000000022] loss=248.982915606 | avg=67.536827905 | rare=0.018144609
[epoch 000000023] loss=307.694278172 | avg=54.468221664 | rare=0.025322606
[epoch 000000024] loss=293.920615060 | avg=51.075874329 | rare=0.024284474
[epoch 000000025] loss=341.111570086 | avg=45.675895827 | rare=0.029543568
[epoch 000000026] loss=401.204769679 | avg=35.224858965 | rare=0.036597991
[epoch 000000027] loss=302.607591902 | avg=36.903694562 | rare=0.026570389
[epoch 000000028] loss=290.313253130 | avg=36.525049891 | rare=0.025378820
[epoch 000000029] loss=364.240281241 | avg=21.236656257 | rare=0.034300363
[epoch 000000030] loss=366.570271083 | avg=20.043576854 | rare=0.034652669
[epoch 000000031] loss=418.842293876 | avg=18.618794646 | rare=0.040022350
[epoch 000000032] loss=256.367712838 | avg=19.373215743 | rare=0.023699450
[epoch 000000033] loss=290.766868591 | avg=16.261485032 | rare=0.027450539
[epoch 000000034] loss=285.112473624 | avg=11.789618662 | rare=0.027332286
[epoch 000000035] loss=306.667447226 | avg=12.313654048 | rare=0.029435380
[epoch 000000036] loss=442.388869149 | avg=15.480284214 | rare=0.042690858
[epoch 000000037] loss=231.480970383 | avg=25.413575854 | rare=0.020606740
[epoch 000000038] loss=374.995711190 | avg=15.254198824 | rare=0.035974152
[epoch 000000039] loss=282.193691526 | avg=10.460502829 | rare=0.027173319
[epoch 000000040] loss=271.171059200 | avg=10.390490907 | rare=0.026078057
[epoch 000000041] loss=212.473123823 | avg=9.754504647 | rare=0.020271862
[epoch 000000042] loss=241.765852247 | avg=12.734170641 | rare=0.022903168
[epoch 000000043] loss=284.403690883 | avg=10.284149204 | rare=0.027411954
[epoch 000000044] loss=335.331112453 | avg=8.029005051 | rare=0.032730210
[epoch 000000045] loss=290.748301370 | avg=7.105562959 | rare=0.028364274
[epoch 000000046] loss=225.017759051 | avg=5.417666333 | rare=0.021960009
[epoch 000000047] loss=187.189505441 | avg=6.075331245 | rare=0.018111417
[epoch 000000048] loss=213.054036277 | avg=6.536203453 | rare=0.020651783
[epoch 000000049] loss=257.631615775 | avg=7.110086901 | rare=0.025052153
[epoch 000000050] loss=209.278443473 | avg=5.934521130 | rare=0.020334392
[epoch 000000051] loss=190.930871146 | avg=5.289515427 | rare=0.018564136
[epoch 000000052] loss=187.935248239 | avg=4.247315202 | rare=0.018368793
[epoch 000000053] loss=187.481730870 | avg=4.937940598 | rare=0.018254379
[epoch 000000054] loss=174.087649209 | avg=4.553451044 | rare=0.016953420
[epoch 000000055] loss=163.430540630 | avg=3.993436251 | rare=0.015943710
[epoch 000000056] loss=183.731998444 | avg=5.243194665 | rare=0.017848881
[epoch 000000057] loss=139.810610362 | avg=3.786832264 | rare=0.013602378
[epoch 000000058] loss=134.440909386 | avg=4.055840731 | rare=0.013038507
[epoch 000000059] loss=131.148611614 | avg=3.730243581 | rare=0.012741837
[epoch 000000060] loss=112.070518221 | avg=4.421640941 | rare=0.010764888
[epoch 000000061] loss=136.485813141 | avg=6.664454630 | rare=0.012982136
[epoch 000000062] loss=175.858652660 | avg=4.484580312 | rare=0.017137407
[epoch 000000063] loss=142.961752210 | avg=3.650028620 | rare=0.013931172
[epoch 000000064] loss=144.581808363 | avg=3.914396933 | rare=0.014066741
[epoch 000000065] loss=153.461435590 | avg=4.137502262 | rare=0.014932393
[epoch 000000066] loss=168.994715554 | avg=3.587359105 | rare=0.016540736
[epoch 000000067] loss=133.715644291 | avg=3.714646220 | rare=0.013000100
[epoch 000000068] loss=98.520331791 | avg=2.982678464 | rare=0.009553765
[epoch 000000069] loss=98.344330106 | avg=3.683292406 | rare=0.009466104
[epoch 000000070] loss=97.224346433 | avg=2.661490270 | rare=0.009456286
[epoch 000000071] loss=81.977918761 | avg=2.828255466 | rare=0.007914966
[epoch 000000072] loss=93.021468435 | avg=2.358605725 | rare=0.009066286
[epoch 000000073] loss=75.061360087 | avg=2.609736349 | rare=0.007245162
[epoch 000000074] loss=82.016074726 | avg=5.059608647 | rare=0.007695647
[epoch 000000075] loss=107.624614034 | avg=2.738669600 | rare=0.010488594
[epoch 000000076] loss=102.654471261 | avg=5.602980018 | rare=0.009705149
[epoch 000000077] loss=85.783646720 | avg=2.600512998 | rare=0.008318313
[epoch 000000078] loss=114.549988202 | avg=3.007157488 | rare=0.011154283
[epoch 000000079] loss=95.263824190 | avg=2.672759295 | rare=0.009259107
[epoch 000000080] loss=72.880634580 | avg=2.545328174 | rare=0.007033531
[epoch 000000081] loss=104.656827382 | avg=4.705121466 | rare=0.009995170
[epoch 000000082] loss=73.429765156 | avg=3.475079979 | rare=0.006995468
[epoch 000000083] loss=100.939545223 | avg=2.538721604 | rare=0.009840082
[epoch 000000084] loss=108.723597935 | avg=3.538912313 | rare=0.010518469
[epoch 000000085] loss=107.935201372 | avg=2.519914780 | rare=0.010541529
[epoch 000000086] loss=87.423039845 | avg=2.398733292 | rare=0.008502431
[epoch 000000087] loss=79.186138562 | avg=2.217151710 | rare=0.007696899
[epoch 000000088] loss=73.451564516 | avg=2.258340171 | rare=0.007119322
[epoch 000000089] loss=83.640828950 | avg=2.434210777 | rare=0.008120662
[epoch 000000090] loss=58.351861954 | avg=2.909763506 | rare=0.005544210
[epoch 000000091] loss=77.908539363 | avg=2.406700483 | rare=0.007550184
[epoch 000000092] loss=60.994040353 | avg=2.133188784 | rare=0.005886085
[epoch 000000093] loss=56.491720336 | avg=1.964274347 | rare=0.005452745
[epoch 000000094] loss=57.078328678 | avg=2.133719036 | rare=0.005494461
[epoch 000000095] loss=65.583186286 | avg=1.795091024 | rare=0.006378810
[epoch 000000096] loss=53.482399123 | avg=1.909086423 | rare=0.005157331
[epoch 000000097] loss=65.275611060 | avg=1.967826690 | rare=0.006330778
[epoch 000000098] loss=62.249715805 | avg=1.800487859 | rare=0.006044923
[epoch 000000099] loss=65.448676382 | avg=1.874045210 | rare=0.006357463
[epoch 000000100] loss=65.609209333 | avg=2.071223872 | rare=0.006353799
Accuracy: 63.96%  (CI 95%: [62.63%, 65.28%])
Robust Accuracy: 63.96415%  (CI 95%: [62.84861%, 65.40986%])
Conditional Robust Accuracy: 100.00000%  (CI 95%: [100.00000%, 100.00000%])
Accuracy: 79.88%  (CI 95%: [78.75%, 80.97%])
Robust Accuracy: 79.80584%  (CI 95%: [78.96986%, 80.81193%])
Conditional Robust Accuracy: 99.52301%  (CI 95%: [99.38834%, 99.64282%])
#################lr: 1e-06#############################

Training naive with sgd...

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

[epoch 000000001] loss=36697.019252232 | avg=0.263567181 | rare=3.669675503
[epoch 000000002] loss=36609.113560268 | avg=0.264090906 | rare=3.660884976
[epoch 000000003] loss=19079.830463954 | avg=1.561339580 | rare=1.907826938
[epoch 000000004] loss=834.598013742 | avg=1.766997491 | rare=0.083283102
[epoch 000000005] loss=457.938847133 | avg=1.641072503 | rare=0.045629777
[epoch 000000006] loss=300.213206700 | avg=1.990852799 | rare=0.029822235
[epoch 000000007] loss=257.738561358 | avg=1.853802306 | rare=0.025588476
[epoch 000000008] loss=218.284961155 | avg=1.911748929 | rare=0.021637321
[epoch 000000009] loss=182.054759434 | avg=1.767765565 | rare=0.018028699
[epoch 000000010] loss=159.745092664 | avg=1.773316656 | rare=0.015797178
[epoch 000000011] loss=169.259794508 | avg=1.560016930 | rare=0.016769978
[epoch 000000012] loss=136.185758863 | avg=1.717052656 | rare=0.013446871
[epoch 000000013] loss=111.455260686 | avg=1.964501645 | rare=0.010949076
[epoch 000000014] loss=119.721069336 | avg=1.728578925 | rare=0.011799249
[epoch 000000015] loss=112.346425193 | avg=1.857145352 | rare=0.011048928
[epoch 000000016] loss=108.757921491 | avg=1.586496242 | rare=0.010717142
[epoch 000000017] loss=104.749304090 | avg=1.465863330 | rare=0.010328344
[epoch 000000018] loss=101.246116638 | avg=1.459906740 | rare=0.009978621
[epoch 000000019] loss=96.546494348 | avg=1.493029118 | rare=0.009505346
[epoch 000000020] loss=86.627410616 | avg=1.700903969 | rare=0.008492651
[epoch 000000021] loss=78.281537737 | avg=1.982001807 | rare=0.007629954
[epoch 000000022] loss=88.187410627 | avg=1.392253927 | rare=0.008679516
[epoch 000000023] loss=89.628535679 | avg=1.351597863 | rare=0.008827694
[epoch 000000024] loss=79.398497173 | avg=1.384337885 | rare=0.007801416
[epoch 000000025] loss=82.711751393 | avg=1.453047259 | rare=0.008125870
[epoch 000000026] loss=70.291853496 | avg=1.607484477 | rare=0.006868437
[epoch 000000027] loss=68.815086365 | avg=1.863602034 | rare=0.006695148
[epoch 000000028] loss=70.334158761 | avg=1.395711737 | rare=0.006893845
[epoch 000000029] loss=66.862757819 | avg=1.396308933 | rare=0.006546645
[epoch 000000030] loss=69.258304868 | avg=1.397946613 | rare=0.006786036
[epoch 000000031] loss=69.372935159 | avg=1.402240183 | rare=0.006797070
[epoch 000000032] loss=65.777559825 | avg=1.362449867 | rare=0.006441511
[epoch 000000033] loss=63.313088417 | avg=1.386953831 | rare=0.006192614
[epoch 000000034] loss=67.672479085 | avg=1.362515782 | rare=0.006630996
[epoch 000000035] loss=66.544954300 | avg=1.380862117 | rare=0.006516409
[epoch 000000036] loss=57.258743831 | avg=1.321931362 | rare=0.005593681
[epoch 000000037] loss=59.040796007 | avg=1.346072495 | rare=0.005769472
[epoch 000000038] loss=57.664130620 | avg=1.386045703 | rare=0.005627808
[epoch 000000039] loss=52.257634435 | avg=1.338944903 | rare=0.005091869
[epoch 000000040] loss=57.250470298 | avg=1.304989934 | rare=0.005594548
[epoch 000000041] loss=54.899315425 | avg=1.269485465 | rare=0.005362983
[epoch 000000042] loss=53.717456136 | avg=1.268390068 | rare=0.005244907
[epoch 000000043] loss=49.612493651 | avg=1.223756803 | rare=0.004838874
[epoch 000000044] loss=50.892101152 | avg=1.296682801 | rare=0.004959542
[epoch 000000045] loss=47.768788610 | avg=1.395787179 | rare=0.004637300
[epoch 000000046] loss=49.246302741 | avg=1.400249183 | rare=0.004784605
[epoch 000000047] loss=50.179258892 | avg=1.474562807 | rare=0.004870470
[epoch 000000048] loss=49.658226013 | avg=1.296625827 | rare=0.004836160
[epoch 000000049] loss=50.283573151 | avg=1.324273701 | rare=0.004895930
[epoch 000000050] loss=49.634791919 | avg=1.165874434 | rare=0.004846892
[epoch 000000051] loss=50.410335541 | avg=1.186335381 | rare=0.004922400
[epoch 000000052] loss=48.897478376 | avg=1.248854620 | rare=0.004764862
[epoch 000000053] loss=51.550393786 | avg=1.478102850 | rare=0.005007229
[epoch 000000054] loss=51.508056641 | avg=1.258148866 | rare=0.005024991
[epoch 000000055] loss=47.477085658 | avg=1.480293223 | rare=0.004599679
[epoch 000000056] loss=46.605397769 | avg=1.271989490 | rare=0.004533341
[epoch 000000057] loss=46.266989163 | avg=1.411552923 | rare=0.004485544
[epoch 000000058] loss=47.511067935 | avg=1.295928729 | rare=0.004621514
[epoch 000000059] loss=45.940395355 | avg=1.256144822 | rare=0.004468425
[epoch 000000060] loss=44.731766701 | avg=1.405375089 | rare=0.004332639
[epoch 000000061] loss=47.359714099 | avg=1.422588314 | rare=0.004593713
[epoch 000000062] loss=42.789439883 | avg=1.408461877 | rare=0.004138098
[epoch 000000063] loss=52.584933417 | avg=1.349149495 | rare=0.005123578
[epoch 000000064] loss=47.967537063 | avg=1.397471573 | rare=0.004657007
[epoch 000000065] loss=44.023288727 | avg=1.319230923 | rare=0.004270406
[epoch 000000066] loss=44.206061499 | avg=1.425066748 | rare=0.004278099
[epoch 000000067] loss=45.834818431 | avg=1.216452122 | rare=0.004461837
[epoch 000000068] loss=46.571284498 | avg=1.196745285 | rare=0.004537454
[epoch 000000069] loss=44.856235777 | avg=1.260055874 | rare=0.004359618
[epoch 000000070] loss=40.745993342 | avg=1.372654864 | rare=0.003937334
[epoch 000000071] loss=40.280089651 | avg=1.251132676 | rare=0.003902896
[epoch 000000072] loss=41.833361626 | avg=1.208426884 | rare=0.004062494
[epoch 000000073] loss=40.913357462 | avg=1.285318600 | rare=0.003962804
[epoch 000000074] loss=37.882995061 | avg=1.257879070 | rare=0.003662512
[epoch 000000075] loss=37.742697273 | avg=1.286788676 | rare=0.003645591
[epoch 000000076] loss=33.960713659 | avg=1.266982675 | rare=0.003269373
[epoch 000000077] loss=37.169688361 | avg=1.116215438 | rare=0.003605347
[epoch 000000078] loss=36.068857057 | avg=1.243781975 | rare=0.003482508
[epoch 000000079] loss=41.839992183 | avg=1.308424124 | rare=0.004053157
[epoch 000000080] loss=40.513085365 | avg=1.233062514 | rare=0.003928002
[epoch 000000081] loss=36.905306271 | avg=1.169205197 | rare=0.003573610
[epoch 000000082] loss=34.689167159 | avg=1.340485147 | rare=0.003334868
[epoch 000000083] loss=36.353956086 | avg=1.192750863 | rare=0.003516121
[epoch 000000084] loss=37.844907897 | avg=1.124082744 | rare=0.003672082
[epoch 000000085] loss=42.107482910 | avg=1.156360750 | rare=0.004095112
[epoch 000000086] loss=40.588560649 | avg=1.369324552 | rare=0.003921924
[epoch 000000087] loss=35.672740936 | avg=1.155705141 | rare=0.003451704
[epoch 000000088] loss=36.198983329 | avg=1.053138397 | rare=0.003514585
[epoch 000000089] loss=36.441170692 | avg=1.104272289 | rare=0.003533690
[epoch 000000090] loss=36.328996522 | avg=1.102657561 | rare=0.003522634
[epoch 000000091] loss=35.263665608 | avg=1.085690175 | rare=0.003417798
[epoch 000000092] loss=33.713102681 | avg=1.083557934 | rare=0.003262954
[epoch 000000093] loss=35.383705003 | avg=1.108971545 | rare=0.003427473
[epoch 000000094] loss=32.499305044 | avg=1.231075849 | rare=0.003126823
[epoch 000000095] loss=38.257581506 | avg=1.049748783 | rare=0.003720783
[epoch 000000096] loss=42.763866697 | avg=1.275558361 | rare=0.004148831
[epoch 000000097] loss=35.832273006 | avg=1.087517023 | rare=0.003474476
[epoch 000000098] loss=35.736636843 | avg=1.066927097 | rare=0.003466971
[epoch 000000099] loss=32.524514471 | avg=1.180569921 | rare=0.003134394
[epoch 000000100] loss=33.967573438 | avg=1.030623738 | rare=0.003293695

Training safe with sgd...

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

[epoch 000000001] loss=3860.957676479 | avg=3.283441186 | rare=0.385767424
[epoch 000000002] loss=3857.097726004 | avg=3.295365265 | rare=0.385380238
[epoch 000000003] loss=2033.071321760 | avg=2.727197681 | rare=0.203034411
[epoch 000000004] loss=580.161738804 | avg=1.751111729 | rare=0.057841063
[epoch 000000005] loss=332.279958452 | avg=1.520702967 | rare=0.033075926
[epoch 000000006] loss=247.906984602 | avg=1.475958066 | rare=0.024643103
[epoch 000000007] loss=205.196333749 | avg=1.445955873 | rare=0.020375038
[epoch 000000008] loss=189.058668409 | avg=1.379167531 | rare=0.018767950
[epoch 000000009] loss=193.189547403 | avg=1.363918815 | rare=0.019182563
[epoch 000000010] loss=164.651188442 | avg=1.376880501 | rare=0.016327431
[epoch 000000011] loss=158.383425031 | avg=1.401674773 | rare=0.015698175
[epoch 000000012] loss=151.376453945 | avg=1.382013014 | rare=0.014999444
[epoch 000000013] loss=146.978970119 | avg=1.365109529 | rare=0.014561386
[epoch 000000014] loss=129.837138585 | avg=1.418234783 | rare=0.012841890
[epoch 000000015] loss=131.783560617 | avg=1.377845875 | rare=0.013040572
[epoch 000000016] loss=128.766222818 | avg=1.396326917 | rare=0.012736990
[epoch 000000017] loss=116.099555697 | avg=1.409573827 | rare=0.011468998
[epoch 000000018] loss=114.435877391 | avg=1.403499867 | rare=0.011303238
[epoch 000000019] loss=124.728902544 | avg=1.421989637 | rare=0.012330691
[epoch 000000020] loss=108.511289597 | avg=1.421765310 | rare=0.010708952
[epoch 000000021] loss=104.691044944 | avg=1.428674059 | rare=0.010326237
[epoch 000000022] loss=94.437164579 | avg=1.462755944 | rare=0.009297441
[epoch 000000023] loss=103.104269845 | avg=1.475794469 | rare=0.010162848
[epoch 000000024] loss=99.565497262 | avg=1.486430713 | rare=0.009807907
[epoch 000000025] loss=105.618447168 | avg=1.477977523 | rare=0.010414047
[epoch 000000026] loss=107.523140226 | avg=1.491267306 | rare=0.010603187
[epoch 000000027] loss=90.578517914 | avg=1.518055064 | rare=0.008906046
[epoch 000000028] loss=89.923818861 | avg=1.506665494 | rare=0.008841715
[epoch 000000029] loss=81.777848380 | avg=1.533876095 | rare=0.008024397
[epoch 000000030] loss=72.483172008 | avg=1.542969201 | rare=0.007094020
[epoch 000000031] loss=87.122823988 | avg=1.519110475 | rare=0.008560371
[epoch 000000032] loss=85.673099245 | avg=1.518716122 | rare=0.008415438
[epoch 000000033] loss=87.275382451 | avg=1.517769516 | rare=0.008575761
[epoch 000000034] loss=79.964963913 | avg=1.550046359 | rare=0.007841492
[epoch 000000035] loss=82.076402937 | avg=1.541193528 | rare=0.008053521
[epoch 000000036] loss=65.042811802 | avg=1.555215614 | rare=0.006348760
[epoch 000000037] loss=77.466073990 | avg=1.545232807 | rare=0.007592084
[epoch 000000038] loss=75.547954832 | avg=1.544203256 | rare=0.007400375
[epoch 000000039] loss=76.171548026 | avg=1.520076326 | rare=0.007465147
[epoch 000000040] loss=69.392305919 | avg=1.507058416 | rare=0.006788525
[epoch 000000041] loss=81.369683674 | avg=1.509429336 | rare=0.007986025
[epoch 000000042] loss=96.202875819 | avg=1.529697333 | rare=0.009467318
[epoch 000000043] loss=70.538484846 | avg=1.562081388 | rare=0.006897640
[epoch 000000044] loss=69.123710905 | avg=1.537372010 | rare=0.006758634
[epoch 000000045] loss=73.183895929 | avg=1.548335816 | rare=0.007163556
[epoch 000000046] loss=64.301994051 | avg=1.521218232 | rare=0.006278078
[epoch 000000047] loss=75.259679794 | avg=1.495087590 | rare=0.007376459
[epoch 000000048] loss=66.484294891 | avg=1.509596118 | rare=0.006497470
[epoch 000000049] loss=61.047261102 | avg=1.519471748 | rare=0.005952779
[epoch 000000050] loss=66.986616952 | avg=1.507785993 | rare=0.006547883
[epoch 000000051] loss=64.772700446 | avg=1.499493165 | rare=0.006327321
[epoch 000000052] loss=68.664182118 | avg=1.508730173 | rare=0.006715545
[epoch 000000053] loss=59.430728912 | avg=1.520050526 | rare=0.005791068
[epoch 000000054] loss=54.959571838 | avg=1.516681399 | rare=0.005344289
[epoch 000000055] loss=54.203602791 | avg=1.490694259 | rare=0.005271291
[epoch 000000056] loss=65.326130458 | avg=1.484518043 | rare=0.006384161
[epoch 000000057] loss=74.094023568 | avg=1.487786957 | rare=0.007260624
[epoch 000000058] loss=57.609981264 | avg=1.484786221 | rare=0.005612519
[epoch 000000059] loss=54.707728795 | avg=1.469869605 | rare=0.005323786
[epoch 000000060] loss=69.152297565 | avg=1.467826818 | rare=0.006768447
[epoch 000000061] loss=55.357522147 | avg=1.514703751 | rare=0.005384282
[epoch 000000062] loss=53.098374231 | avg=1.479449621 | rare=0.005161893
[epoch 000000063] loss=52.274475098 | avg=1.474143156 | rare=0.005080033
[epoch 000000064] loss=57.154210227 | avg=1.481052995 | rare=0.005567316
[epoch 000000065] loss=54.656742232 | avg=1.455226685 | rare=0.005320152
[epoch 000000066] loss=50.243731090 | avg=1.466430971 | rare=0.004877730
[epoch 000000067] loss=74.955658640 | avg=1.458764298 | rare=0.007349689
[epoch 000000068] loss=68.193341119 | avg=1.457938612 | rare=0.006673540
[epoch 000000069] loss=47.862143380 | avg=1.458810287 | rare=0.004640333
[epoch 000000070] loss=65.454250336 | avg=1.445011130 | rare=0.006400924
[epoch 000000071] loss=68.996026993 | avg=1.463840510 | rare=0.006753219
[epoch 000000072] loss=64.429155486 | avg=1.440046208 | rare=0.006298911
[epoch 000000073] loss=71.609073775 | avg=1.434868259 | rare=0.007017421
[epoch 000000074] loss=52.218225752 | avg=1.455258957 | rare=0.005076297
[epoch 000000075] loss=79.057969502 | avg=1.470719968 | rare=0.007758725
[epoch 000000076] loss=54.108256749 | avg=1.465676674 | rare=0.005264258
[epoch 000000077] loss=76.213706970 | avg=1.438659855 | rare=0.007477505
[epoch 000000078] loss=53.223668780 | avg=1.451093478 | rare=0.005177258
[epoch 000000079] loss=59.247810228 | avg=1.457554511 | rare=0.005779026
[epoch 000000080] loss=57.136153494 | avg=1.438258989 | rare=0.005569789
[epoch 000000081] loss=65.733349528 | avg=1.448274485 | rare=0.006428507
[epoch 000000082] loss=60.955502101 | avg=1.423040731 | rare=0.005953246
[epoch 000000083] loss=57.677580152 | avg=1.435899947 | rare=0.005624168
[epoch 000000084] loss=52.516603334 | avg=1.403131953 | rare=0.005111347
[epoch 000000085] loss=64.518152509 | avg=1.410491117 | rare=0.006310766
[epoch 000000086] loss=75.194878306 | avg=1.405541122 | rare=0.007378934
[epoch 000000087] loss=51.211313111 | avg=1.384539868 | rare=0.004982677
[epoch 000000088] loss=53.371037074 | avg=1.401726595 | rare=0.005196931
[epoch 000000089] loss=45.747981616 | avg=1.401522066 | rare=0.004434646
[epoch 000000090] loss=49.528450830 | avg=1.398547437 | rare=0.004812990
[epoch 000000091] loss=61.441286087 | avg=1.399252074 | rare=0.006004203
[epoch 000000092] loss=59.216219766 | avg=1.399998665 | rare=0.005781622
[epoch 000000093] loss=91.410976887 | avg=1.378682264 | rare=0.009003230
[epoch 000000094] loss=62.277357101 | avg=1.379777857 | rare=0.006089758
[epoch 000000095] loss=56.899535043 | avg=1.376716707 | rare=0.005552282
[epoch 000000096] loss=53.827122961 | avg=1.362126589 | rare=0.005246500
[epoch 000000097] loss=47.729674067 | avg=1.371900703 | rare=0.004635777
[epoch 000000098] loss=61.699096748 | avg=1.359026705 | rare=0.006034007
[epoch 000000099] loss=71.030925751 | avg=1.384301041 | rare=0.006964662
[epoch 000000100] loss=58.220168522 | avg=1.358504551 | rare=0.005686166
Accuracy: 77.03%  (CI 95%: [75.85%, 78.17%])
Robust Accuracy: 76.95444%  (CI 95%: [76.11368%, 78.16910%])
Conditional Robust Accuracy: 99.30007%  (CI 95%: [99.16932%, 99.43529%])
Accuracy: 79.92%  (CI 95%: [78.79%, 81.01%])
Robust Accuracy: 79.86116%  (CI 95%: [78.96313%, 80.89993%])
Conditional Robust Accuracy: 99.48196%  (CI 95%: [99.35517%, 99.60770%])

In [ ]:

configs = [ ("naive", "adam") ,("safe", "adam")  ]
final_results_adam = {}
for lr in lrs:
    print(f"#################lr: {lr}#############################")
    configs_result = {}
    # result_init = train_all(X_train, y_train,init_model, NUM_EPOCHS, GAMMA, SAMPLES_TRAIN, SIGMA, configs = [ ("naive", "sgd") ] , SAFE_BIAS=15.0, lr=lr, batch_size = BATCH_SIZE )
    # configs_result[("init_naive", "sgd")] = eval_one(
    #                                       result_init[("naive", "sgd")][0], X_test, y_test,
    #                                       sigma=SIGMA, SAMPLES_EVAL=SAMPLES_EVAL,
    #                                       J_chunk=5000,        # <= keep m small
    #                                       N_chunk=512,      # <= keep B small
    #                                       B=300             # <= lighter bootstrap
    #                                   )
    results = train_all(X_train, y_train,pre_model, NUM_EPOCHS, GAMMA, SAMPLES_TRAIN, SIGMA, configs = configs , SAFE_BIAS=15.0, lr=lr, batch_size = BATCH_SIZE )

    for config in configs:
        configs_result[config] = eval_one(
                                          results[config][0], X_test, y_test,
                                          sigma=SIGMA, SAMPLES_EVAL=SAMPLES_EVAL,
                                          J_chunk=5000,        # <= keep m small
                                          N_chunk=512,      # <= keep B small
                                          B=300             # <= lighter bootstrap
                                      )
    final_results_adam[lr] = configs_result

#################lr: 0.1#############################

Training naive with adam...

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

[epoch 000000001] loss=36697.019252232 | avg=0.263567181 | rare=3.669675503
[epoch 000000002] loss=36609.113560268 | avg=0.264090906 | rare=3.660884976
[epoch 000000003] loss=18645.471176147 | avg=54.192323256 | rare=1.859127913
[epoch 000000004] loss=563.105625698 | avg=462.043023246 | rare=0.010106260
[epoch 000000005] loss=1020.963287354 | avg=734.638351440 | rare=0.028632493
[epoch 000000006] loss=1276.839146205 | avg=728.982129778 | rare=0.054785701
[epoch 000000007] loss=1430.391470773 | avg=851.179242815 | rare=0.057921222
[epoch 000000008] loss=1483.265311105 | avg=818.914668492 | rare=0.066435064
[epoch 000000009] loss=1085.031978062 | avg=751.825326102 | rare=0.033320664
[epoch 000000010] loss=994.858263288 | avg=673.832083566 | rare=0.032102617
[epoch 000000011] loss=1075.939444406 | avg=426.186708723 | rare=0.064975273
[epoch 000000012] loss=760.789354597 | avg=537.384222848 | rare=0.022340513
[epoch 000000013] loss=648.379074097 | avg=429.772772653 | rare=0.021860629
[epoch 000000014] loss=549.726795741 | avg=349.792371477 | rare=0.019993443
[epoch 000000015] loss=406.855810983 | avg=299.283763341 | rare=0.010757205
[epoch 000000016] loss=307.182025364 | avg=185.162020002 | rare=0.012202001
[epoch 000000017] loss=256.207011632 | avg=111.309258052 | rare=0.014489775
[epoch 000000018] loss=192.259939466 | avg=84.603338514 | rare=0.010765660
[epoch 000000019] loss=205.193305969 | avg=57.814446313 | rare=0.014737886
[epoch 000000020] loss=83.889396940 | avg=53.894321442 | rare=0.002999507
[epoch 000000021] loss=68.081037521 | avg=42.620431355 | rare=0.002546061
[epoch 000000022] loss=48.289211273 | avg=24.197756904 | rare=0.002409145
[epoch 000000023] loss=135.211827414 | avg=73.192145688 | rare=0.006201968
[epoch 000000024] loss=189.423112052 | avg=160.545322963 | rare=0.002887779
[epoch 000000025] loss=187.573674883 | avg=146.554979597 | rare=0.004101870
[epoch 000000026] loss=174.546416146 | avg=127.280179705 | rare=0.004726623
[epoch 000000027] loss=142.574139186 | avg=102.758252280 | rare=0.003981589
[epoch 000000028] loss=128.294769287 | avg=71.910766602 | rare=0.005638400
[epoch 000000029] loss=100.145205362 | avg=56.322611128 | rare=0.004382259
[epoch 000000030] loss=88.636106491 | avg=43.170028142 | rare=0.004546608
[epoch 000000031] loss=57.842205320 | avg=35.999142374 | rare=0.002184306
[epoch 000000032] loss=35.306942667 | avg=30.901890891 | rare=0.000440505
[epoch 000000033] loss=29.757094519 | avg=25.272658484 | rare=0.000448444
[epoch 000000034] loss=22.631555421 | avg=19.970118659 | rare=0.000266144
[epoch 000000035] loss=21.008969239 | avg=15.613593442 | rare=0.000539538
[epoch 000000036] loss=15.807498796 | avg=11.883125850 | rare=0.000392437
[epoch 000000037] loss=25.239288126 | avg=9.259925774 | rare=0.001597936
[epoch 000000038] loss=25.463520186 | avg=7.063321011 | rare=0.001840020
[epoch 000000039] loss=19.749590397 | avg=4.856454866 | rare=0.001489314
[epoch 000000040] loss=31.632422107 | avg=4.821017844 | rare=0.002681140
[epoch 000000041] loss=100.184384755 | avg=7.072508982 | rare=0.009311187
[epoch 000000042] loss=30.438633306 | avg=5.149800539 | rare=0.002528883
[epoch 000000043] loss=25.243338381 | avg=3.908454282 | rare=0.002133488
[epoch 000000044] loss=21.398954391 | avg=2.905476860 | rare=0.001849348
[epoch 000000045] loss=15.228937200 | avg=2.690354024 | rare=0.001253858
[epoch 000000046] loss=21.329269937 | avg=2.427037358 | rare=0.001890223
[epoch 000000047] loss=20.753898025 | avg=2.244592871 | rare=0.001850931
[epoch 000000048] loss=20.230658770 | avg=1.822331744 | rare=0.001840833
[epoch 000000049] loss=18.908735224 | avg=1.833960542 | rare=0.001707478
[epoch 000000050] loss=32.447114314 | avg=2.095500767 | rare=0.003035161
[epoch 000000051] loss=25.655661983 | avg=2.010632464 | rare=0.002364503
[epoch 000000052] loss=30.150908368 | avg=1.865684237 | rare=0.002828522
[epoch 000000053] loss=26.761326585 | avg=1.935082410 | rare=0.002482624
[epoch 000000054] loss=29.564830235 | avg=1.932546139 | rare=0.002763228
[epoch 000000055] loss=13.430423626 | avg=1.772617544 | rare=0.001165781
[epoch 000000056] loss=17.290893912 | avg=1.835140782 | rare=0.001545575
[epoch 000000057] loss=30.110659259 | avg=2.029961918 | rare=0.002808070
[epoch 000000058] loss=33.000514686 | avg=2.167523026 | rare=0.003083299
[epoch 000000059] loss=23.520757266 | avg=1.976911323 | rare=0.002154385
[epoch 000000060] loss=19.418043375 | avg=1.460517777 | rare=0.001795753
[epoch 000000061] loss=21.588113478 | avg=1.515662474 | rare=0.002007245
[epoch 000000062] loss=32.843536113 | avg=1.590544871 | rare=0.003125299
[epoch 000000063] loss=10.874574627 | avg=1.290255440 | rare=0.000958432
[epoch 000000064] loss=15.345236949 | avg=1.360516650 | rare=0.001398472
[epoch 000000065] loss=16.997316590 | avg=1.305796368 | rare=0.001569152
[epoch 000000066] loss=17.309158879 | avg=0.990079463 | rare=0.001631908
[epoch 000000067] loss=15.018634234 | avg=1.132051310 | rare=0.001388658
[epoch 000000068] loss=8.476405646 | avg=0.923556771 | rare=0.000755285
[epoch 000000069] loss=9.551721062 | avg=1.269561678 | rare=0.000828216
[epoch 000000070] loss=26.813881261 | avg=1.349954362 | rare=0.002546393
[epoch 000000071] loss=17.030701186 | avg=1.121025217 | rare=0.001590968
[epoch 000000072] loss=13.173870270 | avg=1.189523974 | rare=0.001198435
[epoch 000000073] loss=13.835949574 | avg=1.238001619 | rare=0.001259795
[epoch 000000074] loss=16.933819643 | avg=1.156106336 | rare=0.001577771
[epoch 000000075] loss=9.197079884 | avg=1.103592472 | rare=0.000809349
[epoch 000000076] loss=39.794580187 | avg=2.220458891 | rare=0.003757412
[epoch 000000077] loss=19.246535097 | avg=2.396197719 | rare=0.001685034
[epoch 000000078] loss=21.669244017 | avg=2.452548444 | rare=0.001921670
[epoch 000000079] loss=12.472853831 | avg=1.765534231 | rare=0.001070732
[epoch 000000080] loss=13.226879409 | avg=1.612926756 | rare=0.001161395
[epoch 000000081] loss=14.346269710 | avg=1.429352105 | rare=0.001291692
[epoch 000000082] loss=8.583004057 | avg=1.069003024 | rare=0.000751400
[epoch 000000083] loss=8.777170002 | avg=1.147875164 | rare=0.000762929
[epoch 000000084] loss=12.180618312 | avg=1.174320787 | rare=0.001100630
[epoch 000000085] loss=7.216348938 | avg=0.940261223 | rare=0.000627609
[epoch 000000086] loss=4.719949228 | avg=0.826531674 | rare=0.000389342
[epoch 000000087] loss=6.598797087 | avg=0.800310965 | rare=0.000579849
[epoch 000000088] loss=2.471249700 | avg=0.730079008 | rare=0.000174117
[epoch 000000089] loss=4.987566352 | avg=0.738433485 | rare=0.000424913
[epoch 000000090] loss=2.248429737 | avg=0.697362240 | rare=0.000155107
[epoch 000000091] loss=6.110140345 | avg=0.687272276 | rare=0.000542287
[epoch 000000092] loss=0.886010732 | avg=0.676247226 | rare=0.000020976
[epoch 000000093] loss=1.123500598 | avg=0.679181763 | rare=0.000044432
[epoch 000000094] loss=0.717453731 | avg=0.678036843 | rare=0.000003942
[epoch 000000095] loss=0.680970124 | avg=0.678741085 | rare=0.000000223
[epoch 000000096] loss=0.680028119 | avg=0.678146609 | rare=0.000000188
[epoch 000000097] loss=0.678204366 | avg=0.677722812 | rare=0.000000048
[epoch 000000098] loss=0.677263341 | avg=0.677119604 | rare=0.000000014
[epoch 000000099] loss=0.676823467 | avg=0.676693593 | rare=0.000000013
[epoch 000000100] loss=0.676022061 | avg=0.675953929 | rare=0.000000007

Training safe with adam...

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

[epoch 000000001] loss=3860.957676479 | avg=3.283441186 | rare=0.385767424
[epoch 000000002] loss=3857.097726004 | avg=3.295365265 | rare=0.385380238
[epoch 000000003] loss=1697.328764234 | avg=128.237618991 | rare=0.156909113
[epoch 000000004] loss=762.552219936 | avg=449.710715158 | rare=0.031284150
[epoch 000000005] loss=739.087201800 | avg=622.761755807 | rare=0.011632545
[epoch 000000006] loss=591.865676880 | avg=419.586201259 | rare=0.017227948
[epoch 000000007] loss=561.757093157 | avg=275.315417698 | rare=0.028644168
[epoch 000000008] loss=387.559828622 | avg=221.506949289 | rare=0.016605288
[epoch 000000009] loss=345.030116490 | avg=90.331972667 | rare=0.025469815
[epoch 000000010] loss=136.118590219 | avg=30.572798184 | rare=0.010554579
[epoch 000000011] loss=137.374580928 | avg=28.275424072 | rare=0.010909916
[epoch 000000012] loss=160.245217460 | avg=55.837660926 | rare=0.010440756
[epoch 000000013] loss=79.209598814 | avg=41.462049757 | rare=0.003774755
[epoch 000000014] loss=109.719273703 | avg=27.211799622 | rare=0.008250748
[epoch 000000015] loss=92.082671574 | avg=19.472284658 | rare=0.007261039
[epoch 000000016] loss=44.078243256 | avg=9.791139432 | rare=0.003428710
[epoch 000000017] loss=137.968470710 | avg=25.599903975 | rare=0.011236857
[epoch 000000018] loss=117.331700189 | avg=49.576466697 | rare=0.006775523
[epoch 000000019] loss=113.346271515 | avg=41.522486550 | rare=0.007182378
[epoch 000000020] loss=121.887262072 | avg=19.533207348 | rare=0.010235405
[epoch 000000021] loss=72.890748024 | avg=14.545739617 | rare=0.005834501
[epoch 000000022] loss=45.421313286 | avg=5.843291964 | rare=0.003957802
[epoch 000000023] loss=34.661544561 | avg=5.804254532 | rare=0.002885729
[epoch 000000024] loss=52.867336546 | avg=5.080669522 | rare=0.004778667
[epoch 000000025] loss=31.772417205 | avg=3.458996756 | rare=0.002831342
[epoch 000000026] loss=32.440681594 | avg=2.563232005 | rare=0.002987745
[epoch 000000027] loss=24.459430967 | avg=2.523694464 | rare=0.002193574
[epoch 000000028] loss=25.931321280 | avg=2.493401732 | rare=0.002343792
[epoch 000000029] loss=22.504977669 | avg=2.174569224 | rare=0.002033041
[epoch 000000030] loss=25.126811777 | avg=2.105119543 | rare=0.002302169
[epoch 000000031] loss=41.806086745 | avg=3.108650020 | rare=0.003869744
[epoch 000000032] loss=23.146012000 | avg=3.158701054 | rare=0.001998731
[epoch 000000033] loss=48.145556927 | avg=4.697971412 | rare=0.004344759
[epoch 000000034] loss=46.785024643 | avg=7.926431622 | rare=0.003885859
[epoch 000000035] loss=25.261929240 | avg=4.909699610 | rare=0.002035223
[epoch 000000036] loss=30.054199253 | avg=4.387122035 | rare=0.002566708
[epoch 000000037] loss=37.487895966 | avg=5.874489103 | rare=0.003161341
[epoch 000000038] loss=20.780840261 | avg=3.934138758 | rare=0.001684670
[epoch 000000039] loss=17.512227058 | avg=2.933352394 | rare=0.001457887
[epoch 000000040] loss=20.998561076 | avg=3.777248468 | rare=0.001722131
[epoch 000000041] loss=27.641455718 | avg=3.819301827 | rare=0.002382215
[epoch 000000042] loss=25.069238390 | avg=3.848576375 | rare=0.002122066
[epoch 000000043] loss=26.449957848 | avg=4.275797248 | rare=0.002217416
[epoch 000000044] loss=43.947986603 | avg=4.985695158 | rare=0.003896229
[epoch 000000045] loss=26.227476290 | avg=7.430114065 | rare=0.001879736
[epoch 000000046] loss=65.928186485 | avg=6.156693084 | rare=0.005977149
[epoch 000000047] loss=30.895101070 | avg=7.372231415 | rare=0.002352287
[epoch 000000048] loss=148.079679217 | avg=11.791881357 | rare=0.013628780
[epoch 000000049] loss=292.666238512 | avg=54.914644991 | rare=0.023775160
[epoch 000000050] loss=331.961298261 | avg=118.000364849 | rare=0.021396093
[epoch 000000051] loss=134.697641100 | avg=65.296478680 | rare=0.006940117
[epoch 000000052] loss=48.783877781 | avg=20.644179412 | rare=0.002813970
[epoch 000000053] loss=47.841948100 | avg=13.738396917 | rare=0.003410355
[epoch 000000054] loss=34.779587337 | avg=6.487787809 | rare=0.002829180
[epoch 000000055] loss=49.598880563 | avg=4.820744344 | rare=0.004477814
[epoch 000000056] loss=32.771780150 | avg=2.615764030 | rare=0.003015602
[epoch 000000057] loss=25.176797186 | avg=2.330386758 | rare=0.002284641
[epoch 000000058] loss=26.496747289 | avg=2.717951536 | rare=0.002377880
[epoch 000000059] loss=25.403219155 | avg=2.980726089 | rare=0.002242249
[epoch 000000060] loss=18.165462834 | avg=3.311916998 | rare=0.001485355
[epoch 000000061] loss=23.190468448 | avg=3.152457527 | rare=0.002003801
[epoch 000000062] loss=27.923787662 | avg=2.927294629 | rare=0.002499649
[epoch 000000063] loss=17.687156950 | avg=2.826479963 | rare=0.001486068
[epoch 000000064] loss=16.599486487 | avg=3.044102958 | rare=0.001355538
[epoch 000000065] loss=32.584957327 | avg=3.450154492 | rare=0.002913480
[epoch 000000066] loss=32.947749547 | avg=3.343535423 | rare=0.002960421
[epoch 000000067] loss=26.882782391 | avg=3.562783020 | rare=0.002332000
[epoch 000000068] loss=9.034514427 | avg=6.463771497 | rare=0.000257074
[epoch 000000069] loss=9.666273458 | avg=9.666273458 | rare=0.000000000
[epoch 000000070] loss=12.814286232 | avg=6.772992151 | rare=0.000604129
[epoch 000000071] loss=40.134355000 | avg=3.819471683 | rare=0.003631488
[epoch 000000072] loss=26.947658198 | avg=3.297956024 | rare=0.002364970
[epoch 000000073] loss=18.876133306 | avg=2.579132983 | rare=0.001629700
[epoch 000000074] loss=15.689145224 | avg=2.589099663 | rare=0.001310005
[epoch 000000075] loss=16.469309841 | avg=3.076707550 | rare=0.001339260
[epoch 000000076] loss=7.826050929 | avg=6.724766731 | rare=0.000110128
[epoch 000000077] loss=138.937899249 | avg=37.935555901 | rare=0.010100234
[epoch 000000078] loss=942.939466204 | avg=900.723783221 | rare=0.004221567
[epoch 000000079] loss=318.936905452 | avg=311.269845009 | rare=0.000766706
[epoch 000000080] loss=308.892717634 | avg=90.150382451 | rare=0.021874233
[epoch 000000081] loss=94.528271948 | avg=16.559543133 | rare=0.007796873
[epoch 000000082] loss=39.011601448 | avg=9.931263106 | rare=0.002908034
[epoch 000000083] loss=14.473290954 | avg=5.164189816 | rare=0.000930910
[epoch 000000084] loss=32.366740772 | avg=5.056607178 | rare=0.002731013
[epoch 000000085] loss=16.839702232 | avg=4.773775135 | rare=0.001206593
[epoch 000000086] loss=17.836713859 | avg=5.220215763 | rare=0.001261650
[epoch 000000087] loss=12.150821073 | avg=7.391546760 | rare=0.000475927
[epoch 000000088] loss=31.721865416 | avg=6.255947556 | rare=0.002546592
[epoch 000000089] loss=37.497287886 | avg=4.103720597 | rare=0.003339357
[epoch 000000090] loss=8.953909601 | avg=5.561006818 | rare=0.000339290
[epoch 000000091] loss=33.574861935 | avg=5.697062526 | rare=0.002787780
[epoch 000000092] loss=54.904339245 | avg=4.744522503 | rare=0.005015982
[epoch 000000093] loss=8.923544441 | avg=5.903637971 | rare=0.000301991
[epoch 000000094] loss=56.122287273 | avg=19.622255700 | rare=0.003650003
[epoch 000000095] loss=222.347389221 | avg=204.030926296 | rare=0.001831646
[epoch 000000096] loss=140.308281830 | avg=22.233353342 | rare=0.011807493
[epoch 000000097] loss=22.347646645 | avg=5.866303052 | rare=0.001648134
[epoch 000000098] loss=10.654620954 | avg=7.293665137 | rare=0.000336096
[epoch 000000099] loss=31.736221143 | avg=8.145208836 | rare=0.002359101
[epoch 000000100] loss=67.201598712 | avg=7.120607802 | rare=0.006008099
Accuracy: 64.14%  (CI 95%: [62.81%, 65.46%])
Robust Accuracy: 64.13956%  (CI 95%: [63.02746%, 65.59056%])
Conditional Robust Accuracy: 99.99392%  (CI 95%: [99.97863%, 100.00000%])
Accuracy: 73.49%  (CI 95%: [72.25%, 74.69%])
Robust Accuracy: 73.49722%  (CI 95%: [72.41470%, 74.75343%])
Conditional Robust Accuracy: 99.91129%  (CI 95%: [99.86509%, 99.95982%])
#################lr: 0.01#############################

Training naive with adam...

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

[epoch 000000001] loss=36697.019252232 | avg=0.263567181 | rare=3.669675503
[epoch 000000002] loss=36609.113560268 | avg=0.264090906 | rare=3.660884976
[epoch 000000003] loss=18764.617246355 | avg=2.179396439 | rare=1.876243812
[epoch 000000004] loss=316.600503104 | avg=6.170247589 | rare=0.031043025
[epoch 000000005] loss=469.174909319 | avg=5.595555612 | rare=0.046357936
[epoch 000000006] loss=654.198172433 | avg=4.245711940 | rare=0.064995245
[epoch 000000007] loss=440.760160174 | avg=3.812788606 | rare=0.043694737
[epoch 000000008] loss=406.457754953 | avg=3.237344572 | rare=0.040322041
[epoch 000000009] loss=316.772722517 | avg=2.753774064 | rare=0.031401895
[epoch 000000010] loss=241.325415475 | avg=2.534280539 | rare=0.023879114
[epoch 000000011] loss=142.203258514 | avg=2.269113277 | rare=0.013993414
[epoch 000000012] loss=129.265516554 | avg=2.026989213 | rare=0.012723853
[epoch 000000013] loss=135.341711317 | avg=1.836277119 | rare=0.013350543
[epoch 000000014] loss=149.824940545 | avg=1.712547473 | rare=0.014811239
[epoch 000000015] loss=98.340797152 | avg=1.721929584 | rare=0.009661887
[epoch 000000016] loss=117.854558672 | avg=1.576195981 | rare=0.011627836
[epoch 000000017] loss=96.983229228 | avg=1.646716475 | rare=0.009533651
[epoch 000000018] loss=119.548415593 | avg=1.545170614 | rare=0.011800325
[epoch 000000019] loss=98.199773243 | avg=1.473253497 | rare=0.009672652
[epoch 000000020] loss=124.241226196 | avg=1.456037768 | rare=0.012278519
[epoch 000000021] loss=123.910014016 | avg=1.646122873 | rare=0.012226389
[epoch 000000022] loss=124.684147426 | avg=1.520528070 | rare=0.012316362
[epoch 000000023] loss=96.028937476 | avg=1.474094893 | rare=0.009455484
[epoch 000000024] loss=89.104460580 | avg=1.766547126 | rare=0.008733791
[epoch 000000025] loss=72.956901005 | avg=1.745189386 | rare=0.007121171
[epoch 000000026] loss=78.091049467 | avg=1.801288426 | rare=0.007628976
[epoch 000000027] loss=85.649871009 | avg=2.103562415 | rare=0.008354631
[epoch 000000028] loss=77.648813520 | avg=2.085134080 | rare=0.007556368
[epoch 000000029] loss=67.295961108 | avg=1.691703328 | rare=0.006560426
[epoch 000000030] loss=69.804435458 | avg=1.470476031 | rare=0.006833396
[epoch 000000031] loss=57.803503309 | avg=1.366879003 | rare=0.005643662
[epoch 000000032] loss=67.107018335 | avg=1.505849574 | rare=0.006560117
[epoch 000000033] loss=52.624987738 | avg=1.283550169 | rare=0.005134144
[epoch 000000034] loss=73.632804871 | avg=1.516278974 | rare=0.007211653
[epoch 000000035] loss=65.831964629 | avg=2.117775611 | rare=0.006371419
[epoch 000000036] loss=73.264819418 | avg=2.017659281 | rare=0.007124716
[epoch 000000037] loss=73.915224348 | avg=1.790102499 | rare=0.007212512
[epoch 000000038] loss=66.454562051 | avg=1.884673774 | rare=0.006456989
[epoch 000000039] loss=57.805436816 | avg=1.526406416 | rare=0.005627903
[epoch 000000040] loss=51.005790983 | avg=1.223657587 | rare=0.004978213
[epoch 000000041] loss=51.844215257 | avg=1.155798197 | rare=0.005068842
[epoch 000000042] loss=42.206897463 | avg=1.177796398 | rare=0.004102910
[epoch 000000043] loss=52.939083917 | avg=1.097283142 | rare=0.005184180
[epoch 000000044] loss=45.652143070 | avg=1.007857391 | rare=0.004464429
[epoch 000000045] loss=39.138539723 | avg=0.961607571 | rare=0.003817693
[epoch 000000046] loss=42.608817237 | avg=0.959443246 | rare=0.004164937
[epoch 000000047] loss=39.772143500 | avg=0.955096023 | rare=0.003881705
[epoch 000000048] loss=31.516607012 | avg=1.003166854 | rare=0.003051344
[epoch 000000049] loss=41.921643393 | avg=1.041986529 | rare=0.004087966
[epoch 000000050] loss=43.179045813 | avg=1.034367263 | rare=0.004214468
[epoch 000000051] loss=48.211972645 | avg=1.434026582 | rare=0.004677795
[epoch 000000052] loss=39.322490828 | avg=1.197424139 | rare=0.003812507
[epoch 000000053] loss=51.110769272 | avg=1.196017487 | rare=0.004991475
[epoch 000000054] loss=35.872700283 | avg=1.195594817 | rare=0.003467711
[epoch 000000055] loss=42.070131574 | avg=1.320903608 | rare=0.004074923
[epoch 000000056] loss=34.009561811 | avg=1.200739690 | rare=0.003280882
[epoch 000000057] loss=43.740532875 | avg=1.212288214 | rare=0.004252825
[epoch 000000058] loss=39.869447708 | avg=1.052024918 | rare=0.003881742
[epoch 000000059] loss=38.928605080 | avg=1.043501675 | rare=0.003788510
[epoch 000000060] loss=38.400116103 | avg=1.100508473 | rare=0.003729961
[epoch 000000061] loss=39.554191181 | avg=1.177791676 | rare=0.003837640
[epoch 000000062] loss=34.065315110 | avg=1.128104891 | rare=0.003293721
[epoch 000000063] loss=32.289807320 | avg=1.032809415 | rare=0.003125700
[epoch 000000064] loss=26.155753272 | avg=1.025500442 | rare=0.002513025
[epoch 000000065] loss=25.747597899 | avg=1.133861678 | rare=0.002461374
[epoch 000000066] loss=33.480210849 | avg=1.179773271 | rare=0.003230044
[epoch 000000067] loss=37.671151706 | avg=1.191231804 | rare=0.003647992
[epoch 000000068] loss=37.363495009 | avg=1.289208029 | rare=0.003607429
[epoch 000000069] loss=29.962677343 | avg=1.073030744 | rare=0.002888965
[epoch 000000070] loss=35.684642383 | avg=1.090004419 | rare=0.003459464
[epoch 000000071] loss=28.754208292 | avg=1.047807187 | rare=0.002770640
[epoch 000000072] loss=31.419594628 | avg=1.030069245 | rare=0.003038953
[epoch 000000073] loss=32.833746229 | avg=1.193542314 | rare=0.003164020
[epoch 000000074] loss=36.556835175 | avg=0.998800563 | rare=0.003555803
[epoch 000000075] loss=29.583424773 | avg=0.989615636 | rare=0.002859381
[epoch 000000076] loss=30.114021778 | avg=1.035308702 | rare=0.002907871
[epoch 000000077] loss=28.896998950 | avg=0.994692726 | rare=0.002790231
[epoch 000000078] loss=26.953408582 | avg=1.196206842 | rare=0.002575720
[epoch 000000079] loss=27.641451359 | avg=1.054552019 | rare=0.002658690
[epoch 000000080] loss=29.657581942 | avg=1.118232557 | rare=0.002853935
[epoch 000000081] loss=32.813587734 | avg=1.143826808 | rare=0.003166976
[epoch 000000082] loss=30.021962166 | avg=1.017887269 | rare=0.002900407
[epoch 000000083] loss=25.065830605 | avg=1.099411815 | rare=0.002396642
[epoch 000000084] loss=39.512353897 | avg=1.087196661 | rare=0.003842516
[epoch 000000085] loss=33.778243610 | avg=1.039990251 | rare=0.003273825
[epoch 000000086] loss=34.101482187 | avg=1.036005544 | rare=0.003306548
[epoch 000000087] loss=38.660244942 | avg=0.975686801 | rare=0.003768456
[epoch 000000088] loss=25.162400382 | avg=0.997430546 | rare=0.002416497
[epoch 000000089] loss=26.435612951 | avg=0.950891776 | rare=0.002548472
[epoch 000000090] loss=20.908809049 | avg=0.985933002 | rare=0.001992288
[epoch 000000091] loss=28.545219081 | avg=1.058262071 | rare=0.002748696
[epoch 000000092] loss=26.838123594 | avg=0.984367102 | rare=0.002585376
[epoch 000000093] loss=23.759645053 | avg=1.048684444 | rare=0.002271096
[epoch 000000094] loss=23.463383130 | avg=0.909209430 | rare=0.002255417
[epoch 000000095] loss=27.434795243 | avg=0.912379963 | rare=0.002652242
[epoch 000000096] loss=20.312329497 | avg=0.863932188 | rare=0.001944840
[epoch 000000097] loss=24.386926787 | avg=0.883706131 | rare=0.002350322
[epoch 000000098] loss=21.368557044 | avg=0.921341232 | rare=0.002044722
[epoch 000000099] loss=22.492565700 | avg=0.834218149 | rare=0.002165835
[epoch 000000100] loss=22.699904782 | avg=0.920603058 | rare=0.002177930

Training safe with adam...

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

[epoch 000000001] loss=3860.957676479 | avg=3.283441186 | rare=0.385767424
[epoch 000000002] loss=3857.097726004 | avg=3.295365265 | rare=0.385380238
[epoch 000000003] loss=1607.842960903 | avg=4.973445450 | rare=0.160286951
[epoch 000000004] loss=456.804510934 | avg=5.585043328 | rare=0.045121946
[epoch 000000005] loss=598.060869489 | avg=4.395150900 | rare=0.059366573
[epoch 000000006] loss=348.972427368 | avg=4.343806386 | rare=0.034462862
[epoch 000000007] loss=119.716769082 | avg=5.033644710 | rare=0.011468312
[epoch 000000008] loss=91.686097009 | avg=4.798989398 | rare=0.008688711
[epoch 000000009] loss=62.503628322 | avg=4.481659974 | rare=0.005802197
[epoch 000000010] loss=57.697049686 | avg=4.423358951 | rare=0.005327369
[epoch 000000011] loss=48.339669364 | avg=4.311665859 | rare=0.004402800
[epoch 000000012] loss=57.921560832 | avg=4.834598047 | rare=0.005308696
[epoch 000000013] loss=57.088959830 | avg=4.033361520 | rare=0.005305560
[epoch 000000014] loss=58.146972656 | avg=3.431999683 | rare=0.005471497
[epoch 000000015] loss=97.186075211 | avg=3.086356657 | rare=0.009409972
[epoch 000000016] loss=83.691357749 | avg=3.103540591 | rare=0.008058782
[epoch 000000017] loss=75.116504397 | avg=3.161734973 | rare=0.007195477
[epoch 000000018] loss=145.430849893 | avg=2.126480622 | rare=0.014330437
[epoch 000000019] loss=89.001620429 | avg=1.826041656 | rare=0.008717558
[epoch 000000020] loss=70.918501445 | avg=1.965914658 | rare=0.006895259
[epoch 000000021] loss=68.763238634 | avg=2.028552396 | rare=0.006673469
[epoch 000000022] loss=78.307839530 | avg=1.962399210 | rare=0.007634544
[epoch 000000023] loss=67.634177617 | avg=2.164309527 | rare=0.006546987
[epoch 000000024] loss=67.163612502 | avg=1.918219575 | rare=0.006524539
[epoch 000000025] loss=89.530411039 | avg=1.941451677 | rare=0.008758896
[epoch 000000026] loss=86.660670417 | avg=1.912744735 | rare=0.008474793
[epoch 000000027] loss=112.556395394 | avg=2.124129142 | rare=0.011043227
[epoch 000000028] loss=85.507672719 | avg=1.790960201 | rare=0.008371671
[epoch 000000029] loss=100.125074659 | avg=1.730214494 | rare=0.009839486
[epoch 000000030] loss=91.381039483 | avg=1.517094484 | rare=0.008986394
[epoch 000000031] loss=79.251494953 | avg=1.730776523 | rare=0.007752072
[epoch 000000032] loss=69.914327077 | avg=1.541759099 | rare=0.006837257
[epoch 000000033] loss=67.666497912 | avg=1.479081009 | rare=0.006618742
[epoch 000000034] loss=65.821820940 | avg=1.842882344 | rare=0.006397894
[epoch 000000035] loss=65.450623921 | avg=1.475189303 | rare=0.006397543
[epoch 000000036] loss=55.567638261 | avg=1.491126912 | rare=0.005407651
[epoch 000000037] loss=75.379806246 | avg=1.619074319 | rare=0.007376073
[epoch 000000038] loss=74.848353454 | avg=1.686344956 | rare=0.007316201
[epoch 000000039] loss=89.280186244 | avg=1.662617019 | rare=0.008761757
[epoch 000000040] loss=67.482201440 | avg=1.818745843 | rare=0.006566346
[epoch 000000041] loss=91.485408306 | avg=1.641962775 | rare=0.008984345
[epoch 000000042] loss=70.598708289 | avg=1.625176200 | rare=0.006897353
[epoch 000000043] loss=79.635693141 | avg=1.658158915 | rare=0.007797754
[epoch 000000044] loss=52.974154745 | avg=1.753127200 | rare=0.005122103
[epoch 000000045] loss=73.359504700 | avg=1.782600667 | rare=0.007157690
[epoch 000000046] loss=61.751201493 | avg=1.695323723 | rare=0.006005588
[epoch 000000047] loss=71.160579136 | avg=1.720528219 | rare=0.006944005
[epoch 000000048] loss=60.479865755 | avg=1.591567005 | rare=0.005888830
[epoch 000000049] loss=59.566604478 | avg=1.562831904 | rare=0.005800377
[epoch 000000050] loss=52.710669790 | avg=1.465564345 | rare=0.005124510
[epoch 000000051] loss=60.554942948 | avg=1.547537114 | rare=0.005900741
[epoch 000000052] loss=64.119485174 | avg=1.368113663 | rare=0.006275137
[epoch 000000053] loss=61.687523433 | avg=1.487462810 | rare=0.006020006
[epoch 000000054] loss=49.372929028 | avg=1.321092197 | rare=0.004805184
[epoch 000000055] loss=45.309664045 | avg=1.265575698 | rare=0.004404409
[epoch 000000056] loss=73.072606632 | avg=1.324846949 | rare=0.007174776
[epoch 000000057] loss=71.333437102 | avg=1.367410455 | rare=0.006996603
[epoch 000000058] loss=43.235949925 | avg=1.340404417 | rare=0.004189555
[epoch 000000059] loss=60.601783616 | avg=1.385379655 | rare=0.005921641
[epoch 000000060] loss=54.183595249 | avg=1.339141965 | rare=0.005284445
[epoch 000000061] loss=55.112915720 | avg=1.327533032 | rare=0.005378538
[epoch 000000062] loss=47.130706515 | avg=1.336459662 | rare=0.004579425
[epoch 000000063] loss=66.605644090 | avg=1.449773282 | rare=0.006515587
[epoch 000000064] loss=57.080329759 | avg=1.523456837 | rare=0.005555687
[epoch 000000065] loss=128.318070820 | avg=1.839741204 | rare=0.012647833
[epoch 000000066] loss=46.508866106 | avg=2.136755407 | rare=0.004437211
[epoch 000000067] loss=52.430873326 | avg=1.581912662 | rare=0.005084896
[epoch 000000068] loss=52.167775563 | avg=1.694707377 | rare=0.005047307
[epoch 000000069] loss=75.845867429 | avg=1.432082389 | rare=0.007441378
[epoch 000000070] loss=59.766714232 | avg=1.596929678 | rare=0.005816978
[epoch 000000071] loss=63.903767450 | avg=1.482895110 | rare=0.006242087
[epoch 000000072] loss=59.393262454 | avg=1.559363050 | rare=0.005783390
[epoch 000000073] loss=77.151848112 | avg=1.433954247 | rare=0.007571789
[epoch 000000074] loss=47.287350450 | avg=1.497924336 | rare=0.004578943
[epoch 000000075] loss=57.620634079 | avg=1.703260320 | rare=0.005591737
[epoch 000000076] loss=45.823324067 | avg=1.519546815 | rare=0.004430378
[epoch 000000077] loss=55.992766789 | avg=1.308318589 | rare=0.005468445
[epoch 000000078] loss=63.567611490 | avg=1.617568604 | rare=0.006195004
[epoch 000000079] loss=68.254085268 | avg=1.316041972 | rare=0.006693804
[epoch 000000080] loss=47.635349546 | avg=1.253038751 | rare=0.004638231
[epoch 000000081] loss=45.638722828 | avg=1.370882630 | rare=0.004426784
[epoch 000000082] loss=45.425788879 | avg=1.417827189 | rare=0.004400796
[epoch 000000083] loss=82.841262272 | avg=1.622734623 | rare=0.008121853
[epoch 000000084] loss=41.354496956 | avg=1.255992098 | rare=0.004009850
[epoch 000000085] loss=40.167576926 | avg=1.233179961 | rare=0.003893440
[epoch 000000086] loss=29.985721656 | avg=1.310432604 | rare=0.002867529
[epoch 000000087] loss=38.657180037 | avg=1.508047210 | rare=0.003714913
[epoch 000000088] loss=85.362377439 | avg=1.732767778 | rare=0.008362961
[epoch 000000089] loss=69.342982701 | avg=1.845071614 | rare=0.006749791
[epoch 000000090] loss=68.336200714 | avg=1.646280289 | rare=0.006668992
[epoch 000000091] loss=65.920588630 | avg=1.476497250 | rare=0.006444409
[epoch 000000092] loss=54.366234779 | avg=1.563277543 | rare=0.005280296
[epoch 000000093] loss=89.706933703 | avg=1.551244148 | rare=0.008815569
[epoch 000000094] loss=53.535662787 | avg=1.565691224 | rare=0.005196997
[epoch 000000095] loss=74.755365917 | avg=1.407925333 | rare=0.007334744
[epoch 000000096] loss=49.307957241 | avg=1.618659701 | rare=0.004768930
[epoch 000000097] loss=62.297830037 | avg=1.447933078 | rare=0.006084990
[epoch 000000098] loss=50.578577995 | avg=1.787325314 | rare=0.004879125
[epoch 000000099] loss=75.808316367 | avg=1.540623861 | rare=0.007426769
[epoch 000000100] loss=52.728733744 | avg=1.576371329 | rare=0.005115236
Accuracy: 82.27%  (CI 95%: [81.19%, 83.30%])
Robust Accuracy: 82.27462%  (CI 95%: [81.40089%, 83.38100%])
Conditional Robust Accuracy: 99.55602%  (CI 95%: [99.46360%, 99.65554%])
Accuracy: 82.05%  (CI 95%: [80.97%, 83.09%])
Robust Accuracy: 81.96712%  (CI 95%: [81.05309%, 83.01455%])
Conditional Robust Accuracy: 99.13101%  (CI 95%: [98.98298%, 99.26651%])
#################lr: 0.001#############################

Training naive with adam...

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

[epoch 000000001] loss=36697.019252232 | avg=0.263567181 | rare=3.669675503
[epoch 000000002] loss=36609.113560268 | avg=0.264090906 | rare=3.660884976
[epoch 000000003] loss=25755.617396763 | avg=0.607099998 | rare=2.575501059
[epoch 000000004] loss=1896.100476946 | avg=2.259390014 | rare=0.189384112
[epoch 000000005] loss=903.340227400 | avg=2.510532175 | rare=0.090082970
[epoch 000000006] loss=672.960477557 | avg=2.539234298 | rare=0.067042123
[epoch 000000007] loss=616.944002424 | avg=2.471927490 | rare=0.061447208
[epoch 000000008] loss=643.154157366 | avg=2.365679196 | rare=0.064078847
[epoch 000000009] loss=756.961887905 | avg=2.242409161 | rare=0.075471948
[epoch 000000010] loss=676.785901751 | avg=2.198186355 | rare=0.067458771
[epoch 000000011] loss=781.656018938 | avg=2.075671187 | rare=0.077958035
[epoch 000000012] loss=759.989798410 | avg=2.019301840 | rare=0.075797050
[epoch 000000013] loss=829.407527379 | avg=1.861934747 | rare=0.082754560
[epoch 000000014] loss=819.062094552 | avg=1.778869561 | rare=0.081728322
[epoch 000000015] loss=793.810198103 | avg=1.701329981 | rare=0.079210886
[epoch 000000016] loss=803.868678502 | avg=1.582250919 | rare=0.080228643
[epoch 000000017] loss=812.883313860 | avg=1.472670555 | rare=0.081141065
[epoch 000000018] loss=777.377393450 | avg=1.382089385 | rare=0.077599531
[epoch 000000019] loss=759.552777972 | avg=1.276247467 | rare=0.075827653
[epoch 000000020] loss=846.704010010 | avg=1.123179891 | rare=0.084558082
[epoch 000000021] loss=794.894910540 | avg=1.037045670 | rare=0.079385786
[epoch 000000022] loss=637.706122262 | avg=1.031061083 | rare=0.063667506
[epoch 000000023] loss=558.021582467 | avg=1.022429756 | rare=0.055699915
[epoch 000000024] loss=510.301864624 | avg=1.016634771 | rare=0.050928523
[epoch 000000025] loss=458.909569877 | avg=1.021628618 | rare=0.045788794
[epoch 000000026] loss=416.090541295 | avg=1.011933178 | rare=0.041507861
[epoch 000000027] loss=372.617923192 | avg=1.018935331 | rare=0.037159899
[epoch 000000028] loss=333.206739153 | avg=1.012509342 | rare=0.033219423
[epoch 000000029] loss=293.527290344 | avg=1.000796774 | rare=0.029252649
[epoch 000000030] loss=281.037842887 | avg=0.984064145 | rare=0.028005378
[epoch 000000031] loss=255.136046273 | avg=0.963996048 | rare=0.025417205
[epoch 000000032] loss=240.147043501 | avg=0.932653010 | rare=0.023921439
[epoch 000000033] loss=231.602928162 | avg=0.914848328 | rare=0.023068808
[epoch 000000034] loss=225.373853411 | avg=0.895381050 | rare=0.022447847
[epoch 000000035] loss=215.511402675 | avg=0.878669462 | rare=0.021463273
[epoch 000000036] loss=199.621867589 | avg=0.895977604 | rare=0.019872589
[epoch 000000037] loss=190.373784746 | avg=0.861052620 | rare=0.018951273
[epoch 000000038] loss=175.038372585 | avg=0.856508489 | rare=0.017418186
[epoch 000000039] loss=168.390785217 | avg=0.837663127 | rare=0.016755312
[epoch 000000040] loss=157.524431501 | avg=0.831273185 | rare=0.015669316
[epoch 000000041] loss=157.253347124 | avg=0.823190319 | rare=0.015643015
[epoch 000000042] loss=140.968275343 | avg=0.826135827 | rare=0.014014214
[epoch 000000043] loss=138.716907501 | avg=0.823239199 | rare=0.013789367
[epoch 000000044] loss=129.449320112 | avg=0.830087819 | rare=0.012861923
[epoch 000000045] loss=131.507232121 | avg=0.833954249 | rare=0.013067328
[epoch 000000046] loss=122.352703639 | avg=0.819612265 | rare=0.012153309
[epoch 000000047] loss=126.757805416 | avg=0.799528735 | rare=0.012595828
[epoch 000000048] loss=114.307794843 | avg=0.813907713 | rare=0.011349389
[epoch 000000049] loss=111.479007176 | avg=0.807898981 | rare=0.011067111
[epoch 000000050] loss=111.208267212 | avg=0.807002996 | rare=0.011040126
[epoch 000000051] loss=108.669821603 | avg=0.800001792 | rare=0.010786982
[epoch 000000052] loss=99.254404340 | avg=0.793708550 | rare=0.009846070
[epoch 000000053] loss=98.675941467 | avg=0.788745552 | rare=0.009788720
[epoch 000000054] loss=94.304378510 | avg=0.778775283 | rare=0.009352560
[epoch 000000055] loss=91.703695025 | avg=0.777898422 | rare=0.009092580
[epoch 000000056] loss=89.921462468 | avg=0.768939444 | rare=0.008915252
[epoch 000000057] loss=89.008266721 | avg=0.758516410 | rare=0.008824975
[epoch 000000058] loss=84.505297252 | avg=0.761242232 | rare=0.008374405
[epoch 000000059] loss=85.574402945 | avg=0.756633627 | rare=0.008481777
[epoch 000000060] loss=94.371873311 | avg=0.753661833 | rare=0.009361821
[epoch 000000061] loss=90.336596080 | avg=0.754071155 | rare=0.008958252
[epoch 000000062] loss=81.591285978 | avg=0.749375437 | rare=0.008084191
[epoch 000000063] loss=78.178782054 | avg=0.755059302 | rare=0.007742372
[epoch 000000064] loss=76.305126463 | avg=0.762391486 | rare=0.007554274
[epoch 000000065] loss=84.243977410 | avg=0.764345484 | rare=0.008347963
[epoch 000000066] loss=75.628108161 | avg=0.768783982 | rare=0.007485932
[epoch 000000067] loss=75.248382296 | avg=0.772165784 | rare=0.007447622
[epoch 000000068] loss=78.155510494 | avg=0.763108696 | rare=0.007739240
[epoch 000000069] loss=77.306249619 | avg=0.767835787 | rare=0.007653841
[epoch 000000070] loss=68.800455093 | avg=0.759361995 | rare=0.006804109
[epoch 000000071] loss=68.094758170 | avg=0.751029772 | rare=0.006734373
[epoch 000000072] loss=68.734769549 | avg=0.754337758 | rare=0.006798043
[epoch 000000073] loss=66.004898344 | avg=0.755144038 | rare=0.006524975
[epoch 000000074] loss=61.450191770 | avg=0.755987274 | rare=0.006069420
[epoch 000000075] loss=65.868971688 | avg=0.766643890 | rare=0.006510233
[epoch 000000076] loss=60.154570716 | avg=0.765253165 | rare=0.005938932
[epoch 000000077] loss=59.472280775 | avg=0.754174301 | rare=0.005871811
[epoch 000000078] loss=51.617891039 | avg=0.752830327 | rare=0.005086506
[epoch 000000079] loss=55.381944656 | avg=0.763607379 | rare=0.005461834
[epoch 000000080] loss=46.320986612 | avg=0.759413417 | rare=0.004556157
[epoch 000000081] loss=55.197449412 | avg=0.743443979 | rare=0.005445401
[epoch 000000082] loss=46.997992924 | avg=0.747816673 | rare=0.004625018
[epoch 000000083] loss=50.432655607 | avg=0.739671013 | rare=0.004969298
[epoch 000000084] loss=45.670084545 | avg=0.743692739 | rare=0.004492639
[epoch 000000085] loss=46.134868077 | avg=0.743194989 | rare=0.004539167
[epoch 000000086] loss=47.007093021 | avg=0.748056395 | rare=0.004625904
[epoch 000000087] loss=45.535539763 | avg=0.748283420 | rare=0.004478726
[epoch 000000088] loss=43.259629250 | avg=0.743776083 | rare=0.004251585
[epoch 000000089] loss=42.721631186 | avg=0.755365227 | rare=0.004196627
[epoch 000000090] loss=44.200962339 | avg=0.756576440 | rare=0.004344439
[epoch 000000091] loss=43.092883927 | avg=0.738773384 | rare=0.004235411
[epoch 000000092] loss=41.698315893 | avg=0.757263337 | rare=0.004094105
[epoch 000000093] loss=42.713642257 | avg=0.749935108 | rare=0.004196371
[epoch 000000094] loss=41.992470196 | avg=0.744174187 | rare=0.004124830
[epoch 000000095] loss=39.570637839 | avg=0.742329402 | rare=0.003882831
[epoch 000000096] loss=37.377024378 | avg=0.759220617 | rare=0.003661780
[epoch 000000097] loss=41.093848501 | avg=0.739246569 | rare=0.004035460
[epoch 000000098] loss=42.559241431 | avg=0.740548713 | rare=0.004181869
[epoch 000000099] loss=40.415215628 | avg=0.750128214 | rare=0.003966509
[epoch 000000100] loss=42.677559444 | avg=0.746100664 | rare=0.004193146

Training safe with adam...

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

[epoch 000000001] loss=3860.957676479 | avg=3.283441186 | rare=0.385767424
[epoch 000000002] loss=3857.097726004 | avg=3.295365265 | rare=0.385380238
[epoch 000000003] loss=2095.864713396 | avg=4.038028530 | rare=0.209182668
[epoch 000000004] loss=620.450055804 | avg=3.970251356 | rare=0.061647980
[epoch 000000005] loss=570.402313232 | avg=3.618429525 | rare=0.056678389
[epoch 000000006] loss=796.733564104 | avg=2.840276616 | rare=0.079389330
[epoch 000000007] loss=1405.264753069 | avg=1.964636351 | rare=0.140330013
[epoch 000000008] loss=1051.507729667 | avg=1.974593282 | rare=0.104953315
[epoch 000000009] loss=782.869537354 | avg=2.116703953 | rare=0.078075283
[epoch 000000010] loss=636.778926304 | avg=2.160762029 | rare=0.063461816
[epoch 000000011] loss=573.768055507 | avg=2.112652208 | rare=0.057165540
[epoch 000000012] loss=530.335896083 | avg=2.080644727 | rare=0.052825525
[epoch 000000013] loss=491.461024693 | avg=2.107197285 | rare=0.048935384
[epoch 000000014] loss=413.014053345 | avg=2.168677228 | rare=0.041084537
[epoch 000000015] loss=352.335656302 | avg=2.225762606 | rare=0.035010989
[epoch 000000016] loss=321.134303502 | avg=2.264101880 | rare=0.031887020
[epoch 000000017] loss=316.395711626 | avg=2.264114669 | rare=0.031413160
[epoch 000000018] loss=274.510926383 | avg=2.369915170 | rare=0.027214101
[epoch 000000019] loss=239.764050075 | avg=2.444823350 | rare=0.023731923
[epoch 000000020] loss=227.343455723 | avg=2.486148034 | rare=0.022485731
[epoch 000000021] loss=217.766123635 | avg=2.477413859 | rare=0.021528871
[epoch 000000022] loss=196.322808402 | avg=2.498181445 | rare=0.019382463
[epoch 000000023] loss=194.976016453 | avg=2.508842094 | rare=0.019246717
[epoch 000000024] loss=183.871382032 | avg=2.486135874 | rare=0.018138525
[epoch 000000025] loss=180.057612828 | avg=2.546752385 | rare=0.017751086
[epoch 000000026] loss=166.242029463 | avg=2.527784228 | rare=0.016371424
[epoch 000000027] loss=169.383241926 | avg=2.507597327 | rare=0.016687564
[epoch 000000028] loss=159.791446686 | avg=2.497298002 | rare=0.015729415
[epoch 000000029] loss=143.342162541 | avg=2.483855418 | rare=0.014085831
[epoch 000000030] loss=153.516395569 | avg=2.458677939 | rare=0.015105772
[epoch 000000031] loss=148.291327885 | avg=2.439680968 | rare=0.014585165
[epoch 000000032] loss=146.922161102 | avg=2.359265498 | rare=0.014456290
[epoch 000000033] loss=144.696099418 | avg=2.287838629 | rare=0.014240826
[epoch 000000034] loss=148.799072266 | avg=2.199462891 | rare=0.014659961
[epoch 000000035] loss=146.851422446 | avg=2.091508508 | rare=0.014475991
[epoch 000000036] loss=146.600087302 | avg=2.013180775 | rare=0.014458691
[epoch 000000037] loss=145.492633820 | avg=1.997962628 | rare=0.014349467
[epoch 000000038] loss=137.763233185 | avg=1.975593584 | rare=0.013578764
[epoch 000000039] loss=146.975936345 | avg=1.923932620 | rare=0.014505201
[epoch 000000040] loss=127.014681680 | avg=1.944944211 | rare=0.012506974
[epoch 000000041] loss=124.723700932 | avg=1.948146599 | rare=0.012277555
[epoch 000000042] loss=142.270233154 | avg=1.931691749 | rare=0.014033854
[epoch 000000043] loss=124.491250174 | avg=1.939357724 | rare=0.012255189
[epoch 000000044] loss=128.414934976 | avg=1.911264462 | rare=0.012650367
[epoch 000000045] loss=122.582872936 | avg=1.890811758 | rare=0.012069206
[epoch 000000046] loss=123.436994825 | avg=1.840493986 | rare=0.012159650
[epoch 000000047] loss=119.350297655 | avg=1.799684754 | rare=0.011755061
[epoch 000000048] loss=122.169508798 | avg=1.771499762 | rare=0.012039801
[epoch 000000049] loss=138.882185800 | avg=1.753256406 | rare=0.013712893
[epoch 000000050] loss=126.006002699 | avg=1.779718629 | rare=0.012422628
[epoch 000000051] loss=122.116376059 | avg=1.763007079 | rare=0.012035337
[epoch 000000052] loss=116.419326237 | avg=1.752899502 | rare=0.011466643
[epoch 000000053] loss=112.470878329 | avg=1.727813934 | rare=0.011074306
[epoch 000000054] loss=129.060386658 | avg=1.728106354 | rare=0.012733228
[epoch 000000055] loss=111.203437260 | avg=1.700456245 | rare=0.010950298
[epoch 000000056] loss=113.324431828 | avg=1.708245218 | rare=0.011161619
[epoch 000000057] loss=127.767485482 | avg=1.707752671 | rare=0.012605973
[epoch 000000058] loss=108.158470154 | avg=1.766072750 | rare=0.010639240
[epoch 000000059] loss=109.993007660 | avg=1.768216635 | rare=0.010822479
[epoch 000000060] loss=105.052810124 | avg=1.747169503 | rare=0.010330564
[epoch 000000061] loss=112.611331395 | avg=1.731468064 | rare=0.011087986
[epoch 000000062] loss=106.589932305 | avg=1.721486432 | rare=0.010486845
[epoch 000000063] loss=113.258262089 | avg=1.687749514 | rare=0.011157051
[epoch 000000064] loss=115.635330745 | avg=1.689345002 | rare=0.011394599
[epoch 000000065] loss=120.101524626 | avg=1.676146328 | rare=0.011842538
[epoch 000000066] loss=119.959280831 | avg=1.641003404 | rare=0.011831827
[epoch 000000067] loss=130.795294080 | avg=1.674163095 | rare=0.012912113
[epoch 000000068] loss=121.717502594 | avg=1.611173170 | rare=0.012010633
[epoch 000000069] loss=130.643514361 | avg=1.634031330 | rare=0.012900948
[epoch 000000070] loss=119.987752642 | avg=1.599497787 | rare=0.011838825
[epoch 000000071] loss=128.806722369 | avg=1.636735652 | rare=0.012716999
[epoch 000000072] loss=119.454567501 | avg=1.657733296 | rare=0.011779683
[epoch 000000073] loss=115.048219953 | avg=1.646337850 | rare=0.011340188
[epoch 000000074] loss=113.187591825 | avg=1.638616383 | rare=0.011154898
[epoch 000000075] loss=107.808963776 | avg=1.654662507 | rare=0.010615430
[epoch 000000076] loss=110.078841073 | avg=1.617998983 | rare=0.010846084
[epoch 000000077] loss=123.651666369 | avg=1.592029308 | rare=0.012205964
[epoch 000000078] loss=104.035844530 | avg=1.570751650 | rare=0.010246509
[epoch 000000079] loss=112.594078609 | avg=1.623469480 | rare=0.011097061
[epoch 000000080] loss=106.707953044 | avg=1.577881575 | rare=0.010513007
[epoch 000000081] loss=102.963894980 | avg=1.559750140 | rare=0.010140414
[epoch 000000082] loss=122.215922219 | avg=1.572699845 | rare=0.012064322
[epoch 000000083] loss=107.558515821 | avg=1.529065464 | rare=0.010602945
[epoch 000000084] loss=116.917543684 | avg=1.460462749 | rare=0.011545708
[epoch 000000085] loss=120.874990191 | avg=1.456309893 | rare=0.011941868
[epoch 000000086] loss=114.117995671 | avg=1.434975224 | rare=0.011268302
[epoch 000000087] loss=129.562516349 | avg=1.361753915 | rare=0.012820076
[epoch 000000088] loss=129.527222225 | avg=1.398228926 | rare=0.012812900
[epoch 000000089] loss=146.320344652 | avg=1.379400986 | rare=0.014494094
[epoch 000000090] loss=122.089534215 | avg=1.378456899 | rare=0.012071108
[epoch 000000091] loss=128.119723184 | avg=1.447393979 | rare=0.012667233
[epoch 000000092] loss=127.263671330 | avg=1.363751079 | rare=0.012589992
[epoch 000000093] loss=119.556454250 | avg=1.345683702 | rare=0.011821077
[epoch 000000094] loss=115.741488320 | avg=1.345843613 | rare=0.011439565
[epoch 000000095] loss=119.434135982 | avg=1.302417449 | rare=0.011813172
[epoch 000000096] loss=120.567350115 | avg=1.356718693 | rare=0.011921063
[epoch 000000097] loss=131.252714975 | avg=1.375853343 | rare=0.012987686
[epoch 000000098] loss=110.940114702 | avg=1.354327372 | rare=0.010958579
[epoch 000000099] loss=118.158876964 | avg=1.313456842 | rare=0.011684542
[epoch 000000100] loss=111.654328482 | avg=1.324140366 | rare=0.011033019
Accuracy: 79.84%  (CI 95%: [78.71%, 80.93%])
Robust Accuracy: 80.08121%  (CI 95%: [79.09183%, 81.04041%])
Conditional Robust Accuracy: 99.27556%  (CI 95%: [99.12190%, 99.42328%])
Accuracy: 82.57%  (CI 95%: [81.50%, 83.59%])
Robust Accuracy: 82.52972%  (CI 95%: [81.60688%, 83.52719%])
Conditional Robust Accuracy: 99.03566%  (CI 95%: [98.86570%, 99.21637%])
#################lr: 0.0001#############################

Training naive with adam...

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

[epoch 000000001] loss=36697.019252232 | avg=0.263567181 | rare=3.669675503
[epoch 000000002] loss=36609.113560268 | avg=0.264090906 | rare=3.660884976
[epoch 000000003] loss=35622.472377232 | avg=0.268322828 | rare=3.562220437
[epoch 000000004] loss=27176.374162946 | avg=0.390009880 | rare=2.717598387
[epoch 000000005] loss=18676.746303013 | avg=0.642450988 | rare=1.867610420
[epoch 000000006] loss=13213.894810268 | avg=0.909399280 | rare=1.321298523
[epoch 000000007] loss=9719.676513672 | avg=1.132517563 | rare=0.971854406
[epoch 000000008] loss=7431.156842913 | avg=1.309477227 | rare=0.742984738
[epoch 000000009] loss=5913.429373605 | avg=1.447156949 | rare=0.591198214
[epoch 000000010] loss=4888.219726562 | avg=1.556654624 | rare=0.488666300
[epoch 000000011] loss=4158.074951172 | avg=1.642631514 | rare=0.415643234
[epoch 000000012] loss=3601.598039900 | avg=1.712145618 | rare=0.359988589
[epoch 000000013] loss=3205.369454520 | avg=1.766438757 | rare=0.320360305
[epoch 000000014] loss=2892.270874023 | avg=1.804007096 | rare=0.289046688
[epoch 000000015] loss=2616.286725725 | avg=1.841076153 | rare=0.261444562
[epoch 000000016] loss=2411.321132115 | avg=1.880620403 | rare=0.240944052
[epoch 000000017] loss=2261.151480539 | avg=1.902297684 | rare=0.225924922
[epoch 000000018] loss=2099.421229771 | avg=1.914787318 | rare=0.209750643
[epoch 000000019] loss=1971.703238351 | avg=1.927396229 | rare=0.196977587
[epoch 000000020] loss=1821.380754743 | avg=1.944162948 | rare=0.181943660
[epoch 000000021] loss=1719.374232701 | avg=1.956826448 | rare=0.171741740
[epoch 000000022] loss=1632.430289132 | avg=1.977514616 | rare=0.163045279
[epoch 000000023] loss=1553.989039830 | avg=1.981439573 | rare=0.155200760
[epoch 000000024] loss=1489.162013463 | avg=1.985833074 | rare=0.148717618
[epoch 000000025] loss=1421.400050572 | avg=1.996742811 | rare=0.141940332
[epoch 000000026] loss=1365.599696568 | avg=2.009108577 | rare=0.136359058
[epoch 000000027] loss=1320.257925851 | avg=2.011789450 | rare=0.131824613
[epoch 000000028] loss=1278.655029297 | avg=2.022911140 | rare=0.127663212
[epoch 000000029] loss=1240.194763184 | avg=2.031083524 | rare=0.123816367
[epoch 000000030] loss=1183.421879360 | avg=2.034709437 | rare=0.118138718
[epoch 000000031] loss=1144.872096470 | avg=2.033424011 | rare=0.114283867
[epoch 000000032] loss=1116.514225551 | avg=2.046674235 | rare=0.111446757
[epoch 000000033] loss=1094.395324707 | avg=2.037195325 | rare=0.109235814
[epoch 000000034] loss=1069.630528041 | avg=2.036048898 | rare=0.106759448
[epoch 000000035] loss=1026.310337612 | avg=2.048488651 | rare=0.102426186
[epoch 000000036] loss=1002.531712123 | avg=2.053190308 | rare=0.100047853
[epoch 000000037] loss=998.807643345 | avg=2.056957866 | rare=0.099675068
[epoch 000000038] loss=969.599142892 | avg=2.049927354 | rare=0.096754921
[epoch 000000039] loss=939.466169085 | avg=2.046164436 | rare=0.093741999
[epoch 000000040] loss=917.509499686 | avg=2.049542495 | rare=0.091545996
[epoch 000000041] loss=893.294655936 | avg=2.045130355 | rare=0.089124953
[epoch 000000042] loss=870.886775426 | avg=2.060293666 | rare=0.086882648
[epoch 000000043] loss=858.431610107 | avg=2.048119153 | rare=0.085638349
[epoch 000000044] loss=840.864549909 | avg=2.055529049 | rare=0.083880903
[epoch 000000045] loss=821.205483573 | avg=2.060427810 | rare=0.081914506
[epoch 000000046] loss=810.491428920 | avg=2.053738867 | rare=0.080843769
[epoch 000000047] loss=795.728441511 | avg=2.049861354 | rare=0.079367857
[epoch 000000048] loss=789.133122035 | avg=2.056929222 | rare=0.078707619
[epoch 000000049] loss=792.291931152 | avg=2.057458631 | rare=0.079023447
[epoch 000000050] loss=783.438943045 | avg=2.051554041 | rare=0.078138739
[epoch 000000051] loss=757.334851946 | avg=2.050408781 | rare=0.075528445
[epoch 000000052] loss=755.616197859 | avg=2.043680991 | rare=0.075357251
[epoch 000000053] loss=744.310084752 | avg=2.044880620 | rare=0.074226520
[epoch 000000054] loss=735.991208758 | avg=2.034247671 | rare=0.073395695
[epoch 000000055] loss=732.653564453 | avg=2.033445324 | rare=0.073062011
[epoch 000000056] loss=719.645595006 | avg=2.030444494 | rare=0.071761515
[epoch 000000057] loss=729.764495850 | avg=2.021989550 | rare=0.072774251
[epoch 000000058] loss=713.287309919 | avg=2.029693110 | rare=0.071125761
[epoch 000000059] loss=703.331124442 | avg=2.020175397 | rare=0.070131095
[epoch 000000060] loss=704.505615234 | avg=2.022586916 | rare=0.070248304
[epoch 000000061] loss=693.205466134 | avg=2.017324959 | rare=0.069118813
[epoch 000000062] loss=686.579049247 | avg=2.005492943 | rare=0.068457356
[epoch 000000063] loss=687.973205566 | avg=2.000796148 | rare=0.068597241
[epoch 000000064] loss=681.041303362 | avg=1.997515253 | rare=0.067904379
[epoch 000000065] loss=689.774047852 | avg=1.992699810 | rare=0.068778135
[epoch 000000066] loss=679.845094953 | avg=1.982168436 | rare=0.067786293
[epoch 000000067] loss=668.274723598 | avg=1.980872912 | rare=0.066629386
[epoch 000000068] loss=657.171473912 | avg=1.965278310 | rare=0.065520620
[epoch 000000069] loss=640.275612967 | avg=1.974776660 | rare=0.063830084
[epoch 000000070] loss=637.687456403 | avg=1.961358121 | rare=0.063572609
[epoch 000000071] loss=639.088091169 | avg=1.966861708 | rare=0.063712124
[epoch 000000072] loss=657.421617780 | avg=1.954678638 | rare=0.065546693
[epoch 000000073] loss=657.029072353 | avg=1.944482318 | rare=0.065508458
[epoch 000000074] loss=644.241598947 | avg=1.937943671 | rare=0.064230365
[epoch 000000075] loss=644.548211234 | avg=1.927519287 | rare=0.064262069
[epoch 000000076] loss=644.811824254 | avg=1.919882366 | rare=0.064289195
[epoch 000000077] loss=638.448447091 | avg=1.918892341 | rare=0.063652954
[epoch 000000078] loss=644.171011789 | avg=1.907878041 | rare=0.064226314
[epoch 000000079] loss=634.024536133 | avg=1.903799329 | rare=0.063212074
[epoch 000000080] loss=631.574637277 | avg=1.887292939 | rare=0.062968734
[epoch 000000081] loss=625.544172015 | avg=1.882422805 | rare=0.062366175
[epoch 000000082] loss=619.736456735 | avg=1.874589026 | rare=0.061786187
[epoch 000000083] loss=620.597268241 | avg=1.864730980 | rare=0.061873254
[epoch 000000084] loss=627.298956735 | avg=1.856187420 | rare=0.062544277
[epoch 000000085] loss=616.816343035 | avg=1.850583919 | rare=0.061496576
[epoch 000000086] loss=602.691567557 | avg=1.841398443 | rare=0.060085018
[epoch 000000087] loss=597.810267857 | avg=1.833486233 | rare=0.059597678
[epoch 000000088] loss=605.539969308 | avg=1.819955042 | rare=0.060372002
[epoch 000000089] loss=593.741250174 | avg=1.820368094 | rare=0.059192088
[epoch 000000090] loss=594.225165231 | avg=1.806783923 | rare=0.059241839
[epoch 000000091] loss=595.973425729 | avg=1.800677734 | rare=0.059417274
[epoch 000000092] loss=603.224140712 | avg=1.780085904 | rare=0.060144405
[epoch 000000093] loss=603.663369315 | avg=1.770438365 | rare=0.060189294
[epoch 000000094] loss=602.806904384 | avg=1.767365345 | rare=0.060103954
[epoch 000000095] loss=595.557671683 | avg=1.750527152 | rare=0.059380714
[epoch 000000096] loss=615.624511719 | avg=1.743868700 | rare=0.061388064
[epoch 000000097] loss=612.713383266 | avg=1.719872747 | rare=0.061099352
[epoch 000000098] loss=612.220605033 | avg=1.710155938 | rare=0.061051044
[epoch 000000099] loss=618.566353934 | avg=1.695873439 | rare=0.061687049
[epoch 000000100] loss=620.485473633 | avg=1.670946922 | rare=0.061881452

Training safe with adam...

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

[epoch 000000001] loss=3860.957676479 | avg=3.283441186 | rare=0.385767424
[epoch 000000002] loss=3857.097726004 | avg=3.295365265 | rare=0.385380238
[epoch 000000003] loss=3493.723371233 | avg=3.420763459 | rare=0.349030261
[epoch 000000004] loss=2276.637215751 | avg=3.848426529 | rare=0.227278882
[epoch 000000005] loss=1569.076956613 | avg=4.089708482 | rare=0.156498724
[epoch 000000006] loss=1227.247253418 | avg=4.152497258 | rare=0.122309476
[epoch 000000007] loss=1035.340188163 | avg=4.071500812 | rare=0.103126871
[epoch 000000008] loss=964.046970912 | avg=3.922072206 | rare=0.096012490
[epoch 000000009] loss=965.664193290 | avg=3.766294820 | rare=0.096189789
[epoch 000000010] loss=1013.942831857 | avg=3.608417664 | rare=0.101033440
[epoch 000000011] loss=975.235403878 | avg=3.514461994 | rare=0.097172097
[epoch 000000012] loss=892.170976911 | avg=3.534335034 | rare=0.088863666
[epoch 000000013] loss=835.803161621 | avg=3.509500282 | rare=0.083229366
[epoch 000000014] loss=847.846252441 | avg=3.447448049 | rare=0.084439880
[epoch 000000015] loss=768.393907819 | avg=3.437480927 | rare=0.076495643
[epoch 000000016] loss=754.974456787 | avg=3.445291860 | rare=0.075152917
[epoch 000000017] loss=773.565652030 | avg=3.372410110 | rare=0.077019324
[epoch 000000018] loss=779.221099854 | avg=3.311587249 | rare=0.077590950
[epoch 000000019] loss=740.418797084 | avg=3.259449652 | rare=0.073715935
[epoch 000000020] loss=754.684757778 | avg=3.194389224 | rare=0.075149037
[epoch 000000021] loss=771.377179827 | avg=3.114939196 | rare=0.076826224
[epoch 000000022] loss=811.586430141 | avg=3.038217340 | rare=0.080854821
[epoch 000000023] loss=791.593157087 | avg=2.965338860 | rare=0.078862782
[epoch 000000024] loss=812.732557024 | avg=2.842403769 | rare=0.080989016
[epoch 000000025] loss=825.532492501 | avg=2.767676081 | rare=0.082276482
[epoch 000000026] loss=847.213958740 | avg=2.672879900 | rare=0.084454107
[epoch 000000027] loss=910.593104771 | avg=2.555599451 | rare=0.090803750
[epoch 000000028] loss=1044.917646136 | avg=2.405219572 | rare=0.104251243
[epoch 000000029] loss=1108.799429757 | avg=2.278018560 | rare=0.110652140
[epoch 000000030] loss=1209.983956473 | avg=2.139778239 | rare=0.120784417
[epoch 000000031] loss=1367.125313895 | avg=1.991306245 | rare=0.136513401
[epoch 000000032] loss=1521.941502162 | avg=1.855378125 | rare=0.152008614
[epoch 000000033] loss=1477.287597656 | avg=1.809936438 | rare=0.147547767
[epoch 000000034] loss=1452.028346470 | avg=1.762924986 | rare=0.145026539
[epoch 000000035] loss=1413.824471610 | avg=1.749757154 | rare=0.141207471
[epoch 000000036] loss=1394.444484166 | avg=1.730115048 | rare=0.139271435
[epoch 000000037] loss=1345.089460100 | avg=1.716184088 | rare=0.134337330
[epoch 000000038] loss=1295.116428920 | avg=1.704023549 | rare=0.129341240
[epoch 000000039] loss=1269.805472238 | avg=1.696995531 | rare=0.126810848
[epoch 000000040] loss=1210.528346470 | avg=1.698333025 | rare=0.120883000
[epoch 000000041] loss=1170.199340820 | avg=1.692204492 | rare=0.116850712
[epoch 000000042] loss=1152.019823347 | avg=1.693812047 | rare=0.115032601
[epoch 000000043] loss=1150.350537981 | avg=1.690890908 | rare=0.114865963
[epoch 000000044] loss=1132.293343680 | avg=1.692752566 | rare=0.113060059
[epoch 000000045] loss=1105.171482631 | avg=1.687731990 | rare=0.110348376
[epoch 000000046] loss=1061.996717181 | avg=1.683747292 | rare=0.106031298
[epoch 000000047] loss=1055.765450614 | avg=1.676932539 | rare=0.105408852
[epoch 000000048] loss=1031.711722238 | avg=1.687905031 | rare=0.103002383
[epoch 000000049] loss=1021.589098249 | avg=1.683805985 | rare=0.101990529
[epoch 000000050] loss=1010.453953334 | avg=1.684121609 | rare=0.100876982
[epoch 000000051] loss=976.132023403 | avg=1.683106806 | rare=0.097444891
[epoch 000000052] loss=985.137010847 | avg=1.669133271 | rare=0.098346787
[epoch 000000053] loss=953.809797015 | avg=1.669089615 | rare=0.095214070
[epoch 000000054] loss=952.435036795 | avg=1.664120913 | rare=0.095077092
[epoch 000000055] loss=947.829432896 | avg=1.662747349 | rare=0.094616669
[epoch 000000056] loss=923.705788749 | avg=1.669232743 | rare=0.092203657
[epoch 000000057] loss=911.032056536 | avg=1.658846617 | rare=0.090937321
[epoch 000000058] loss=884.220820836 | avg=1.669007633 | rare=0.088255181
[epoch 000000059] loss=877.702989851 | avg=1.661809734 | rare=0.087604118
[epoch 000000060] loss=866.122140067 | avg=1.664855914 | rare=0.086445729
[epoch 000000061] loss=853.215907506 | avg=1.666499019 | rare=0.085154941
[epoch 000000062] loss=848.621285575 | avg=1.664559901 | rare=0.084695673
[epoch 000000063] loss=849.692435128 | avg=1.673896313 | rare=0.084801854
[epoch 000000064] loss=843.002755301 | avg=1.675001400 | rare=0.084132775
[epoch 000000065] loss=824.776803153 | avg=1.676222341 | rare=0.082310058
[epoch 000000066] loss=809.521048410 | avg=1.671808498 | rare=0.080784924
[epoch 000000067] loss=804.412035261 | avg=1.680319905 | rare=0.080273171
[epoch 000000068] loss=800.284153530 | avg=1.672169072 | rare=0.079861198
[epoch 000000069] loss=768.399754116 | avg=1.686813176 | rare=0.076671294
[epoch 000000070] loss=754.804787772 | avg=1.681791731 | rare=0.075312300
[epoch 000000071] loss=731.716160366 | avg=1.691454538 | rare=0.073002470
[epoch 000000072] loss=719.264596122 | avg=1.699670758 | rare=0.071756492
[epoch 000000073] loss=717.908752441 | avg=1.703570502 | rare=0.071620518
[epoch 000000074] loss=701.430315290 | avg=1.705530805 | rare=0.069972478
[epoch 000000075] loss=679.432355608 | avg=1.713866489 | rare=0.067771847
[epoch 000000076] loss=676.942692348 | avg=1.719919733 | rare=0.067522278
[epoch 000000077] loss=681.013423375 | avg=1.710924106 | rare=0.067930250
[epoch 000000078] loss=663.689392090 | avg=1.730160041 | rare=0.066195924
[epoch 000000079] loss=656.345480783 | avg=1.731633808 | rare=0.065461386
[epoch 000000080] loss=641.679447719 | avg=1.720287911 | rare=0.063995916
[epoch 000000081] loss=639.347207206 | avg=1.731782419 | rare=0.063761542
[epoch 000000082] loss=622.093113491 | avg=1.734737618 | rare=0.062035837
[epoch 000000083] loss=610.545189994 | avg=1.734986254 | rare=0.060881020
[epoch 000000084] loss=624.470659528 | avg=1.748774844 | rare=0.062272188
[epoch 000000085] loss=608.954079764 | avg=1.759319808 | rare=0.060719477
[epoch 000000086] loss=608.753376552 | avg=1.751035418 | rare=0.060700234
[epoch 000000087] loss=605.177313668 | avg=1.747429737 | rare=0.060342988
[epoch 000000088] loss=600.718215942 | avg=1.750914029 | rare=0.059896730
[epoch 000000089] loss=585.423104422 | avg=1.754972952 | rare=0.058366813
[epoch 000000090] loss=574.899217878 | avg=1.752114526 | rare=0.057314711
[epoch 000000091] loss=573.844685146 | avg=1.762111247 | rare=0.057208258
[epoch 000000092] loss=563.926576887 | avg=1.756990143 | rare=0.056216958
[epoch 000000093] loss=559.336739676 | avg=1.761869226 | rare=0.055757487
[epoch 000000094] loss=567.381524222 | avg=1.758858851 | rare=0.056562266
[epoch 000000095] loss=556.157991682 | avg=1.752757830 | rare=0.055440523
[epoch 000000096] loss=539.042759487 | avg=1.764199861 | rare=0.053727856
[epoch 000000097] loss=540.801873343 | avg=1.762290452 | rare=0.053903958
[epoch 000000098] loss=544.893469674 | avg=1.746746191 | rare=0.054314671
[epoch 000000099] loss=532.476808820 | avg=1.756172691 | rare=0.053072062
[epoch 000000100] loss=525.190723964 | avg=1.745314300 | rare=0.052344543
Accuracy: 75.46%  (CI 95%: [74.25%, 76.63%])
Robust Accuracy: 75.88303%  (CI 95%: [74.98800%, 77.02439%])
Conditional Robust Accuracy: 98.22258%  (CI 95%: [97.99711%, 98.39867%])
Accuracy: 79.42%  (CI 95%: [78.28%, 80.52%])
Robust Accuracy: 79.80452%  (CI 95%: [78.93901%, 80.76271%])
Conditional Robust Accuracy: 97.97456%  (CI 95%: [97.70857%, 98.17305%])
#################lr: 1e-05#############################

Training naive with adam...

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

[epoch 000000001] loss=36697.019252232 | avg=0.263567181 | rare=3.669675503
[epoch 000000002] loss=36609.113560268 | avg=0.264090906 | rare=3.660884976
[epoch 000000003] loss=36517.567243304 | avg=0.263736683 | rare=3.651730333
[epoch 000000004] loss=35920.274553571 | avg=0.264255436 | rare=3.592001012
[epoch 000000005] loss=35111.002232143 | avg=0.267841737 | rare=3.511073419
[epoch 000000006] loss=34149.682198661 | avg=0.275009818 | rare=3.414940783
[epoch 000000007] loss=33099.677873884 | avg=0.285310511 | rare=3.309939197
[epoch 000000008] loss=32077.047991071 | avg=0.297136271 | rare=3.207675099
[epoch 000000009] loss=31026.078543527 | avg=0.311397054 | rare=3.102576699
[epoch 000000010] loss=29986.323102679 | avg=0.327124347 | rare=2.998599580
[epoch 000000011] loss=29054.727120536 | avg=0.344942874 | rare=2.905438202
[epoch 000000012] loss=28032.285156250 | avg=0.363077632 | rare=2.803192190
[epoch 000000013] loss=27103.656250000 | avg=0.383279089 | rare=2.710327319
[epoch 000000014] loss=26176.944475446 | avg=0.403729598 | rare=2.617654051
[epoch 000000015] loss=25312.486886161 | avg=0.424963683 | rare=2.531206216
[epoch 000000016] loss=24435.637695312 | avg=0.449290733 | rare=2.443518894
[epoch 000000017] loss=23562.626813616 | avg=0.473197169 | rare=2.356215375
[epoch 000000018] loss=22776.463309152 | avg=0.495097220 | rare=2.277596848
[epoch 000000019] loss=22000.944893973 | avg=0.519049359 | rare=2.200042571
[epoch 000000020] loss=21290.321428571 | avg=0.543264621 | rare=2.128977810
[epoch 000000021] loss=20595.210100446 | avg=0.565291618 | rare=2.059464463
[epoch 000000022] loss=19947.579520089 | avg=0.589820645 | rare=1.994699001
[epoch 000000023] loss=19307.737583705 | avg=0.614720408 | rare=1.930712317
[epoch 000000024] loss=18728.078962054 | avg=0.635122870 | rare=1.872744407
[epoch 000000025] loss=18110.885044643 | avg=0.660218550 | rare=1.811022469
[epoch 000000026] loss=17541.464285714 | avg=0.683492401 | rare=1.754078073
[epoch 000000027] loss=17026.748814174 | avg=0.707979943 | rare=1.702604106
[epoch 000000028] loss=16514.677246094 | avg=0.731628018 | rare=1.651394580
[epoch 000000029] loss=16007.336914062 | avg=0.753245320 | rare=1.600658349
[epoch 000000030] loss=15531.529854911 | avg=0.777434651 | rare=1.553075220
[epoch 000000031] loss=15105.149832589 | avg=0.795192429 | rare=1.510435436
[epoch 000000032] loss=14650.695242746 | avg=0.820583850 | rare=1.464987465
[epoch 000000033] loss=14275.515904018 | avg=0.841268659 | rare=1.427467440
[epoch 000000034] loss=13820.618512835 | avg=0.862209167 | rare=1.381975634
[epoch 000000035] loss=13404.459263393 | avg=0.888235501 | rare=1.340357091
[epoch 000000036] loss=13013.837960379 | avg=0.904260239 | rare=1.301293365
[epoch 000000037] loss=12649.595284598 | avg=0.929174853 | rare=1.264866608
[epoch 000000038] loss=12347.672921317 | avg=0.945176614 | rare=1.234672785
[epoch 000000039] loss=11955.542480469 | avg=0.965983689 | rare=1.195457654
[epoch 000000040] loss=11637.152064732 | avg=0.984862864 | rare=1.163616725
[epoch 000000041] loss=11304.876743862 | avg=1.001611880 | rare=1.130387502
[epoch 000000042] loss=10980.385114397 | avg=1.027102636 | rare=1.097935796
[epoch 000000043] loss=10719.780273438 | avg=1.040833533 | rare=1.071873937
[epoch 000000044] loss=10423.955775670 | avg=1.064222583 | rare=1.042289163
[epoch 000000045] loss=10187.329171317 | avg=1.081108502 | rare=1.018624812
[epoch 000000046] loss=9937.245326451 | avg=1.096002732 | rare=0.993614938
[epoch 000000047] loss=9668.474190848 | avg=1.116828093 | rare=0.966735721
[epoch 000000048] loss=9446.920131138 | avg=1.135700941 | rare=0.944578430
[epoch 000000049] loss=9232.793317522 | avg=1.148748355 | rare=0.923164440
[epoch 000000050] loss=8983.187709263 | avg=1.168487191 | rare=0.898201930
[epoch 000000051] loss=8802.880440848 | avg=1.184829644 | rare=0.880169566
[epoch 000000052] loss=8592.500139509 | avg=1.195444822 | rare=0.859130455
[epoch 000000053] loss=8370.537806920 | avg=1.216325428 | rare=0.836932165
[epoch 000000054] loss=8163.228690011 | avg=1.232006720 | rare=0.816199669
[epoch 000000055] loss=7977.731410435 | avg=1.246179487 | rare=0.797648528
[epoch 000000056] loss=7813.187325614 | avg=1.258557975 | rare=0.781192877
[epoch 000000057] loss=7656.387590681 | avg=1.270240792 | rare=0.765511743
[epoch 000000058] loss=7449.441127232 | avg=1.287175000 | rare=0.744815396
[epoch 000000059] loss=7301.735351562 | avg=1.302067356 | rare=0.730043322
[epoch 000000060] loss=7124.999511719 | avg=1.320158737 | rare=0.712367935
[epoch 000000061] loss=6953.515938895 | avg=1.333654216 | rare=0.695218231
[epoch 000000062] loss=6825.319859096 | avg=1.340472315 | rare=0.682397932
[epoch 000000063] loss=6671.347900391 | avg=1.357197881 | rare=0.666999072
[epoch 000000064] loss=6514.956577846 | avg=1.375177843 | rare=0.651358140
[epoch 000000065] loss=6385.398402623 | avg=1.387547842 | rare=0.638401087
[epoch 000000066] loss=6261.878801618 | avg=1.393802941 | rare=0.626048497
[epoch 000000067] loss=6158.352015904 | avg=1.408186342 | rare=0.615694391
[epoch 000000068] loss=6021.492745536 | avg=1.415057302 | rare=0.602007764
[epoch 000000069] loss=5903.302804129 | avg=1.431908565 | rare=0.590187081
[epoch 000000070] loss=5771.365548270 | avg=1.438925641 | rare=0.576992661
[epoch 000000071] loss=5673.303118025 | avg=1.454544578 | rare=0.567184848
[epoch 000000072] loss=5554.307407924 | avg=1.465331980 | rare=0.555284211
[epoch 000000073] loss=5452.647809710 | avg=1.480614109 | rare=0.545116723
[epoch 000000074] loss=5355.238351004 | avg=1.489847098 | rare=0.535374846
[epoch 000000075] loss=5268.709228516 | avg=1.494556546 | rare=0.526721465
[epoch 000000076] loss=5166.802769252 | avg=1.503218412 | rare=0.516529958
[epoch 000000077] loss=5053.475934710 | avg=1.516481646 | rare=0.505195937
[epoch 000000078] loss=4967.410818917 | avg=1.528220585 | rare=0.496588271
[epoch 000000079] loss=4884.509416853 | avg=1.539670621 | rare=0.488296971
[epoch 000000080] loss=4818.175537109 | avg=1.538586336 | rare=0.481663698
[epoch 000000081] loss=4716.840994699 | avg=1.556375793 | rare=0.471528456
[epoch 000000082] loss=4637.350237165 | avg=1.568869088 | rare=0.463578141
[epoch 000000083] loss=4571.972324916 | avg=1.575272662 | rare=0.457039703
[epoch 000000084] loss=4492.047781808 | avg=1.584574163 | rare=0.449046320
[epoch 000000085] loss=4410.824079241 | avg=1.591980883 | rare=0.440923210
[epoch 000000086] loss=4335.997070312 | avg=1.603025402 | rare=0.433439404
[epoch 000000087] loss=4274.669224330 | avg=1.604312437 | rare=0.427306495
[epoch 000000088] loss=4197.003470285 | avg=1.612499833 | rare=0.419539098
[epoch 000000089] loss=4138.431553432 | avg=1.623296125 | rare=0.413680824
[epoch 000000090] loss=4073.901890346 | avg=1.628491538 | rare=0.407227329
[epoch 000000091] loss=4003.289655413 | avg=1.640933854 | rare=0.400164870
[epoch 000000092] loss=3946.489885603 | avg=1.644907296 | rare=0.394484499
[epoch 000000093] loss=3895.363420759 | avg=1.652346986 | rare=0.389371106
[epoch 000000094] loss=3824.555576869 | avg=1.666409450 | rare=0.382288920
[epoch 000000095] loss=3773.147774833 | avg=1.667893997 | rare=0.377147985
[epoch 000000096] loss=3714.802769252 | avg=1.678132074 | rare=0.371312465
[epoch 000000097] loss=3666.109008789 | avg=1.684948180 | rare=0.366442401
[epoch 000000098] loss=3620.952043806 | avg=1.692644264 | rare=0.361925936
[epoch 000000099] loss=3567.185337612 | avg=1.696407054 | rare=0.356548893
[epoch 000000100] loss=3543.859776088 | avg=1.698627532 | rare=0.354216116

Training safe with adam...

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

[epoch 000000001] loss=3860.957676479 | avg=3.283441186 | rare=0.385767424
[epoch 000000002] loss=3857.097726004 | avg=3.295365265 | rare=0.385380238
[epoch 000000003] loss=3824.916067941 | avg=3.308758531 | rare=0.382160727
[epoch 000000004] loss=3669.366995675 | avg=3.362229058 | rare=0.366600477
[epoch 000000005] loss=3506.775094169 | avg=3.406036070 | rare=0.350336905
[epoch 000000006] loss=3350.328002930 | avg=3.468084352 | rare=0.334685996
[epoch 000000007] loss=3210.456298828 | avg=3.519419278 | rare=0.320693691
[epoch 000000008] loss=3061.758649554 | avg=3.563302943 | rare=0.305819539
[epoch 000000009] loss=2925.840366908 | avg=3.609999708 | rare=0.292223041
[epoch 000000010] loss=2819.557407924 | avg=3.644491400 | rare=0.281591290
[epoch 000000011] loss=2691.936767578 | avg=3.680153711 | rare=0.268825658
[epoch 000000012] loss=2579.788870675 | avg=3.712616665 | rare=0.257607625
[epoch 000000013] loss=2489.046404157 | avg=3.745469979 | rare=0.248530089
[epoch 000000014] loss=2398.529052734 | avg=3.767908420 | rare=0.239476115
[epoch 000000015] loss=2315.533604213 | avg=3.799127221 | rare=0.231173444
[epoch 000000016] loss=2257.763846261 | avg=3.835602726 | rare=0.225392823
[epoch 000000017] loss=2178.397652762 | avg=3.859300971 | rare=0.217453832
[epoch 000000018] loss=2108.593802316 | avg=3.870445149 | rare=0.210472338
[epoch 000000019] loss=2012.928336007 | avg=3.891324656 | rare=0.200903702
[epoch 000000020] loss=1958.725864955 | avg=3.903285231 | rare=0.195482258
[epoch 000000021] loss=1911.427472796 | avg=3.921086652 | rare=0.190750643
[epoch 000000022] loss=1879.135785784 | avg=3.930077876 | rare=0.187520570
[epoch 000000023] loss=1827.981558664 | avg=3.932894690 | rare=0.182404867
[epoch 000000024] loss=1781.491925921 | avg=3.933736954 | rare=0.177755817
[epoch 000000025] loss=1721.121268136 | avg=3.938816343 | rare=0.171718243
[epoch 000000026] loss=1665.272478376 | avg=3.951344388 | rare=0.166132114
[epoch 000000027] loss=1636.711574009 | avg=3.950127108 | rare=0.163276144
[epoch 000000028] loss=1599.524893624 | avg=3.957180074 | rare=0.159556771
[epoch 000000029] loss=1567.778180804 | avg=3.959489686 | rare=0.156381870
[epoch 000000030] loss=1539.346426828 | avg=3.955216289 | rare=0.153539121
[epoch 000000031] loss=1497.572291783 | avg=3.945281506 | rare=0.149362701
[epoch 000000032] loss=1473.062543597 | avg=3.956045628 | rare=0.146910650
[epoch 000000033] loss=1457.216936384 | avg=3.938124640 | rare=0.145327881
[epoch 000000034] loss=1440.605765206 | avg=3.933348060 | rare=0.143667241
[epoch 000000035] loss=1411.629080636 | avg=3.940870251 | rare=0.140768821
[epoch 000000036] loss=1390.092668806 | avg=3.922008429 | rare=0.138617068
[epoch 000000037] loss=1368.879725865 | avg=3.921905603 | rare=0.136495782
[epoch 000000038] loss=1340.901402065 | avg=3.898910148 | rare=0.133700248
[epoch 000000039] loss=1318.669817243 | avg=3.899292162 | rare=0.131477052
[epoch 000000040] loss=1297.003836496 | avg=3.893838491 | rare=0.129310999
[epoch 000000041] loss=1281.886779785 | avg=3.866604788 | rare=0.127802018
[epoch 000000042] loss=1270.783604213 | avg=3.879671710 | rare=0.126690394
[epoch 000000043] loss=1260.902465820 | avg=3.855010118 | rare=0.125704746
[epoch 000000044] loss=1235.452383859 | avg=3.851485917 | rare=0.123160088
[epoch 000000045] loss=1231.732517787 | avg=3.848316278 | rare=0.122788420
[epoch 000000046] loss=1218.550842285 | avg=3.823635697 | rare=0.121472720
[epoch 000000047] loss=1201.552629743 | avg=3.809308972 | rare=0.119774333
[epoch 000000048] loss=1205.144801549 | avg=3.812452674 | rare=0.120133235
[epoch 000000049] loss=1203.668596540 | avg=3.792028427 | rare=0.119987656
[epoch 000000050] loss=1157.387708391 | avg=3.779905268 | rare=0.115360782
[epoch 000000051] loss=1161.999651228 | avg=3.768072980 | rare=0.115823159
[epoch 000000052] loss=1148.365330287 | avg=3.744263819 | rare=0.114462108
[epoch 000000053] loss=1129.284528460 | avg=3.744725006 | rare=0.112553981
[epoch 000000054] loss=1136.490583147 | avg=3.728673118 | rare=0.113276191
[epoch 000000055] loss=1128.443790981 | avg=3.720293999 | rare=0.112472352
[epoch 000000056] loss=1120.154453823 | avg=3.702361890 | rare=0.111645207
[epoch 000000057] loss=1111.171460833 | avg=3.684590816 | rare=0.110748689
[epoch 000000058] loss=1116.948630197 | avg=3.687876156 | rare=0.111326074
[epoch 000000059] loss=1118.400848389 | avg=3.674826435 | rare=0.111472603
[epoch 000000060] loss=1097.590676444 | avg=3.673838513 | rare=0.109391685
[epoch 000000061] loss=1086.057974679 | avg=3.670007569 | rare=0.108238798
[epoch 000000062] loss=1089.563084194 | avg=3.643454518 | rare=0.108591964
[epoch 000000063] loss=1091.929927281 | avg=3.645146540 | rare=0.108828478
[epoch 000000064] loss=1071.692404611 | avg=3.647141371 | rare=0.106804525
[epoch 000000065] loss=1062.790788923 | avg=3.643993837 | rare=0.105914678
[epoch 000000066] loss=1070.850529262 | avg=3.620948945 | rare=0.106722959
[epoch 000000067] loss=1069.889421735 | avg=3.616989068 | rare=0.106627242
[epoch 000000068] loss=1074.768864223 | avg=3.596379246 | rare=0.107117250
[epoch 000000069] loss=1070.315420968 | avg=3.593346936 | rare=0.106672209
[epoch 000000070] loss=1078.670663016 | avg=3.574524709 | rare=0.107509613
[epoch 000000071] loss=1078.558458601 | avg=3.571888651 | rare=0.107498657
[epoch 000000072] loss=1059.376582554 | avg=3.557110633 | rare=0.105581946
[epoch 000000073] loss=1070.780683245 | avg=3.549280558 | rare=0.106723140
[epoch 000000074] loss=1070.090776716 | avg=3.543340428 | rare=0.106654743
[epoch 000000075] loss=1063.567474365 | avg=3.524078829 | rare=0.106004340
[epoch 000000076] loss=1057.379455566 | avg=3.518288067 | rare=0.105386119
[epoch 000000077] loss=1044.263523647 | avg=3.520663261 | rare=0.104074284
[epoch 000000078] loss=1036.901471819 | avg=3.512930785 | rare=0.103338854
[epoch 000000079] loss=1022.789943150 | avg=3.515316520 | rare=0.101927462
[epoch 000000080] loss=1031.014526367 | avg=3.487817594 | rare=0.102752670
[epoch 000000081] loss=1022.771283831 | avg=3.499737484 | rare=0.101927155
[epoch 000000082] loss=1015.974286761 | avg=3.499771646 | rare=0.101247451
[epoch 000000083] loss=1005.803619385 | avg=3.491892985 | rare=0.100231174
[epoch 000000084] loss=996.251098633 | avg=3.492131693 | rare=0.099275897
[epoch 000000085] loss=986.563323975 | avg=3.488556998 | rare=0.098307477
[epoch 000000086] loss=982.150037493 | avg=3.487626076 | rare=0.097866241
[epoch 000000087] loss=984.147417341 | avg=3.477766888 | rare=0.098066964
[epoch 000000088] loss=975.220206124 | avg=3.475238068 | rare=0.097174497
[epoch 000000089] loss=977.379725865 | avg=3.488872715 | rare=0.097389085
[epoch 000000090] loss=958.552429199 | avg=3.472591008 | rare=0.095507983
[epoch 000000091] loss=954.459110805 | avg=3.476578815 | rare=0.095098254
[epoch 000000092] loss=957.887329102 | avg=3.461840851 | rare=0.095442551
[epoch 000000093] loss=945.681230818 | avg=3.455828718 | rare=0.094222540
[epoch 000000094] loss=938.308654785 | avg=3.469550678 | rare=0.093483910
[epoch 000000095] loss=924.566462926 | avg=3.458262239 | rare=0.092110821
[epoch 000000096] loss=927.088618687 | avg=3.460012487 | rare=0.092362860
[epoch 000000097] loss=916.643062047 | avg=3.460693938 | rare=0.091318237
[epoch 000000098] loss=915.074515206 | avg=3.463637931 | rare=0.091161087
[epoch 000000099] loss=901.739920480 | avg=3.454113569 | rare=0.089828582
[epoch 000000100] loss=898.022474016 | avg=3.444691317 | rare=0.089457779
Accuracy: 71.14%  (CI 95%: [69.87%, 72.37%])
Robust Accuracy: 71.18155%  (CI 95%: [70.32514%, 72.27385%])
Conditional Robust Accuracy: 93.72513%  (CI 95%: [93.49532%, 93.96989%])
Accuracy: 73.69%  (CI 95%: [72.45%, 74.88%])
Robust Accuracy: 73.86172%  (CI 95%: [72.90688%, 74.97868%])
Conditional Robust Accuracy: 98.06185%  (CI 95%: [97.87117%, 98.28289%])
#################lr: 1e-06#############################

Training naive with adam...

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

[epoch 000000001] loss=36697.019252232 | avg=0.263567181 | rare=3.669675503
[epoch 000000002] loss=36609.113560268 | avg=0.264090906 | rare=3.660884976
[epoch 000000003] loss=36608.557477679 | avg=0.263811002 | rare=3.660829340
[epoch 000000004] loss=36606.599330357 | avg=0.263506766 | rare=3.660633666
[epoch 000000005] loss=36574.302734375 | avg=0.263573258 | rare=3.657403844
[epoch 000000006] loss=36490.300223214 | avg=0.263740451 | rare=3.649003693
[epoch 000000007] loss=36375.188058036 | avg=0.263873108 | rare=3.637492367
[epoch 000000008] loss=36345.233537946 | avg=0.263727842 | rare=3.634496995
[epoch 000000009] loss=36233.201171875 | avg=0.263843462 | rare=3.623293791
[epoch 000000010] loss=36176.544642857 | avg=0.264100757 | rare=3.617628115
[epoch 000000011] loss=36136.694754464 | avg=0.264342726 | rare=3.613643067
[epoch 000000012] loss=35995.318917411 | avg=0.263841845 | rare=3.599505510
[epoch 000000013] loss=35920.854073661 | avg=0.264603070 | rare=3.592058914
[epoch 000000014] loss=35884.563058036 | avg=0.264346208 | rare=3.588429911
[epoch 000000015] loss=35847.379185268 | avg=0.264172097 | rare=3.584711501
[epoch 000000016] loss=35722.102120536 | avg=0.265224259 | rare=3.572183694
[epoch 000000017] loss=35564.854910714 | avg=0.265930034 | rare=3.556458967
[epoch 000000018] loss=35491.736328125 | avg=0.265981412 | rare=3.549146959
[epoch 000000019] loss=35383.654854911 | avg=0.266389068 | rare=3.538338900
[epoch 000000020] loss=35359.469029018 | avg=0.266451042 | rare=3.535920313
[epoch 000000021] loss=35206.974609375 | avg=0.267005055 | rare=3.520670789
[epoch 000000022] loss=35128.888392857 | avg=0.267872873 | rare=3.512862018
[epoch 000000023] loss=35076.879464286 | avg=0.268019662 | rare=3.507661053
[epoch 000000024] loss=34994.316685268 | avg=0.268549353 | rare=3.499404890
[epoch 000000025] loss=34872.096261161 | avg=0.268828761 | rare=3.487182839
[epoch 000000026] loss=34742.317243304 | avg=0.269906736 | rare=3.474204745
[epoch 000000027] loss=34704.668805804 | avg=0.269955426 | rare=3.470439792
[epoch 000000028] loss=34550.993861607 | avg=0.271395021 | rare=3.455072250
[epoch 000000029] loss=34448.781250000 | avg=0.271192577 | rare=3.444850973
[epoch 000000030] loss=34388.452566964 | avg=0.273178173 | rare=3.438817978
[epoch 000000031] loss=34301.988281250 | avg=0.272404413 | rare=3.430171609
[epoch 000000032] loss=34159.120814732 | avg=0.273491259 | rare=3.415884648
[epoch 000000033] loss=34134.923549107 | avg=0.275059706 | rare=3.413464802
[epoch 000000034] loss=34021.541992188 | avg=0.275690023 | rare=3.402126619
[epoch 000000035] loss=33907.085100446 | avg=0.277388539 | rare=3.390680807
[epoch 000000036] loss=33799.892857143 | avg=0.277152745 | rare=3.379961627
[epoch 000000037] loss=33686.569196429 | avg=0.279297282 | rare=3.368629013
[epoch 000000038] loss=33657.423549107 | avg=0.278764139 | rare=3.365714533
[epoch 000000039] loss=33496.066406250 | avg=0.280857094 | rare=3.349578551
[epoch 000000040] loss=33408.282505580 | avg=0.281877028 | rare=3.340800064
[epoch 000000041] loss=33337.148437500 | avg=0.281706220 | rare=3.333686709
[epoch 000000042] loss=33184.968191964 | avg=0.284304289 | rare=3.318468469
[epoch 000000043] loss=33148.365792411 | avg=0.284684185 | rare=3.314808079
[epoch 000000044] loss=33035.187779018 | avg=0.286550028 | rare=3.303490196
[epoch 000000045] loss=32937.800362723 | avg=0.286901476 | rare=3.293751342
[epoch 000000046] loss=32846.163225446 | avg=0.287182759 | rare=3.284587588
[epoch 000000047] loss=32730.310825893 | avg=0.287971171 | rare=3.273002301
[epoch 000000048] loss=32611.919363839 | avg=0.290464003 | rare=3.261162911
[epoch 000000049] loss=32477.270368304 | avg=0.291171838 | rare=3.247697932
[epoch 000000050] loss=32356.673688616 | avg=0.292910948 | rare=3.235638056
[epoch 000000051] loss=32329.903459821 | avg=0.293543460 | rare=3.232961008
[epoch 000000052] loss=32228.851422991 | avg=0.294422126 | rare=3.222855704
[epoch 000000053] loss=32088.406668527 | avg=0.296062978 | rare=3.208811130
[epoch 000000054] loss=31959.442103795 | avg=0.297228473 | rare=3.195914439
[epoch 000000055] loss=31865.508370536 | avg=0.298391576 | rare=3.186521053
[epoch 000000056] loss=31786.907645089 | avg=0.299948918 | rare=3.178660767
[epoch 000000057] loss=31663.394112723 | avg=0.301529067 | rare=3.166309220
[epoch 000000058] loss=31528.472098214 | avg=0.303612713 | rare=3.152816841
[epoch 000000059] loss=31461.117466518 | avg=0.304861154 | rare=3.146081277
[epoch 000000060] loss=31311.719029018 | avg=0.306839949 | rare=3.131141186
[epoch 000000061] loss=31206.837053571 | avg=0.308277856 | rare=3.120652880
[epoch 000000062] loss=31151.045898438 | avg=0.307939016 | rare=3.115073783
[epoch 000000063] loss=31051.890764509 | avg=0.311719707 | rare=3.105157920
[epoch 000000064] loss=30929.241768973 | avg=0.312402627 | rare=3.092892919
[epoch 000000065] loss=30814.324916295 | avg=0.314332204 | rare=3.081401093
[epoch 000000066] loss=30709.529715402 | avg=0.315195905 | rare=3.070921438
[epoch 000000067] loss=30673.388532366 | avg=0.316859081 | rare=3.067307200
[epoch 000000068] loss=30507.132533482 | avg=0.317781627 | rare=3.050681489
[epoch 000000069] loss=30425.003348214 | avg=0.319459770 | rare=3.042468395
[epoch 000000070] loss=30296.403738839 | avg=0.321126742 | rare=3.029608284
[epoch 000000071] loss=30216.063337054 | avg=0.322642188 | rare=3.021574071
[epoch 000000072] loss=30123.489536830 | avg=0.324708802 | rare=3.012316499
[epoch 000000073] loss=30046.140625000 | avg=0.327656633 | rare=3.004581332
[epoch 000000074] loss=29916.363699777 | avg=0.328203244 | rare=2.991603528
[epoch 000000075] loss=29826.209123884 | avg=0.329868838 | rare=2.982587934
[epoch 000000076] loss=29694.800781250 | avg=0.331621753 | rare=2.969446966
[epoch 000000077] loss=29539.064034598 | avg=0.334258763 | rare=2.953873004
[epoch 000000078] loss=29472.110212054 | avg=0.336323787 | rare=2.947177427
[epoch 000000079] loss=29384.686104911 | avg=0.338029781 | rare=2.938434788
[epoch 000000080] loss=29379.460100446 | avg=0.336389527 | rare=2.937912362
[epoch 000000081] loss=29214.867187500 | avg=0.340541723 | rare=2.921452693
[epoch 000000082] loss=29113.673409598 | avg=0.342119828 | rare=2.911333152
[epoch 000000083] loss=29044.328543527 | avg=0.343362272 | rare=2.904398543
[epoch 000000084] loss=28978.006417411 | avg=0.345583592 | rare=2.897766079
[epoch 000000085] loss=28849.679129464 | avg=0.348437586 | rare=2.884933046
[epoch 000000086] loss=28745.011858259 | avg=0.349851263 | rare=2.874466198
[epoch 000000087] loss=28661.894531250 | avg=0.350489870 | rare=2.866154381
[epoch 000000088] loss=28525.239397321 | avg=0.352079887 | rare=2.852488773
[epoch 000000089] loss=28483.479771205 | avg=0.354770918 | rare=2.848312480
[epoch 000000090] loss=28381.576729911 | avg=0.355544795 | rare=2.838122146
[epoch 000000091] loss=28258.507812500 | avg=0.359459596 | rare=2.825814809
[epoch 000000092] loss=28233.762416295 | avg=0.359965484 | rare=2.823340246
[epoch 000000093] loss=28138.067382812 | avg=0.361928433 | rare=2.813770550
[epoch 000000094] loss=28000.008789062 | avg=0.364989617 | rare=2.799964377
[epoch 000000095] loss=27863.043805804 | avg=0.366974015 | rare=2.786267672
[epoch 000000096] loss=27759.058175223 | avg=0.369547593 | rare=2.775868859
[epoch 000000097] loss=27630.899135045 | avg=0.372817095 | rare=2.763052600
[epoch 000000098] loss=27526.523437500 | avg=0.374706528 | rare=2.752614907
[epoch 000000099] loss=27469.261160714 | avg=0.374862488 | rare=2.746888621
[epoch 000000100] loss=27399.692661830 | avg=0.375808341 | rare=2.739931669

Training safe with adam...

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

[epoch 000000001] loss=3860.957676479 | avg=3.283441186 | rare=0.385767424
[epoch 000000002] loss=3857.097726004 | avg=3.295365265 | rare=0.385380238
[epoch 000000003] loss=3857.695329939 | avg=3.295669198 | rare=0.385439966
[epoch 000000004] loss=3841.634957450 | avg=3.303570236 | rare=0.383833138
[epoch 000000005] loss=3827.234061105 | avg=3.298907706 | rare=0.382393513
[epoch 000000006] loss=3816.036516462 | avg=3.312948942 | rare=0.381272359
[epoch 000000007] loss=3801.555995396 | avg=3.320481607 | rare=0.379823542
[epoch 000000008] loss=3777.265328544 | avg=3.323581253 | rare=0.377394172
[epoch 000000009] loss=3765.785173689 | avg=3.329890370 | rare=0.376245533
[epoch 000000010] loss=3751.659336635 | avg=3.331652965 | rare=0.374832775
[epoch 000000011] loss=3734.394967215 | avg=3.336350628 | rare=0.373105858
[epoch 000000012] loss=3716.308436802 | avg=3.340253694 | rare=0.371296817
[epoch 000000013] loss=3701.311976842 | avg=3.346650839 | rare=0.369796527
[epoch 000000014] loss=3683.139107840 | avg=3.345653006 | rare=0.367979348
[epoch 000000015] loss=3663.639229911 | avg=3.349293113 | rare=0.366028992
[epoch 000000016] loss=3655.958583287 | avg=3.366565892 | rare=0.365259202
[epoch 000000017] loss=3627.187779018 | avg=3.375034230 | rare=0.362381271
[epoch 000000018] loss=3622.478044782 | avg=3.374248011 | rare=0.361910386
[epoch 000000019] loss=3598.477486747 | avg=3.386372515 | rare=0.359509106
[epoch 000000020] loss=3589.447719029 | avg=3.385421855 | rare=0.358606232
[epoch 000000021] loss=3566.420776367 | avg=3.395449366 | rare=0.356302530
[epoch 000000022] loss=3566.310459682 | avg=3.402000274 | rare=0.356290845
[epoch 000000023] loss=3535.469761440 | avg=3.402922715 | rare=0.353206679
[epoch 000000024] loss=3534.144060407 | avg=3.403897660 | rare=0.353074012
[epoch 000000025] loss=3506.999982561 | avg=3.411351034 | rare=0.350358859
[epoch 000000026] loss=3489.541992188 | avg=3.421951737 | rare=0.348612004
[epoch 000000027] loss=3484.568464007 | avg=3.423162324 | rare=0.348114527
[epoch 000000028] loss=3460.864397321 | avg=3.433004396 | rare=0.345743137
[epoch 000000029] loss=3437.350516183 | avg=3.436775855 | rare=0.343391372
[epoch 000000030] loss=3437.255702427 | avg=3.438502789 | rare=0.343381724
[epoch 000000031] loss=3411.477137974 | avg=3.439166614 | rare=0.340803802
[epoch 000000032] loss=3382.766898019 | avg=3.454077687 | rare=0.337931280
[epoch 000000033] loss=3389.104544503 | avg=3.446868777 | rare=0.338565767
[epoch 000000034] loss=3361.598545619 | avg=3.453817827 | rare=0.335814474
[epoch 000000035] loss=3341.381731306 | avg=3.469740697 | rare=0.333791196
[epoch 000000036] loss=3336.841744559 | avg=3.465215274 | rare=0.333337652
[epoch 000000037] loss=3318.177071708 | avg=3.480472394 | rare=0.331469659
[epoch 000000038] loss=3313.704642160 | avg=3.472599983 | rare=0.331023210
[epoch 000000039] loss=3287.728724888 | avg=3.484638436 | rare=0.328424407
[epoch 000000040] loss=3279.862060547 | avg=3.488530840 | rare=0.327637353
[epoch 000000041] loss=3254.578805106 | avg=3.482949870 | rare=0.325109588
[epoch 000000042] loss=3248.894548689 | avg=3.504863943 | rare=0.324538967
[epoch 000000043] loss=3230.201503209 | avg=3.495328733 | rare=0.322670624
[epoch 000000044] loss=3222.711809431 | avg=3.507058399 | rare=0.321920476
[epoch 000000045] loss=3216.897914342 | avg=3.516223005 | rare=0.321338170
[epoch 000000046] loss=3192.857666016 | avg=3.511410679 | rare=0.318934626
[epoch 000000047] loss=3180.446934291 | avg=3.510343977 | rare=0.317693659
[epoch 000000048] loss=3164.437953404 | avg=3.526533229 | rare=0.316091144
[epoch 000000049] loss=3160.449201311 | avg=3.521438139 | rare=0.315692774
[epoch 000000050] loss=3143.595267160 | avg=3.529582790 | rare=0.314006569
[epoch 000000051] loss=3132.495936802 | avg=3.538735271 | rare=0.312895719
[epoch 000000052] loss=3120.694806780 | avg=3.532053096 | rare=0.311716278
[epoch 000000053] loss=3100.124424526 | avg=3.551566039 | rare=0.309657284
[epoch 000000054] loss=3093.225045340 | avg=3.548577717 | rare=0.308967646
[epoch 000000055] loss=3089.642124721 | avg=3.552203110 | rare=0.308608990
[epoch 000000056] loss=3073.172694615 | avg=3.551561918 | rare=0.306962115
[epoch 000000057] loss=3043.294764927 | avg=3.553698012 | rare=0.303974109
[epoch 000000058] loss=3034.275826590 | avg=3.566202351 | rare=0.303070962
[epoch 000000059] loss=3030.326206752 | avg=3.567523394 | rare=0.302675869
[epoch 000000060] loss=2996.661028181 | avg=3.579307318 | rare=0.299308172
[epoch 000000061] loss=2982.036237444 | avg=3.586601053 | rare=0.297844963
[epoch 000000062] loss=2969.284232003 | avg=3.573937654 | rare=0.296571031
[epoch 000000063] loss=2955.548008510 | avg=3.592578990 | rare=0.295195545
[epoch 000000064] loss=2945.897286551 | avg=3.598802175 | rare=0.294229854
[epoch 000000065] loss=2931.718296596 | avg=3.609818016 | rare=0.292810847
[epoch 000000066] loss=2922.904750279 | avg=3.601475171 | rare=0.291930320
[epoch 000000067] loss=2921.584594727 | avg=3.604121191 | rare=0.291798049
[epoch 000000068] loss=2908.203334263 | avg=3.601826242 | rare=0.290460154
[epoch 000000069] loss=2894.033028739 | avg=3.613876360 | rare=0.289041913
[epoch 000000070] loss=2865.274762835 | avg=3.614738328 | rare=0.286165996
[epoch 000000071] loss=2871.189348493 | avg=3.626248121 | rare=0.286756311
[epoch 000000072] loss=2858.043090820 | avg=3.623392974 | rare=0.285441969
[epoch 000000073] loss=2846.371146066 | avg=3.635392002 | rare=0.284273573
[epoch 000000074] loss=2837.478829520 | avg=3.640571594 | rare=0.283383823
[epoch 000000075] loss=2819.496268136 | avg=3.635358589 | rare=0.281586096
[epoch 000000076] loss=2811.594116211 | avg=3.634564536 | rare=0.280795959
[epoch 000000077] loss=2787.749093192 | avg=3.646737950 | rare=0.278410237
[epoch 000000078] loss=2771.376412528 | avg=3.648879732 | rare=0.276772759
[epoch 000000079] loss=2768.587437221 | avg=3.659628493 | rare=0.276492784
[epoch 000000080] loss=2763.933506557 | avg=3.644240413 | rare=0.276028927
[epoch 000000081] loss=2737.469290597 | avg=3.664968916 | rare=0.273380430
[epoch 000000082] loss=2721.110979353 | avg=3.672750132 | rare=0.271743821
[epoch 000000083] loss=2717.450526646 | avg=3.673257027 | rare=0.271377731
[epoch 000000084] loss=2713.090454102 | avg=3.673550299 | rare=0.270941690
[epoch 000000085] loss=2693.486240932 | avg=3.679577759 | rare=0.268980664
[epoch 000000086] loss=2690.622994559 | avg=3.681557979 | rare=0.268694140
[epoch 000000087] loss=2670.567522321 | avg=3.674388306 | rare=0.266689315
[epoch 000000088] loss=2657.079223633 | avg=3.681542976 | rare=0.265339772
[epoch 000000089] loss=2662.619663783 | avg=3.692608271 | rare=0.265892707
[epoch 000000090] loss=2645.580113002 | avg=3.687259197 | rare=0.264189283
[epoch 000000091] loss=2632.780482701 | avg=3.700785858 | rare=0.262907965
[epoch 000000092] loss=2625.454223633 | avg=3.694738592 | rare=0.262175948
[epoch 000000093] loss=2623.740234375 | avg=3.692972405 | rare=0.262004726
[epoch 000000094] loss=2614.680315290 | avg=3.709708997 | rare=0.261097058
[epoch 000000095] loss=2596.019112723 | avg=3.702726007 | rare=0.259231631
[epoch 000000096] loss=2586.772617885 | avg=3.708517756 | rare=0.258306405
[epoch 000000097] loss=2579.354352679 | avg=3.715740204 | rare=0.257563859
[epoch 000000098] loss=2567.887782506 | avg=3.722969191 | rare=0.256416482
[epoch 000000099] loss=2547.718802316 | avg=3.723114814 | rare=0.254399568
[epoch 000000100] loss=2541.710693359 | avg=3.722231831 | rare=0.253798847
Accuracy: 83.29%  (CI 95%: [82.23%, 84.29%])
Robust Accuracy: 65.56304%  (CI 95%: [65.16374%, 66.02107%])
Conditional Robust Accuracy: 68.87675%  (CI 95%: [68.35940%, 69.38028%])
Accuracy: 68.73%  (CI 95%: [67.43%, 69.99%])
Robust Accuracy: 69.65286%  (CI 95%: [68.69512%, 70.78369%])
Conditional Robust Accuracy: 96.50785%  (CI 95%: [96.32894%, 96.70766%])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import pandas as pd

def results_to_df(
    final_results: dict,
    *,
    # pretty labels for the config key (e.g., 'naive', 'safe', etc.)
    config_map: dict | None = None,
    # per-config safe bias values, e.g. {'safe': 15, 'safe_neg': 15}
    safe_bias_map: dict | None = None,
    # global run metadata (use None if not applicable)
    sigma: float | None = None,
    gamma: float | None = None,
    num_epochs: int | None = None,
    # display options
    percent: bool = True,           # convert metrics to %
    ci_decimals: int = 2,           # decimals for CI strings
    val_decimals: int = 2,          # decimals for value columns
):
    """
    Convert nested results to a tidy DataFrame with CI columns.
    final_results structure (example):
      {
        step_size: {
          (config_key, opt): {
             'acc': float, 'acc_ci': (lo, hi),
             'RA': float,  'RA_ci': (lo, hi),
             'CRA': float, 'CRA_ci': (lo, hi)
          }, ...
        }, ...
      }
    """
    config_map = config_map or {}
    safe_bias_map = safe_bias_map or {}

    def _p(x):
        return 100.0 * x if (x is not None and percent) else x

    def _fmt(val, lo_hi):
        if val is None or lo_hi is None:
            return ""
        lo, hi = lo_hi
        val, lo, hi = _p(val), _p(lo), _p(hi)
        return f"{val:.{val_decimals}f} [{lo:.{ci_decimals}f}, {hi:.{ci_decimals}f}]"

    rows = []
    for step_size, runs in final_results.items():
        for (cfg_key, opt), m in runs.items():
            # raw numbers
            acc, acc_ci = m.get('acc'), m.get('acc_ci')
            ra,  ra_ci  = m.get('RA'),  m.get('RA_ci')
            cra, cra_ci = m.get('CRA'), m.get('CRA_ci')

            # formatted strings
            acc_ci_str = _fmt(acc, acc_ci)
            ra_ci_str  = _fmt(ra,  ra_ci)
            cra_ci_str = _fmt(cra, cra_ci)

            # human labels
            opt_lbl = str(opt).upper()
            cfg_lbl = config_map.get(cfg_key, cfg_key)

            rows.append({
                "Opt": opt_lbl,
                "Config": cfg_lbl,
                "Safe Bias": safe_bias_map.get(cfg_key, "-"),
                "Step Size": step_size,
                "Sigma": sigma if sigma is not None else "-",
                "Gamma": gamma if gamma is not None else "-",
                "Number of Epochs": num_epochs if num_epochs is not None else "-",

                # numeric cols (already % if percent=True)
                "Test Acc": None if acc is None else round(_p(acc), val_decimals),
                "Test Acc (95% CI)": acc_ci_str,
                "RA": None if ra is None else round(_p(ra), val_decimals),
                "RA (95% CI)": ra_ci_str,
                "CRA": None if cra is None else round(_p(cra), val_decimals),
                "CRA (95% CI)": cra_ci_str,
            })

    df = pd.DataFrame(rows)

    # sort for readability
    sort_cols = ["Opt", "Step Size", "Config"]
    for c in sort_cols:
        if c not in df.columns:
            sort_cols.remove(c)
    if sort_cols:
        df = df.sort_values(sort_cols, ascending= [True, False, True]).reset_index(drop=True)

    return df

In [ ]:
config_map = {
    "init_naive": "SCRATCH+RE",
    "naive": "PT+RE",
    "safe": "PT+SAFE(+15)+RE",
    "safe_neg": "PT+SAFE(−15)+RE",
}
safe_bias_map = {"safe": 15, "safe_neg": 15}

df_sgd_large = results_to_df(
    final_results,
    config_map=config_map,
    safe_bias_map=safe_bias_map,
    sigma=0.7,
    gamma=10_000,
    num_epochs=100,
    percent=True,
)

# If you also want a version that keeps only the three headline columns:
# df_view = df[["Opt","Config","Safe Bias","Step Size","Sigma","Gamma","Number of Epochs",
#               "Test Acc","Test Acc (95% CI)","RA","RA (95% CI)","CRA","CRA (95% CI)"]]

In [ ]:
df_sgd_large

,Opt,Config,Safe Bias,Step Size,Sigma,Gamma,Number of Epochs,Test Acc,Test Acc (95% CI),RA,RA (95% CI),CRA,CRA (95% CI)
0,SGD,PT+RE,-,0.100000,0.7,10000,100,63.96,"63.96 [62.63, 65.28]",63.96,"63.96 [62.85, 65.41]",100.00,"100.00 [100.00, 100.00]"
1,SGD,PT+SAFE(+15)+RE,15,0.100000,0.7,10000,100,63.96,"63.96 [62.63, 65.28]",63.96,"63.96 [62.85, 65.41]",100.00,"100.00 [100.00, 100.00]"
2,SGD,PT+RE,-,0.010000,0.7,10000,100,63.96,"63.96 [62.63, 65.28]",63.96,"63.96 [62.85, 65.41]",100.00,"100.00 [100.00, 100.00]"
3,SGD,PT+SAFE(+15)+RE,15,0.010000,0.7,10000,100,63.96,"63.96 [62.63, 65.28]",63.96,"63.96 [62.85, 65.41]",100.00,"100.00 [100.00, 100.00]"
4,SGD,PT+RE,-,0.001000,0.7,10000,100,63.96,"63.96 [62.63, 65.28]",63.96,"63.96 [62.85, 65.41]",100.00,"100.00 [100.00, 100.00]"
5,SGD,PT+SAFE(+15)+RE,15,0.001000,0.7,10000,100,63.96,"63.96 [62.63, 65.28]",63.96,"63.96 [62.85, 65.41]",100.00,"100.00 [100.00, 100.00]"
6,SGD,PT+RE,-,0.000100,0.7,10000,100,63.96,"63.96 [62.63, 65.28]",63.96,"63.96 [62.85, 65.41]",100.00,"100.00 [100.00, 100.00]"
7,SGD,PT+SAFE(+15)+RE,15,0.000100,0.7,10000,100,63.96,"63.96 [62.63, 65.28]",63.96,"63.96 [62.85, 65.41]",100.00,"100.00 [100.00, 100.00]"
8,SGD,PT+RE,-,0.000010,0.7,10000,100,63.96,"63.96 [62.63, 65.28]",63.96,"63.96 [62.85, 65.41]",100.00,"100.00 [100.00, 100.00]"
9,SGD,PT+SAFE(+15)+RE,15,0.000010,0.7,10000,100,79.88,"79.88 [78.75, 80.97]",79.81,"79.81 [78.97, 80.81]",99.52,"99.52 [99.39, 99.64]"
10,SGD,PT+RE,-,0.000001,0.7,10000,100,77.03,"77.03 [75.85, 78.17]",76.95,"76.95 [76.11, 78.17]",99.30,"99.30 [99.17, 99.44]"
11,SGD,PT+SAFE(+15)+RE,15,0.000001,0.7,10000,100,79.92,"79.92 [78.79, 81.01]",79.86,"79.86 [78.96, 80.90]",99.48,"99.48 [99.36, 99.61]"

In [ ]:
df_adam_large = df_sgd_large = results_to_df(
    final_results_adam,
    config_map=config_map,
    safe_bias_map=safe_bias_map,
    sigma=0.7,
    gamma=10_000,
    num_epochs=100,
    percent=True,
)
df_adam_large

,Opt,Config,Safe Bias,Step Size,Sigma,Gamma,Number of Epochs,Test Acc,Test Acc (95% CI),RA,RA (95% CI),CRA,CRA (95% CI)
0,ADAM,PT+RE,-,0.100000,0.7,10000,100,64.14,"64.14 [62.81, 65.46]",64.14,"64.14 [63.03, 65.59]",99.99,"99.99 [99.98, 100.00]"
1,ADAM,PT+SAFE(+15)+RE,15,0.100000,0.7,10000,100,73.49,"73.49 [72.25, 74.69]",73.50,"73.50 [72.41, 74.75]",99.91,"99.91 [99.87, 99.96]"
2,ADAM,PT+RE,-,0.010000,0.7,10000,100,82.27,"82.27 [81.19, 83.30]",82.27,"82.27 [81.40, 83.38]",99.56,"99.56 [99.46, 99.66]"
3,ADAM,PT+SAFE(+15)+RE,15,0.010000,0.7,10000,100,82.05,"82.05 [80.97, 83.09]",81.97,"81.97 [81.05, 83.01]",99.13,"99.13 [98.98, 99.27]"
4,ADAM,PT+RE,-,0.001000,0.7,10000,100,79.84,"79.84 [78.71, 80.93]",80.08,"80.08 [79.09, 81.04]",99.28,"99.28 [99.12, 99.42]"
5,ADAM,PT+SAFE(+15)+RE,15,0.001000,0.7,10000,100,82.57,"82.57 [81.50, 83.59]",82.53,"82.53 [81.61, 83.53]",99.04,"99.04 [98.87, 99.22]"
6,ADAM,PT+RE,-,0.000100,0.7,10000,100,75.46,"75.46 [74.25, 76.63]",75.88,"75.88 [74.99, 77.02]",98.22,"98.22 [98.00, 98.40]"
7,ADAM,PT+SAFE(+15)+RE,15,0.000100,0.7,10000,100,79.42,"79.42 [78.28, 80.52]",79.80,"79.80 [78.94, 80.76]",97.97,"97.97 [97.71, 98.17]"
8,ADAM,PT+RE,-,0.000010,0.7,10000,100,71.14,"71.14 [69.87, 72.37]",71.18,"71.18 [70.33, 72.27]",93.73,"93.73 [93.50, 93.97]"
9,ADAM,PT+SAFE(+15)+RE,15,0.000010,0.7,10000,100,73.69,"73.69 [72.45, 74.88]",73.86,"73.86 [72.91, 74.98]",98.06,"98.06 [97.87, 98.28]"
10,ADAM,PT+RE,-,0.000001,0.7,10000,100,83.29,"83.29 [82.23, 84.29]",65.56,"65.56 [65.16, 66.02]",68.88,"68.88 [68.36, 69.38]"
11,ADAM,PT+SAFE(+15)+RE,15,0.000001,0.7,10000,100,68.73,"68.73 [67.43, 69.99]",69.65,"69.65 [68.70, 70.78]",96.51,"96.51 [96.33, 96.71]"

# Multi-seed settings

In [17]:
import torch
import torch.nn as nn
import torch.optim as optim
from tqdm.auto import tqdm
from torch.utils.data import TensorDataset, DataLoader
from sklearn.tree import DecisionTreeClassifier, export_text
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# --- optional: small speed win on CUDA for fixed-size batches ---
torch.backends.cudnn.benchmark = True

from contextlib import nullcontext


# for decision tree baseline
def fit_dt(name,X_train,y_train,X_test,y_test,   **tree_kwargs):
    clf = DecisionTreeClassifier(random_state=42, **tree_kwargs)
    clf.fit(X_train, y_train)
    ypred = clf.predict(X_test)
    acc = accuracy_score(y_test, ypred)
    print(f"\n{name}: test accuracy = {acc:.4f}")
    # show the tiny tree
    try:
        print(export_text(clf, feature_names=[f"x{j}" for j in range(Xtr.shape[1])]))
    except Exception:
        pass
    return acc, clf


def pretrain(X, y, model, num_epochs=10000, lr=1e-3, batch_size=256, use_amp=True, device=None):
    """
    Pretrain with BCEWithLogitsLoss on mini-batches, GPU if available.
    """
    if device is None:
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    else:
        device = torch.device(device)

    model = model.to(device)

    ds = TensorDataset(X, y)  # X,y should be on CPU for pin_memory to work best
    dl = DataLoader(
        ds,
        batch_size=batch_size,
        shuffle=True,
        pin_memory=(device.type == "cuda"),
        num_workers=2,
        prefetch_factor=2,
        persistent_workers=True
    )

    criterion = nn.BCEWithLogitsLoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)

    amp_enabled = use_amp and (device.type == "cuda")
    scaler = torch.amp.GradScaler("cuda") if amp_enabled else None
    autocast_ctx = torch.amp.autocast("cuda", dtype=torch.float16) if amp_enabled else nullcontext()

    for epoch in tqdm(range(1, num_epochs + 1), desc="Epochs", dynamic_ncols=True):
        model.train()
        for xb, yb in dl:
            xb = xb.to(device, non_blocking=True)
            yb = yb.to(device, non_blocking=True).squeeze(-1).float()

            optimizer.zero_grad(set_to_none=True)
            with autocast_ctx:
                outputs = model(xb).squeeze(-1)
                loss = criterion(outputs, yb)

            if amp_enabled:
                scaler.scale(loss).backward()
                scaler.step(optimizer)
                scaler.update()
            else:
                loss.backward()
                optimizer.step()

    return model



@torch.no_grad()
def _clean_correct_mask_binary(model, x, y):
    logits = model(x).squeeze(-1)
    pred = (torch.sigmoid(logits) >= 0.5).float()
    y_flat = y.squeeze(-1).float()
    return (pred == y_flat).float()

def _rare_event_margin_binary(model, x, y, sigma=0.1, J=10):
    """
    Vectorized rare-event margin; runs on whatever device x is on.
    """
    device = x.device
    B = x.shape[0]

    I_clean = _clean_correct_mask_binary(model, x, y).to(device)  # (B,)

    eps = sigma * torch.randn((J,) + x.shape, device=device)      # (J,B,...)
    x_noisy = x.unsqueeze(0) + eps
    x_flat  = x_noisy.reshape(J * B, *x.shape[1:])

    logits = model(x_flat).squeeze(-1)                            # (J*B,)
    y_rep  = y.squeeze(-1).float().unsqueeze(0).repeat(J,1).reshape(-1)

    s = (2.0 * y_rep - 1.0)
    g_y = s * logits
    margin = (-2.0 * g_y).clamp_min(0.0)

    margin_JB = margin.view(J, B)
    margin_mean = margin_JB.mean(dim=0)
    margin_masked = margin_mean * I_clean
    return margin_masked.mean()


def joint_train(
    X, y, pre_model, num_epochs=100,
    gamma=1000, num_samples=10, sigma=0.1, IF_SAFE=False, SAFE_BIAS=100,
    batch_size=256,
    opt="adam", lr=1e-3, weight_decay=0.0, betas=(0.9, 0.999),
    sgd_momentum=0.0, sgd_nesterov=False,
    use_amp=True, device=None, seed=42 # <--- ADD THIS
):
    if device is None:
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    else:
        device = torch.device(device)

    # Use the parameter instead of hardcoding 42
    torch.manual_seed(seed) # <--- CHANGE THIS

    # ... rest of your function remains exactly the same ...

    # init model from pretrained
    new_model = type(pre_model)(X.shape[-1]).to(device)
    new_model.load_state_dict(pre_model.state_dict(), strict=False)

    if IF_SAFE:
        with torch.no_grad():
            new_model.fc_last.bias.fill_(SAFE_BIAS)

    # Keep data on CPU; move per batch
    ds = TensorDataset(X, y)
    dl = DataLoader(
        ds,
        batch_size=batch_size,
        shuffle=True,
        pin_memory=(device.type == "cuda"),
        num_workers=2,
        prefetch_factor=2,
        persistent_workers=True
    )

    criterion = nn.BCEWithLogitsLoss()

    # optimizer
    if callable(opt):
        optimizer = opt(new_model.parameters())
    else:
        key = str(opt).lower()
        if key == "adam":
            optimizer = optim.Adam(new_model.parameters(), lr=lr, betas=betas, weight_decay=weight_decay)
        elif key == "sgd":
            optimizer = optim.SGD(new_model.parameters(), lr=lr, momentum=sgd_momentum,
                                  nesterov=sgd_nesterov, weight_decay=weight_decay)
        else:
            raise ValueError(f"Unknown opt='{opt}'")

    # AMP (new API)
    amp_enabled = use_amp and (device.type == "cuda")
    scaler = torch.amp.GradScaler("cuda") if amp_enabled else None
    autocast_ctx = torch.amp.autocast("cuda", dtype=torch.float16) if amp_enabled else nullcontext()

    history = {"epoch": [], "loss": [], "loss_avg": [], "loss_rare": [], "optimizer": str(opt)}

    # Epoch progress bar
    for epoch in tqdm(range(1, num_epochs + 1), desc="Epochs", dynamic_ncols=True):
        new_model.train()
        tot = tot_avg = tot_rare = 0.0
        n_batches = 0

        # Inner per-batch bar (set leave=False to keep output clean)
        for xb, yb in dl:
            xb = xb.to(device, non_blocking=True)
            yb = yb.to(device, non_blocking=True).squeeze(-1).float()

            optimizer.zero_grad(set_to_none=True)
            with autocast_ctx:
                logits_clean = new_model(xb).squeeze(-1)
                loss_avg = criterion(logits_clean, yb)
                loss_rare = _rare_event_margin_binary(new_model, xb, yb, sigma=sigma, J=num_samples)
                loss = loss_avg + gamma * loss_rare

            if epoch >1:  # skip backward on epoch 1 to keep initial model intact for eval
                if amp_enabled:
                    scaler.scale(loss).backward()
                    scaler.step(optimizer)
                    scaler.update()
                else:
                    loss.backward()
                    optimizer.step()

            tot += float(loss)
            tot_avg += float(loss_avg)
            tot_rare += float(loss_rare)
            n_batches += 1

        epoch_loss = tot / max(1, n_batches)
        epoch_avg  = tot_avg / max(1, n_batches)
        epoch_rare = tot_rare / max(1, n_batches)

        history["epoch"].append(epoch)
        history["loss"].append(epoch_loss)
        history["loss_avg"].append(epoch_avg)
        history["loss_rare"].append(epoch_rare)

        # Show running stats on the epoch bar

        tqdm.write(f"[epoch {epoch:09d}] loss={epoch_loss:.9f} | avg={epoch_avg:.9f} | rare={epoch_rare:.9f}")

    return new_model, history



def train_all(X, y, pre_model, num_epochs, gamma, num_samples, sigma, device=None,
              configs = [("naive", "adam"),("safe", "adam"),("safe_neg", "adam"),
                         ("naive", "sgd"),("safe", "sgd"),("safe_neg", "sgd") ],
              SAFE_BIAS = 10, seed=42, **kw): # <--- ADD THIS

    if device is None:
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    results = {}   # results[("naive","adam")] = (model, hist)

    for cfg, opt in configs:
        if cfg == "naive":
            print(f"\nTraining naive with {opt}...")
            naive_model, naive_hist = joint_train(
                X, y, pre_model, num_epochs=num_epochs, gamma=gamma,
                num_samples=num_samples, sigma=sigma, IF_SAFE=False,
                opt=opt, device=device, seed=seed, **kw # <--- PASS SEED
            )
            results[("naive", opt)] = (naive_model, naive_hist)

        elif cfg == "safe":
            print(f"\nTraining safe with {opt}...")
            safe_model, safe_hist = joint_train(
                X, y, pre_model, num_epochs=num_epochs, gamma=gamma,
                num_samples=num_samples, sigma=sigma, IF_SAFE=True, SAFE_BIAS=SAFE_BIAS,
                opt=opt, device=device, seed=seed, **kw # <--- PASS SEED
            )
            results[("safe", opt)] = (safe_model, safe_hist)

        elif cfg == "safe_neg":
            print(f"\nTraining safe_neg with {opt}...")
            safe_neg_model, safe_neg_hist = joint_train(
                X, y, pre_model, num_epochs=num_epochs, gamma=gamma,
                num_samples=num_samples, sigma=sigma, IF_SAFE=True, SAFE_BIAS=-SAFE_BIAS,
                opt=opt, device=device, seed=seed, **kw # <--- PASS SEED
            )
            results[("safe_neg", opt)] = (safe_neg_model, safe_neg_hist)

    return results

In [18]:
import numpy as np

# SIGMA = 1.

NUM_EPOCHS = 200
# Define your seeds
seeds = [42, 100, 2026, 333, 777]
# seeds = [ 100, 2026]
configs = [("naive", "sgd"), ("safe", "sgd")]
lrs = [ 1e-3,1e-4, 1e-5, 1e-6,1e-7,1e-8, 1e-9,]
final_results_adam = {}
GAMMA = 100000.
SAMPLES_TRAIN = 1000
SAMPLES_EVAL = 100000

for lr in lrs:
    print(f"\n{'#'*20} lr: {lr} {'#'*20}")

    # Initialize lists to hold the 5 seed results for each config
    configs_result = {config: [] for config in configs}

    for s in seeds:
        print(f"  --> Running Seed: {s}")

        # 1. Train models for the current seed
        # (Ensure your updated train_all accepts and utilizes the 'seed' parameter)
        results = train_all(
            X_train, y_train, pre_model,
            NUM_EPOCHS, GAMMA, SAMPLES_TRAIN, SIGMA,
            configs=configs, SAFE_BIAS=200.0, lr=lr, batch_size=BATCH_SIZE,
            seed=s
        )

        # 2. Evaluate models and append to the respective config list
        for config in configs:
            eval_metrics = eval_one(
                results[config][0], X_test, y_test,
                sigma=SIGMA, SAMPLES_EVAL=SAMPLES_EVAL,
                J_chunk=5000,    # Smart chunking to prevent Colab OOM errors
                N_chunk=512,
                B=300
            )
            configs_result[config].append(eval_metrics)

    # Store the aggregated seed data for this learning rate
    final_results_adam[lr] = configs_result

print("\nGrid Search Complete!")

#################### lr: 0.001 ####################
  --> Running Seed: 42

Training naive with sgd...

Epochs:   0%|          | 0/200 [00:00<?, ?it/s]

/tmp/ipykernel_1097/4280458666.py:202: UserWarning: Converting a tensor with requires_grad=True to a scalar may lead to unexpected behavior.
Consider using tensor.detach() first. (Triggered internally at /pytorch/torch/csrc/autograd/generated/python_variable_methods.cpp:836.)
  tot += float(loss)

[epoch 000000001] loss=178608.407366071 | avg=0.319726129 | rare=1.786080871
[epoch 000000002] loss=178494.834821429 | avg=0.319935188 | rare=1.784945164
[epoch 000000003] loss=nan | avg=nan | rare=nan
[epoch 000000004] loss=nan | avg=nan | rare=nan
[epoch 000000005] loss=nan | avg=nan | rare=nan
[epoch 000000006] loss=nan | avg=nan | rare=nan
[epoch 000000007] loss=nan | avg=nan | rare=nan
[epoch 000000008] loss=nan | avg=nan | rare=nan
[epoch 000000009] loss=nan | avg=nan | rare=nan
[epoch 000000010] loss=nan | avg=nan | rare=nan
[epoch 000000011] loss=nan | avg=nan | rare=nan
[epoch 000000012] loss=nan | avg=nan | rare=nan
[epoch 000000013] loss=nan | avg=nan | rare=nan
[epoch 000000014] loss=nan | avg=nan | rare=nan
[epoch 000000015] loss=nan | avg=nan | rare=nan
[epoch 000000016] loss=nan | avg=nan | rare=nan
[epoch 000000017] loss=nan | avg=nan | rare=nan
[epoch 000000018] loss=nan | avg=nan | rare=nan
[epoch 000000019] loss=nan | avg=nan | rare=nan
[epoch 000000020] loss=nan | avg=nan | rare=nan
[epoch 000000021] loss=nan | avg=nan | rare=nan
[epoch 000000022] loss=nan | avg=nan | rare=nan
[epoch 000000023] loss=nan | avg=nan | rare=nan
[epoch 000000024] loss=nan | avg=nan | rare=nan
[epoch 000000025] loss=nan | avg=nan | rare=nan
[epoch 000000026] loss=nan | avg=nan | rare=nan
[epoch 000000027] loss=nan | avg=nan | rare=nan
[epoch 000000028] loss=nan | avg=nan | rare=nan
[epoch 000000029] loss=nan | avg=nan | rare=nan
[epoch 000000030] loss=nan | avg=nan | rare=nan
[epoch 000000031] loss=nan | avg=nan | rare=nan
[epoch 000000032] loss=nan | avg=nan | rare=nan
[epoch 000000033] loss=nan | avg=nan | rare=nan
[epoch 000000034] loss=nan | avg=nan | rare=nan
[epoch 000000035] loss=nan | avg=nan | rare=nan
[epoch 000000036] loss=nan | avg=nan | rare=nan
[epoch 000000037] loss=nan | avg=nan | rare=nan
[epoch 000000038] loss=nan | avg=nan | rare=nan
[epoch 000000039] loss=nan | avg=nan | rare=nan
[epoch 000000040] loss=nan | avg=nan | rare=nan
[epoch 000000041] loss=nan | avg=nan | rare=nan
[epoch 000000042] loss=nan | avg=nan | rare=nan
[epoch 000000043] loss=nan | avg=nan | rare=nan
[epoch 000000044] loss=nan | avg=nan | rare=nan
[epoch 000000045] loss=nan | avg=nan | rare=nan
[epoch 000000046] loss=nan | avg=nan | rare=nan
[epoch 000000047] loss=nan | avg=nan | rare=nan
[epoch 000000048] loss=nan | avg=nan | rare=nan
[epoch 000000049] loss=nan | avg=nan | rare=nan
[epoch 000000050] loss=nan | avg=nan | rare=nan
[epoch 000000051] loss=nan | avg=nan | rare=nan
[epoch 000000052] loss=nan | avg=nan | rare=nan
[epoch 000000053] loss=nan | avg=nan | rare=nan
[epoch 000000054] loss=nan | avg=nan | rare=nan
[epoch 000000055] loss=nan | avg=nan | rare=nan
[epoch 000000056] loss=nan | avg=nan | rare=nan
[epoch 000000057] loss=nan | avg=nan | rare=nan
[epoch 000000058] loss=nan | avg=nan | rare=nan
[epoch 000000059] loss=nan | avg=nan | rare=nan
[epoch 000000060] loss=nan | avg=nan | rare=nan
[epoch 000000061] loss=nan | avg=nan | rare=nan
[epoch 000000062] loss=nan | avg=nan | rare=nan
[epoch 000000063] loss=nan | avg=nan | rare=nan
[epoch 000000064] loss=nan | avg=nan | rare=nan
[epoch 000000065] loss=nan | avg=nan | rare=nan
[epoch 000000066] loss=nan | avg=nan | rare=nan
[epoch 000000067] loss=nan | avg=nan | rare=nan
[epoch 000000068] loss=nan | avg=nan | rare=nan
[epoch 000000069] loss=nan | avg=nan | rare=nan
[epoch 000000070] loss=nan | avg=nan | rare=nan
[epoch 000000071] loss=nan | avg=nan | rare=nan
[epoch 000000072] loss=nan | avg=nan | rare=nan
[epoch 000000073] loss=nan | avg=nan | rare=nan
[epoch 000000074] loss=nan | avg=nan | rare=nan
[epoch 000000075] loss=nan | avg=nan | rare=nan
[epoch 000000076] loss=nan | avg=nan | rare=nan
[epoch 000000077] loss=nan | avg=nan | rare=nan
[epoch 000000078] loss=nan | avg=nan | rare=nan
[epoch 000000079] loss=nan | avg=nan | rare=nan
[epoch 000000080] loss=nan | avg=nan | rare=nan
[epoch 000000081] loss=nan | avg=nan | rare=nan
[epoch 000000082] loss=nan | avg=nan | rare=nan
[epoch 000000083] loss=nan | avg=nan | rare=nan
[epoch 000000084] loss=nan | avg=nan | rare=nan
[epoch 000000085] loss=nan | avg=nan | rare=nan
[epoch 000000086] loss=nan | avg=nan | rare=nan
[epoch 000000087] loss=nan | avg=nan | rare=nan
[epoch 000000088] loss=nan | avg=nan | rare=nan
[epoch 000000089] loss=nan | avg=nan | rare=nan
[epoch 000000090] loss=nan | avg=nan | rare=nan
[epoch 000000091] loss=nan | avg=nan | rare=nan
[epoch 000000092] loss=nan | avg=nan | rare=nan
[epoch 000000093] loss=nan | avg=nan | rare=nan
[epoch 000000094] loss=nan | avg=nan | rare=nan
[epoch 000000095] loss=nan | avg=nan | rare=nan
[epoch 000000096] loss=nan | avg=nan | rare=nan
[epoch 000000097] loss=nan | avg=nan | rare=nan
[epoch 000000098] loss=nan | avg=nan | rare=nan
[epoch 000000099] loss=nan | avg=nan | rare=nan
[epoch 000000100] loss=nan | avg=nan | rare=nan
[epoch 000000101] loss=nan | avg=nan | rare=nan
[epoch 000000102] loss=nan | avg=nan | rare=nan
[epoch 000000103] loss=nan | avg=nan | rare=nan
[epoch 000000104] loss=nan | avg=nan | rare=nan
[epoch 000000105] loss=nan | avg=nan | rare=nan
[epoch 000000106] loss=nan | avg=nan | rare=nan
[epoch 000000107] loss=nan | avg=nan | rare=nan
[epoch 000000108] loss=nan | avg=nan | rare=nan
[epoch 000000109] loss=nan | avg=nan | rare=nan
[epoch 000000110] loss=nan | avg=nan | rare=nan
[epoch 000000111] loss=nan | avg=nan | rare=nan
[epoch 000000112] loss=nan | avg=nan | rare=nan
[epoch 000000113] loss=nan | avg=nan | rare=nan
[epoch 000000114] loss=nan | avg=nan | rare=nan
[epoch 000000115] loss=nan | avg=nan | rare=nan
[epoch 000000116] loss=nan | avg=nan | rare=nan
[epoch 000000117] loss=nan | avg=nan | rare=nan
[epoch 000000118] loss=nan | avg=nan | rare=nan
[epoch 000000119] loss=nan | avg=nan | rare=nan
[epoch 000000120] loss=nan | avg=nan | rare=nan
[epoch 000000121] loss=nan | avg=nan | rare=nan
[epoch 000000122] loss=nan | avg=nan | rare=nan
[epoch 000000123] loss=nan | avg=nan | rare=nan
[epoch 000000124] loss=nan | avg=nan | rare=nan
[epoch 000000125] loss=nan | avg=nan | rare=nan
[epoch 000000126] loss=nan | avg=nan | rare=nan
[epoch 000000127] loss=nan | avg=nan | rare=nan
[epoch 000000128] loss=nan | avg=nan | rare=nan
[epoch 000000129] loss=nan | avg=nan | rare=nan
[epoch 000000130] loss=nan | avg=nan | rare=nan
[epoch 000000131] loss=nan | avg=nan | rare=nan
[epoch 000000132] loss=nan | avg=nan | rare=nan
[epoch 000000133] loss=nan | avg=nan | rare=nan
[epoch 000000134] loss=nan | avg=nan | rare=nan
[epoch 000000135] loss=nan | avg=nan | rare=nan
[epoch 000000136] loss=nan | avg=nan | rare=nan
[epoch 000000137] loss=nan | avg=nan | rare=nan
[epoch 000000138] loss=nan | avg=nan | rare=nan
[epoch 000000139] loss=nan | avg=nan | rare=nan
[epoch 000000140] loss=nan | avg=nan | rare=nan
[epoch 000000141] loss=nan | avg=nan | rare=nan
[epoch 000000142] loss=nan | avg=nan | rare=nan
[epoch 000000143] loss=nan | avg=nan | rare=nan
[epoch 000000144] loss=nan | avg=nan | rare=nan
[epoch 000000145] loss=nan | avg=nan | rare=nan
[epoch 000000146] loss=nan | avg=nan | rare=nan
[epoch 000000147] loss=nan | avg=nan | rare=nan
[epoch 000000148] loss=nan | avg=nan | rare=nan
[epoch 000000149] loss=nan | avg=nan | rare=nan
[epoch 000000150] loss=nan | avg=nan | rare=nan
[epoch 000000151] loss=nan | avg=nan | rare=nan
[epoch 000000152] loss=nan | avg=nan | rare=nan
[epoch 000000153] loss=nan | avg=nan | rare=nan
[epoch 000000154] loss=nan | avg=nan | rare=nan
[epoch 000000155] loss=nan | avg=nan | rare=nan
[epoch 000000156] loss=nan | avg=nan | rare=nan
[epoch 000000157] loss=nan | avg=nan | rare=nan
[epoch 000000158] loss=nan | avg=nan | rare=nan
[epoch 000000159] loss=nan | avg=nan | rare=nan
[epoch 000000160] loss=nan | avg=nan | rare=nan
[epoch 000000161] loss=nan | avg=nan | rare=nan
[epoch 000000162] loss=nan | avg=nan | rare=nan
[epoch 000000163] loss=nan | avg=nan | rare=nan
[epoch 000000164] loss=nan | avg=nan | rare=nan
[epoch 000000165] loss=nan | avg=nan | rare=nan
[epoch 000000166] loss=nan | avg=nan | rare=nan
[epoch 000000167] loss=nan | avg=nan | rare=nan
[epoch 000000168] loss=nan | avg=nan | rare=nan
[epoch 000000169] loss=nan | avg=nan | rare=nan
[epoch 000000170] loss=nan | avg=nan | rare=nan
[epoch 000000171] loss=nan | avg=nan | rare=nan
[epoch 000000172] loss=nan | avg=nan | rare=nan
[epoch 000000173] loss=nan | avg=nan | rare=nan
[epoch 000000174] loss=nan | avg=nan | rare=nan
[epoch 000000175] loss=nan | avg=nan | rare=nan
[epoch 000000176] loss=nan | avg=nan | rare=nan
[epoch 000000177] loss=nan | avg=nan | rare=nan
[epoch 000000178] loss=nan | avg=nan | rare=nan
[epoch 000000179] loss=nan | avg=nan | rare=nan
[epoch 000000180] loss=nan | avg=nan | rare=nan
[epoch 000000181] loss=nan | avg=nan | rare=nan
[epoch 000000182] loss=nan | avg=nan | rare=nan
[epoch 000000183] loss=nan | avg=nan | rare=nan
[epoch 000000184] loss=nan | avg=nan | rare=nan
[epoch 000000185] loss=nan | avg=nan | rare=nan
[epoch 000000186] loss=nan | avg=nan | rare=nan
[epoch 000000187] loss=nan | avg=nan | rare=nan
[epoch 000000188] loss=nan | avg=nan | rare=nan
[epoch 000000189] loss=nan | avg=nan | rare=nan
[epoch 000000190] loss=nan | avg=nan | rare=nan
[epoch 000000191] loss=nan | avg=nan | rare=nan
[epoch 000000192] loss=nan | avg=nan | rare=nan
[epoch 000000193] loss=nan | avg=nan | rare=nan
[epoch 000000194] loss=nan | avg=nan | rare=nan
[epoch 000000195] loss=nan | avg=nan | rare=nan
[epoch 000000196] loss=nan | avg=nan | rare=nan
[epoch 000000197] loss=nan | avg=nan | rare=nan
[epoch 000000198] loss=nan | avg=nan | rare=nan
[epoch 000000199] loss=nan | avg=nan | rare=nan
[epoch 000000200] loss=nan | avg=nan | rare=nan

Training safe with sgd...

Epochs:   0%|          | 0/200 [00:00<?, ?it/s]

[epoch 000000001] loss=99.187316622 | avg=67.356073380 | rare=0.000318312
[epoch 000000002] loss=233.292025702 | avg=60.914196832 | rare=0.001723778
[epoch 000000003] loss=110519.067583902 | avg=44.524699620 | rare=1.104745413
[epoch 000000004] loss=nan | avg=nan | rare=nan
[epoch 000000005] loss=nan | avg=nan | rare=nan
[epoch 000000006] loss=nan | avg=nan | rare=nan
[epoch 000000007] loss=nan | avg=nan | rare=nan
[epoch 000000008] loss=nan | avg=nan | rare=nan
[epoch 000000009] loss=nan | avg=nan | rare=nan
[epoch 000000010] loss=nan | avg=nan | rare=nan
[epoch 000000011] loss=nan | avg=nan | rare=nan
[epoch 000000012] loss=nan | avg=nan | rare=nan
[epoch 000000013] loss=nan | avg=nan | rare=nan
[epoch 000000014] loss=nan | avg=nan | rare=nan
[epoch 000000015] loss=nan | avg=nan | rare=nan
[epoch 000000016] loss=nan | avg=nan | rare=nan
[epoch 000000017] loss=nan | avg=nan | rare=nan
[epoch 000000018] loss=nan | avg=nan | rare=nan
[epoch 000000019] loss=nan | avg=nan | rare=nan
[epoch 000000020] loss=nan | avg=nan | rare=nan
[epoch 000000021] loss=nan | avg=nan | rare=nan
[epoch 000000022] loss=nan | avg=nan | rare=nan
[epoch 000000023] loss=nan | avg=nan | rare=nan
[epoch 000000024] loss=nan | avg=nan | rare=nan
[epoch 000000025] loss=nan | avg=nan | rare=nan
[epoch 000000026] loss=nan | avg=nan | rare=nan
[epoch 000000027] loss=nan | avg=nan | rare=nan
[epoch 000000028] loss=nan | avg=nan | rare=nan
[epoch 000000029] loss=nan | avg=nan | rare=nan
[epoch 000000030] loss=nan | avg=nan | rare=nan
[epoch 000000031] loss=nan | avg=nan | rare=nan
[epoch 000000032] loss=nan | avg=nan | rare=nan
[epoch 000000033] loss=nan | avg=nan | rare=nan
[epoch 000000034] loss=nan | avg=nan | rare=nan
[epoch 000000035] loss=nan | avg=nan | rare=nan
[epoch 000000036] loss=nan | avg=nan | rare=nan
[epoch 000000037] loss=nan | avg=nan | rare=nan
[epoch 000000038] loss=nan | avg=nan | rare=nan
[epoch 000000039] loss=nan | avg=nan | rare=nan
[epoch 000000040] loss=nan | avg=nan | rare=nan
[epoch 000000041] loss=nan | avg=nan | rare=nan
[epoch 000000042] loss=nan | avg=nan | rare=nan
[epoch 000000043] loss=nan | avg=nan | rare=nan
[epoch 000000044] loss=nan | avg=nan | rare=nan
[epoch 000000045] loss=nan | avg=nan | rare=nan
[epoch 000000046] loss=nan | avg=nan | rare=nan
[epoch 000000047] loss=nan | avg=nan | rare=nan
[epoch 000000048] loss=nan | avg=nan | rare=nan
[epoch 000000049] loss=nan | avg=nan | rare=nan
[epoch 000000050] loss=nan | avg=nan | rare=nan
[epoch 000000051] loss=nan | avg=nan | rare=nan
[epoch 000000052] loss=nan | avg=nan | rare=nan
[epoch 000000053] loss=nan | avg=nan | rare=nan
[epoch 000000054] loss=nan | avg=nan | rare=nan
[epoch 000000055] loss=nan | avg=nan | rare=nan
[epoch 000000056] loss=nan | avg=nan | rare=nan
[epoch 000000057] loss=nan | avg=nan | rare=nan
[epoch 000000058] loss=nan | avg=nan | rare=nan
[epoch 000000059] loss=nan | avg=nan | rare=nan
[epoch 000000060] loss=nan | avg=nan | rare=nan
[epoch 000000061] loss=nan | avg=nan | rare=nan
[epoch 000000062] loss=nan | avg=nan | rare=nan
[epoch 000000063] loss=nan | avg=nan | rare=nan
[epoch 000000064] loss=nan | avg=nan | rare=nan
[epoch 000000065] loss=nan | avg=nan | rare=nan
[epoch 000000066] loss=nan | avg=nan | rare=nan
[epoch 000000067] loss=nan | avg=nan | rare=nan
[epoch 000000068] loss=nan | avg=nan | rare=nan
[epoch 000000069] loss=nan | avg=nan | rare=nan
[epoch 000000070] loss=nan | avg=nan | rare=nan
[epoch 000000071] loss=nan | avg=nan | rare=nan
[epoch 000000072] loss=nan | avg=nan | rare=nan
[epoch 000000073] loss=nan | avg=nan | rare=nan
[epoch 000000074] loss=nan | avg=nan | rare=nan
[epoch 000000075] loss=nan | avg=nan | rare=nan
[epoch 000000076] loss=nan | avg=nan | rare=nan
[epoch 000000077] loss=nan | avg=nan | rare=nan
[epoch 000000078] loss=nan | avg=nan | rare=nan
[epoch 000000079] loss=nan | avg=nan | rare=nan
[epoch 000000080] loss=nan | avg=nan | rare=nan
[epoch 000000081] loss=nan | avg=nan | rare=nan
[epoch 000000082] loss=nan | avg=nan | rare=nan
[epoch 000000083] loss=nan | avg=nan | rare=nan
[epoch 000000084] loss=nan | avg=nan | rare=nan
[epoch 000000085] loss=nan | avg=nan | rare=nan
[epoch 000000086] loss=nan | avg=nan | rare=nan
[epoch 000000087] loss=nan | avg=nan | rare=nan
[epoch 000000088] loss=nan | avg=nan | rare=nan
[epoch 000000089] loss=nan | avg=nan | rare=nan
[epoch 000000090] loss=nan | avg=nan | rare=nan
[epoch 000000091] loss=nan | avg=nan | rare=nan
[epoch 000000092] loss=nan | avg=nan | rare=nan
[epoch 000000093] loss=nan | avg=nan | rare=nan
[epoch 000000094] loss=nan | avg=nan | rare=nan
[epoch 000000095] loss=nan | avg=nan | rare=nan
[epoch 000000096] loss=nan | avg=nan | rare=nan
[epoch 000000097] loss=nan | avg=nan | rare=nan
[epoch 000000098] loss=nan | avg=nan | rare=nan
[epoch 000000099] loss=nan | avg=nan | rare=nan
[epoch 000000100] loss=nan | avg=nan | rare=nan
[epoch 000000101] loss=nan | avg=nan | rare=nan
[epoch 000000102] loss=nan | avg=nan | rare=nan
[epoch 000000103] loss=nan | avg=nan | rare=nan
[epoch 000000104] loss=nan | avg=nan | rare=nan
[epoch 000000105] loss=nan | avg=nan | rare=nan
[epoch 000000106] loss=nan | avg=nan | rare=nan
[epoch 000000107] loss=nan | avg=nan | rare=nan
[epoch 000000108] loss=nan | avg=nan | rare=nan
[epoch 000000109] loss=nan | avg=nan | rare=nan
[epoch 000000110] loss=nan | avg=nan | rare=nan
[epoch 000000111] loss=nan | avg=nan | rare=nan
[epoch 000000112] loss=nan | avg=nan | rare=nan
[epoch 000000113] loss=nan | avg=nan | rare=nan
[epoch 000000114] loss=nan | avg=nan | rare=nan
[epoch 000000115] loss=nan | avg=nan | rare=nan
[epoch 000000116] loss=nan | avg=nan | rare=nan
[epoch 000000117] loss=nan | avg=nan | rare=nan
[epoch 000000118] loss=nan | avg=nan | rare=nan
[epoch 000000119] loss=nan | avg=nan | rare=nan
[epoch 000000120] loss=nan | avg=nan | rare=nan
[epoch 000000121] loss=nan | avg=nan | rare=nan
[epoch 000000122] loss=nan | avg=nan | rare=nan
[epoch 000000123] loss=nan | avg=nan | rare=nan
[epoch 000000124] loss=nan | avg=nan | rare=nan
[epoch 000000125] loss=nan | avg=nan | rare=nan
[epoch 000000126] loss=nan | avg=nan | rare=nan
[epoch 000000127] loss=nan | avg=nan | rare=nan
[epoch 000000128] loss=nan | avg=nan | rare=nan
[epoch 000000129] loss=nan | avg=nan | rare=nan
[epoch 000000130] loss=nan | avg=nan | rare=nan
[epoch 000000131] loss=nan | avg=nan | rare=nan
[epoch 000000132] loss=nan | avg=nan | rare=nan
[epoch 000000133] loss=nan | avg=nan | rare=nan
[epoch 000000134] loss=nan | avg=nan | rare=nan
[epoch 000000135] loss=nan | avg=nan | rare=nan
[epoch 000000136] loss=nan | avg=nan | rare=nan
[epoch 000000137] loss=nan | avg=nan | rare=nan
[epoch 000000138] loss=nan | avg=nan | rare=nan
[epoch 000000139] loss=nan | avg=nan | rare=nan
[epoch 000000140] loss=nan | avg=nan | rare=nan
[epoch 000000141] loss=nan | avg=nan | rare=nan
[epoch 000000142] loss=nan | avg=nan | rare=nan
[epoch 000000143] loss=nan | avg=nan | rare=nan
[epoch 000000144] loss=nan | avg=nan | rare=nan
[epoch 000000145] loss=nan | avg=nan | rare=nan
[epoch 000000146] loss=nan | avg=nan | rare=nan
[epoch 000000147] loss=nan | avg=nan | rare=nan
[epoch 000000148] loss=nan | avg=nan | rare=nan
[epoch 000000149] loss=nan | avg=nan | rare=nan
[epoch 000000150] loss=nan | avg=nan | rare=nan
[epoch 000000151] loss=nan | avg=nan | rare=nan
[epoch 000000152] loss=nan | avg=nan | rare=nan
[epoch 000000153] loss=nan | avg=nan | rare=nan
[epoch 000000154] loss=nan | avg=nan | rare=nan
[epoch 000000155] loss=nan | avg=nan | rare=nan
[epoch 000000156] loss=nan | avg=nan | rare=nan
[epoch 000000157] loss=nan | avg=nan | rare=nan
[epoch 000000158] loss=nan | avg=nan | rare=nan
[epoch 000000159] loss=nan | avg=nan | rare=nan
[epoch 000000160] loss=nan | avg=nan | rare=nan
[epoch 000000161] loss=nan | avg=nan | rare=nan
[epoch 000000162] loss=nan | avg=nan | rare=nan
[epoch 000000163] loss=nan | avg=nan | rare=nan
[epoch 000000164] loss=nan | avg=nan | rare=nan
[epoch 000000165] loss=nan | avg=nan | rare=nan
[epoch 000000166] loss=nan | avg=nan | rare=nan
[epoch 000000167] loss=nan | avg=nan | rare=nan
[epoch 000000168] loss=nan | avg=nan | rare=nan
[epoch 000000169] loss=nan | avg=nan | rare=nan
[epoch 000000170] loss=nan | avg=nan | rare=nan
[epoch 000000171] loss=nan | avg=nan | rare=nan
[epoch 000000172] loss=nan | avg=nan | rare=nan
[epoch 000000173] loss=nan | avg=nan | rare=nan
[epoch 000000174] loss=nan | avg=nan | rare=nan
[epoch 000000175] loss=nan | avg=nan | rare=nan
[epoch 000000176] loss=nan | avg=nan | rare=nan
[epoch 000000177] loss=nan | avg=nan | rare=nan
[epoch 000000178] loss=nan | avg=nan | rare=nan
[epoch 000000179] loss=nan | avg=nan | rare=nan
[epoch 000000180] loss=nan | avg=nan | rare=nan
[epoch 000000181] loss=nan | avg=nan | rare=nan
[epoch 000000182] loss=nan | avg=nan | rare=nan
[epoch 000000183] loss=nan | avg=nan | rare=nan
[epoch 000000184] loss=nan | avg=nan | rare=nan
[epoch 000000185] loss=nan | avg=nan | rare=nan
[epoch 000000186] loss=nan | avg=nan | rare=nan
[epoch 000000187] loss=nan | avg=nan | rare=nan
[epoch 000000188] loss=nan | avg=nan | rare=nan
[epoch 000000189] loss=nan | avg=nan | rare=nan
[epoch 000000190] loss=nan | avg=nan | rare=nan
[epoch 000000191] loss=nan | avg=nan | rare=nan
[epoch 000000192] loss=nan | avg=nan | rare=nan
[epoch 000000193] loss=nan | avg=nan | rare=nan
[epoch 000000194] loss=nan | avg=nan | rare=nan
[epoch 000000195] loss=nan | avg=nan | rare=nan
[epoch 000000196] loss=nan | avg=nan | rare=nan
[epoch 000000197] loss=nan | avg=nan | rare=nan
[epoch 000000198] loss=nan | avg=nan | rare=nan
[epoch 000000199] loss=nan | avg=nan | rare=nan
[epoch 000000200] loss=nan | avg=nan | rare=nan
Accuracy: 63.96%  (CI 95%: [62.63%, 65.28%])
Robust Accuracy: 63.96415%  (CI 95%: [62.84861%, 65.40986%])
Conditional Robust Accuracy: 100.00000%  (CI 95%: [100.00000%, 100.00000%])
Accuracy: 63.96%  (CI 95%: [62.63%, 65.28%])
Robust Accuracy: 63.96415%  (CI 95%: [62.84861%, 65.40986%])
Conditional Robust Accuracy: 100.00000%  (CI 95%: [100.00000%, 100.00000%])
  --> Running Seed: 100

Training naive with sgd...

Epochs:   0%|          | 0/200 [00:00<?, ?it/s]

[epoch 000000001] loss=178466.601562500 | avg=0.319753973 | rare=1.784662809
[epoch 000000002] loss=178522.145089286 | avg=0.320083375 | rare=1.785218264
[epoch 000000003] loss=nan | avg=nan | rare=nan
[epoch 000000004] loss=nan | avg=nan | rare=nan
[epoch 000000005] loss=nan | avg=nan | rare=nan
[epoch 000000006] loss=nan | avg=nan | rare=nan
[epoch 000000007] loss=nan | avg=nan | rare=nan
[epoch 000000008] loss=nan | avg=nan | rare=nan
[epoch 000000009] loss=nan | avg=nan | rare=nan
[epoch 000000010] loss=nan | avg=nan | rare=nan
[epoch 000000011] loss=nan | avg=nan | rare=nan
[epoch 000000012] loss=nan | avg=nan | rare=nan
[epoch 000000013] loss=nan | avg=nan | rare=nan
[epoch 000000014] loss=nan | avg=nan | rare=nan
[epoch 000000015] loss=nan | avg=nan | rare=nan
[epoch 000000016] loss=nan | avg=nan | rare=nan
[epoch 000000017] loss=nan | avg=nan | rare=nan
[epoch 000000018] loss=nan | avg=nan | rare=nan
[epoch 000000019] loss=nan | avg=nan | rare=nan
[epoch 000000020] loss=nan | avg=nan | rare=nan
[epoch 000000021] loss=nan | avg=nan | rare=nan
[epoch 000000022] loss=nan | avg=nan | rare=nan
[epoch 000000023] loss=nan | avg=nan | rare=nan
[epoch 000000024] loss=nan | avg=nan | rare=nan
[epoch 000000025] loss=nan | avg=nan | rare=nan
[epoch 000000026] loss=nan | avg=nan | rare=nan
[epoch 000000027] loss=nan | avg=nan | rare=nan
[epoch 000000028] loss=nan | avg=nan | rare=nan
[epoch 000000029] loss=nan | avg=nan | rare=nan
[epoch 000000030] loss=nan | avg=nan | rare=nan
[epoch 000000031] loss=nan | avg=nan | rare=nan
[epoch 000000032] loss=nan | avg=nan | rare=nan
[epoch 000000033] loss=nan | avg=nan | rare=nan
[epoch 000000034] loss=nan | avg=nan | rare=nan
[epoch 000000035] loss=nan | avg=nan | rare=nan
[epoch 000000036] loss=nan | avg=nan | rare=nan
[epoch 000000037] loss=nan | avg=nan | rare=nan
[epoch 000000038] loss=nan | avg=nan | rare=nan
[epoch 000000039] loss=nan | avg=nan | rare=nan
[epoch 000000040] loss=nan | avg=nan | rare=nan
[epoch 000000041] loss=nan | avg=nan | rare=nan
[epoch 000000042] loss=nan | avg=nan | rare=nan
[epoch 000000043] loss=nan | avg=nan | rare=nan
[epoch 000000044] loss=nan | avg=nan | rare=nan
[epoch 000000045] loss=nan | avg=nan | rare=nan
[epoch 000000046] loss=nan | avg=nan | rare=nan
[epoch 000000047] loss=nan | avg=nan | rare=nan
[epoch 000000048] loss=nan | avg=nan | rare=nan
[epoch 000000049] loss=nan | avg=nan | rare=nan
[epoch 000000050] loss=nan | avg=nan | rare=nan
[epoch 000000051] loss=nan | avg=nan | rare=nan
[epoch 000000052] loss=nan | avg=nan | rare=nan
[epoch 000000053] loss=nan | avg=nan | rare=nan
[epoch 000000054] loss=nan | avg=nan | rare=nan
[epoch 000000055] loss=nan | avg=nan | rare=nan
[epoch 000000056] loss=nan | avg=nan | rare=nan
[epoch 000000057] loss=nan | avg=nan | rare=nan
[epoch 000000058] loss=nan | avg=nan | rare=nan
[epoch 000000059] loss=nan | avg=nan | rare=nan
[epoch 000000060] loss=nan | avg=nan | rare=nan
[epoch 000000061] loss=nan | avg=nan | rare=nan
[epoch 000000062] loss=nan | avg=nan | rare=nan
[epoch 000000063] loss=nan | avg=nan | rare=nan
[epoch 000000064] loss=nan | avg=nan | rare=nan
[epoch 000000065] loss=nan | avg=nan | rare=nan
[epoch 000000066] loss=nan | avg=nan | rare=nan
[epoch 000000067] loss=nan | avg=nan | rare=nan
[epoch 000000068] loss=nan | avg=nan | rare=nan
[epoch 000000069] loss=nan | avg=nan | rare=nan
[epoch 000000070] loss=nan | avg=nan | rare=nan
[epoch 000000071] loss=nan | avg=nan | rare=nan
[epoch 000000072] loss=nan | avg=nan | rare=nan
[epoch 000000073] loss=nan | avg=nan | rare=nan
[epoch 000000074] loss=nan | avg=nan | rare=nan
[epoch 000000075] loss=nan | avg=nan | rare=nan
[epoch 000000076] loss=nan | avg=nan | rare=nan
[epoch 000000077] loss=nan | avg=nan | rare=nan
[epoch 000000078] loss=nan | avg=nan | rare=nan
[epoch 000000079] loss=nan | avg=nan | rare=nan
[epoch 000000080] loss=nan | avg=nan | rare=nan
[epoch 000000081] loss=nan | avg=nan | rare=nan
[epoch 000000082] loss=nan | avg=nan | rare=nan
[epoch 000000083] loss=nan | avg=nan | rare=nan
[epoch 000000084] loss=nan | avg=nan | rare=nan
[epoch 000000085] loss=nan | avg=nan | rare=nan
[epoch 000000086] loss=nan | avg=nan | rare=nan
[epoch 000000087] loss=nan | avg=nan | rare=nan
[epoch 000000088] loss=nan | avg=nan | rare=nan
[epoch 000000089] loss=nan | avg=nan | rare=nan
[epoch 000000090] loss=nan | avg=nan | rare=nan
[epoch 000000091] loss=nan | avg=nan | rare=nan
[epoch 000000092] loss=nan | avg=nan | rare=nan
[epoch 000000093] loss=nan | avg=nan | rare=nan
[epoch 000000094] loss=nan | avg=nan | rare=nan
[epoch 000000095] loss=nan | avg=nan | rare=nan
[epoch 000000096] loss=nan | avg=nan | rare=nan
[epoch 000000097] loss=nan | avg=nan | rare=nan
[epoch 000000098] loss=nan | avg=nan | rare=nan
[epoch 000000099] loss=nan | avg=nan | rare=nan
[epoch 000000100] loss=nan | avg=nan | rare=nan
[epoch 000000101] loss=nan | avg=nan | rare=nan
[epoch 000000102] loss=nan | avg=nan | rare=nan
[epoch 000000103] loss=nan | avg=nan | rare=nan
[epoch 000000104] loss=nan | avg=nan | rare=nan
[epoch 000000105] loss=nan | avg=nan | rare=nan
[epoch 000000106] loss=nan | avg=nan | rare=nan
[epoch 000000107] loss=nan | avg=nan | rare=nan
[epoch 000000108] loss=nan | avg=nan | rare=nan
[epoch 000000109] loss=nan | avg=nan | rare=nan
[epoch 000000110] loss=nan | avg=nan | rare=nan
[epoch 000000111] loss=nan | avg=nan | rare=nan
[epoch 000000112] loss=nan | avg=nan | rare=nan
[epoch 000000113] loss=nan | avg=nan | rare=nan
[epoch 000000114] loss=nan | avg=nan | rare=nan
[epoch 000000115] loss=nan | avg=nan | rare=nan
[epoch 000000116] loss=nan | avg=nan | rare=nan
[epoch 000000117] loss=nan | avg=nan | rare=nan
[epoch 000000118] loss=nan | avg=nan | rare=nan
[epoch 000000119] loss=nan | avg=nan | rare=nan
[epoch 000000120] loss=nan | avg=nan | rare=nan
[epoch 000000121] loss=nan | avg=nan | rare=nan
[epoch 000000122] loss=nan | avg=nan | rare=nan
[epoch 000000123] loss=nan | avg=nan | rare=nan
[epoch 000000124] loss=nan | avg=nan | rare=nan
[epoch 000000125] loss=nan | avg=nan | rare=nan
[epoch 000000126] loss=nan | avg=nan | rare=nan
[epoch 000000127] loss=nan | avg=nan | rare=nan
[epoch 000000128] loss=nan | avg=nan | rare=nan
[epoch 000000129] loss=nan | avg=nan | rare=nan
[epoch 000000130] loss=nan | avg=nan | rare=nan
[epoch 000000131] loss=nan | avg=nan | rare=nan
[epoch 000000132] loss=nan | avg=nan | rare=nan
[epoch 000000133] loss=nan | avg=nan | rare=nan
[epoch 000000134] loss=nan | avg=nan | rare=nan
[epoch 000000135] loss=nan | avg=nan | rare=nan
[epoch 000000136] loss=nan | avg=nan | rare=nan
[epoch 000000137] loss=nan | avg=nan | rare=nan
[epoch 000000138] loss=nan | avg=nan | rare=nan
[epoch 000000139] loss=nan | avg=nan | rare=nan
[epoch 000000140] loss=nan | avg=nan | rare=nan
[epoch 000000141] loss=nan | avg=nan | rare=nan
[epoch 000000142] loss=nan | avg=nan | rare=nan
[epoch 000000143] loss=nan | avg=nan | rare=nan
[epoch 000000144] loss=nan | avg=nan | rare=nan
[epoch 000000145] loss=nan | avg=nan | rare=nan
[epoch 000000146] loss=nan | avg=nan | rare=nan
[epoch 000000147] loss=nan | avg=nan | rare=nan
[epoch 000000148] loss=nan | avg=nan | rare=nan
[epoch 000000149] loss=nan | avg=nan | rare=nan
[epoch 000000150] loss=nan | avg=nan | rare=nan
[epoch 000000151] loss=nan | avg=nan | rare=nan
[epoch 000000152] loss=nan | avg=nan | rare=nan
[epoch 000000153] loss=nan | avg=nan | rare=nan
[epoch 000000154] loss=nan | avg=nan | rare=nan
[epoch 000000155] loss=nan | avg=nan | rare=nan
[epoch 000000156] loss=nan | avg=nan | rare=nan
[epoch 000000157] loss=nan | avg=nan | rare=nan
[epoch 000000158] loss=nan | avg=nan | rare=nan
[epoch 000000159] loss=nan | avg=nan | rare=nan
[epoch 000000160] loss=nan | avg=nan | rare=nan
[epoch 000000161] loss=nan | avg=nan | rare=nan
[epoch 000000162] loss=nan | avg=nan | rare=nan
[epoch 000000163] loss=nan | avg=nan | rare=nan
[epoch 000000164] loss=nan | avg=nan | rare=nan
[epoch 000000165] loss=nan | avg=nan | rare=nan
[epoch 000000166] loss=nan | avg=nan | rare=nan
[epoch 000000167] loss=nan | avg=nan | rare=nan
[epoch 000000168] loss=nan | avg=nan | rare=nan
[epoch 000000169] loss=nan | avg=nan | rare=nan
[epoch 000000170] loss=nan | avg=nan | rare=nan
[epoch 000000171] loss=nan | avg=nan | rare=nan
[epoch 000000172] loss=nan | avg=nan | rare=nan
[epoch 000000173] loss=nan | avg=nan | rare=nan
[epoch 000000174] loss=nan | avg=nan | rare=nan
[epoch 000000175] loss=nan | avg=nan | rare=nan
[epoch 000000176] loss=nan | avg=nan | rare=nan
[epoch 000000177] loss=nan | avg=nan | rare=nan
[epoch 000000178] loss=nan | avg=nan | rare=nan
[epoch 000000179] loss=nan | avg=nan | rare=nan
[epoch 000000180] loss=nan | avg=nan | rare=nan
[epoch 000000181] loss=nan | avg=nan | rare=nan
[epoch 000000182] loss=nan | avg=nan | rare=nan
[epoch 000000183] loss=nan | avg=nan | rare=nan
[epoch 000000184] loss=nan | avg=nan | rare=nan
[epoch 000000185] loss=nan | avg=nan | rare=nan
[epoch 000000186] loss=nan | avg=nan | rare=nan
[epoch 000000187] loss=nan | avg=nan | rare=nan
[epoch 000000188] loss=nan | avg=nan | rare=nan
[epoch 000000189] loss=nan | avg=nan | rare=nan
[epoch 000000190] loss=nan | avg=nan | rare=nan
[epoch 000000191] loss=nan | avg=nan | rare=nan
[epoch 000000192] loss=nan | avg=nan | rare=nan
[epoch 000000193] loss=nan | avg=nan | rare=nan
[epoch 000000194] loss=nan | avg=nan | rare=nan
[epoch 000000195] loss=nan | avg=nan | rare=nan
[epoch 000000196] loss=nan | avg=nan | rare=nan
[epoch 000000197] loss=nan | avg=nan | rare=nan
[epoch 000000198] loss=nan | avg=nan | rare=nan
[epoch 000000199] loss=nan | avg=nan | rare=nan
[epoch 000000200] loss=nan | avg=nan | rare=nan

Training safe with sgd...

Epochs:   0%|          | 0/200 [00:00<?, ?it/s]

[epoch 000000001] loss=106.265415737 | avg=67.539784023 | rare=0.000387256
[epoch 000000002] loss=149.806556702 | avg=64.170399802 | rare=0.000856362
[epoch 000000003] loss=nan | avg=nan | rare=nan
[epoch 000000004] loss=nan | avg=nan | rare=nan
[epoch 000000005] loss=nan | avg=nan | rare=nan
[epoch 000000006] loss=nan | avg=nan | rare=nan
[epoch 000000007] loss=nan | avg=nan | rare=nan
[epoch 000000008] loss=nan | avg=nan | rare=nan
[epoch 000000009] loss=nan | avg=nan | rare=nan
[epoch 000000010] loss=nan | avg=nan | rare=nan
[epoch 000000011] loss=nan | avg=nan | rare=nan
[epoch 000000012] loss=nan | avg=nan | rare=nan
[epoch 000000013] loss=nan | avg=nan | rare=nan
[epoch 000000014] loss=nan | avg=nan | rare=nan
[epoch 000000015] loss=nan | avg=nan | rare=nan
[epoch 000000016] loss=nan | avg=nan | rare=nan
[epoch 000000017] loss=nan | avg=nan | rare=nan
[epoch 000000018] loss=nan | avg=nan | rare=nan
[epoch 000000019] loss=nan | avg=nan | rare=nan
[epoch 000000020] loss=nan | avg=nan | rare=nan
[epoch 000000021] loss=nan | avg=nan | rare=nan
[epoch 000000022] loss=nan | avg=nan | rare=nan
[epoch 000000023] loss=nan | avg=nan | rare=nan
[epoch 000000024] loss=nan | avg=nan | rare=nan
[epoch 000000025] loss=nan | avg=nan | rare=nan
[epoch 000000026] loss=nan | avg=nan | rare=nan
[epoch 000000027] loss=nan | avg=nan | rare=nan
[epoch 000000028] loss=nan | avg=nan | rare=nan
[epoch 000000029] loss=nan | avg=nan | rare=nan
[epoch 000000030] loss=nan | avg=nan | rare=nan
[epoch 000000031] loss=nan | avg=nan | rare=nan
[epoch 000000032] loss=nan | avg=nan | rare=nan
[epoch 000000033] loss=nan | avg=nan | rare=nan
[epoch 000000034] loss=nan | avg=nan | rare=nan
[epoch 000000035] loss=nan | avg=nan | rare=nan
[epoch 000000036] loss=nan | avg=nan | rare=nan
[epoch 000000037] loss=nan | avg=nan | rare=nan
[epoch 000000038] loss=nan | avg=nan | rare=nan
[epoch 000000039] loss=nan | avg=nan | rare=nan
[epoch 000000040] loss=nan | avg=nan | rare=nan
[epoch 000000041] loss=nan | avg=nan | rare=nan
[epoch 000000042] loss=nan | avg=nan | rare=nan
[epoch 000000043] loss=nan | avg=nan | rare=nan
[epoch 000000044] loss=nan | avg=nan | rare=nan
[epoch 000000045] loss=nan | avg=nan | rare=nan
[epoch 000000046] loss=nan | avg=nan | rare=nan
[epoch 000000047] loss=nan | avg=nan | rare=nan
[epoch 000000048] loss=nan | avg=nan | rare=nan
[epoch 000000049] loss=nan | avg=nan | rare=nan
[epoch 000000050] loss=nan | avg=nan | rare=nan
[epoch 000000051] loss=nan | avg=nan | rare=nan
[epoch 000000052] loss=nan | avg=nan | rare=nan
[epoch 000000053] loss=nan | avg=nan | rare=nan
[epoch 000000054] loss=nan | avg=nan | rare=nan
[epoch 000000055] loss=nan | avg=nan | rare=nan
[epoch 000000056] loss=nan | avg=nan | rare=nan
[epoch 000000057] loss=nan | avg=nan | rare=nan
[epoch 000000058] loss=nan | avg=nan | rare=nan
[epoch 000000059] loss=nan | avg=nan | rare=nan
[epoch 000000060] loss=nan | avg=nan | rare=nan
[epoch 000000061] loss=nan | avg=nan | rare=nan
[epoch 000000062] loss=nan | avg=nan | rare=nan
[epoch 000000063] loss=nan | avg=nan | rare=nan
[epoch 000000064] loss=nan | avg=nan | rare=nan
[epoch 000000065] loss=nan | avg=nan | rare=nan
[epoch 000000066] loss=nan | avg=nan | rare=nan
[epoch 000000067] loss=nan | avg=nan | rare=nan
[epoch 000000068] loss=nan | avg=nan | rare=nan
[epoch 000000069] loss=nan | avg=nan | rare=nan
[epoch 000000070] loss=nan | avg=nan | rare=nan
[epoch 000000071] loss=nan | avg=nan | rare=nan
[epoch 000000072] loss=nan | avg=nan | rare=nan
[epoch 000000073] loss=nan | avg=nan | rare=nan
[epoch 000000074] loss=nan | avg=nan | rare=nan
[epoch 000000075] loss=nan | avg=nan | rare=nan
[epoch 000000076] loss=nan | avg=nan | rare=nan
[epoch 000000077] loss=nan | avg=nan | rare=nan
[epoch 000000078] loss=nan | avg=nan | rare=nan
[epoch 000000079] loss=nan | avg=nan | rare=nan
[epoch 000000080] loss=nan | avg=nan | rare=nan
[epoch 000000081] loss=nan | avg=nan | rare=nan
[epoch 000000082] loss=nan | avg=nan | rare=nan
[epoch 000000083] loss=nan | avg=nan | rare=nan
[epoch 000000084] loss=nan | avg=nan | rare=nan
[epoch 000000085] loss=nan | avg=nan | rare=nan
[epoch 000000086] loss=nan | avg=nan | rare=nan
[epoch 000000087] loss=nan | avg=nan | rare=nan
[epoch 000000088] loss=nan | avg=nan | rare=nan
[epoch 000000089] loss=nan | avg=nan | rare=nan
[epoch 000000090] loss=nan | avg=nan | rare=nan
[epoch 000000091] loss=nan | avg=nan | rare=nan
[epoch 000000092] loss=nan | avg=nan | rare=nan
[epoch 000000093] loss=nan | avg=nan | rare=nan
[epoch 000000094] loss=nan | avg=nan | rare=nan
[epoch 000000095] loss=nan | avg=nan | rare=nan
[epoch 000000096] loss=nan | avg=nan | rare=nan
[epoch 000000097] loss=nan | avg=nan | rare=nan
[epoch 000000098] loss=nan | avg=nan | rare=nan
[epoch 000000099] loss=nan | avg=nan | rare=nan
[epoch 000000100] loss=nan | avg=nan | rare=nan
[epoch 000000101] loss=nan | avg=nan | rare=nan
[epoch 000000102] loss=nan | avg=nan | rare=nan
[epoch 000000103] loss=nan | avg=nan | rare=nan
[epoch 000000104] loss=nan | avg=nan | rare=nan
[epoch 000000105] loss=nan | avg=nan | rare=nan
[epoch 000000106] loss=nan | avg=nan | rare=nan
[epoch 000000107] loss=nan | avg=nan | rare=nan
[epoch 000000108] loss=nan | avg=nan | rare=nan
[epoch 000000109] loss=nan | avg=nan | rare=nan
[epoch 000000110] loss=nan | avg=nan | rare=nan
[epoch 000000111] loss=nan | avg=nan | rare=nan
[epoch 000000112] loss=nan | avg=nan | rare=nan
[epoch 000000113] loss=nan | avg=nan | rare=nan
[epoch 000000114] loss=nan | avg=nan | rare=nan
[epoch 000000115] loss=nan | avg=nan | rare=nan
[epoch 000000116] loss=nan | avg=nan | rare=nan
[epoch 000000117] loss=nan | avg=nan | rare=nan
[epoch 000000118] loss=nan | avg=nan | rare=nan
[epoch 000000119] loss=nan | avg=nan | rare=nan
[epoch 000000120] loss=nan | avg=nan | rare=nan
[epoch 000000121] loss=nan | avg=nan | rare=nan
[epoch 000000122] loss=nan | avg=nan | rare=nan
[epoch 000000123] loss=nan | avg=nan | rare=nan
[epoch 000000124] loss=nan | avg=nan | rare=nan
[epoch 000000125] loss=nan | avg=nan | rare=nan
[epoch 000000126] loss=nan | avg=nan | rare=nan
[epoch 000000127] loss=nan | avg=nan | rare=nan
[epoch 000000128] loss=nan | avg=nan | rare=nan
[epoch 000000129] loss=nan | avg=nan | rare=nan
[epoch 000000130] loss=nan | avg=nan | rare=nan
[epoch 000000131] loss=nan | avg=nan | rare=nan
[epoch 000000132] loss=nan | avg=nan | rare=nan
[epoch 000000133] loss=nan | avg=nan | rare=nan
[epoch 000000134] loss=nan | avg=nan | rare=nan
[epoch 000000135] loss=nan | avg=nan | rare=nan
[epoch 000000136] loss=nan | avg=nan | rare=nan
[epoch 000000137] loss=nan | avg=nan | rare=nan
[epoch 000000138] loss=nan | avg=nan | rare=nan
[epoch 000000139] loss=nan | avg=nan | rare=nan
[epoch 000000140] loss=nan | avg=nan | rare=nan
[epoch 000000141] loss=nan | avg=nan | rare=nan
[epoch 000000142] loss=nan | avg=nan | rare=nan
[epoch 000000143] loss=nan | avg=nan | rare=nan
[epoch 000000144] loss=nan | avg=nan | rare=nan
[epoch 000000145] loss=nan | avg=nan | rare=nan
[epoch 000000146] loss=nan | avg=nan | rare=nan
[epoch 000000147] loss=nan | avg=nan | rare=nan
[epoch 000000148] loss=nan | avg=nan | rare=nan
[epoch 000000149] loss=nan | avg=nan | rare=nan
[epoch 000000150] loss=nan | avg=nan | rare=nan
[epoch 000000151] loss=nan | avg=nan | rare=nan
[epoch 000000152] loss=nan | avg=nan | rare=nan
[epoch 000000153] loss=nan | avg=nan | rare=nan
[epoch 000000154] loss=nan | avg=nan | rare=nan
[epoch 000000155] loss=nan | avg=nan | rare=nan
[epoch 000000156] loss=nan | avg=nan | rare=nan
[epoch 000000157] loss=nan | avg=nan | rare=nan
[epoch 000000158] loss=nan | avg=nan | rare=nan
[epoch 000000159] loss=nan | avg=nan | rare=nan
[epoch 000000160] loss=nan | avg=nan | rare=nan
[epoch 000000161] loss=nan | avg=nan | rare=nan
[epoch 000000162] loss=nan | avg=nan | rare=nan
[epoch 000000163] loss=nan | avg=nan | rare=nan
[epoch 000000164] loss=nan | avg=nan | rare=nan
[epoch 000000165] loss=nan | avg=nan | rare=nan
[epoch 000000166] loss=nan | avg=nan | rare=nan
[epoch 000000167] loss=nan | avg=nan | rare=nan
[epoch 000000168] loss=nan | avg=nan | rare=nan
[epoch 000000169] loss=nan | avg=nan | rare=nan
[epoch 000000170] loss=nan | avg=nan | rare=nan
[epoch 000000171] loss=nan | avg=nan | rare=nan
[epoch 000000172] loss=nan | avg=nan | rare=nan
[epoch 000000173] loss=nan | avg=nan | rare=nan
[epoch 000000174] loss=nan | avg=nan | rare=nan
[epoch 000000175] loss=nan | avg=nan | rare=nan
[epoch 000000176] loss=nan | avg=nan | rare=nan
[epoch 000000177] loss=nan | avg=nan | rare=nan
[epoch 000000178] loss=nan | avg=nan | rare=nan
[epoch 000000179] loss=nan | avg=nan | rare=nan
[epoch 000000180] loss=nan | avg=nan | rare=nan
[epoch 000000181] loss=nan | avg=nan | rare=nan
[epoch 000000182] loss=nan | avg=nan | rare=nan
[epoch 000000183] loss=nan | avg=nan | rare=nan
[epoch 000000184] loss=nan | avg=nan | rare=nan
[epoch 000000185] loss=nan | avg=nan | rare=nan
[epoch 000000186] loss=nan | avg=nan | rare=nan
[epoch 000000187] loss=nan | avg=nan | rare=nan
[epoch 000000188] loss=nan | avg=nan | rare=nan
[epoch 000000189] loss=nan | avg=nan | rare=nan
[epoch 000000190] loss=nan | avg=nan | rare=nan
[epoch 000000191] loss=nan | avg=nan | rare=nan
[epoch 000000192] loss=nan | avg=nan | rare=nan
[epoch 000000193] loss=nan | avg=nan | rare=nan
[epoch 000000194] loss=nan | avg=nan | rare=nan
[epoch 000000195] loss=nan | avg=nan | rare=nan
[epoch 000000196] loss=nan | avg=nan | rare=nan
[epoch 000000197] loss=nan | avg=nan | rare=nan
[epoch 000000198] loss=nan | avg=nan | rare=nan
[epoch 000000199] loss=nan | avg=nan | rare=nan
[epoch 000000200] loss=nan | avg=nan | rare=nan
Accuracy: 63.96%  (CI 95%: [62.63%, 65.28%])
Robust Accuracy: 63.96415%  (CI 95%: [62.84861%, 65.40986%])
Conditional Robust Accuracy: 100.00000%  (CI 95%: [100.00000%, 100.00000%])
Accuracy: 36.04%  (CI 95%: [34.72%, 37.37%])
Robust Accuracy: 36.03586%  (CI 95%: [34.59014%, 37.15139%])
Conditional Robust Accuracy: 100.00000%  (CI 95%: [100.00000%, 100.00000%])
  --> Running Seed: 2026

Training naive with sgd...

Epochs:   0%|          | 0/200 [00:00<?, ?it/s]

[epoch 000000001] loss=178684.989955357 | avg=0.319395542 | rare=1.786846706
[epoch 000000002] loss=178375.775669643 | avg=0.319636160 | rare=1.783754570
[epoch 000000003] loss=nan | avg=nan | rare=nan
[epoch 000000004] loss=nan | avg=nan | rare=nan
[epoch 000000005] loss=nan | avg=nan | rare=nan
[epoch 000000006] loss=nan | avg=nan | rare=nan
[epoch 000000007] loss=nan | avg=nan | rare=nan
[epoch 000000008] loss=nan | avg=nan | rare=nan
[epoch 000000009] loss=nan | avg=nan | rare=nan
[epoch 000000010] loss=nan | avg=nan | rare=nan
[epoch 000000011] loss=nan | avg=nan | rare=nan
[epoch 000000012] loss=nan | avg=nan | rare=nan
[epoch 000000013] loss=nan | avg=nan | rare=nan
[epoch 000000014] loss=nan | avg=nan | rare=nan
[epoch 000000015] loss=nan | avg=nan | rare=nan
[epoch 000000016] loss=nan | avg=nan | rare=nan
[epoch 000000017] loss=nan | avg=nan | rare=nan
[epoch 000000018] loss=nan | avg=nan | rare=nan
[epoch 000000019] loss=nan | avg=nan | rare=nan
[epoch 000000020] loss=nan | avg=nan | rare=nan
[epoch 000000021] loss=nan | avg=nan | rare=nan
[epoch 000000022] loss=nan | avg=nan | rare=nan
[epoch 000000023] loss=nan | avg=nan | rare=nan
[epoch 000000024] loss=nan | avg=nan | rare=nan
[epoch 000000025] loss=nan | avg=nan | rare=nan
[epoch 000000026] loss=nan | avg=nan | rare=nan
[epoch 000000027] loss=nan | avg=nan | rare=nan
[epoch 000000028] loss=nan | avg=nan | rare=nan
[epoch 000000029] loss=nan | avg=nan | rare=nan
[epoch 000000030] loss=nan | avg=nan | rare=nan
[epoch 000000031] loss=nan | avg=nan | rare=nan
[epoch 000000032] loss=nan | avg=nan | rare=nan
[epoch 000000033] loss=nan | avg=nan | rare=nan
[epoch 000000034] loss=nan | avg=nan | rare=nan
[epoch 000000035] loss=nan | avg=nan | rare=nan
[epoch 000000036] loss=nan | avg=nan | rare=nan
[epoch 000000037] loss=nan | avg=nan | rare=nan
[epoch 000000038] loss=nan | avg=nan | rare=nan
[epoch 000000039] loss=nan | avg=nan | rare=nan
[epoch 000000040] loss=nan | avg=nan | rare=nan
[epoch 000000041] loss=nan | avg=nan | rare=nan
[epoch 000000042] loss=nan | avg=nan | rare=nan
[epoch 000000043] loss=nan | avg=nan | rare=nan
[epoch 000000044] loss=nan | avg=nan | rare=nan
[epoch 000000045] loss=nan | avg=nan | rare=nan
[epoch 000000046] loss=nan | avg=nan | rare=nan
[epoch 000000047] loss=nan | avg=nan | rare=nan
[epoch 000000048] loss=nan | avg=nan | rare=nan
[epoch 000000049] loss=nan | avg=nan | rare=nan
[epoch 000000050] loss=nan | avg=nan | rare=nan
[epoch 000000051] loss=nan | avg=nan | rare=nan
[epoch 000000052] loss=nan | avg=nan | rare=nan
[epoch 000000053] loss=nan | avg=nan | rare=nan
[epoch 000000054] loss=nan | avg=nan | rare=nan
[epoch 000000055] loss=nan | avg=nan | rare=nan
[epoch 000000056] loss=nan | avg=nan | rare=nan
[epoch 000000057] loss=nan | avg=nan | rare=nan
[epoch 000000058] loss=nan | avg=nan | rare=nan
[epoch 000000059] loss=nan | avg=nan | rare=nan
[epoch 000000060] loss=nan | avg=nan | rare=nan
[epoch 000000061] loss=nan | avg=nan | rare=nan
[epoch 000000062] loss=nan | avg=nan | rare=nan
[epoch 000000063] loss=nan | avg=nan | rare=nan
[epoch 000000064] loss=nan | avg=nan | rare=nan
[epoch 000000065] loss=nan | avg=nan | rare=nan
[epoch 000000066] loss=nan | avg=nan | rare=nan
[epoch 000000067] loss=nan | avg=nan | rare=nan
[epoch 000000068] loss=nan | avg=nan | rare=nan
[epoch 000000069] loss=nan | avg=nan | rare=nan
[epoch 000000070] loss=nan | avg=nan | rare=nan
[epoch 000000071] loss=nan | avg=nan | rare=nan
[epoch 000000072] loss=nan | avg=nan | rare=nan
[epoch 000000073] loss=nan | avg=nan | rare=nan
[epoch 000000074] loss=nan | avg=nan | rare=nan
[epoch 000000075] loss=nan | avg=nan | rare=nan
[epoch 000000076] loss=nan | avg=nan | rare=nan
[epoch 000000077] loss=nan | avg=nan | rare=nan
[epoch 000000078] loss=nan | avg=nan | rare=nan
[epoch 000000079] loss=nan | avg=nan | rare=nan
[epoch 000000080] loss=nan | avg=nan | rare=nan
[epoch 000000081] loss=nan | avg=nan | rare=nan
[epoch 000000082] loss=nan | avg=nan | rare=nan
[epoch 000000083] loss=nan | avg=nan | rare=nan
[epoch 000000084] loss=nan | avg=nan | rare=nan
[epoch 000000085] loss=nan | avg=nan | rare=nan
[epoch 000000086] loss=nan | avg=nan | rare=nan
[epoch 000000087] loss=nan | avg=nan | rare=nan
[epoch 000000088] loss=nan | avg=nan | rare=nan
[epoch 000000089] loss=nan | avg=nan | rare=nan
[epoch 000000090] loss=nan | avg=nan | rare=nan
[epoch 000000091] loss=nan | avg=nan | rare=nan
[epoch 000000092] loss=nan | avg=nan | rare=nan
[epoch 000000093] loss=nan | avg=nan | rare=nan
[epoch 000000094] loss=nan | avg=nan | rare=nan
[epoch 000000095] loss=nan | avg=nan | rare=nan
[epoch 000000096] loss=nan | avg=nan | rare=nan
[epoch 000000097] loss=nan | avg=nan | rare=nan
[epoch 000000098] loss=nan | avg=nan | rare=nan
[epoch 000000099] loss=nan | avg=nan | rare=nan
[epoch 000000100] loss=nan | avg=nan | rare=nan
[epoch 000000101] loss=nan | avg=nan | rare=nan
[epoch 000000102] loss=nan | avg=nan | rare=nan
[epoch 000000103] loss=nan | avg=nan | rare=nan
[epoch 000000104] loss=nan | avg=nan | rare=nan
[epoch 000000105] loss=nan | avg=nan | rare=nan
[epoch 000000106] loss=nan | avg=nan | rare=nan
[epoch 000000107] loss=nan | avg=nan | rare=nan
[epoch 000000108] loss=nan | avg=nan | rare=nan
[epoch 000000109] loss=nan | avg=nan | rare=nan
[epoch 000000110] loss=nan | avg=nan | rare=nan
[epoch 000000111] loss=nan | avg=nan | rare=nan
[epoch 000000112] loss=nan | avg=nan | rare=nan
[epoch 000000113] loss=nan | avg=nan | rare=nan
[epoch 000000114] loss=nan | avg=nan | rare=nan
[epoch 000000115] loss=nan | avg=nan | rare=nan
[epoch 000000116] loss=nan | avg=nan | rare=nan
[epoch 000000117] loss=nan | avg=nan | rare=nan
[epoch 000000118] loss=nan | avg=nan | rare=nan
[epoch 000000119] loss=nan | avg=nan | rare=nan
[epoch 000000120] loss=nan | avg=nan | rare=nan
[epoch 000000121] loss=nan | avg=nan | rare=nan
[epoch 000000122] loss=nan | avg=nan | rare=nan
[epoch 000000123] loss=nan | avg=nan | rare=nan
[epoch 000000124] loss=nan | avg=nan | rare=nan
[epoch 000000125] loss=nan | avg=nan | rare=nan
[epoch 000000126] loss=nan | avg=nan | rare=nan
[epoch 000000127] loss=nan | avg=nan | rare=nan
[epoch 000000128] loss=nan | avg=nan | rare=nan
[epoch 000000129] loss=nan | avg=nan | rare=nan
[epoch 000000130] loss=nan | avg=nan | rare=nan
[epoch 000000131] loss=nan | avg=nan | rare=nan
[epoch 000000132] loss=nan | avg=nan | rare=nan
[epoch 000000133] loss=nan | avg=nan | rare=nan
[epoch 000000134] loss=nan | avg=nan | rare=nan
[epoch 000000135] loss=nan | avg=nan | rare=nan
[epoch 000000136] loss=nan | avg=nan | rare=nan
[epoch 000000137] loss=nan | avg=nan | rare=nan
[epoch 000000138] loss=nan | avg=nan | rare=nan
[epoch 000000139] loss=nan | avg=nan | rare=nan
[epoch 000000140] loss=nan | avg=nan | rare=nan
[epoch 000000141] loss=nan | avg=nan | rare=nan
[epoch 000000142] loss=nan | avg=nan | rare=nan
[epoch 000000143] loss=nan | avg=nan | rare=nan
[epoch 000000144] loss=nan | avg=nan | rare=nan
[epoch 000000145] loss=nan | avg=nan | rare=nan
[epoch 000000146] loss=nan | avg=nan | rare=nan
[epoch 000000147] loss=nan | avg=nan | rare=nan
[epoch 000000148] loss=nan | avg=nan | rare=nan
[epoch 000000149] loss=nan | avg=nan | rare=nan
[epoch 000000150] loss=nan | avg=nan | rare=nan
[epoch 000000151] loss=nan | avg=nan | rare=nan
[epoch 000000152] loss=nan | avg=nan | rare=nan
[epoch 000000153] loss=nan | avg=nan | rare=nan
[epoch 000000154] loss=nan | avg=nan | rare=nan
[epoch 000000155] loss=nan | avg=nan | rare=nan
[epoch 000000156] loss=nan | avg=nan | rare=nan
[epoch 000000157] loss=nan | avg=nan | rare=nan
[epoch 000000158] loss=nan | avg=nan | rare=nan
[epoch 000000159] loss=nan | avg=nan | rare=nan
[epoch 000000160] loss=nan | avg=nan | rare=nan
[epoch 000000161] loss=nan | avg=nan | rare=nan
[epoch 000000162] loss=nan | avg=nan | rare=nan
[epoch 000000163] loss=nan | avg=nan | rare=nan
[epoch 000000164] loss=nan | avg=nan | rare=nan
[epoch 000000165] loss=nan | avg=nan | rare=nan
[epoch 000000166] loss=nan | avg=nan | rare=nan
[epoch 000000167] loss=nan | avg=nan | rare=nan
[epoch 000000168] loss=nan | avg=nan | rare=nan
[epoch 000000169] loss=nan | avg=nan | rare=nan
[epoch 000000170] loss=nan | avg=nan | rare=nan
[epoch 000000171] loss=nan | avg=nan | rare=nan
[epoch 000000172] loss=nan | avg=nan | rare=nan
[epoch 000000173] loss=nan | avg=nan | rare=nan
[epoch 000000174] loss=nan | avg=nan | rare=nan
[epoch 000000175] loss=nan | avg=nan | rare=nan
[epoch 000000176] loss=nan | avg=nan | rare=nan
[epoch 000000177] loss=nan | avg=nan | rare=nan
[epoch 000000178] loss=nan | avg=nan | rare=nan
[epoch 000000179] loss=nan | avg=nan | rare=nan
[epoch 000000180] loss=nan | avg=nan | rare=nan
[epoch 000000181] loss=nan | avg=nan | rare=nan
[epoch 000000182] loss=nan | avg=nan | rare=nan
[epoch 000000183] loss=nan | avg=nan | rare=nan
[epoch 000000184] loss=nan | avg=nan | rare=nan
[epoch 000000185] loss=nan | avg=nan | rare=nan
[epoch 000000186] loss=nan | avg=nan | rare=nan
[epoch 000000187] loss=nan | avg=nan | rare=nan
[epoch 000000188] loss=nan | avg=nan | rare=nan
[epoch 000000189] loss=nan | avg=nan | rare=nan
[epoch 000000190] loss=nan | avg=nan | rare=nan
[epoch 000000191] loss=nan | avg=nan | rare=nan
[epoch 000000192] loss=nan | avg=nan | rare=nan
[epoch 000000193] loss=nan | avg=nan | rare=nan
[epoch 000000194] loss=nan | avg=nan | rare=nan
[epoch 000000195] loss=nan | avg=nan | rare=nan
[epoch 000000196] loss=nan | avg=nan | rare=nan
[epoch 000000197] loss=nan | avg=nan | rare=nan
[epoch 000000198] loss=nan | avg=nan | rare=nan
[epoch 000000199] loss=nan | avg=nan | rare=nan
[epoch 000000200] loss=nan | avg=nan | rare=nan

Training safe with sgd...

Epochs:   0%|          | 0/200 [00:00<?, ?it/s]

[epoch 000000001] loss=104.809024811 | avg=67.430143629 | rare=0.000373789
[epoch 000000002] loss=149.155136108 | avg=64.682156972 | rare=0.000844730
[epoch 000000003] loss=15761.248531614 | avg=318.209589005 | rare=0.154430388
[epoch 000000004] loss=nan | avg=nan | rare=nan
[epoch 000000005] loss=nan | avg=nan | rare=nan
[epoch 000000006] loss=nan | avg=nan | rare=nan
[epoch 000000007] loss=nan | avg=nan | rare=nan
[epoch 000000008] loss=nan | avg=nan | rare=nan
[epoch 000000009] loss=nan | avg=nan | rare=nan
[epoch 000000010] loss=nan | avg=nan | rare=nan
[epoch 000000011] loss=nan | avg=nan | rare=nan
[epoch 000000012] loss=nan | avg=nan | rare=nan
[epoch 000000013] loss=nan | avg=nan | rare=nan
[epoch 000000014] loss=nan | avg=nan | rare=nan
[epoch 000000015] loss=nan | avg=nan | rare=nan
[epoch 000000016] loss=nan | avg=nan | rare=nan
[epoch 000000017] loss=nan | avg=nan | rare=nan
[epoch 000000018] loss=nan | avg=nan | rare=nan
[epoch 000000019] loss=nan | avg=nan | rare=nan
[epoch 000000020] loss=nan | avg=nan | rare=nan
[epoch 000000021] loss=nan | avg=nan | rare=nan
[epoch 000000022] loss=nan | avg=nan | rare=nan
[epoch 000000023] loss=nan | avg=nan | rare=nan
[epoch 000000024] loss=nan | avg=nan | rare=nan
[epoch 000000025] loss=nan | avg=nan | rare=nan
[epoch 000000026] loss=nan | avg=nan | rare=nan
[epoch 000000027] loss=nan | avg=nan | rare=nan
[epoch 000000028] loss=nan | avg=nan | rare=nan
[epoch 000000029] loss=nan | avg=nan | rare=nan
[epoch 000000030] loss=nan | avg=nan | rare=nan
[epoch 000000031] loss=nan | avg=nan | rare=nan
[epoch 000000032] loss=nan | avg=nan | rare=nan
[epoch 000000033] loss=nan | avg=nan | rare=nan
[epoch 000000034] loss=nan | avg=nan | rare=nan
[epoch 000000035] loss=nan | avg=nan | rare=nan
[epoch 000000036] loss=nan | avg=nan | rare=nan
[epoch 000000037] loss=nan | avg=nan | rare=nan
[epoch 000000038] loss=nan | avg=nan | rare=nan
[epoch 000000039] loss=nan | avg=nan | rare=nan
[epoch 000000040] loss=nan | avg=nan | rare=nan
[epoch 000000041] loss=nan | avg=nan | rare=nan
[epoch 000000042] loss=nan | avg=nan | rare=nan
[epoch 000000043] loss=nan | avg=nan | rare=nan
[epoch 000000044] loss=nan | avg=nan | rare=nan
[epoch 000000045] loss=nan | avg=nan | rare=nan
[epoch 000000046] loss=nan | avg=nan | rare=nan
[epoch 000000047] loss=nan | avg=nan | rare=nan
[epoch 000000048] loss=nan | avg=nan | rare=nan
[epoch 000000049] loss=nan | avg=nan | rare=nan
[epoch 000000050] loss=nan | avg=nan | rare=nan
[epoch 000000051] loss=nan | avg=nan | rare=nan
[epoch 000000052] loss=nan | avg=nan | rare=nan
[epoch 000000053] loss=nan | avg=nan | rare=nan
[epoch 000000054] loss=nan | avg=nan | rare=nan
[epoch 000000055] loss=nan | avg=nan | rare=nan
[epoch 000000056] loss=nan | avg=nan | rare=nan
[epoch 000000057] loss=nan | avg=nan | rare=nan
[epoch 000000058] loss=nan | avg=nan | rare=nan
[epoch 000000059] loss=nan | avg=nan | rare=nan
[epoch 000000060] loss=nan | avg=nan | rare=nan
[epoch 000000061] loss=nan | avg=nan | rare=nan
[epoch 000000062] loss=nan | avg=nan | rare=nan
[epoch 000000063] loss=nan | avg=nan | rare=nan
[epoch 000000064] loss=nan | avg=nan | rare=nan
[epoch 000000065] loss=nan | avg=nan | rare=nan
[epoch 000000066] loss=nan | avg=nan | rare=nan
[epoch 000000067] loss=nan | avg=nan | rare=nan
[epoch 000000068] loss=nan | avg=nan | rare=nan
[epoch 000000069] loss=nan | avg=nan | rare=nan
[epoch 000000070] loss=nan | avg=nan | rare=nan
[epoch 000000071] loss=nan | avg=nan | rare=nan
[epoch 000000072] loss=nan | avg=nan | rare=nan
[epoch 000000073] loss=nan | avg=nan | rare=nan
[epoch 000000074] loss=nan | avg=nan | rare=nan
[epoch 000000075] loss=nan | avg=nan | rare=nan
[epoch 000000076] loss=nan | avg=nan | rare=nan
[epoch 000000077] loss=nan | avg=nan | rare=nan
[epoch 000000078] loss=nan | avg=nan | rare=nan
[epoch 000000079] loss=nan | avg=nan | rare=nan
[epoch 000000080] loss=nan | avg=nan | rare=nan
[epoch 000000081] loss=nan | avg=nan | rare=nan
[epoch 000000082] loss=nan | avg=nan | rare=nan
[epoch 000000083] loss=nan | avg=nan | rare=nan
[epoch 000000084] loss=nan | avg=nan | rare=nan
[epoch 000000085] loss=nan | avg=nan | rare=nan
[epoch 000000086] loss=nan | avg=nan | rare=nan
[epoch 000000087] loss=nan | avg=nan | rare=nan
[epoch 000000088] loss=nan | avg=nan | rare=nan
[epoch 000000089] loss=nan | avg=nan | rare=nan
[epoch 000000090] loss=nan | avg=nan | rare=nan
[epoch 000000091] loss=nan | avg=nan | rare=nan
[epoch 000000092] loss=nan | avg=nan | rare=nan
[epoch 000000093] loss=nan | avg=nan | rare=nan
[epoch 000000094] loss=nan | avg=nan | rare=nan
[epoch 000000095] loss=nan | avg=nan | rare=nan
[epoch 000000096] loss=nan | avg=nan | rare=nan
[epoch 000000097] loss=nan | avg=nan | rare=nan
[epoch 000000098] loss=nan | avg=nan | rare=nan
[epoch 000000099] loss=nan | avg=nan | rare=nan
[epoch 000000100] loss=nan | avg=nan | rare=nan
[epoch 000000101] loss=nan | avg=nan | rare=nan
[epoch 000000102] loss=nan | avg=nan | rare=nan
[epoch 000000103] loss=nan | avg=nan | rare=nan
[epoch 000000104] loss=nan | avg=nan | rare=nan
[epoch 000000105] loss=nan | avg=nan | rare=nan
[epoch 000000106] loss=nan | avg=nan | rare=nan
[epoch 000000107] loss=nan | avg=nan | rare=nan
[epoch 000000108] loss=nan | avg=nan | rare=nan
[epoch 000000109] loss=nan | avg=nan | rare=nan
[epoch 000000110] loss=nan | avg=nan | rare=nan
[epoch 000000111] loss=nan | avg=nan | rare=nan
[epoch 000000112] loss=nan | avg=nan | rare=nan
[epoch 000000113] loss=nan | avg=nan | rare=nan
[epoch 000000114] loss=nan | avg=nan | rare=nan
[epoch 000000115] loss=nan | avg=nan | rare=nan
[epoch 000000116] loss=nan | avg=nan | rare=nan
[epoch 000000117] loss=nan | avg=nan | rare=nan
[epoch 000000118] loss=nan | avg=nan | rare=nan
[epoch 000000119] loss=nan | avg=nan | rare=nan
[epoch 000000120] loss=nan | avg=nan | rare=nan
[epoch 000000121] loss=nan | avg=nan | rare=nan
[epoch 000000122] loss=nan | avg=nan | rare=nan
[epoch 000000123] loss=nan | avg=nan | rare=nan
[epoch 000000124] loss=nan | avg=nan | rare=nan
[epoch 000000125] loss=nan | avg=nan | rare=nan
[epoch 000000126] loss=nan | avg=nan | rare=nan
[epoch 000000127] loss=nan | avg=nan | rare=nan
[epoch 000000128] loss=nan | avg=nan | rare=nan
[epoch 000000129] loss=nan | avg=nan | rare=nan
[epoch 000000130] loss=nan | avg=nan | rare=nan
[epoch 000000131] loss=nan | avg=nan | rare=nan
[epoch 000000132] loss=nan | avg=nan | rare=nan
[epoch 000000133] loss=nan | avg=nan | rare=nan
[epoch 000000134] loss=nan | avg=nan | rare=nan
[epoch 000000135] loss=nan | avg=nan | rare=nan
[epoch 000000136] loss=nan | avg=nan | rare=nan
[epoch 000000137] loss=nan | avg=nan | rare=nan
[epoch 000000138] loss=nan | avg=nan | rare=nan
[epoch 000000139] loss=nan | avg=nan | rare=nan
[epoch 000000140] loss=nan | avg=nan | rare=nan
[epoch 000000141] loss=nan | avg=nan | rare=nan
[epoch 000000142] loss=nan | avg=nan | rare=nan
[epoch 000000143] loss=nan | avg=nan | rare=nan
[epoch 000000144] loss=nan | avg=nan | rare=nan
[epoch 000000145] loss=nan | avg=nan | rare=nan
[epoch 000000146] loss=nan | avg=nan | rare=nan
[epoch 000000147] loss=nan | avg=nan | rare=nan
[epoch 000000148] loss=nan | avg=nan | rare=nan
[epoch 000000149] loss=nan | avg=nan | rare=nan
[epoch 000000150] loss=nan | avg=nan | rare=nan
[epoch 000000151] loss=nan | avg=nan | rare=nan
[epoch 000000152] loss=nan | avg=nan | rare=nan
[epoch 000000153] loss=nan | avg=nan | rare=nan
[epoch 000000154] loss=nan | avg=nan | rare=nan
[epoch 000000155] loss=nan | avg=nan | rare=nan
[epoch 000000156] loss=nan | avg=nan | rare=nan
[epoch 000000157] loss=nan | avg=nan | rare=nan
[epoch 000000158] loss=nan | avg=nan | rare=nan
[epoch 000000159] loss=nan | avg=nan | rare=nan
[epoch 000000160] loss=nan | avg=nan | rare=nan
[epoch 000000161] loss=nan | avg=nan | rare=nan
[epoch 000000162] loss=nan | avg=nan | rare=nan
[epoch 000000163] loss=nan | avg=nan | rare=nan
[epoch 000000164] loss=nan | avg=nan | rare=nan
[epoch 000000165] loss=nan | avg=nan | rare=nan
[epoch 000000166] loss=nan | avg=nan | rare=nan
[epoch 000000167] loss=nan | avg=nan | rare=nan
[epoch 000000168] loss=nan | avg=nan | rare=nan
[epoch 000000169] loss=nan | avg=nan | rare=nan
[epoch 000000170] loss=nan | avg=nan | rare=nan
[epoch 000000171] loss=nan | avg=nan | rare=nan
[epoch 000000172] loss=nan | avg=nan | rare=nan
[epoch 000000173] loss=nan | avg=nan | rare=nan
[epoch 000000174] loss=nan | avg=nan | rare=nan
[epoch 000000175] loss=nan | avg=nan | rare=nan
[epoch 000000176] loss=nan | avg=nan | rare=nan
[epoch 000000177] loss=nan | avg=nan | rare=nan
[epoch 000000178] loss=nan | avg=nan | rare=nan
[epoch 000000179] loss=nan | avg=nan | rare=nan
[epoch 000000180] loss=nan | avg=nan | rare=nan
[epoch 000000181] loss=nan | avg=nan | rare=nan
[epoch 000000182] loss=nan | avg=nan | rare=nan
[epoch 000000183] loss=nan | avg=nan | rare=nan
[epoch 000000184] loss=nan | avg=nan | rare=nan
[epoch 000000185] loss=nan | avg=nan | rare=nan
[epoch 000000186] loss=nan | avg=nan | rare=nan
[epoch 000000187] loss=nan | avg=nan | rare=nan
[epoch 000000188] loss=nan | avg=nan | rare=nan
[epoch 000000189] loss=nan | avg=nan | rare=nan
[epoch 000000190] loss=nan | avg=nan | rare=nan
[epoch 000000191] loss=nan | avg=nan | rare=nan
[epoch 000000192] loss=nan | avg=nan | rare=nan
[epoch 000000193] loss=nan | avg=nan | rare=nan
[epoch 000000194] loss=nan | avg=nan | rare=nan
[epoch 000000195] loss=nan | avg=nan | rare=nan
[epoch 000000196] loss=nan | avg=nan | rare=nan
[epoch 000000197] loss=nan | avg=nan | rare=nan
[epoch 000000198] loss=nan | avg=nan | rare=nan
[epoch 000000199] loss=nan | avg=nan | rare=nan
[epoch 000000200] loss=nan | avg=nan | rare=nan
Accuracy: 63.96%  (CI 95%: [62.63%, 65.28%])
Robust Accuracy: 63.96415%  (CI 95%: [62.84861%, 65.40986%])
Conditional Robust Accuracy: 100.00000%  (CI 95%: [100.00000%, 100.00000%])
Accuracy: 63.96%  (CI 95%: [62.63%, 65.28%])
Robust Accuracy: 63.96415%  (CI 95%: [62.84861%, 65.40986%])
Conditional Robust Accuracy: 100.00000%  (CI 95%: [100.00000%, 100.00000%])
  --> Running Seed: 333

Training naive with sgd...

Epochs:   0%|          | 0/200 [00:00<?, ?it/s]

[epoch 000000001] loss=178734.889508929 | avg=0.320698721 | rare=1.787345699
[epoch 000000002] loss=178522.055803571 | avg=0.320004421 | rare=1.785217379
[epoch 000000003] loss=nan | avg=nan | rare=nan
[epoch 000000004] loss=nan | avg=nan | rare=nan
[epoch 000000005] loss=nan | avg=nan | rare=nan
[epoch 000000006] loss=nan | avg=nan | rare=nan
[epoch 000000007] loss=nan | avg=nan | rare=nan
[epoch 000000008] loss=nan | avg=nan | rare=nan
[epoch 000000009] loss=nan | avg=nan | rare=nan
[epoch 000000010] loss=nan | avg=nan | rare=nan
[epoch 000000011] loss=nan | avg=nan | rare=nan
[epoch 000000012] loss=nan | avg=nan | rare=nan
[epoch 000000013] loss=nan | avg=nan | rare=nan
[epoch 000000014] loss=nan | avg=nan | rare=nan
[epoch 000000015] loss=nan | avg=nan | rare=nan
[epoch 000000016] loss=nan | avg=nan | rare=nan
[epoch 000000017] loss=nan | avg=nan | rare=nan
[epoch 000000018] loss=nan | avg=nan | rare=nan
[epoch 000000019] loss=nan | avg=nan | rare=nan
[epoch 000000020] loss=nan | avg=nan | rare=nan
[epoch 000000021] loss=nan | avg=nan | rare=nan
[epoch 000000022] loss=nan | avg=nan | rare=nan
[epoch 000000023] loss=nan | avg=nan | rare=nan
[epoch 000000024] loss=nan | avg=nan | rare=nan
[epoch 000000025] loss=nan | avg=nan | rare=nan
[epoch 000000026] loss=nan | avg=nan | rare=nan
[epoch 000000027] loss=nan | avg=nan | rare=nan
[epoch 000000028] loss=nan | avg=nan | rare=nan
[epoch 000000029] loss=nan | avg=nan | rare=nan
[epoch 000000030] loss=nan | avg=nan | rare=nan
[epoch 000000031] loss=nan | avg=nan | rare=nan
[epoch 000000032] loss=nan | avg=nan | rare=nan
[epoch 000000033] loss=nan | avg=nan | rare=nan
[epoch 000000034] loss=nan | avg=nan | rare=nan
[epoch 000000035] loss=nan | avg=nan | rare=nan
[epoch 000000036] loss=nan | avg=nan | rare=nan
[epoch 000000037] loss=nan | avg=nan | rare=nan
[epoch 000000038] loss=nan | avg=nan | rare=nan
[epoch 000000039] loss=nan | avg=nan | rare=nan
[epoch 000000040] loss=nan | avg=nan | rare=nan
[epoch 000000041] loss=nan | avg=nan | rare=nan
[epoch 000000042] loss=nan | avg=nan | rare=nan
[epoch 000000043] loss=nan | avg=nan | rare=nan
[epoch 000000044] loss=nan | avg=nan | rare=nan
[epoch 000000045] loss=nan | avg=nan | rare=nan
[epoch 000000046] loss=nan | avg=nan | rare=nan
[epoch 000000047] loss=nan | avg=nan | rare=nan
[epoch 000000048] loss=nan | avg=nan | rare=nan
[epoch 000000049] loss=nan | avg=nan | rare=nan
[epoch 000000050] loss=nan | avg=nan | rare=nan
[epoch 000000051] loss=nan | avg=nan | rare=nan
[epoch 000000052] loss=nan | avg=nan | rare=nan
[epoch 000000053] loss=nan | avg=nan | rare=nan
[epoch 000000054] loss=nan | avg=nan | rare=nan
[epoch 000000055] loss=nan | avg=nan | rare=nan
[epoch 000000056] loss=nan | avg=nan | rare=nan
[epoch 000000057] loss=nan | avg=nan | rare=nan
[epoch 000000058] loss=nan | avg=nan | rare=nan
[epoch 000000059] loss=nan | avg=nan | rare=nan
[epoch 000000060] loss=nan | avg=nan | rare=nan
[epoch 000000061] loss=nan | avg=nan | rare=nan
[epoch 000000062] loss=nan | avg=nan | rare=nan
[epoch 000000063] loss=nan | avg=nan | rare=nan
[epoch 000000064] loss=nan | avg=nan | rare=nan
[epoch 000000065] loss=nan | avg=nan | rare=nan
[epoch 000000066] loss=nan | avg=nan | rare=nan
[epoch 000000067] loss=nan | avg=nan | rare=nan
[epoch 000000068] loss=nan | avg=nan | rare=nan
[epoch 000000069] loss=nan | avg=nan | rare=nan
[epoch 000000070] loss=nan | avg=nan | rare=nan
[epoch 000000071] loss=nan | avg=nan | rare=nan
[epoch 000000072] loss=nan | avg=nan | rare=nan
[epoch 000000073] loss=nan | avg=nan | rare=nan
[epoch 000000074] loss=nan | avg=nan | rare=nan
[epoch 000000075] loss=nan | avg=nan | rare=nan
[epoch 000000076] loss=nan | avg=nan | rare=nan
[epoch 000000077] loss=nan | avg=nan | rare=nan
[epoch 000000078] loss=nan | avg=nan | rare=nan
[epoch 000000079] loss=nan | avg=nan | rare=nan
[epoch 000000080] loss=nan | avg=nan | rare=nan
[epoch 000000081] loss=nan | avg=nan | rare=nan
[epoch 000000082] loss=nan | avg=nan | rare=nan
[epoch 000000083] loss=nan | avg=nan | rare=nan
[epoch 000000084] loss=nan | avg=nan | rare=nan
[epoch 000000085] loss=nan | avg=nan | rare=nan
[epoch 000000086] loss=nan | avg=nan | rare=nan
[epoch 000000087] loss=nan | avg=nan | rare=nan
[epoch 000000088] loss=nan | avg=nan | rare=nan
[epoch 000000089] loss=nan | avg=nan | rare=nan
[epoch 000000090] loss=nan | avg=nan | rare=nan
[epoch 000000091] loss=nan | avg=nan | rare=nan
[epoch 000000092] loss=nan | avg=nan | rare=nan
[epoch 000000093] loss=nan | avg=nan | rare=nan
[epoch 000000094] loss=nan | avg=nan | rare=nan
[epoch 000000095] loss=nan | avg=nan | rare=nan
[epoch 000000096] loss=nan | avg=nan | rare=nan
[epoch 000000097] loss=nan | avg=nan | rare=nan
[epoch 000000098] loss=nan | avg=nan | rare=nan
[epoch 000000099] loss=nan | avg=nan | rare=nan
[epoch 000000100] loss=nan | avg=nan | rare=nan
[epoch 000000101] loss=nan | avg=nan | rare=nan
[epoch 000000102] loss=nan | avg=nan | rare=nan
[epoch 000000103] loss=nan | avg=nan | rare=nan
[epoch 000000104] loss=nan | avg=nan | rare=nan
[epoch 000000105] loss=nan | avg=nan | rare=nan
[epoch 000000106] loss=nan | avg=nan | rare=nan
[epoch 000000107] loss=nan | avg=nan | rare=nan
[epoch 000000108] loss=nan | avg=nan | rare=nan
[epoch 000000109] loss=nan | avg=nan | rare=nan
[epoch 000000110] loss=nan | avg=nan | rare=nan
[epoch 000000111] loss=nan | avg=nan | rare=nan
[epoch 000000112] loss=nan | avg=nan | rare=nan
[epoch 000000113] loss=nan | avg=nan | rare=nan
[epoch 000000114] loss=nan | avg=nan | rare=nan
[epoch 000000115] loss=nan | avg=nan | rare=nan
[epoch 000000116] loss=nan | avg=nan | rare=nan
[epoch 000000117] loss=nan | avg=nan | rare=nan
[epoch 000000118] loss=nan | avg=nan | rare=nan
[epoch 000000119] loss=nan | avg=nan | rare=nan
[epoch 000000120] loss=nan | avg=nan | rare=nan
[epoch 000000121] loss=nan | avg=nan | rare=nan

KeyboardInterrupt:

In [ ]:
import numpy as np

# Automatically extract and sort learning rates descending (0.1 down to 1e-6)
lrs = sorted(list(final_results_adam.keys()), reverse=True)
configs = [('naive', 'sgd'), ('safe', 'sgd')]

print("LaTeX Table Rows:\n")

for lr in lrs:
    # Format the learning rate beautifully for LaTeX (e.g., 0.1 -> 10^{-1})
    exponent = int(np.round(np.log10(lr)))
    row_string = f"$10^{{{exponent}}}$"

    for config in configs:
        # Extract the metrics for all 5 seeds and convert to percentages
        # Note: Using 'acc' instead of 'PA' based on your dictionary structure
        pa_scores = [res['acc'] * 100 for res in final_results_adam[lr][config]]
        cra_scores = [res['CRA'] * 100 for res in final_results_adam[lr][config]]

        # Calculate mean and standard deviation
        pa_mean, pa_std = np.mean(pa_scores), np.std(pa_scores)
        cra_mean, cra_std = np.mean(cra_scores), np.std(cra_scores)

        # Format the string: Mean (SD) / Mean (SD)
        cell_str = f"{pa_mean:.1f} ({pa_std:.1f}) / {cra_mean:.1f} ({cra_std:.1f})"

        # Apply LaTeX bolding if the configuration meets the success thresholds
        if pa_mean >= 80.0 and cra_mean >= 98.0:
            cell_str = f"\\textbf{{{cell_str}}}"

        # Append to the row string separated by the LaTeX column divider (&)
        row_string += f" & {cell_str}"

    # Cap off the row with the LaTeX line break (\\)
    row_string += " \\\\"

    print(row_string)

In [20]:
import numpy as np


# NUM_EPOCHS = 100
# Define your seeds
seeds = [42, 100]
lrs = [10.0, 1.,1e-1, 1e-2, 1e-3,1e-4, 1e-5,]

lrs = [ 1.,1e-1, 1e-2, 1e-3,1e-4]


configs = [("naive", "adam"), ("safe", "adam")]
final_results = {}
# SAMPLES_EVAL = 10000
# GAMMA = 10000.
# SAMPLES_TRAIN = 100000

for lr in lrs:
    print(f"\n{'#'*20} lr: {lr} {'#'*20}")

    # Initialize lists to hold the 5 seed results for each config
    configs_result = {config: [] for config in configs}

    for s in seeds:
        print(f"  --> Running Seed: {s}")

        # 1. Train models for the current seed
        # (Ensure your updated train_all accepts and utilizes the 'seed' parameter)
        results = train_all(
            X_train, y_train, pre_model,
            NUM_EPOCHS, GAMMA, SAMPLES_TRAIN, SIGMA,
            configs=configs, SAFE_BIAS=150.0, lr=lr, batch_size=BATCH_SIZE,
            seed=s
        )

        # 2. Evaluate models and append to the respective config list
        for config in configs:
            eval_metrics = eval_one(
                results[config][0], X_test, y_test,
                sigma=SIGMA, SAMPLES_EVAL=SAMPLES_EVAL,
                J_chunk=5000,    # Smart chunking to prevent Colab OOM errors
                N_chunk=512,
                B=300
            )
            configs_result[config].append(eval_metrics)

    # Store the aggregated seed data for this learning rate
    final_results[lr] = configs_result

print("\nGrid Search Complete!")

#################### lr: 1.0 ####################
  --> Running Seed: 42

Training naive with adam...

Epochs:   0%|          | 0/200 [00:00<?, ?it/s]

[epoch 000000001] loss=178608.407366071 | avg=0.319726129 | rare=1.786080871
[epoch 000000002] loss=178494.834821429 | avg=0.319935188 | rare=1.784945164
[epoch 000000003] loss=nan | avg=nan | rare=nan
[epoch 000000004] loss=nan | avg=nan | rare=nan
[epoch 000000005] loss=nan | avg=nan | rare=nan
[epoch 000000006] loss=nan | avg=nan | rare=nan
[epoch 000000007] loss=nan | avg=nan | rare=nan
[epoch 000000008] loss=nan | avg=nan | rare=nan
[epoch 000000009] loss=nan | avg=nan | rare=nan
[epoch 000000010] loss=nan | avg=nan | rare=nan
[epoch 000000011] loss=nan | avg=nan | rare=nan
[epoch 000000012] loss=nan | avg=nan | rare=nan
[epoch 000000013] loss=nan | avg=nan | rare=nan
[epoch 000000014] loss=nan | avg=nan | rare=nan
[epoch 000000015] loss=nan | avg=nan | rare=nan
[epoch 000000016] loss=nan | avg=nan | rare=nan
[epoch 000000017] loss=nan | avg=nan | rare=nan
[epoch 000000018] loss=nan | avg=nan | rare=nan
[epoch 000000019] loss=nan | avg=nan | rare=nan
[epoch 000000020] loss=nan | avg=nan | rare=nan
[epoch 000000021] loss=nan | avg=nan | rare=nan
[epoch 000000022] loss=nan | avg=nan | rare=nan
[epoch 000000023] loss=nan | avg=nan | rare=nan
[epoch 000000024] loss=nan | avg=nan | rare=nan
[epoch 000000025] loss=nan | avg=nan | rare=nan
[epoch 000000026] loss=nan | avg=nan | rare=nan
[epoch 000000027] loss=nan | avg=nan | rare=nan
[epoch 000000028] loss=nan | avg=nan | rare=nan
[epoch 000000029] loss=nan | avg=nan | rare=nan
[epoch 000000030] loss=nan | avg=nan | rare=nan
[epoch 000000031] loss=nan | avg=nan | rare=nan
[epoch 000000032] loss=nan | avg=nan | rare=nan
[epoch 000000033] loss=nan | avg=nan | rare=nan
[epoch 000000034] loss=nan | avg=nan | rare=nan
[epoch 000000035] loss=nan | avg=nan | rare=nan
[epoch 000000036] loss=nan | avg=nan | rare=nan
[epoch 000000037] loss=nan | avg=nan | rare=nan
[epoch 000000038] loss=nan | avg=nan | rare=nan
[epoch 000000039] loss=nan | avg=nan | rare=nan
[epoch 000000040] loss=nan | avg=nan | rare=nan
[epoch 000000041] loss=nan | avg=nan | rare=nan
[epoch 000000042] loss=nan | avg=nan | rare=nan
[epoch 000000043] loss=nan | avg=nan | rare=nan
[epoch 000000044] loss=nan | avg=nan | rare=nan
[epoch 000000045] loss=nan | avg=nan | rare=nan
[epoch 000000046] loss=nan | avg=nan | rare=nan
[epoch 000000047] loss=nan | avg=nan | rare=nan
[epoch 000000048] loss=nan | avg=nan | rare=nan
[epoch 000000049] loss=nan | avg=nan | rare=nan
[epoch 000000050] loss=nan | avg=nan | rare=nan
[epoch 000000051] loss=nan | avg=nan | rare=nan
[epoch 000000052] loss=nan | avg=nan | rare=nan
[epoch 000000053] loss=nan | avg=nan | rare=nan
[epoch 000000054] loss=nan | avg=nan | rare=nan
[epoch 000000055] loss=nan | avg=nan | rare=nan
[epoch 000000056] loss=nan | avg=nan | rare=nan
[epoch 000000057] loss=nan | avg=nan | rare=nan
[epoch 000000058] loss=nan | avg=nan | rare=nan
[epoch 000000059] loss=nan | avg=nan | rare=nan
[epoch 000000060] loss=nan | avg=nan | rare=nan
[epoch 000000061] loss=nan | avg=nan | rare=nan
[epoch 000000062] loss=nan | avg=nan | rare=nan
[epoch 000000063] loss=nan | avg=nan | rare=nan
[epoch 000000064] loss=nan | avg=nan | rare=nan
[epoch 000000065] loss=nan | avg=nan | rare=nan
[epoch 000000066] loss=nan | avg=nan | rare=nan
[epoch 000000067] loss=nan | avg=nan | rare=nan
[epoch 000000068] loss=nan | avg=nan | rare=nan
[epoch 000000069] loss=nan | avg=nan | rare=nan
[epoch 000000070] loss=nan | avg=nan | rare=nan
[epoch 000000071] loss=nan | avg=nan | rare=nan
[epoch 000000072] loss=nan | avg=nan | rare=nan
[epoch 000000073] loss=nan | avg=nan | rare=nan
[epoch 000000074] loss=nan | avg=nan | rare=nan
[epoch 000000075] loss=nan | avg=nan | rare=nan
[epoch 000000076] loss=nan | avg=nan | rare=nan
[epoch 000000077] loss=nan | avg=nan | rare=nan
[epoch 000000078] loss=nan | avg=nan | rare=nan
[epoch 000000079] loss=nan | avg=nan | rare=nan
[epoch 000000080] loss=nan | avg=nan | rare=nan
[epoch 000000081] loss=nan | avg=nan | rare=nan
[epoch 000000082] loss=nan | avg=nan | rare=nan
[epoch 000000083] loss=nan | avg=nan | rare=nan
[epoch 000000084] loss=nan | avg=nan | rare=nan
[epoch 000000085] loss=nan | avg=nan | rare=nan
[epoch 000000086] loss=nan | avg=nan | rare=nan
[epoch 000000087] loss=nan | avg=nan | rare=nan
[epoch 000000088] loss=nan | avg=nan | rare=nan
[epoch 000000089] loss=nan | avg=nan | rare=nan
[epoch 000000090] loss=nan | avg=nan | rare=nan
[epoch 000000091] loss=nan | avg=nan | rare=nan
[epoch 000000092] loss=nan | avg=nan | rare=nan
[epoch 000000093] loss=nan | avg=nan | rare=nan
[epoch 000000094] loss=nan | avg=nan | rare=nan
[epoch 000000095] loss=nan | avg=nan | rare=nan
[epoch 000000096] loss=nan | avg=nan | rare=nan
[epoch 000000097] loss=nan | avg=nan | rare=nan
[epoch 000000098] loss=nan | avg=nan | rare=nan
[epoch 000000099] loss=nan | avg=nan | rare=nan
[epoch 000000100] loss=nan | avg=nan | rare=nan
[epoch 000000101] loss=nan | avg=nan | rare=nan
[epoch 000000102] loss=nan | avg=nan | rare=nan
[epoch 000000103] loss=nan | avg=nan | rare=nan
[epoch 000000104] loss=nan | avg=nan | rare=nan
[epoch 000000105] loss=nan | avg=nan | rare=nan
[epoch 000000106] loss=nan | avg=nan | rare=nan
[epoch 000000107] loss=nan | avg=nan | rare=nan
[epoch 000000108] loss=nan | avg=nan | rare=nan
[epoch 000000109] loss=nan | avg=nan | rare=nan
[epoch 000000110] loss=nan | avg=nan | rare=nan
[epoch 000000111] loss=nan | avg=nan | rare=nan
[epoch 000000112] loss=nan | avg=nan | rare=nan
[epoch 000000113] loss=nan | avg=nan | rare=nan
[epoch 000000114] loss=nan | avg=nan | rare=nan
[epoch 000000115] loss=nan | avg=nan | rare=nan
[epoch 000000116] loss=nan | avg=nan | rare=nan
[epoch 000000117] loss=nan | avg=nan | rare=nan
[epoch 000000118] loss=nan | avg=nan | rare=nan
[epoch 000000119] loss=nan | avg=nan | rare=nan
[epoch 000000120] loss=nan | avg=nan | rare=nan
[epoch 000000121] loss=nan | avg=nan | rare=nan
[epoch 000000122] loss=nan | avg=nan | rare=nan
[epoch 000000123] loss=nan | avg=nan | rare=nan
[epoch 000000124] loss=nan | avg=nan | rare=nan
[epoch 000000125] loss=nan | avg=nan | rare=nan
[epoch 000000126] loss=nan | avg=nan | rare=nan
[epoch 000000127] loss=nan | avg=nan | rare=nan
[epoch 000000128] loss=nan | avg=nan | rare=nan
[epoch 000000129] loss=nan | avg=nan | rare=nan
[epoch 000000130] loss=nan | avg=nan | rare=nan
[epoch 000000131] loss=nan | avg=nan | rare=nan
[epoch 000000132] loss=nan | avg=nan | rare=nan
[epoch 000000133] loss=nan | avg=nan | rare=nan
[epoch 000000134] loss=nan | avg=nan | rare=nan
[epoch 000000135] loss=nan | avg=nan | rare=nan
[epoch 000000136] loss=nan | avg=nan | rare=nan
[epoch 000000137] loss=nan | avg=nan | rare=nan
[epoch 000000138] loss=nan | avg=nan | rare=nan
[epoch 000000139] loss=nan | avg=nan | rare=nan
[epoch 000000140] loss=nan | avg=nan | rare=nan
[epoch 000000141] loss=nan | avg=nan | rare=nan
[epoch 000000142] loss=nan | avg=nan | rare=nan
[epoch 000000143] loss=nan | avg=nan | rare=nan
[epoch 000000144] loss=nan | avg=nan | rare=nan
[epoch 000000145] loss=nan | avg=nan | rare=nan
[epoch 000000146] loss=nan | avg=nan | rare=nan
[epoch 000000147] loss=nan | avg=nan | rare=nan
[epoch 000000148] loss=nan | avg=nan | rare=nan
[epoch 000000149] loss=nan | avg=nan | rare=nan
[epoch 000000150] loss=nan | avg=nan | rare=nan
[epoch 000000151] loss=nan | avg=nan | rare=nan
[epoch 000000152] loss=nan | avg=nan | rare=nan
[epoch 000000153] loss=nan | avg=nan | rare=nan
[epoch 000000154] loss=nan | avg=nan | rare=nan
[epoch 000000155] loss=nan | avg=nan | rare=nan
[epoch 000000156] loss=nan | avg=nan | rare=nan
[epoch 000000157] loss=nan | avg=nan | rare=nan
[epoch 000000158] loss=nan | avg=nan | rare=nan
[epoch 000000159] loss=nan | avg=nan | rare=nan
[epoch 000000160] loss=nan | avg=nan | rare=nan
[epoch 000000161] loss=nan | avg=nan | rare=nan
[epoch 000000162] loss=nan | avg=nan | rare=nan
[epoch 000000163] loss=nan | avg=nan | rare=nan
[epoch 000000164] loss=nan | avg=nan | rare=nan
[epoch 000000165] loss=nan | avg=nan | rare=nan
[epoch 000000166] loss=nan | avg=nan | rare=nan
[epoch 000000167] loss=nan | avg=nan | rare=nan
[epoch 000000168] loss=nan | avg=nan | rare=nan
[epoch 000000169] loss=nan | avg=nan | rare=nan
[epoch 000000170] loss=nan | avg=nan | rare=nan
[epoch 000000171] loss=nan | avg=nan | rare=nan
[epoch 000000172] loss=nan | avg=nan | rare=nan
[epoch 000000173] loss=nan | avg=nan | rare=nan
[epoch 000000174] loss=nan | avg=nan | rare=nan
[epoch 000000175] loss=nan | avg=nan | rare=nan
[epoch 000000176] loss=nan | avg=nan | rare=nan
[epoch 000000177] loss=nan | avg=nan | rare=nan
[epoch 000000178] loss=nan | avg=nan | rare=nan
[epoch 000000179] loss=nan | avg=nan | rare=nan
[epoch 000000180] loss=nan | avg=nan | rare=nan
[epoch 000000181] loss=nan | avg=nan | rare=nan
[epoch 000000182] loss=nan | avg=nan | rare=nan
[epoch 000000183] loss=nan | avg=nan | rare=nan
[epoch 000000184] loss=nan | avg=nan | rare=nan
[epoch 000000185] loss=nan | avg=nan | rare=nan
[epoch 000000186] loss=nan | avg=nan | rare=nan
[epoch 000000187] loss=nan | avg=nan | rare=nan
[epoch 000000188] loss=nan | avg=nan | rare=nan
[epoch 000000189] loss=nan | avg=nan | rare=nan
[epoch 000000190] loss=nan | avg=nan | rare=nan
[epoch 000000191] loss=nan | avg=nan | rare=nan
[epoch 000000192] loss=nan | avg=nan | rare=nan
[epoch 000000193] loss=nan | avg=nan | rare=nan
[epoch 000000194] loss=nan | avg=nan | rare=nan
[epoch 000000195] loss=nan | avg=nan | rare=nan
[epoch 000000196] loss=nan | avg=nan | rare=nan
[epoch 000000197] loss=nan | avg=nan | rare=nan
[epoch 000000198] loss=nan | avg=nan | rare=nan
[epoch 000000199] loss=nan | avg=nan | rare=nan
[epoch 000000200] loss=nan | avg=nan | rare=nan

Training safe with adam...

Epochs:   0%|          | 0/200 [00:00<?, ?it/s]

[epoch 000000001] loss=142.110842296 | avg=49.984584263 | rare=0.000921263
[epoch 000000002] loss=nan | avg=nan | rare=nan
[epoch 000000003] loss=1527.921237946 | avg=336.449505942 | rare=0.011914718
[epoch 000000004] loss=53.681502206 | avg=53.681502206 | rare=0.000000000
[epoch 000000005] loss=53.673619952 | avg=53.673619952 | rare=0.000000000
[epoch 000000006] loss=53.839760917 | avg=53.839760917 | rare=0.000000000
[epoch 000000007] loss=53.857183456 | avg=53.857183456 | rare=0.000000000
[epoch 000000008] loss=53.667760577 | avg=53.667760577 | rare=0.000000000
[epoch 000000009] loss=53.691014971 | avg=53.691014971 | rare=0.000000000
[epoch 000000010] loss=53.586384092 | avg=53.586384092 | rare=0.000000000
[epoch 000000011] loss=53.472632272 | avg=53.472632272 | rare=0.000000000
[epoch 000000012] loss=53.450143814 | avg=53.450143814 | rare=0.000000000
[epoch 000000013] loss=53.325847626 | avg=53.325847626 | rare=0.000000000
[epoch 000000014] loss=53.151245117 | avg=53.151245117 | rare=0.000000000
[epoch 000000015] loss=53.027956826 | avg=53.027956826 | rare=0.000000000
[epoch 000000016] loss=53.142069135 | avg=53.142069135 | rare=0.000000000
[epoch 000000017] loss=53.103280204 | avg=53.103280204 | rare=0.000000000
[epoch 000000018] loss=52.891982487 | avg=52.891982487 | rare=0.000000000
[epoch 000000019] loss=52.897713797 | avg=52.897713797 | rare=0.000000000
[epoch 000000020] loss=52.669807979 | avg=52.669807979 | rare=0.000000000
[epoch 000000021] loss=52.682809012 | avg=52.682809012 | rare=0.000000000
[epoch 000000022] loss=52.469264439 | avg=52.469264439 | rare=0.000000000
[epoch 000000023] loss=52.305105482 | avg=52.305105482 | rare=0.000000000
[epoch 000000024] loss=52.173712867 | avg=52.173712867 | rare=0.000000000
[epoch 000000025] loss=52.134402139 | avg=52.134402139 | rare=0.000000000
[epoch 000000026] loss=52.088316509 | avg=52.088316509 | rare=0.000000000
[epoch 000000027] loss=51.861349923 | avg=51.861349923 | rare=0.000000000
[epoch 000000028] loss=51.807006291 | avg=51.807006291 | rare=0.000000000
[epoch 000000029] loss=51.682092122 | avg=51.682092122 | rare=0.000000000
[epoch 000000030] loss=51.495312282 | avg=51.495312282 | rare=0.000000000
[epoch 000000031] loss=51.270661218 | avg=51.270661218 | rare=0.000000000
[epoch 000000032] loss=51.527834211 | avg=51.228979928 | rare=0.000002989
[epoch 000000033] loss=50.892255783 | avg=50.892255783 | rare=0.000000000
[epoch 000000034] loss=50.834534509 | avg=50.834534509 | rare=0.000000000
[epoch 000000035] loss=50.797878810 | avg=50.797878810 | rare=0.000000000
[epoch 000000036] loss=50.604590825 | avg=50.604590825 | rare=0.000000000
[epoch 000000037] loss=50.488178526 | avg=50.488178526 | rare=0.000000000
[epoch 000000038] loss=50.241761071 | avg=50.241761071 | rare=0.000000000
[epoch 000000039] loss=50.115768160 | avg=50.115768160 | rare=0.000000000
[epoch 000000040] loss=49.937980652 | avg=49.937980652 | rare=0.000000000
[epoch 000000041] loss=49.646063668 | avg=49.646063668 | rare=0.000000000
[epoch 000000042] loss=49.651718685 | avg=49.651718685 | rare=0.000000000
[epoch 000000043] loss=49.297222410 | avg=49.297222410 | rare=0.000000000
[epoch 000000044] loss=49.175455093 | avg=49.175455093 | rare=0.000000000
[epoch 000000045] loss=49.095882961 | avg=49.095882961 | rare=0.000000000
[epoch 000000046] loss=48.842412131 | avg=48.842412131 | rare=0.000000000
[epoch 000000047] loss=48.580898285 | avg=48.580898285 | rare=0.000000000
[epoch 000000048] loss=48.521031243 | avg=48.521031243 | rare=0.000000000
[epoch 000000049] loss=48.320828847 | avg=48.320828847 | rare=0.000000000
[epoch 000000050] loss=48.077163424 | avg=48.077163424 | rare=0.000000000
[epoch 000000051] loss=47.907408033 | avg=47.907408033 | rare=0.000000000
[epoch 000000052] loss=47.606474740 | avg=47.606474740 | rare=0.000000000
[epoch 000000053] loss=47.542842320 | avg=47.542842320 | rare=0.000000000
[epoch 000000054] loss=47.282896042 | avg=47.282896042 | rare=0.000000000
[epoch 000000055] loss=47.095247541 | avg=47.095247541 | rare=0.000000000
[epoch 000000056] loss=46.826818739 | avg=46.826818739 | rare=0.000000000
[epoch 000000057] loss=46.544303349 | avg=46.544303349 | rare=0.000000000
[epoch 000000058] loss=46.404970987 | avg=46.404970987 | rare=0.000000000
[epoch 000000059] loss=46.157183511 | avg=46.157183511 | rare=0.000000000
[epoch 000000060] loss=46.021913256 | avg=46.021913256 | rare=0.000000000
[epoch 000000061] loss=45.829402924 | avg=45.829402924 | rare=0.000000000
[epoch 000000062] loss=45.477412360 | avg=45.477412360 | rare=0.000000000
[epoch 000000063] loss=45.285092763 | avg=45.285092763 | rare=0.000000000
[epoch 000000064] loss=45.116010393 | avg=45.116010393 | rare=0.000000000
[epoch 000000065] loss=44.923752104 | avg=44.923752104 | rare=0.000000000
[epoch 000000066] loss=44.620634624 | avg=44.620634624 | rare=0.000000000
[epoch 000000067] loss=44.317539215 | avg=44.317539215 | rare=0.000000000
[epoch 000000068] loss=44.014557702 | avg=44.014557702 | rare=0.000000000
[epoch 000000069] loss=43.848734719 | avg=43.848734719 | rare=0.000000000
[epoch 000000070] loss=43.527351924 | avg=43.527351924 | rare=0.000000000
[epoch 000000071] loss=43.454320635 | avg=43.454320635 | rare=0.000000000
[epoch 000000072] loss=43.035631997 | avg=43.035631997 | rare=0.000000000
[epoch 000000073] loss=42.863825934 | avg=42.863825934 | rare=0.000000000
[epoch 000000074] loss=42.623698098 | avg=42.623698098 | rare=0.000000000
[epoch 000000075] loss=42.213304792 | avg=42.213304792 | rare=0.000000000
[epoch 000000076] loss=41.945994241 | avg=41.945994241 | rare=0.000000000
[epoch 000000077] loss=41.749607359 | avg=41.749607359 | rare=0.000000000
[epoch 000000078] loss=41.448796681 | avg=41.448796681 | rare=0.000000000
[epoch 000000079] loss=41.241846630 | avg=41.241846630 | rare=0.000000000
[epoch 000000080] loss=40.791186741 | avg=40.791186741 | rare=0.000000000
[epoch 000000081] loss=40.606678554 | avg=40.606678554 | rare=0.000000000
[epoch 000000082] loss=40.396824700 | avg=40.396824700 | rare=0.000000000
[epoch 000000083] loss=40.068111420 | avg=40.068111420 | rare=0.000000000
[epoch 000000084] loss=39.767101015 | avg=39.767101015 | rare=0.000000000
[epoch 000000085] loss=39.506081717 | avg=39.506081717 | rare=0.000000000
[epoch 000000086] loss=39.146298545 | avg=39.146298545 | rare=0.000000000
[epoch 000000087] loss=38.771657944 | avg=38.771657944 | rare=0.000000000
[epoch 000000088] loss=38.522072111 | avg=38.522072111 | rare=0.000000000
[epoch 000000089] loss=38.256483895 | avg=38.256483895 | rare=0.000000000
[epoch 000000090] loss=37.897691999 | avg=37.897691999 | rare=0.000000000
[epoch 000000091] loss=37.634917940 | avg=37.634917940 | rare=0.000000000
[epoch 000000092] loss=37.244291306 | avg=37.244291306 | rare=0.000000000
[epoch 000000093] loss=36.900421960 | avg=36.900421960 | rare=0.000000000
[epoch 000000094] loss=36.656678336 | avg=36.656678336 | rare=0.000000000
[epoch 000000095] loss=36.264904567 | avg=36.264904567 | rare=0.000000000
[epoch 000000096] loss=35.937861034 | avg=35.937861034 | rare=0.000000000
[epoch 000000097] loss=35.637634550 | avg=35.637634550 | rare=0.000000000
[epoch 000000098] loss=35.305690493 | avg=35.305690493 | rare=0.000000000
[epoch 000000099] loss=34.959485190 | avg=34.959485190 | rare=0.000000000
[epoch 000000100] loss=34.567534855 | avg=34.567534855 | rare=0.000000000
[epoch 000000101] loss=34.213236128 | avg=34.213236128 | rare=0.000000000
[epoch 000000102] loss=33.906660625 | avg=33.906660625 | rare=0.000000000
[epoch 000000103] loss=33.460566112 | avg=33.460566112 | rare=0.000000000
[epoch 000000104] loss=33.212730408 | avg=33.212730408 | rare=0.000000000
[epoch 000000105] loss=32.765269279 | avg=32.765269279 | rare=0.000000000
[epoch 000000106] loss=32.482683182 | avg=32.482683182 | rare=0.000000000
[epoch 000000107] loss=32.142600468 | avg=32.142600468 | rare=0.000000000
[epoch 000000108] loss=31.775067193 | avg=31.775067193 | rare=0.000000000
[epoch 000000109] loss=31.496253695 | avg=31.496253695 | rare=0.000000000
[epoch 000000110] loss=30.956809589 | avg=30.956809589 | rare=0.000000000
[epoch 000000111] loss=30.542021343 | avg=30.542021343 | rare=0.000000000
[epoch 000000112] loss=30.144386836 | avg=30.144386836 | rare=0.000000000
[epoch 000000113] loss=29.821455683 | avg=29.821455683 | rare=0.000000000
[epoch 000000114] loss=29.442253794 | avg=29.442253794 | rare=0.000000000
[epoch 000000115] loss=29.032914162 | avg=29.032914162 | rare=0.000000000
[epoch 000000116] loss=28.627875328 | avg=28.627875328 | rare=0.000000000
[epoch 000000117] loss=28.212459700 | avg=28.212459700 | rare=0.000000000
[epoch 000000118] loss=27.847130094 | avg=27.847130094 | rare=0.000000000
[epoch 000000119] loss=27.418472563 | avg=27.418472563 | rare=0.000000000
[epoch 000000120] loss=26.992265565 | avg=26.992265565 | rare=0.000000000
[epoch 000000121] loss=26.639215606 | avg=26.639215606 | rare=0.000000000
[epoch 000000122] loss=26.183752741 | avg=26.183752741 | rare=0.000000000
[epoch 000000123] loss=25.767914363 | avg=25.767914363 | rare=0.000000000
[epoch 000000124] loss=25.269333158 | avg=25.269333158 | rare=0.000000000
[epoch 000000125] loss=24.904400417 | avg=24.904400417 | rare=0.000000000
[epoch 000000126] loss=24.473103251 | avg=24.473103251 | rare=0.000000000
[epoch 000000127] loss=24.036692892 | avg=24.036692892 | rare=0.000000000
[epoch 000000128] loss=23.591747965 | avg=23.591747965 | rare=0.000000000
[epoch 000000129] loss=23.156924384 | avg=23.156924384 | rare=0.000000000
[epoch 000000130] loss=22.649218559 | avg=22.649218559 | rare=0.000000000
[epoch 000000131] loss=22.218266078 | avg=22.218266078 | rare=0.000000000
[epoch 000000132] loss=21.747720582 | avg=21.747720582 | rare=0.000000000
[epoch 000000133] loss=21.305671556 | avg=21.305671556 | rare=0.000000000
[epoch 000000134] loss=20.825706754 | avg=20.825706754 | rare=0.000000000
[epoch 000000135] loss=20.342289107 | avg=20.342289107 | rare=0.000000000
[epoch 000000136] loss=19.874203001 | avg=19.874203001 | rare=0.000000000
[epoch 000000137] loss=19.395520891 | avg=19.395520891 | rare=0.000000000
[epoch 000000138] loss=18.936180523 | avg=18.936180523 | rare=0.000000000
[epoch 000000139] loss=18.472540038 | avg=18.472540038 | rare=0.000000000
[epoch 000000140] loss=17.962386404 | avg=17.962386404 | rare=0.000000000
[epoch 000000141] loss=17.464220319 | avg=17.464220319 | rare=0.000000000
[epoch 000000142] loss=17.028683526 | avg=17.028683526 | rare=0.000000000
[epoch 000000143] loss=16.459650721 | avg=16.459650721 | rare=0.000000000
[epoch 000000144] loss=15.963809831 | avg=15.963809831 | rare=0.000000000
[epoch 000000145] loss=15.466418743 | avg=15.466418743 | rare=0.000000000
[epoch 000000146] loss=14.982454777 | avg=14.982454777 | rare=0.000000000
[epoch 000000147] loss=14.452161789 | avg=14.452161789 | rare=0.000000000
[epoch 000000148] loss=13.921792439 | avg=13.921792439 | rare=0.000000000
[epoch 000000149] loss=13.392658234 | avg=13.392658234 | rare=0.000000000
[epoch 000000150] loss=12.881771224 | avg=12.881771224 | rare=0.000000000
[epoch 000000151] loss=12.385630063 | avg=12.385630063 | rare=0.000000000
[epoch 000000152] loss=11.814894336 | avg=11.814894336 | rare=0.000000000
[epoch 000000153] loss=11.294391973 | avg=11.294391973 | rare=0.000000000
[epoch 000000154] loss=10.733373097 | avg=10.733373097 | rare=0.000000000
[epoch 000000155] loss=10.164153916 | avg=10.164153916 | rare=0.000000000
[epoch 000000156] loss=9.627466338 | avg=9.627466338 | rare=0.000000000
[epoch 000000157] loss=9.059479850 | avg=9.059479850 | rare=0.000000000
[epoch 000000158] loss=8.499607495 | avg=8.499607495 | rare=0.000000000
[epoch 000000159] loss=7.933139086 | avg=7.933139086 | rare=0.000000000
[epoch 000000160] loss=7.357979536 | avg=7.357979536 | rare=0.000000000
[epoch 000000161] loss=6.779013259 | avg=6.779013259 | rare=0.000000000
[epoch 000000162] loss=6.207550389 | avg=6.207550389 | rare=0.000000000
[epoch 000000163] loss=5.617309059 | avg=5.617309059 | rare=0.000000000
[epoch 000000164] loss=5.030396870 | avg=5.030396870 | rare=0.000000000
[epoch 000000165] loss=4.433169331 | avg=4.433169331 | rare=0.000000000
[epoch 000000166] loss=3.837167484 | avg=3.837167484 | rare=0.000000000
[epoch 000000167] loss=3.226183670 | avg=3.226183670 | rare=0.000000000
[epoch 000000168] loss=2.621474351 | avg=2.621474351 | rare=0.000000000
[epoch 000000169] loss=2.018184057 | avg=2.018184057 | rare=0.000000000
[epoch 000000170] loss=1.423343318 | avg=1.423343318 | rare=0.000000000
[epoch 000000171] loss=0.920075029 | avg=0.920075029 | rare=0.000000000
[epoch 000000172] loss=0.674566499 | avg=0.674566499 | rare=0.000000000
[epoch 000000173] loss=0.649708607 | avg=0.649708607 | rare=0.000000000
[epoch 000000174] loss=0.649689738 | avg=0.649689738 | rare=0.000000000
[epoch 000000175] loss=0.646498110 | avg=0.646498110 | rare=0.000000000
[epoch 000000176] loss=0.646607539 | avg=0.646607539 | rare=0.000000000
[epoch 000000177] loss=0.646095753 | avg=0.646095753 | rare=0.000000000
[epoch 000000178] loss=0.646524532 | avg=0.646524532 | rare=0.000000000
[epoch 000000179] loss=0.646545253 | avg=0.646545253 | rare=0.000000000
[epoch 000000180] loss=0.646484447 | avg=0.646484447 | rare=0.000000000
[epoch 000000181] loss=0.646025160 | avg=0.646025160 | rare=0.000000000
[epoch 000000182] loss=0.646480198 | avg=0.646480198 | rare=0.000000000
[epoch 000000183] loss=0.646666454 | avg=0.646666454 | rare=0.000000000
[epoch 000000184] loss=0.646271118 | avg=0.646271118 | rare=0.000000000
[epoch 000000185] loss=0.646757671 | avg=0.646757671 | rare=0.000000000
[epoch 000000186] loss=0.646396616 | avg=0.646396616 | rare=0.000000000
[epoch 000000187] loss=0.646635592 | avg=0.646635592 | rare=0.000000000
[epoch 000000188] loss=0.646794515 | avg=0.646794515 | rare=0.000000000
[epoch 000000189] loss=0.646600366 | avg=0.646600366 | rare=0.000000000
[epoch 000000190] loss=0.646632799 | avg=0.646632799 | rare=0.000000000
[epoch 000000191] loss=0.646373557 | avg=0.646373557 | rare=0.000000000
[epoch 000000192] loss=0.646590514 | avg=0.646590514 | rare=0.000000000
[epoch 000000193] loss=0.646770409 | avg=0.646770409 | rare=0.000000000
[epoch 000000194] loss=0.646345339 | avg=0.646345339 | rare=0.000000000
[epoch 000000195] loss=0.646398076 | avg=0.646398076 | rare=0.000000000
[epoch 000000196] loss=0.848323128 | avg=0.646144156 | rare=0.000002022
[epoch 000000197] loss=0.670974744 | avg=0.670974744 | rare=0.000000000
[epoch 000000198] loss=0.646869553 | avg=0.646869553 | rare=0.000000000
[epoch 000000199] loss=0.646768911 | avg=0.646768911 | rare=0.000000000
[epoch 000000200] loss=0.646710008 | avg=0.646710008 | rare=0.000000000
Accuracy: 63.96%  (CI 95%: [62.63%, 65.28%])
Robust Accuracy: 63.96424%  (CI 95%: [62.84865%, 65.40986%])
Conditional Robust Accuracy: 100.00000%  (CI 95%: [100.00000%, 100.00000%])
Accuracy: 63.96%  (CI 95%: [62.63%, 65.28%])
Robust Accuracy: 63.96415%  (CI 95%: [62.84861%, 65.40986%])
Conditional Robust Accuracy: 100.00000%  (CI 95%: [100.00000%, 100.00000%])
  --> Running Seed: 100

Training naive with adam...

Epochs:   0%|          | 0/200 [00:00<?, ?it/s]

[epoch 000000001] loss=178466.601562500 | avg=0.319753973 | rare=1.784662809
[epoch 000000002] loss=178522.145089286 | avg=0.320083375 | rare=1.785218264
[epoch 000000003] loss=238665.427943638 | avg=849.181953945 | rare=2.378162444
[epoch 000000004] loss=nan | avg=nan | rare=nan
[epoch 000000005] loss=nan | avg=nan | rare=nan
[epoch 000000006] loss=nan | avg=nan | rare=nan
[epoch 000000007] loss=nan | avg=nan | rare=nan
[epoch 000000008] loss=nan | avg=nan | rare=nan
[epoch 000000009] loss=nan | avg=nan | rare=nan
[epoch 000000010] loss=nan | avg=nan | rare=nan
[epoch 000000011] loss=nan | avg=nan | rare=nan
[epoch 000000012] loss=nan | avg=nan | rare=nan
[epoch 000000013] loss=nan | avg=nan | rare=nan
[epoch 000000014] loss=nan | avg=nan | rare=nan
[epoch 000000015] loss=nan | avg=nan | rare=nan
[epoch 000000016] loss=nan | avg=nan | rare=nan
[epoch 000000017] loss=nan | avg=nan | rare=nan
[epoch 000000018] loss=nan | avg=nan | rare=nan
[epoch 000000019] loss=nan | avg=nan | rare=nan
[epoch 000000020] loss=nan | avg=nan | rare=nan
[epoch 000000021] loss=nan | avg=nan | rare=nan
[epoch 000000022] loss=nan | avg=nan | rare=nan
[epoch 000000023] loss=nan | avg=nan | rare=nan
[epoch 000000024] loss=nan | avg=nan | rare=nan
[epoch 000000025] loss=nan | avg=nan | rare=nan
[epoch 000000026] loss=nan | avg=nan | rare=nan
[epoch 000000027] loss=nan | avg=nan | rare=nan
[epoch 000000028] loss=nan | avg=nan | rare=nan
[epoch 000000029] loss=nan | avg=nan | rare=nan
[epoch 000000030] loss=nan | avg=nan | rare=nan
[epoch 000000031] loss=nan | avg=nan | rare=nan
[epoch 000000032] loss=nan | avg=nan | rare=nan
[epoch 000000033] loss=nan | avg=nan | rare=nan
[epoch 000000034] loss=nan | avg=nan | rare=nan
[epoch 000000035] loss=nan | avg=nan | rare=nan
[epoch 000000036] loss=nan | avg=nan | rare=nan
[epoch 000000037] loss=nan | avg=nan | rare=nan
[epoch 000000038] loss=nan | avg=nan | rare=nan
[epoch 000000039] loss=nan | avg=nan | rare=nan
[epoch 000000040] loss=nan | avg=nan | rare=nan
[epoch 000000041] loss=nan | avg=nan | rare=nan
[epoch 000000042] loss=nan | avg=nan | rare=nan
[epoch 000000043] loss=nan | avg=nan | rare=nan
[epoch 000000044] loss=nan | avg=nan | rare=nan
[epoch 000000045] loss=nan | avg=nan | rare=nan
[epoch 000000046] loss=nan | avg=nan | rare=nan
[epoch 000000047] loss=nan | avg=nan | rare=nan
[epoch 000000048] loss=nan | avg=nan | rare=nan
[epoch 000000049] loss=nan | avg=nan | rare=nan
[epoch 000000050] loss=nan | avg=nan | rare=nan
[epoch 000000051] loss=nan | avg=nan | rare=nan
[epoch 000000052] loss=nan | avg=nan | rare=nan
[epoch 000000053] loss=nan | avg=nan | rare=nan
[epoch 000000054] loss=nan | avg=nan | rare=nan
[epoch 000000055] loss=nan | avg=nan | rare=nan
[epoch 000000056] loss=nan | avg=nan | rare=nan
[epoch 000000057] loss=nan | avg=nan | rare=nan
[epoch 000000058] loss=nan | avg=nan | rare=nan
[epoch 000000059] loss=nan | avg=nan | rare=nan
[epoch 000000060] loss=nan | avg=nan | rare=nan
[epoch 000000061] loss=nan | avg=nan | rare=nan
[epoch 000000062] loss=nan | avg=nan | rare=nan
[epoch 000000063] loss=nan | avg=nan | rare=nan
[epoch 000000064] loss=nan | avg=nan | rare=nan
[epoch 000000065] loss=nan | avg=nan | rare=nan
[epoch 000000066] loss=nan | avg=nan | rare=nan
[epoch 000000067] loss=nan | avg=nan | rare=nan
[epoch 000000068] loss=nan | avg=nan | rare=nan
[epoch 000000069] loss=nan | avg=nan | rare=nan
[epoch 000000070] loss=nan | avg=nan | rare=nan
[epoch 000000071] loss=nan | avg=nan | rare=nan
[epoch 000000072] loss=nan | avg=nan | rare=nan
[epoch 000000073] loss=nan | avg=nan | rare=nan
[epoch 000000074] loss=nan | avg=nan | rare=nan
[epoch 000000075] loss=nan | avg=nan | rare=nan
[epoch 000000076] loss=nan | avg=nan | rare=nan
[epoch 000000077] loss=nan | avg=nan | rare=nan
[epoch 000000078] loss=nan | avg=nan | rare=nan
[epoch 000000079] loss=nan | avg=nan | rare=nan
[epoch 000000080] loss=nan | avg=nan | rare=nan
[epoch 000000081] loss=nan | avg=nan | rare=nan
[epoch 000000082] loss=nan | avg=nan | rare=nan
[epoch 000000083] loss=nan | avg=nan | rare=nan
[epoch 000000084] loss=nan | avg=nan | rare=nan
[epoch 000000085] loss=nan | avg=nan | rare=nan
[epoch 000000086] loss=nan | avg=nan | rare=nan
[epoch 000000087] loss=nan | avg=nan | rare=nan
[epoch 000000088] loss=nan | avg=nan | rare=nan
[epoch 000000089] loss=nan | avg=nan | rare=nan
[epoch 000000090] loss=nan | avg=nan | rare=nan
[epoch 000000091] loss=nan | avg=nan | rare=nan
[epoch 000000092] loss=nan | avg=nan | rare=nan
[epoch 000000093] loss=nan | avg=nan | rare=nan
[epoch 000000094] loss=nan | avg=nan | rare=nan
[epoch 000000095] loss=nan | avg=nan | rare=nan
[epoch 000000096] loss=nan | avg=nan | rare=nan
[epoch 000000097] loss=nan | avg=nan | rare=nan
[epoch 000000098] loss=nan | avg=nan | rare=nan
[epoch 000000099] loss=nan | avg=nan | rare=nan
[epoch 000000100] loss=nan | avg=nan | rare=nan
[epoch 000000101] loss=nan | avg=nan | rare=nan
[epoch 000000102] loss=nan | avg=nan | rare=nan
[epoch 000000103] loss=nan | avg=nan | rare=nan
[epoch 000000104] loss=nan | avg=nan | rare=nan
[epoch 000000105] loss=nan | avg=nan | rare=nan
[epoch 000000106] loss=nan | avg=nan | rare=nan
[epoch 000000107] loss=nan | avg=nan | rare=nan
[epoch 000000108] loss=nan | avg=nan | rare=nan
[epoch 000000109] loss=nan | avg=nan | rare=nan
[epoch 000000110] loss=nan | avg=nan | rare=nan
[epoch 000000111] loss=nan | avg=nan | rare=nan
[epoch 000000112] loss=nan | avg=nan | rare=nan
[epoch 000000113] loss=nan | avg=nan | rare=nan
[epoch 000000114] loss=nan | avg=nan | rare=nan
[epoch 000000115] loss=nan | avg=nan | rare=nan
[epoch 000000116] loss=nan | avg=nan | rare=nan
[epoch 000000117] loss=nan | avg=nan | rare=nan
[epoch 000000118] loss=nan | avg=nan | rare=nan
[epoch 000000119] loss=nan | avg=nan | rare=nan
[epoch 000000120] loss=nan | avg=nan | rare=nan
[epoch 000000121] loss=nan | avg=nan | rare=nan
[epoch 000000122] loss=nan | avg=nan | rare=nan
[epoch 000000123] loss=nan | avg=nan | rare=nan
[epoch 000000124] loss=nan | avg=nan | rare=nan
[epoch 000000125] loss=nan | avg=nan | rare=nan
[epoch 000000126] loss=nan | avg=nan | rare=nan
[epoch 000000127] loss=nan | avg=nan | rare=nan
[epoch 000000128] loss=nan | avg=nan | rare=nan
[epoch 000000129] loss=nan | avg=nan | rare=nan
[epoch 000000130] loss=nan | avg=nan | rare=nan
[epoch 000000131] loss=nan | avg=nan | rare=nan
[epoch 000000132] loss=nan | avg=nan | rare=nan
[epoch 000000133] loss=nan | avg=nan | rare=nan
[epoch 000000134] loss=nan | avg=nan | rare=nan
[epoch 000000135] loss=nan | avg=nan | rare=nan
[epoch 000000136] loss=nan | avg=nan | rare=nan
[epoch 000000137] loss=nan | avg=nan | rare=nan
[epoch 000000138] loss=nan | avg=nan | rare=nan
[epoch 000000139] loss=nan | avg=nan | rare=nan
[epoch 000000140] loss=nan | avg=nan | rare=nan
[epoch 000000141] loss=nan | avg=nan | rare=nan
[epoch 000000142] loss=nan | avg=nan | rare=nan
[epoch 000000143] loss=nan | avg=nan | rare=nan
[epoch 000000144] loss=nan | avg=nan | rare=nan
[epoch 000000145] loss=nan | avg=nan | rare=nan
[epoch 000000146] loss=nan | avg=nan | rare=nan
[epoch 000000147] loss=nan | avg=nan | rare=nan
[epoch 000000148] loss=nan | avg=nan | rare=nan
[epoch 000000149] loss=nan | avg=nan | rare=nan
[epoch 000000150] loss=nan | avg=nan | rare=nan
[epoch 000000151] loss=nan | avg=nan | rare=nan
[epoch 000000152] loss=nan | avg=nan | rare=nan
[epoch 000000153] loss=nan | avg=nan | rare=nan
[epoch 000000154] loss=nan | avg=nan | rare=nan
[epoch 000000155] loss=nan | avg=nan | rare=nan
[epoch 000000156] loss=nan | avg=nan | rare=nan
[epoch 000000157] loss=nan | avg=nan | rare=nan
[epoch 000000158] loss=nan | avg=nan | rare=nan
[epoch 000000159] loss=nan | avg=nan | rare=nan
[epoch 000000160] loss=nan | avg=nan | rare=nan
[epoch 000000161] loss=nan | avg=nan | rare=nan
[epoch 000000162] loss=nan | avg=nan | rare=nan
[epoch 000000163] loss=nan | avg=nan | rare=nan
[epoch 000000164] loss=nan | avg=nan | rare=nan
[epoch 000000165] loss=nan | avg=nan | rare=nan
[epoch 000000166] loss=nan | avg=nan | rare=nan
[epoch 000000167] loss=nan | avg=nan | rare=nan
[epoch 000000168] loss=nan | avg=nan | rare=nan
[epoch 000000169] loss=nan | avg=nan | rare=nan
[epoch 000000170] loss=nan | avg=nan | rare=nan
[epoch 000000171] loss=nan | avg=nan | rare=nan
[epoch 000000172] loss=nan | avg=nan | rare=nan
[epoch 000000173] loss=nan | avg=nan | rare=nan
[epoch 000000174] loss=nan | avg=nan | rare=nan
[epoch 000000175] loss=nan | avg=nan | rare=nan
[epoch 000000176] loss=nan | avg=nan | rare=nan
[epoch 000000177] loss=nan | avg=nan | rare=nan
[epoch 000000178] loss=nan | avg=nan | rare=nan
[epoch 000000179] loss=nan | avg=nan | rare=nan
[epoch 000000180] loss=nan | avg=nan | rare=nan
[epoch 000000181] loss=nan | avg=nan | rare=nan
[epoch 000000182] loss=nan | avg=nan | rare=nan
[epoch 000000183] loss=nan | avg=nan | rare=nan
[epoch 000000184] loss=nan | avg=nan | rare=nan
[epoch 000000185] loss=nan | avg=nan | rare=nan
[epoch 000000186] loss=nan | avg=nan | rare=nan
[epoch 000000187] loss=nan | avg=nan | rare=nan
[epoch 000000188] loss=nan | avg=nan | rare=nan
[epoch 000000189] loss=nan | avg=nan | rare=nan
[epoch 000000190] loss=nan | avg=nan | rare=nan
[epoch 000000191] loss=nan | avg=nan | rare=nan
[epoch 000000192] loss=nan | avg=nan | rare=nan
[epoch 000000193] loss=nan | avg=nan | rare=nan
[epoch 000000194] loss=nan | avg=nan | rare=nan
[epoch 000000195] loss=nan | avg=nan | rare=nan
[epoch 000000196] loss=nan | avg=nan | rare=nan
[epoch 000000197] loss=nan | avg=nan | rare=nan
[epoch 000000198] loss=nan | avg=nan | rare=nan
[epoch 000000199] loss=nan | avg=nan | rare=nan
[epoch 000000200] loss=nan | avg=nan | rare=nan

Training safe with adam...

Epochs:   0%|          | 0/200 [00:00<?, ?it/s]

[epoch 000000001] loss=142.039022991 | avg=50.119557244 | rare=0.000919195
[epoch 000000002] loss=nan | avg=nan | rare=nan
[epoch 000000003] loss=602.467214312 | avg=174.743463789 | rare=0.004277237
[epoch 000000004] loss=56.444064549 | avg=56.444064549 | rare=0.000000000
[epoch 000000005] loss=53.804801668 | avg=53.804801668 | rare=0.000000000
[epoch 000000006] loss=53.713436399 | avg=53.713436399 | rare=0.000000000
[epoch 000000007] loss=53.642029626 | avg=53.642029626 | rare=0.000000000
[epoch 000000008] loss=53.471830096 | avg=53.471830096 | rare=0.000000000
[epoch 000000009] loss=53.480476107 | avg=53.480476107 | rare=0.000000000
[epoch 000000010] loss=53.479176930 | avg=53.479176930 | rare=0.000000000
[epoch 000000011] loss=53.320612499 | avg=53.320612499 | rare=0.000000000
[epoch 000000012] loss=53.262512480 | avg=53.262512480 | rare=0.000000000
[epoch 000000013] loss=52.887895312 | avg=52.887895312 | rare=0.000000000
[epoch 000000014] loss=52.969096865 | avg=52.969096865 | rare=0.000000000
[epoch 000000015] loss=52.768511363 | avg=52.768511363 | rare=0.000000000
[epoch 000000016] loss=52.488874163 | avg=52.488874163 | rare=0.000000000
[epoch 000000017] loss=52.431891850 | avg=52.431891850 | rare=0.000000000
[epoch 000000018] loss=52.271656309 | avg=52.271656309 | rare=0.000000000
[epoch 000000019] loss=52.002712250 | avg=52.002712250 | rare=0.000000000
[epoch 000000020] loss=51.814319883 | avg=51.814319883 | rare=0.000000000
[epoch 000000021] loss=51.592608043 | avg=51.592608043 | rare=0.000000000
[epoch 000000022] loss=51.450020654 | avg=51.450020654 | rare=0.000000000
[epoch 000000023] loss=51.218397413 | avg=51.218397413 | rare=0.000000000
[epoch 000000024] loss=51.092714582 | avg=51.092714582 | rare=0.000000000
[epoch 000000025] loss=50.924910137 | avg=50.924910137 | rare=0.000000000
[epoch 000000026] loss=50.539342063 | avg=50.539342063 | rare=0.000000000
[epoch 000000027] loss=50.380765642 | avg=50.380765642 | rare=0.000000000
[epoch 000000028] loss=50.171554020 | avg=50.171554020 | rare=0.000000000
[epoch 000000029] loss=50.021017892 | avg=50.021017892 | rare=0.000000000
[epoch 000000030] loss=49.791076388 | avg=49.791076388 | rare=0.000000000
[epoch 000000031] loss=49.444857734 | avg=49.444857734 | rare=0.000000000
[epoch 000000032] loss=49.200266157 | avg=49.200266157 | rare=0.000000000
[epoch 000000033] loss=48.997433799 | avg=48.997433799 | rare=0.000000000
[epoch 000000034] loss=48.593949999 | avg=48.593949999 | rare=0.000000000
[epoch 000000035] loss=48.449280058 | avg=48.449280058 | rare=0.000000000
[epoch 000000036] loss=48.163346972 | avg=48.163346972 | rare=0.000000000
[epoch 000000037] loss=48.004318237 | avg=48.004318237 | rare=0.000000000
[epoch 000000038] loss=47.574735914 | avg=47.574735914 | rare=0.000000000
[epoch 000000039] loss=47.259292875 | avg=47.259292875 | rare=0.000000000
[epoch 000000040] loss=47.164350237 | avg=47.164350237 | rare=0.000000000
[epoch 000000041] loss=46.711141314 | avg=46.711141314 | rare=0.000000000
[epoch 000000042] loss=46.529918943 | avg=46.529918943 | rare=0.000000000
[epoch 000000043] loss=46.123218536 | avg=46.123218536 | rare=0.000000000
[epoch 000000044] loss=45.875387192 | avg=45.875387192 | rare=0.000000000
[epoch 000000045] loss=45.594426019 | avg=45.594426019 | rare=0.000000000
[epoch 000000046] loss=45.273635319 | avg=45.273635319 | rare=0.000000000
[epoch 000000047] loss=44.953999928 | avg=44.953999928 | rare=0.000000000
[epoch 000000048] loss=44.554643903 | avg=44.554643903 | rare=0.000000000
[epoch 000000049] loss=44.225338800 | avg=44.225338800 | rare=0.000000000
[epoch 000000050] loss=43.992947170 | avg=43.992947170 | rare=0.000000000
[epoch 000000051] loss=43.561813627 | avg=43.561813627 | rare=0.000000000
[epoch 000000052] loss=43.258353915 | avg=43.258353915 | rare=0.000000000
[epoch 000000053] loss=42.873100008 | avg=42.873100008 | rare=0.000000000
[epoch 000000054] loss=42.487929753 | avg=42.487929753 | rare=0.000000000
[epoch 000000055] loss=42.174257006 | avg=42.174257006 | rare=0.000000000
[epoch 000000056] loss=41.865577425 | avg=41.865577425 | rare=0.000000000
[epoch 000000057] loss=41.350237438 | avg=41.350237438 | rare=0.000000000
[epoch 000000058] loss=41.165589741 | avg=41.165589741 | rare=0.000000000
[epoch 000000059] loss=40.724325180 | avg=40.724325180 | rare=0.000000000
[epoch 000000060] loss=40.340694155 | avg=40.340694155 | rare=0.000000000
[epoch 000000061] loss=39.914038794 | avg=39.914038794 | rare=0.000000000
[epoch 000000062] loss=39.526527405 | avg=39.526527405 | rare=0.000000000
[epoch 000000063] loss=39.177722658 | avg=39.177722658 | rare=0.000000000
[epoch 000000064] loss=38.835605076 | avg=38.835605076 | rare=0.000000000
[epoch 000000065] loss=38.257859639 | avg=38.257859639 | rare=0.000000000
[epoch 000000066] loss=37.924081257 | avg=37.924081257 | rare=0.000000000
[epoch 000000067] loss=37.438354220 | avg=37.438354220 | rare=0.000000000
[epoch 000000068] loss=37.054845537 | avg=37.054845537 | rare=0.000000000
[epoch 000000069] loss=36.570444107 | avg=36.570444107 | rare=0.000000000
[epoch 000000070] loss=36.212180001 | avg=36.212180001 | rare=0.000000000
[epoch 000000071] loss=35.720655714 | avg=35.720655714 | rare=0.000000000
[epoch 000000072] loss=35.238440377 | avg=35.238440377 | rare=0.000000000
[epoch 000000073] loss=34.887693950 | avg=34.887693950 | rare=0.000000000
[epoch 000000074] loss=34.415635790 | avg=34.415635790 | rare=0.000000000
[epoch 000000075] loss=33.991839818 | avg=33.991839818 | rare=0.000000000
[epoch 000000076] loss=33.477887017 | avg=33.477887017 | rare=0.000000000
[epoch 000000077] loss=33.032490322 | avg=33.032490322 | rare=0.000000000
[epoch 000000078] loss=32.582993644 | avg=32.582993644 | rare=0.000000000
[epoch 000000079] loss=32.043670109 | avg=32.043670109 | rare=0.000000000
[epoch 000000080] loss=31.620292936 | avg=31.620292936 | rare=0.000000000
[epoch 000000081] loss=31.135743686 | avg=31.135743686 | rare=0.000000000
[epoch 000000082] loss=30.554706165 | avg=30.554706165 | rare=0.000000000
[epoch 000000083] loss=30.172253609 | avg=30.172253609 | rare=0.000000000
[epoch 000000084] loss=29.639371191 | avg=29.639371191 | rare=0.000000000
[epoch 000000085] loss=29.084045955 | avg=29.084045955 | rare=0.000000000
[epoch 000000086] loss=28.604018620 | avg=28.604018620 | rare=0.000000000
[epoch 000000087] loss=28.146531650 | avg=28.146531650 | rare=0.000000000
[epoch 000000088] loss=27.490180288 | avg=27.490180288 | rare=0.000000000
[epoch 000000089] loss=27.059838431 | avg=27.059838431 | rare=0.000000000
[epoch 000000090] loss=26.492142677 | avg=26.492142677 | rare=0.000000000
[epoch 000000091] loss=25.915613583 | avg=25.915613583 | rare=0.000000000
[epoch 000000092] loss=25.439246723 | avg=25.439246723 | rare=0.000000000
[epoch 000000093] loss=24.872972352 | avg=24.872972352 | rare=0.000000000
[epoch 000000094] loss=24.331748690 | avg=24.331748690 | rare=0.000000000
[epoch 000000095] loss=23.780850955 | avg=23.780850955 | rare=0.000000000
[epoch 000000096] loss=23.154570716 | avg=23.154570716 | rare=0.000000000
[epoch 000000097] loss=22.625337873 | avg=22.625337873 | rare=0.000000000
[epoch 000000098] loss=22.048467636 | avg=22.048467636 | rare=0.000000000
[epoch 000000099] loss=21.439443452 | avg=21.439443452 | rare=0.000000000
[epoch 000000100] loss=20.843599183 | avg=20.843599183 | rare=0.000000000
[epoch 000000101] loss=20.255835806 | avg=20.255835806 | rare=0.000000000
[epoch 000000102] loss=19.663553374 | avg=19.663553374 | rare=0.000000000
[epoch 000000103] loss=19.059695516 | avg=19.059695516 | rare=0.000000000
[epoch 000000104] loss=18.414400509 | avg=18.414400509 | rare=0.000000000
[epoch 000000105] loss=17.829016685 | avg=17.829016685 | rare=0.000000000
[epoch 000000106] loss=17.201428277 | avg=17.201428277 | rare=0.000000000
[epoch 000000107] loss=16.555246626 | avg=16.555246626 | rare=0.000000000
[epoch 000000108] loss=15.934276104 | avg=15.934276104 | rare=0.000000000
[epoch 000000109] loss=15.292695386 | avg=15.292695386 | rare=0.000000000
[epoch 000000110] loss=14.662957805 | avg=14.662957805 | rare=0.000000000
[epoch 000000111] loss=13.997200217 | avg=13.997200217 | rare=0.000000000
[epoch 000000112] loss=13.354380471 | avg=13.354380471 | rare=0.000000000
[epoch 000000113] loss=12.689684459 | avg=12.689684459 | rare=0.000000000
[epoch 000000114] loss=12.032073157 | avg=12.032073157 | rare=0.000000000
[epoch 000000115] loss=11.356250422 | avg=11.356250422 | rare=0.000000000
[epoch 000000116] loss=10.661502906 | avg=10.661502906 | rare=0.000000000
[epoch 000000117] loss=9.965667725 | avg=9.965667725 | rare=0.000000000
[epoch 000000118] loss=9.311873640 | avg=9.311873640 | rare=0.000000000
[epoch 000000119] loss=8.601270199 | avg=8.601270199 | rare=0.000000000
[epoch 000000120] loss=7.895214864 | avg=7.895214864 | rare=0.000000000
[epoch 000000121] loss=7.172067915 | avg=7.172067915 | rare=0.000000000
[epoch 000000122] loss=6.471951621 | avg=6.471951621 | rare=0.000000000
[epoch 000000123] loss=5.764205149 | avg=5.764205149 | rare=0.000000000
[epoch 000000124] loss=5.038195985 | avg=5.038195985 | rare=0.000000000
[epoch 000000125] loss=4.307502236 | avg=4.307502236 | rare=0.000000000
[epoch 000000126] loss=3.555264252 | avg=3.555264252 | rare=0.000000000
[epoch 000000127] loss=2.806849701 | avg=2.806849701 | rare=0.000000000
[epoch 000000128] loss=2.060834859 | avg=2.060834859 | rare=0.000000000
[epoch 000000129] loss=1.341058697 | avg=1.341058697 | rare=0.000000000
[epoch 000000130] loss=0.796096704 | avg=0.796096704 | rare=0.000000000
[epoch 000000131] loss=0.652778847 | avg=0.652778847 | rare=0.000000000
[epoch 000000132] loss=0.655176265 | avg=0.655176265 | rare=0.000000000
[epoch 000000133] loss=0.647646853 | avg=0.647646853 | rare=0.000000000
[epoch 000000134] loss=0.646975883 | avg=0.646975883 | rare=0.000000000
[epoch 000000135] loss=0.646171055 | avg=0.646171055 | rare=0.000000000
[epoch 000000136] loss=0.646390749 | avg=0.646390749 | rare=0.000000000
[epoch 000000137] loss=0.646337650 | avg=0.646337650 | rare=0.000000000
[epoch 000000138] loss=0.646672589 | avg=0.646672589 | rare=0.000000000
[epoch 000000139] loss=0.646536406 | avg=0.646536406 | rare=0.000000000
[epoch 000000140] loss=0.646627499 | avg=0.646627499 | rare=0.000000000
[epoch 000000141] loss=0.646354105 | avg=0.646354105 | rare=0.000000000
[epoch 000000142] loss=0.647183142 | avg=0.647183142 | rare=0.000000000
[epoch 000000143] loss=0.646605002 | avg=0.646605002 | rare=0.000000000
[epoch 000000144] loss=0.647085117 | avg=0.647085117 | rare=0.000000000
[epoch 000000145] loss=0.646674944 | avg=0.646674944 | rare=0.000000000
[epoch 000000146] loss=0.646743102 | avg=0.646743102 | rare=0.000000000
[epoch 000000147] loss=0.646967560 | avg=0.646967560 | rare=0.000000000
[epoch 000000148] loss=0.646825905 | avg=0.646825905 | rare=0.000000000
[epoch 000000149] loss=0.646099223 | avg=0.646099223 | rare=0.000000000
[epoch 000000150] loss=0.646385129 | avg=0.646385129 | rare=0.000000000
[epoch 000000151] loss=0.646690237 | avg=0.646690237 | rare=0.000000000
[epoch 000000152] loss=0.646464131 | avg=0.646464131 | rare=0.000000000
[epoch 000000153] loss=0.646552469 | avg=0.646552469 | rare=0.000000000
[epoch 000000154] loss=0.646354109 | avg=0.646354109 | rare=0.000000000
[epoch 000000155] loss=0.646614049 | avg=0.646614049 | rare=0.000000000
[epoch 000000156] loss=0.646721768 | avg=0.646721768 | rare=0.000000000
[epoch 000000157] loss=0.646640003 | avg=0.646640003 | rare=0.000000000
[epoch 000000158] loss=0.646653967 | avg=0.646653967 | rare=0.000000000
[epoch 000000159] loss=0.646664028 | avg=0.646664028 | rare=0.000000000
[epoch 000000160] loss=0.646994161 | avg=0.646994161 | rare=0.000000000
[epoch 000000161] loss=0.646831112 | avg=0.646831112 | rare=0.000000000
[epoch 000000162] loss=0.646034517 | avg=0.646034517 | rare=0.000000000
[epoch 000000163] loss=0.646677341 | avg=0.646677341 | rare=0.000000000
[epoch 000000164] loss=0.646929485 | avg=0.646929485 | rare=0.000000000
[epoch 000000165] loss=0.647039818 | avg=0.647039818 | rare=0.000000000
[epoch 000000166] loss=0.646757982 | avg=0.646757982 | rare=0.000000000
[epoch 000000167] loss=0.646364953 | avg=0.646364953 | rare=0.000000000
[epoch 000000168] loss=0.646692893 | avg=0.646692893 | rare=0.000000000
[epoch 000000169] loss=0.646229812 | avg=0.646229812 | rare=0.000000000
[epoch 000000170] loss=0.646580436 | avg=0.646580436 | rare=0.000000000
[epoch 000000171] loss=0.646355416 | avg=0.646355416 | rare=0.000000000
[epoch 000000172] loss=0.646553738 | avg=0.646553738 | rare=0.000000000
[epoch 000000173] loss=0.646249524 | avg=0.646249524 | rare=0.000000000
[epoch 000000174] loss=0.646879669 | avg=0.646879669 | rare=0.000000000
[epoch 000000175] loss=0.646897503 | avg=0.646897503 | rare=0.000000000
[epoch 000000176] loss=0.646374634 | avg=0.646374634 | rare=0.000000000
[epoch 000000177] loss=0.646733825 | avg=0.646733825 | rare=0.000000000
[epoch 000000178] loss=0.646513275 | avg=0.646513275 | rare=0.000000000
[epoch 000000179] loss=0.646432434 | avg=0.646432434 | rare=0.000000000
[epoch 000000180] loss=0.646459409 | avg=0.646459409 | rare=0.000000000
[epoch 000000181] loss=0.646287037 | avg=0.646287037 | rare=0.000000000
[epoch 000000182] loss=0.646287335 | avg=0.646287335 | rare=0.000000000
[epoch 000000183] loss=0.646659723 | avg=0.646659723 | rare=0.000000000
[epoch 000000184] loss=0.645920681 | avg=0.645920681 | rare=0.000000000
[epoch 000000185] loss=0.646224196 | avg=0.646224196 | rare=0.000000000
[epoch 000000186] loss=0.646541970 | avg=0.646541970 | rare=0.000000000
[epoch 000000187] loss=0.646800684 | avg=0.646800684 | rare=0.000000000
[epoch 000000188] loss=0.646273102 | avg=0.646273102 | rare=0.000000000
[epoch 000000189] loss=0.646586435 | avg=0.646586435 | rare=0.000000000
[epoch 000000190] loss=0.646345999 | avg=0.646345999 | rare=0.000000000
[epoch 000000191] loss=0.646433238 | avg=0.646433238 | rare=0.000000000
[epoch 000000192] loss=0.646308486 | avg=0.646308486 | rare=0.000000000
[epoch 000000193] loss=0.646464067 | avg=0.646464067 | rare=0.000000000
[epoch 000000194] loss=0.646852429 | avg=0.646852429 | rare=0.000000000
[epoch 000000195] loss=0.646561661 | avg=0.646561661 | rare=0.000000000
[epoch 000000196] loss=0.646465531 | avg=0.646465531 | rare=0.000000000
[epoch 000000197] loss=0.646170186 | avg=0.646170186 | rare=0.000000000
[epoch 000000198] loss=0.647058815 | avg=0.647058815 | rare=0.000000000
[epoch 000000199] loss=0.646545610 | avg=0.646545610 | rare=0.000000000
[epoch 000000200] loss=0.646741373 | avg=0.646741373 | rare=0.000000000
Accuracy: 36.04%  (CI 95%: [34.72%, 37.37%])
Robust Accuracy: 36.03586%  (CI 95%: [34.59014%, 37.15139%])
Conditional Robust Accuracy: 100.00000%  (CI 95%: [100.00000%, 100.00000%])
Accuracy: 63.96%  (CI 95%: [62.63%, 65.28%])
Robust Accuracy: 63.96415%  (CI 95%: [62.84861%, 65.40986%])
Conditional Robust Accuracy: 100.00000%  (CI 95%: [100.00000%, 100.00000%])

#################### lr: 0.1 ####################
  --> Running Seed: 42

Training naive with adam...

Epochs:   0%|          | 0/200 [00:00<?, ?it/s]

[epoch 000000001] loss=178608.407366071 | avg=0.319726129 | rare=1.786080871
[epoch 000000002] loss=178494.834821429 | avg=0.319935188 | rare=1.784945164
[epoch 000000003] loss=102257.073620387 | avg=80.095191255 | rare=1.021769761
[epoch 000000004] loss=1704.412949698 | avg=604.458444323 | rare=0.010999545
[epoch 000000005] loss=2629.802455357 | avg=2629.802455357 | rare=0.000000000
[epoch 000000006] loss=3399.853393555 | avg=3399.853393555 | rare=0.000000000
[epoch 000000007] loss=3361.281563895 | avg=3361.281563895 | rare=0.000000000
[epoch 000000008] loss=3056.772792271 | avg=3056.772792271 | rare=0.000000000
[epoch 000000009] loss=42418.692432949 | avg=1236.088162286 | rare=0.411826043
[epoch 000000010] loss=nan | avg=inf | rare=nan
[epoch 000000011] loss=nan | avg=nan | rare=nan
[epoch 000000012] loss=nan | avg=nan | rare=nan
[epoch 000000013] loss=nan | avg=nan | rare=nan
[epoch 000000014] loss=nan | avg=nan | rare=nan
[epoch 000000015] loss=nan | avg=nan | rare=nan
[epoch 000000016] loss=nan | avg=nan | rare=nan
[epoch 000000017] loss=nan | avg=nan | rare=nan
[epoch 000000018] loss=nan | avg=nan | rare=nan
[epoch 000000019] loss=nan | avg=nan | rare=nan
[epoch 000000020] loss=nan | avg=nan | rare=nan
[epoch 000000021] loss=nan | avg=inf | rare=nan
[epoch 000000022] loss=1741.652901786 | avg=800.444444929 | rare=0.009412085
[epoch 000000023] loss=1704.287183489 | avg=274.042525155 | rare=0.014302447
[epoch 000000024] loss=2460.602094378 | avg=191.406441825 | rare=0.022691957
[epoch 000000025] loss=30055.219504220 | avg=113.908568655 | rare=0.299413114
[epoch 000000026] loss=1948.985874721 | avg=42.175891059 | rare=0.019068100
[epoch 000000027] loss=1980.209110805 | avg=49.186180932 | rare=0.019310229
[epoch 000000028] loss=1019.070941380 | avg=48.841245106 | rare=0.009702297
[epoch 000000029] loss=1305.112796238 | avg=48.395209721 | rare=0.012567176
[epoch 000000030] loss=1476.104461670 | avg=48.252352578 | rare=0.014278521
[epoch 000000031] loss=3453.131330218 | avg=49.460738863 | rare=0.034036706
[epoch 000000032] loss=3317.829744611 | avg=47.110297067 | rare=0.032707195
[epoch 000000033] loss=1574.437964303 | avg=40.896792684 | rare=0.015335411
[epoch 000000034] loss=1440.573558262 | avg=38.588650840 | rare=0.014019849
[epoch 000000035] loss=3236.598157610 | avg=37.923860414 | rare=0.031986743
[epoch 000000036] loss=13641.908517020 | avg=46.371338163 | rare=0.135955372
[epoch 000000037] loss=4463.269404820 | avg=36.762104443 | rare=0.044265074
[epoch 000000038] loss=3745.291006906 | avg=36.091839109 | rare=0.037091992
[epoch 000000039] loss=2139.300315857 | avg=32.804187775 | rare=0.021064961
[epoch 000000040] loss=1448.074251447 | avg=30.064129693 | rare=0.014180101
[epoch 000000041] loss=8374.739624023 | avg=34.752580779 | rare=0.083399870
[epoch 000000042] loss=2278.478455680 | avg=29.510729245 | rare=0.022489677
[epoch 000000043] loss=2422.346099854 | avg=28.591961997 | rare=0.023937541
[epoch 000000044] loss=2276.387054988 | avg=28.935517720 | rare=0.022474516
[epoch 000000045] loss=11105.215523856 | avg=39.217958042 | rare=0.110659975
[epoch 000000046] loss=7058.664389474 | avg=30.797137805 | rare=0.070278672
[epoch 000000047] loss=3276.499773298 | avg=25.475269045 | rare=0.032510245
[epoch 000000048] loss=1978.195314680 | avg=22.629374777 | rare=0.019555659
[epoch 000000049] loss=1693.929441180 | avg=21.645737716 | rare=0.016722837
[epoch 000000050] loss=4467.137855189 | avg=19.026825121 | rare=0.044481109
[epoch 000000051] loss=2292.479823521 | avg=9.831774729 | rare=0.022826481
[epoch 000000052] loss=1999.553473336 | avg=7.401985032 | rare=0.019921515
[epoch 000000053] loss=6326.177403041 | avg=5.572736723 | rare=0.063206047
[epoch 000000054] loss=1963.670961652 | avg=4.156332169 | rare=0.019595146
[epoch 000000055] loss=4116.837462289 | avg=4.941004489 | rare=0.041118966
[epoch 000000056] loss=2743.682939802 | avg=3.222409597 | rare=0.027404605
[epoch 000000057] loss=211.360021148 | avg=6.127293229 | rare=0.002052327
[epoch 000000058] loss=32.887927430 | avg=8.777757100 | rare=0.000241102
[epoch 000000059] loss=12.255617244 | avg=9.404239825 | rare=0.000028514
[epoch 000000060] loss=12.278519528 | avg=9.483000381 | rare=0.000027955
[epoch 000000061] loss=15.432674442 | avg=9.429103374 | rare=0.000060036
[epoch 000000062] loss=11.768827370 | avg=9.506799153 | rare=0.000022620
[epoch 000000063] loss=15.762562309 | avg=9.486949001 | rare=0.000062756
[epoch 000000064] loss=13.767107419 | avg=9.394401687 | rare=0.000043727
[epoch 000000065] loss=10.756346158 | avg=9.410999911 | rare=0.000013453
[epoch 000000066] loss=10.839683362 | avg=9.253273351 | rare=0.000015864
[epoch 000000067] loss=12.213430200 | avg=9.549722365 | rare=0.000026637
[epoch 000000068] loss=9.543280125 | avg=9.091565473 | rare=0.000004517
[epoch 000000069] loss=11.884088618 | avg=9.126471179 | rare=0.000027576
[epoch 000000070] loss=13.365703668 | avg=8.862324050 | rare=0.000045034
[epoch 000000071] loss=9.738471815 | avg=8.895641702 | rare=0.000008428
[epoch 000000072] loss=11.837130751 | avg=8.874200923 | rare=0.000029629
[epoch 000000073] loss=12.912668467 | avg=8.766473838 | rare=0.000041462
[epoch 000000074] loss=8.775192022 | avg=8.628789391 | rare=0.000001464
[epoch 000000075] loss=9.015856981 | avg=8.794168574 | rare=0.000002217
[epoch 000000076] loss=8.982985360 | avg=8.750840562 | rare=0.000002321
[epoch 000000077] loss=9.984073298 | avg=8.486341340 | rare=0.000014977
[epoch 000000078] loss=9.807840484 | avg=8.319099699 | rare=0.000014887
[epoch 000000079] loss=10.005058595 | avg=8.335583585 | rare=0.000016695
[epoch 000000080] loss=12.229356459 | avg=8.240109273 | rare=0.000039892
[epoch 000000081] loss=10.264065742 | avg=8.131718022 | rare=0.000021323
[epoch 000000082] loss=10.052012818 | avg=8.264772620 | rare=0.000017872
[epoch 000000083] loss=8.286415151 | avg=7.965050748 | rare=0.000003214
[epoch 000000084] loss=8.200714588 | avg=7.929326126 | rare=0.000002714
[epoch 000000085] loss=9.583977393 | avg=7.883494275 | rare=0.000017005
[epoch 000000086] loss=9.439992598 | avg=7.798146827 | rare=0.000016418
[epoch 000000087] loss=8.350059254 | avg=7.820579273 | rare=0.000005295
[epoch 000000088] loss=9.914776053 | avg=7.578546388 | rare=0.000023362
[epoch 000000089] loss=8.419588396 | avg=7.566567489 | rare=0.000008530
[epoch 000000090] loss=8.521221127 | avg=7.661170380 | rare=0.000008601
[epoch 000000091] loss=7.807911958 | avg=7.378138695 | rare=0.000004298
[epoch 000000092] loss=7.998664039 | avg=7.477249384 | rare=0.000005214
[epoch 000000093] loss=7.793986474 | avg=7.480091384 | rare=0.000003139
[epoch 000000094] loss=7.941535779 | avg=7.201048544 | rare=0.000007405
[epoch 000000095] loss=7.132061192 | avg=7.089194621 | rare=0.000000429
[epoch 000000096] loss=7.761124219 | avg=6.955896088 | rare=0.000008052
[epoch 000000097] loss=7.287413103 | avg=6.894880789 | rare=0.000003925
[epoch 000000098] loss=6.771729282 | avg=6.771729282 | rare=0.000000000
[epoch 000000099] loss=9.004052520 | avg=6.714307870 | rare=0.000022897
[epoch 000000100] loss=6.812753524 | avg=6.697985632 | rare=0.000001148
[epoch 000000101] loss=6.712195839 | avg=6.597182070 | rare=0.000001150
[epoch 000000102] loss=6.751872574 | avg=6.533065626 | rare=0.000002188
[epoch 000000103] loss=6.390645828 | avg=6.389136127 | rare=0.000000015
[epoch 000000104] loss=7.320060321 | avg=6.366522210 | rare=0.000009535
[epoch 000000105] loss=8.169427225 | avg=6.354939137 | rare=0.000018145
[epoch 000000106] loss=6.566620759 | avg=6.203352571 | rare=0.000003633
[epoch 000000107] loss=6.326851981 | avg=6.060913052 | rare=0.000002659
[epoch 000000108] loss=6.494249889 | avg=6.028202806 | rare=0.000004660
[epoch 000000109] loss=5.976428781 | avg=5.976428781 | rare=0.000000000
[epoch 000000110] loss=7.883812078 | avg=5.898370939 | rare=0.000019854
[epoch 000000111] loss=6.149441344 | avg=5.817944152 | rare=0.000003315
[epoch 000000112] loss=5.797280669 | avg=5.760765876 | rare=0.000000365
[epoch 000000113] loss=6.091074927 | avg=5.756089449 | rare=0.000003350
[epoch 000000114] loss=5.784245065 | avg=5.668321133 | rare=0.000001159
[epoch 000000115] loss=5.599677920 | avg=5.594178012 | rare=0.000000055
[epoch 000000116] loss=6.950319546 | avg=5.668184740 | rare=0.000012821
[epoch 000000117] loss=6.208043218 | avg=5.579905714 | rare=0.000006281
[epoch 000000118] loss=6.247596792 | avg=5.476745929 | rare=0.000007709
[epoch 000000119] loss=6.010672501 | avg=5.799376965 | rare=0.000002113
[epoch 000000120] loss=7.010095017 | avg=5.375137653 | rare=0.000016350
[epoch 000000121] loss=5.528709905 | avg=5.523012008 | rare=0.000000057
[epoch 000000122] loss=5.297432269 | avg=5.293997662 | rare=0.000000034
[epoch 000000123] loss=5.601308516 | avg=5.307629347 | rare=0.000002937
[epoch 000000124] loss=5.193502988 | avg=5.191663095 | rare=0.000000018
[epoch 000000125] loss=6.948263850 | avg=5.187540582 | rare=0.000017607
[epoch 000000126] loss=5.082899145 | avg=5.078493808 | rare=0.000000044
[epoch 000000127] loss=5.762691668 | avg=5.103354062 | rare=0.000006593
[epoch 000000128] loss=5.710858141 | avg=5.029799853 | rare=0.000006811
[epoch 000000129] loss=5.411470839 | avg=5.045693159 | rare=0.000003658
[epoch 000000130] loss=4.960592134 | avg=4.958474347 | rare=0.000000021
[epoch 000000131] loss=4.895965423 | avg=4.890107308 | rare=0.000000059
[epoch 000000132] loss=5.435817225 | avg=4.859093666 | rare=0.000005767
[epoch 000000133] loss=5.306769133 | avg=4.959244779 | rare=0.000003475
[epoch 000000134] loss=4.827235239 | avg=4.788011551 | rare=0.000000392
[epoch 000000135] loss=5.166885563 | avg=4.755409990 | rare=0.000004115
[epoch 000000136] loss=4.695303065 | avg=4.694178258 | rare=0.000000011
[epoch 000000137] loss=4.663317987 | avg=4.660786254 | rare=0.000000025
[epoch 000000138] loss=4.897947473 | avg=4.625400305 | rare=0.000002725
[epoch 000000139] loss=4.890698433 | avg=4.739700334 | rare=0.000001510
[epoch 000000140] loss=5.098462028 | avg=4.683975501 | rare=0.000004145
[epoch 000000141] loss=4.524957112 | avg=4.523564288 | rare=0.000000014
[epoch 000000142] loss=4.818568179 | avg=4.445489441 | rare=0.000003731
[epoch 000000143] loss=4.471309083 | avg=4.470880917 | rare=0.000000004
[epoch 000000144] loss=4.406433480 | avg=4.404275077 | rare=0.000000022
[epoch 000000145] loss=4.345552444 | avg=4.342688646 | rare=0.000000029
[epoch 000000146] loss=4.823069317 | avg=4.434780870 | rare=0.000003883
[epoch 000000147] loss=4.309274733 | avg=4.306816501 | rare=0.000000025
[epoch 000000148] loss=4.303468619 | avg=4.303074139 | rare=0.000000004
[epoch 000000149] loss=6.225052859 | avg=4.468623170 | rare=0.000017564
[epoch 000000150] loss=4.266897406 | avg=4.261201348 | rare=0.000000057
[epoch 000000151] loss=4.267998457 | avg=4.267020566 | rare=0.000000010
[epoch 000000152] loss=4.272688610 | avg=4.271078825 | rare=0.000000016
[epoch 000000153] loss=4.204752292 | avg=4.202622090 | rare=0.000000021
[epoch 000000154] loss=4.193850977 | avg=4.192492042 | rare=0.000000014
[epoch 000000155] loss=4.171230299 | avg=4.168175127 | rare=0.000000031
[epoch 000000156] loss=4.123702730 | avg=4.122058885 | rare=0.000000016
[epoch 000000157] loss=4.459170571 | avg=4.204998434 | rare=0.000002542
[epoch 000000158] loss=4.244703668 | avg=4.082700372 | rare=0.000001620
[epoch 000000159] loss=4.095728738 | avg=4.094196558 | rare=0.000000015
[epoch 000000160] loss=4.379112150 | avg=4.045474180 | rare=0.000003336
[epoch 000000161] loss=4.259225181 | avg=4.091502207 | rare=0.000001677
[epoch 000000162] loss=4.149031324 | avg=4.008293118 | rare=0.000001407
[epoch 000000163] loss=4.056185527 | avg=4.045989658 | rare=0.000000102
[epoch 000000164] loss=3.989526425 | avg=3.989155088 | rare=0.000000004
[epoch 000000165] loss=4.973191244 | avg=4.006317718 | rare=0.000009669
[epoch 000000166] loss=3.997004569 | avg=3.994457790 | rare=0.000000025
[epoch 000000167] loss=4.022459294 | avg=4.022052688 | rare=0.000000004
[epoch 000000168] loss=4.050137622 | avg=4.048113074 | rare=0.000000020
[epoch 000000169] loss=3.937659042 | avg=3.936392563 | rare=0.000000013
[epoch 000000170] loss=4.906398109 | avg=3.955543348 | rare=0.000009509
[epoch 000000171] loss=3.948185733 | avg=3.947418622 | rare=0.000000008
[epoch 000000172] loss=4.563851799 | avg=3.971132398 | rare=0.000005927
[epoch 000000173] loss=3.899108733 | avg=3.897937553 | rare=0.000000012
[epoch 000000174] loss=3.805616668 | avg=3.803816012 | rare=0.000000018
[epoch 000000175] loss=4.325154918 | avg=3.786479294 | rare=0.000005387
[epoch 000000176] loss=4.000400892 | avg=3.792150131 | rare=0.000002083
[epoch 000000177] loss=3.771208618 | avg=3.769030154 | rare=0.000000022
[epoch 000000178] loss=3.759106534 | avg=3.742623457 | rare=0.000000165
[epoch 000000179] loss=3.904409400 | avg=3.738539483 | rare=0.000001659
[epoch 000000180] loss=3.744215097 | avg=3.743089182 | rare=0.000000011
[epoch 000000181] loss=3.707826189 | avg=3.707700355 | rare=0.000000001
[epoch 000000182] loss=3.657570805 | avg=3.656960266 | rare=0.000000006
[epoch 000000183] loss=4.226337722 | avg=3.678950369 | rare=0.000005474
[epoch 000000184] loss=3.618013935 | avg=3.617259758 | rare=0.000000008
[epoch 000000185] loss=3.595234539 | avg=3.594011537 | rare=0.000000012
[epoch 000000186] loss=3.715655378 | avg=3.715655378 | rare=0.000000000
[epoch 000000187] loss=3.663525769 | avg=3.642424166 | rare=0.000000211
[epoch 000000188] loss=4.044489878 | avg=4.044489878 | rare=0.000000000
[epoch 000000189] loss=4.110447475 | avg=4.101155962 | rare=0.000000093
[epoch 000000190] loss=3.954304167 | avg=3.954304167 | rare=0.000000000
[epoch 000000191] loss=3.805779696 | avg=3.805779696 | rare=0.000000000
[epoch 000000192] loss=3.758668550 | avg=3.758668550 | rare=0.000000000
[epoch 000000193] loss=3.663210085 | avg=3.663210085 | rare=0.000000000
[epoch 000000194] loss=3.595307248 | avg=3.595307248 | rare=0.000000000
[epoch 000000195] loss=3.515836809 | avg=3.515836809 | rare=0.000000000
[epoch 000000196] loss=3.598516251 | avg=3.597579675 | rare=0.000000009
[epoch 000000197] loss=3.428770397 | avg=3.428478803 | rare=0.000000003
[epoch 000000198] loss=3.456247994 | avg=3.431151833 | rare=0.000000251
[epoch 000000199] loss=4.148993398 | avg=3.411231084 | rare=0.000007378
[epoch 000000200] loss=3.480782969 | avg=3.418112942 | rare=0.000000627

Training safe with adam...

Epochs:   0%|          | 0/200 [00:00<?, ?it/s]

[epoch 000000001] loss=142.110842296 | avg=49.984584263 | rare=0.000921263
[epoch 000000002] loss=56501.846847807 | avg=35.241837229 | rare=0.564666052
[epoch 000000003] loss=64591.204272951 | avg=32.113467216 | rare=0.645590918
[epoch 000000004] loss=53.269861766 | avg=53.269861766 | rare=0.000000000
[epoch 000000005] loss=52.583575385 | avg=52.583575385 | rare=0.000000000
[epoch 000000006] loss=161.327069419 | avg=49.641933441 | rare=0.001116851
[epoch 000000007] loss=1308.393377032 | avg=40.603284155 | rare=0.012677901
[epoch 000000008] loss=101.752577373 | avg=49.617434093 | rare=0.000521351
[epoch 000000009] loss=3832.089442662 | avg=41.819640432 | rare=0.037902698
[epoch 000000010] loss=4789.347729274 | avg=41.966833796 | rare=0.047473807
[epoch 000000011] loss=65.907603128 | avg=65.907603128 | rare=0.000000000
[epoch 000000012] loss=69.252427237 | avg=69.252427237 | rare=0.000000000
[epoch 000000013] loss=69.587381635 | avg=69.587381635 | rare=0.000000000
[epoch 000000014] loss=69.416742052 | avg=69.416742052 | rare=0.000000000
[epoch 000000015] loss=69.192518779 | avg=69.192518779 | rare=0.000000000
[epoch 000000016] loss=69.096552713 | avg=69.096552713 | rare=0.000000000
[epoch 000000017] loss=69.062036787 | avg=69.062036787 | rare=0.000000000
[epoch 000000018] loss=68.655320304 | avg=68.655320304 | rare=0.000000000
[epoch 000000019] loss=68.519554683 | avg=68.519554683 | rare=0.000000000
[epoch 000000020] loss=68.079445430 | avg=68.079445430 | rare=0.000000000
[epoch 000000021] loss=67.916472299 | avg=67.916472299 | rare=0.000000000
[epoch 000000022] loss=67.448450906 | avg=67.448450906 | rare=0.000000000
[epoch 000000023] loss=67.117886135 | avg=67.117886135 | rare=0.000000000
[epoch 000000024] loss=66.985625131 | avg=66.985625131 | rare=0.000000000
[epoch 000000025] loss=65.255705425 | avg=65.255705425 | rare=0.000000000
[epoch 000000026] loss=6405.198434012 | avg=33.224672181 | rare=0.063719738
[epoch 000000027] loss=6808.220581055 | avg=21.922471455 | rare=0.067862980
[epoch 000000028] loss=18551.181570871 | avg=38.567209925 | rare=0.185126141
[epoch 000000029] loss=7964.167406355 | avg=21.243363721 | rare=0.079429238
[epoch 000000030] loss=5323.159236363 | avg=15.088380950 | rare=0.053080707
[epoch 000000031] loss=4813.216159276 | avg=17.395366873 | rare=0.047958207
[epoch 000000032] loss=3699.717239380 | avg=11.107006345 | rare=0.036886102
[epoch 000000033] loss=3253.159663609 | avg=12.238170964 | rare=0.032409215
[epoch 000000034] loss=4831.224155971 | avg=10.575551714 | rare=0.048206485
[epoch 000000035] loss=3918.287920271 | avg=10.556865965 | rare=0.039077311
[epoch 000000036] loss=3784.534415109 | avg=8.541554928 | rare=0.037759928
[epoch 000000037] loss=2470.073050363 | avg=9.308023896 | rare=0.024607650
[epoch 000000038] loss=4407.643327985 | avg=8.703726155 | rare=0.043989396
[epoch 000000039] loss=5882.800545829 | avg=11.201225621 | rare=0.058715993
[epoch 000000040] loss=5065.653076172 | avg=14.244762897 | rare=0.050514084
[epoch 000000041] loss=4146.353620257 | avg=12.252340794 | rare=0.041341013
[epoch 000000042] loss=5848.931413923 | avg=11.670528139 | rare=0.058372608
[epoch 000000043] loss=7582.436471122 | avg=11.092323712 | rare=0.075713443
[epoch 000000044] loss=6719.944144113 | avg=12.565331527 | rare=0.067073789
[epoch 000000045] loss=6453.822963170 | avg=10.782466957 | rare=0.064430404
[epoch 000000046] loss=5802.958897182 | avg=9.089715038 | rare=0.057938692
[epoch 000000047] loss=4999.569824219 | avg=9.255108595 | rare=0.049903147
[epoch 000000048] loss=4341.564889090 | avg=8.983528921 | rare=0.043325814
[epoch 000000049] loss=3948.654218401 | avg=9.522227117 | rare=0.039391320
[epoch 000000050] loss=5166.210274833 | avg=9.872658219 | rare=0.051563377
[epoch 000000051] loss=5658.189871652 | avg=11.348668677 | rare=0.056468412
[epoch 000000052] loss=8011.097359794 | avg=10.325517484 | rare=0.080007718
[epoch 000000053] loss=4881.744611468 | avg=11.806395190 | rare=0.048699382
[epoch 000000054] loss=5156.906014579 | avg=11.545130048 | rare=0.051453608
[epoch 000000055] loss=5967.781136649 | avg=11.189933436 | rare=0.059565912
[epoch 000000056] loss=4173.313757760 | avg=15.452732427 | rare=0.041578611
[epoch 000000057] loss=7417.874372210 | avg=11.683123623 | rare=0.074061912
[epoch 000000058] loss=6390.922014509 | avg=10.520286151 | rare=0.063804018
[epoch 000000059] loss=6174.220537458 | avg=10.445745570 | rare=0.061637748
[epoch 000000060] loss=4108.797337123 | avg=15.189754009 | rare=0.040936076
[epoch 000000061] loss=7438.867257254 | avg=11.020945617 | rare=0.074278465
[epoch 000000062] loss=5509.956368583 | avg=10.019956929 | rare=0.054999364
[epoch 000000063] loss=4125.810511998 | avg=8.739164897 | rare=0.041170714
[epoch 000000064] loss=3602.323320661 | avg=12.188327040 | rare=0.035901350
[epoch 000000065] loss=4622.215244838 | avg=13.777613844 | rare=0.046084376
[epoch 000000066] loss=5670.140642439 | avg=12.520351478 | rare=0.056576202
[epoch 000000067] loss=6464.258004325 | avg=10.953973021 | rare=0.064533039
[epoch 000000068] loss=5491.677263532 | avg=10.696419171 | rare=0.054809809
[epoch 000000069] loss=5567.915422712 | avg=11.071237019 | rare=0.055568441
[epoch 000000070] loss=5246.058837891 | avg=10.026153224 | rare=0.052360327
[epoch 000000071] loss=5827.335780552 | avg=9.037461758 | rare=0.058182984
[epoch 000000072] loss=6001.597028460 | avg=11.483469963 | rare=0.059901137
[epoch 000000073] loss=4654.676164900 | avg=9.794663089 | rare=0.046448815
[epoch 000000074] loss=4533.219656808 | avg=8.998016391 | rare=0.045242217
[epoch 000000075] loss=4504.190708705 | avg=9.169595957 | rare=0.044950211
[epoch 000000076] loss=4826.906781878 | avg=9.434918983 | rare=0.048174719
[epoch 000000077] loss=4550.682965960 | avg=9.414713587 | rare=0.045412682
[epoch 000000078] loss=5294.447579520 | avg=9.263542448 | rare=0.052851840
[epoch 000000079] loss=5353.871390206 | avg=8.734834399 | rare=0.053451366
[epoch 000000080] loss=3846.399230957 | avg=8.839148896 | rare=0.038375601
[epoch 000000081] loss=4601.226911272 | avg=11.989019019 | rare=0.045892378
[epoch 000000082] loss=6465.317452567 | avg=11.170439993 | rare=0.064541470
[epoch 000000083] loss=5952.848005022 | avg=11.474497795 | rare=0.059413734
[epoch 000000084] loss=4932.987008231 | avg=10.458700316 | rare=0.049225283
[epoch 000000085] loss=4826.953177316 | avg=9.202789681 | rare=0.048177504
[epoch 000000086] loss=4385.185930525 | avg=9.372013569 | rare=0.043758139
[epoch 000000087] loss=5105.988621303 | avg=8.638313941 | rare=0.050973503
[epoch 000000088] loss=4208.222281320 | avg=8.109145812 | rare=0.042001131
[epoch 000000089] loss=4894.806204660 | avg=8.134930066 | rare=0.048866712
[epoch 000000090] loss=5114.967799595 | avg=8.555511917 | rare=0.051064123
[epoch 000000091] loss=5056.053728376 | avg=9.347488948 | rare=0.050467063
[epoch 000000092] loss=5386.436941964 | avg=7.938483374 | rare=0.053784984
[epoch 000000093] loss=4021.211608887 | avg=10.112715619 | rare=0.040110989
[epoch 000000094] loss=6521.936872210 | avg=10.296993256 | rare=0.065116397
[epoch 000000095] loss=7221.935494559 | avg=10.078816005 | rare=0.072118567
[epoch 000000096] loss=4862.415736607 | avg=10.101078919 | rare=0.048523147
[epoch 000000097] loss=4530.294738770 | avg=9.457932711 | rare=0.045208367
[epoch 000000098] loss=3816.461443220 | avg=9.505963394 | rare=0.038069555
[epoch 000000099] loss=4786.015973772 | avg=8.737985815 | rare=0.047772781
[epoch 000000100] loss=3179.177490234 | avg=10.207223075 | rare=0.031689703
[epoch 000000101] loss=5080.259412493 | avg=10.643031870 | rare=0.050696163
[epoch 000000102] loss=6383.212315151 | avg=9.505900962 | rare=0.063737064
[epoch 000000103] loss=6921.672938756 | avg=8.734428508 | rare=0.069129385
[epoch 000000104] loss=4101.467389788 | avg=8.628985269 | rare=0.040928384
[epoch 000000105] loss=5535.517089844 | avg=9.598196779 | rare=0.055259190
[epoch 000000106] loss=7491.936558315 | avg=8.924287183 | rare=0.074830123
[epoch 000000107] loss=5258.573538644 | avg=9.768395764 | rare=0.052488051
[epoch 000000108] loss=4758.946271624 | avg=8.558663607 | rare=0.047503876
[epoch 000000109] loss=4714.967058454 | avg=8.144302743 | rare=0.047068228
[epoch 000000110] loss=5904.252301897 | avg=8.108165707 | rare=0.058961442
[epoch 000000111] loss=5567.453404018 | avg=8.418095555 | rare=0.055590353
[epoch 000000112] loss=4666.038417271 | avg=8.601042884 | rare=0.046574374
[epoch 000000113] loss=5212.819004604 | avg=8.102644478 | rare=0.052047164
[epoch 000000114] loss=4881.406529018 | avg=8.198048455 | rare=0.048732085
[epoch 000000115] loss=4532.077348982 | avg=9.013368607 | rare=0.045230640
[epoch 000000116] loss=5181.623299735 | avg=11.610920940 | rare=0.051700125
[epoch 000000117] loss=6360.434561593 | avg=11.887217385 | rare=0.063485475
[epoch 000000118] loss=5490.346269880 | avg=12.007935728 | rare=0.054783384
[epoch 000000119] loss=7032.146153041 | avg=9.545106922 | rare=0.070226010
[epoch 000000120] loss=5753.311837333 | avg=9.490629537 | rare=0.057438211
[epoch 000000121] loss=5325.533499581 | avg=9.782658713 | rare=0.053157509
[epoch 000000122] loss=5774.126377651 | avg=9.679626874 | rare=0.057644467
[epoch 000000123] loss=3965.159650530 | avg=11.031368290 | rare=0.039541282
[epoch 000000124] loss=6334.188023158 | avg=10.140594210 | rare=0.063240475
[epoch 000000125] loss=7073.924455915 | avg=9.431752137 | rare=0.070644926
[epoch 000000126] loss=5573.542166574 | avg=9.284322671 | rare=0.055642579
[epoch 000000127] loss=4528.779567174 | avg=9.552596910 | rare=0.045192270
[epoch 000000128] loss=6262.385053362 | avg=9.116833993 | rare=0.062532681
[epoch 000000129] loss=5352.457135882 | avg=10.482550757 | rare=0.053419746
[epoch 000000130] loss=6054.463797433 | avg=9.776753971 | rare=0.060446871
[epoch 000000131] loss=5679.839826311 | avg=11.792939799 | rare=0.056680469
[epoch 000000132] loss=5709.759922573 | avg=9.308046137 | rare=0.057004519
[epoch 000000133] loss=4701.946184431 | avg=9.226316248 | rare=0.046927199
[epoch 000000134] loss=4519.801775251 | avg=9.159941265 | rare=0.045106419
[epoch 000000135] loss=6050.176321847 | avg=9.485384396 | rare=0.060406910
[epoch 000000136] loss=5144.567766462 | avg=9.197841576 | rare=0.051353699
[epoch 000000137] loss=5669.291730608 | avg=8.736108507 | rare=0.056605557
[epoch 000000138] loss=4653.213553292 | avg=9.548690660 | rare=0.046436648
[epoch 000000139] loss=6008.407366071 | avg=8.931707280 | rare=0.059994758
[epoch 000000140] loss=4657.583127703 | avg=10.861139195 | rare=0.046467220
[epoch 000000141] loss=5270.631844657 | avg=11.466234105 | rare=0.052591656
[epoch 000000142] loss=6819.828037807 | avg=9.268190009 | rare=0.068105599
[epoch 000000143] loss=4389.484331403 | avg=10.656969275 | rare=0.043788274
[epoch 000000144] loss=5525.644792829 | avg=11.751499653 | rare=0.055138932
[epoch 000000145] loss=7022.015241350 | avg=12.764247213 | rare=0.070092509
[epoch 000000146] loss=5238.707327706 | avg=10.059604440 | rare=0.052286478
[epoch 000000147] loss=5691.291172573 | avg=8.697996208 | rare=0.056825932
[epoch 000000148] loss=3787.242553711 | avg=10.414847272 | rare=0.037768277
[epoch 000000149] loss=4938.930568150 | avg=9.687941619 | rare=0.049292426
[epoch 000000150] loss=4488.280548096 | avg=12.329362426 | rare=0.044759513
[epoch 000000151] loss=5341.813075474 | avg=10.010308777 | rare=0.053318028
[epoch 000000152] loss=5123.960379464 | avg=9.924474410 | rare=0.051140359
[epoch 000000153] loss=6976.137834821 | avg=8.992557934 | rare=0.069671453
[epoch 000000154] loss=5087.818777902 | avg=8.717625141 | rare=0.050791013
[epoch 000000155] loss=5960.578194754 | avg=9.030409166 | rare=0.059515476
[epoch 000000156] loss=5411.726143973 | avg=8.807729040 | rare=0.054029185
[epoch 000000157] loss=5620.180472238 | avg=8.049189738 | rare=0.056121314
[epoch 000000158] loss=4938.528355190 | avg=9.011542797 | rare=0.049295167
[epoch 000000159] loss=6482.424386161 | avg=8.819754464 | rare=0.064736046
[epoch 000000160] loss=4140.303562709 | avg=11.617532662 | rare=0.041286861
[epoch 000000161] loss=6437.220668248 | avg=9.951631001 | rare=0.064272691
[epoch 000000162] loss=7313.618547712 | avg=8.449964251 | rare=0.073051685
[epoch 000000163] loss=7096.951538086 | avg=8.737090826 | rare=0.070882145
[epoch 000000164] loss=4710.381713867 | avg=8.644343172 | rare=0.047017374
[epoch 000000165] loss=5083.931204660 | avg=8.498691763 | rare=0.050754326
[epoch 000000166] loss=4461.940403530 | avg=9.736630031 | rare=0.044522038
[epoch 000000167] loss=4834.688424247 | avg=9.123538051 | rare=0.048255650
[epoch 000000168] loss=5703.138671875 | avg=8.603355714 | rare=0.056945354
[epoch 000000169] loss=4173.931370326 | avg=9.356993777 | rare=0.041645744
[epoch 000000170] loss=6717.739510672 | avg=9.372269664 | rare=0.067083673
[epoch 000000171] loss=5896.215942383 | avg=9.899662665 | rare=0.058863163
[epoch 000000172] loss=6801.204432896 | avg=10.262638433 | rare=0.067909418
[epoch 000000173] loss=5104.873116629 | avg=10.306107521 | rare=0.050945670
[epoch 000000174] loss=4056.900826590 | avg=8.896122081 | rare=0.040480048
[epoch 000000175] loss=4648.051356724 | avg=7.840441533 | rare=0.046402109
[epoch 000000176] loss=4011.612697056 | avg=7.924134493 | rare=0.040036886
[epoch 000000177] loss=4910.795357840 | avg=8.243428911 | rare=0.049025520
[epoch 000000178] loss=5125.700526646 | avg=8.454730783 | rare=0.051172458
[epoch 000000179] loss=4894.473650251 | avg=9.329949822 | rare=0.048851437
[epoch 000000180] loss=4692.823399135 | avg=8.486755371 | rare=0.046843366
[epoch 000000181] loss=5273.930664062 | avg=8.228985548 | rare=0.052657017
[epoch 000000182] loss=5855.995064872 | avg=8.301516533 | rare=0.058476936
[epoch 000000183] loss=5174.382341657 | avg=10.202974183 | rare=0.051641793
[epoch 000000184] loss=5091.428475516 | avg=9.961357934 | rare=0.050814672
[epoch 000000185] loss=5789.959716797 | avg=8.449334281 | rare=0.057815105
[epoch 000000186] loss=4960.447492327 | avg=9.448380300 | rare=0.049509992
[epoch 000000187] loss=6165.407505580 | avg=8.458162955 | rare=0.061569494
[epoch 000000188] loss=4856.745901925 | avg=8.562798466 | rare=0.048481832
[epoch 000000189] loss=5426.049142020 | avg=8.180870533 | rare=0.054178683
[epoch 000000190] loss=4838.598301479 | avg=8.351468767 | rare=0.048302469
[epoch 000000191] loss=5334.717041016 | avg=8.423686538 | rare=0.053262934
[epoch 000000192] loss=5576.699218750 | avg=8.731953280 | rare=0.055679673
[epoch 000000193] loss=5802.417184012 | avg=8.030934674 | rare=0.057943862
[epoch 000000194] loss=4295.060224261 | avg=8.070542063 | rare=0.042869897
[epoch 000000195] loss=3724.475123814 | avg=8.195657832 | rare=0.037162795
[epoch 000000196] loss=5604.475690569 | avg=8.652120284 | rare=0.055958236
[epoch 000000197] loss=5583.533316476 | avg=9.264315094 | rare=0.055742690
[epoch 000000198] loss=5678.744070871 | avg=8.974644320 | rare=0.056697694
[epoch 000000199] loss=5341.518310547 | avg=8.849822964 | rare=0.053326684
[epoch 000000200] loss=6042.255249023 | avg=8.223765271 | rare=0.060340315
Accuracy: 36.04%  (CI 95%: [34.72%, 37.37%])
Robust Accuracy: 36.03574%  (CI 95%: [34.59018%, 37.15133%])
Conditional Robust Accuracy: 99.99952%  (CI 95%: [99.99860%, 100.00000%])
Accuracy: 82.47%  (CI 95%: [81.39%, 83.50%])
Robust Accuracy: 82.26495%  (CI 95%: [81.42529%, 83.30456%])
Conditional Robust Accuracy: 98.89950%  (CI 95%: [98.72529%, 99.06539%])
  --> Running Seed: 100

Training naive with adam...

Epochs:   0%|          | 0/200 [00:00<?, ?it/s]

[epoch 000000001] loss=178466.601562500 | avg=0.319753973 | rare=1.784662809
[epoch 000000002] loss=178522.145089286 | avg=0.320083375 | rare=1.785218264
[epoch 000000003] loss=104167.613165719 | avg=50.164770097 | rare=1.041174481
[epoch 000000004] loss=3967.238743373 | avg=1202.882899693 | rare=0.027643558
[epoch 000000005] loss=61847.649762835 | avg=832.950138637 | rare=0.610147005
[epoch 000000006] loss=4211.238821847 | avg=473.596714565 | rare=0.037376422
[epoch 000000007] loss=1195.957369123 | avg=387.649213518 | rare=0.008083082
[epoch 000000008] loss=1484.149632045 | avg=327.514593942 | rare=0.011566350
[epoch 000000009] loss=1092.638717651 | avg=297.643859863 | rare=0.007949949
[epoch 000000010] loss=1312.848318917 | avg=278.246672494 | rare=0.010346017
[epoch 000000011] loss=3217.240447998 | avg=264.616019113 | rare=0.029526244
[epoch 000000012] loss=6808.705392020 | avg=204.053250994 | rare=0.066046520
[epoch 000000013] loss=7023.861999512 | avg=116.479736873 | rare=0.069073822
[epoch 000000014] loss=13571.097935268 | avg=42.336383070 | rare=0.135287613
[epoch 000000015] loss=4537.471601214 | avg=19.542993682 | rare=0.045179286
[epoch 000000016] loss=2751.137496948 | avg=19.540130275 | rare=0.027315973
[epoch 000000017] loss=5264.106846401 | avg=22.892171451 | rare=0.052412147
[epoch 000000018] loss=2504.389610835 | avg=17.908257961 | rare=0.024864813
[epoch 000000019] loss=1838.931494577 | avg=16.290523733 | rare=0.018226410
[epoch 000000020] loss=2142.766815186 | avg=16.802143165 | rare=0.021259647
[epoch 000000021] loss=3603.121333531 | avg=18.373778684 | rare=0.035847476
[epoch 000000022] loss=3055.147495815 | avg=16.869438512 | rare=0.030382780
[epoch 000000023] loss=3509.153730120 | avg=18.385306563 | rare=0.034907685
[epoch 000000024] loss=2669.556583949 | avg=14.165237427 | rare=0.026553912
[epoch 000000025] loss=2886.049342564 | avg=10.873720237 | rare=0.028751756
[epoch 000000026] loss=1564.284887041 | avg=9.159624406 | rare=0.015551253
[epoch 000000027] loss=2509.433724540 | avg=13.622360570 | rare=0.024958113
[epoch 000000028] loss=1951.027781078 | avg=13.103340490 | rare=0.019379245
[epoch 000000029] loss=3897.478594099 | avg=11.952528136 | rare=0.038855261
[epoch 000000030] loss=1757.644744873 | avg=8.830557483 | rare=0.017488142
[epoch 000000031] loss=1143.100170680 | avg=7.393735000 | rare=0.011357064
[epoch 000000032] loss=1060.309110369 | avg=7.382463012 | rare=0.010529266
[epoch 000000033] loss=1037.801302774 | avg=6.999977078 | rare=0.010308013
[epoch 000000034] loss=739.223685128 | avg=6.403358289 | rare=0.007328203
[epoch 000000035] loss=1052.753750937 | avg=6.629329034 | rare=0.010461244
[epoch 000000036] loss=1211.301103864 | avg=8.170989956 | rare=0.012031301
[epoch 000000037] loss=520.535187857 | avg=6.714870504 | rare=0.005138203
[epoch 000000038] loss=826.761538914 | avg=7.401039634 | rare=0.008193605
[epoch 000000039] loss=969.091070993 | avg=7.644598552 | rare=0.009614465
[epoch 000000040] loss=979.273129054 | avg=8.339434181 | rare=0.009709337
[epoch 000000041] loss=1068.580498832 | avg=12.361370972 | rare=0.010562191
[epoch 000000042] loss=1465.352776664 | avg=16.195151738 | rare=0.014491576
[epoch 000000043] loss=1770.976344517 | avg=17.578855651 | rare=0.017533975
[epoch 000000044] loss=2307.978454590 | avg=13.978880269 | rare=0.022939996
[epoch 000000045] loss=2245.366317749 | avg=11.822285925 | rare=0.022335441
[epoch 000000046] loss=2778.068324498 | avg=13.763140747 | rare=0.027643052
[epoch 000000047] loss=1128.627478463 | avg=12.829938139 | rare=0.011157976
[epoch 000000048] loss=608.296501977 | avg=18.261055129 | rare=0.005900354
[epoch 000000049] loss=2776.435642787 | avg=19.352081367 | rare=0.027570835
[epoch 000000050] loss=1266.439043318 | avg=97.296491078 | rare=0.011691426
[epoch 000000051] loss=4830.392647879 | avg=79.839135306 | rare=0.047505536
[epoch 000000052] loss=2765.620439802 | avg=94.998649052 | rare=0.026706217
[epoch 000000053] loss=4022.397277832 | avg=57.166803632 | rare=0.039652305
[epoch 000000054] loss=2063.238242013 | avg=55.358688899 | rare=0.020078795
[epoch 000000055] loss=1543.841217041 | avg=58.021346773 | rare=0.014858199
[epoch 000000056] loss=999.966159821 | avg=46.603565080 | rare=0.009533626
[epoch 000000057] loss=937.427016667 | avg=19.798850604 | rare=0.009176282
[epoch 000000058] loss=340.745056970 | avg=19.798957688 | rare=0.003209461
[epoch 000000059] loss=244.466410637 | avg=18.131666728 | rare=0.002263347
[epoch 000000060] loss=199.945635387 | avg=15.685093403 | rare=0.001842605
[epoch 000000061] loss=256.358025142 | avg=14.980577333 | rare=0.002413774
[epoch 000000062] loss=188.016711916 | avg=13.214166709 | rare=0.001748025
[epoch 000000063] loss=182.412805285 | avg=12.889857905 | rare=0.001695229
[epoch 000000064] loss=156.260070801 | avg=13.346410751 | rare=0.001429137
[epoch 000000065] loss=254.855758395 | avg=14.193112714 | rare=0.002406626
[epoch 000000066] loss=234.334536689 | avg=13.975457191 | rare=0.002203591
[epoch 000000067] loss=278.692825862 | avg=13.312469619 | rare=0.002653804
[epoch 000000068] loss=252.149018969 | avg=10.746862888 | rare=0.002414022
[epoch 000000069] loss=81.659350736 | avg=12.279073511 | rare=0.000693803
[epoch 000000070] loss=108.029039928 | avg=13.375851154 | rare=0.000946532
[epoch 000000071] loss=64.650305612 | avg=13.491210120 | rare=0.000511591
[epoch 000000072] loss=109.907617569 | avg=13.281430721 | rare=0.000966262
[epoch 000000073] loss=146.172364916 | avg=12.691757134 | rare=0.001334806
[epoch 000000074] loss=96.719245366 | avg=12.661636148 | rare=0.000840576
[epoch 000000075] loss=120.052349363 | avg=13.329189982 | rare=0.001067232
[epoch 000000076] loss=140.638569423 | avg=13.703863348 | rare=0.001269347
[epoch 000000077] loss=124.068747657 | avg=13.360515186 | rare=0.001107082
[epoch 000000078] loss=115.144321033 | avg=14.073057856 | rare=0.001010713
[epoch 000000079] loss=120.469919205 | avg=13.372384276 | rare=0.001070975
[epoch 000000080] loss=148.429283142 | avg=12.859278611 | rare=0.001355700
[epoch 000000081] loss=134.234067099 | avg=13.821463721 | rare=0.001204126
[epoch 000000082] loss=131.370653697 | avg=13.442093440 | rare=0.001179286
[epoch 000000083] loss=141.563916343 | avg=13.335095542 | rare=0.001282288
[epoch 000000084] loss=97.515083858 | avg=12.959395477 | rare=0.000845557
[epoch 000000085] loss=102.276513372 | avg=13.387670926 | rare=0.000888888
[epoch 000000086] loss=95.745479584 | avg=15.012912614 | rare=0.000807326
[epoch 000000087] loss=50.437779563 | avg=15.448028088 | rare=0.000349898
[epoch 000000088] loss=46.496286801 | avg=15.279788154 | rare=0.000312165
[epoch 000000089] loss=67.337839808 | avg=14.700590270 | rare=0.000526372
[epoch 000000090] loss=73.710480009 | avg=13.907730784 | rare=0.000598028
[epoch 000000091] loss=57.066480296 | avg=13.788825853 | rare=0.000432777
[epoch 000000092] loss=59.528140068 | avg=13.495956898 | rare=0.000460322
[epoch 000000093] loss=41.895255498 | avg=12.938729082 | rare=0.000289565
[epoch 000000094] loss=46.403986250 | avg=13.097448417 | rare=0.000333065
[epoch 000000095] loss=41.291018622 | avg=12.909621443 | rare=0.000283814
[epoch 000000096] loss=64.737709045 | avg=12.666244677 | rare=0.000520715
[epoch 000000097] loss=52.019874573 | avg=12.477066857 | rare=0.000395428
[epoch 000000098] loss=35.730565344 | avg=12.295301778 | rare=0.000234353
[epoch 000000099] loss=33.528393473 | avg=12.431275572 | rare=0.000210971
[epoch 000000100] loss=60.096735273 | avg=12.055703674 | rare=0.000480410
[epoch 000000101] loss=36.595673765 | avg=11.732235568 | rare=0.000248634
[epoch 000000102] loss=257.479699952 | avg=9.613410779 | rare=0.002478663
[epoch 000000103] loss=62.177835056 | avg=5.871384076 | rare=0.000563064
[epoch 000000104] loss=117.237812860 | avg=5.544312443 | rare=0.001116935
[epoch 000000105] loss=47.350638935 | avg=6.269410678 | rare=0.000410812
[epoch 000000106] loss=91.150903497 | avg=6.463578463 | rare=0.000846873
[epoch 000000107] loss=58.565945217 | avg=6.620414700 | rare=0.000519455
[epoch 000000108] loss=122.264823437 | avg=7.298205716 | rare=0.001149666
[epoch 000000109] loss=57.127778394 | avg=9.230118241 | rare=0.000478977
[epoch 000000110] loss=66.331367084 | avg=9.749225208 | rare=0.000565821
[epoch 000000111] loss=71.078200885 | avg=9.605737993 | rare=0.000614725
[epoch 000000112] loss=128.507339478 | avg=9.896731206 | rare=0.001186106
[epoch 000000113] loss=297.228877476 | avg=11.279909985 | rare=0.002859490
[epoch 000000114] loss=230.906852722 | avg=12.693295206 | rare=0.002182136
[epoch 000000115] loss=349.842253549 | avg=13.792467799 | rare=0.003360498
[epoch 000000116] loss=125.290546009 | avg=13.776530879 | rare=0.001115140
[epoch 000000117] loss=137.056841714 | avg=13.109087024 | rare=0.001239478
[epoch 000000118] loss=119.852167538 | avg=12.794598375 | rare=0.001070576
[epoch 000000119] loss=385.363081796 | avg=14.092841012 | rare=0.003712702
[epoch 000000120] loss=205.187141827 | avg=14.865009240 | rare=0.001903221
[epoch 000000121] loss=172.967488153 | avg=13.556662219 | rare=0.001594108
[epoch 000000122] loss=140.304913112 | avg=11.810063124 | rare=0.001284948
[epoch 000000123] loss=87.442241396 | avg=10.371352128 | rare=0.000770709
[epoch 000000124] loss=49.836157935 | avg=9.731879813 | rare=0.000401043
[epoch 000000125] loss=107.027234486 | avg=9.678234441 | rare=0.000973490
[epoch 000000126] loss=46.933188438 | avg=9.706247262 | rare=0.000372269
[epoch 000000127] loss=35.595383644 | avg=9.453654698 | rare=0.000261417
[epoch 000000128] loss=45.685881070 | avg=9.520903792 | rare=0.000361650
[epoch 000000129] loss=52.366715022 | avg=9.550724302 | rare=0.000428160
[epoch 000000130] loss=32.052977017 | avg=9.354964529 | rare=0.000226980
[epoch 000000131] loss=35.090512684 | avg=9.093949352 | rare=0.000259966
[epoch 000000132] loss=19.200467927 | avg=9.077328273 | rare=0.000101231
[epoch 000000133] loss=30.167362894 | avg=9.227594818 | rare=0.000209398
[epoch 000000134] loss=36.269065380 | avg=9.242496184 | rare=0.000270266
[epoch 000000135] loss=93.882514477 | avg=9.190160070 | rare=0.000846924
[epoch 000000136] loss=76.246032306 | avg=8.071691922 | rare=0.000681743
[epoch 000000137] loss=30.666084392 | avg=6.743518148 | rare=0.000239226
[epoch 000000138] loss=110.051299572 | avg=6.299434764 | rare=0.001037519
[epoch 000000139] loss=18.212216241 | avg=4.776166763 | rare=0.000134360
[epoch 000000140] loss=15.350813150 | avg=4.393660665 | rare=0.000109572
[epoch 000000141] loss=19.884752682 | avg=4.206427029 | rare=0.000156783
[epoch 000000142] loss=10.661986726 | avg=4.211937904 | rare=0.000064500
[epoch 000000143] loss=12.508544666 | avg=4.139994366 | rare=0.000083686
[epoch 000000144] loss=18.014766557 | avg=4.049621701 | rare=0.000139651
[epoch 000000145] loss=28.296704837 | avg=4.055886967 | rare=0.000242408
[epoch 000000146] loss=17.379901818 | avg=4.277463981 | rare=0.000131024
[epoch 000000147] loss=61.354826042 | avg=4.645963584 | rare=0.000567089
[epoch 000000148] loss=15.869096552 | avg=4.859890648 | rare=0.000110092
[epoch 000000149] loss=57.275978701 | avg=4.886210918 | rare=0.000523898
[epoch 000000150] loss=41.060891628 | avg=4.592716949 | rare=0.000364682
[epoch 000000151] loss=41.841819627 | avg=4.502727951 | rare=0.000373391
[epoch 000000152] loss=16.714771986 | avg=4.451075145 | rare=0.000122637
[epoch 000000153] loss=31.726886409 | avg=4.392516698 | rare=0.000273344
[epoch 000000154] loss=19.269283192 | avg=4.205852832 | rare=0.000150634
[epoch 000000155] loss=19.817413977 | avg=4.196673206 | rare=0.000156207
[epoch 000000156] loss=32.292821271 | avg=4.239604013 | rare=0.000280532
[epoch 000000157] loss=27.605834757 | avg=4.207605413 | rare=0.000233982
[epoch 000000158] loss=11.111896447 | avg=4.192141499 | rare=0.000069198
[epoch 000000159] loss=193.052826796 | avg=4.586248994 | rare=0.001884666
[epoch 000000160] loss=336.739695515 | avg=4.421715600 | rare=0.003323180
[epoch 000000161] loss=48.866242562 | avg=1.849080128 | rare=0.000470172
[epoch 000000162] loss=124.281858470 | avg=1.429706199 | rare=0.001228522
[epoch 000000163] loss=70.799773978 | avg=1.010067391 | rare=0.000697897
[epoch 000000164] loss=1.969787627 | avg=0.760855096 | rare=0.000012089
[epoch 000000165] loss=3.528442170 | avg=0.736492217 | rare=0.000027919
[epoch 000000166] loss=2.363330854 | avg=0.723970115 | rare=0.000016394
[epoch 000000167] loss=0.907873992 | avg=0.724688883 | rare=0.000001832
[epoch 000000168] loss=1.072328346 | avg=0.730601268 | rare=0.000003417
[epoch 000000169] loss=0.783037228 | avg=0.725137276 | rare=0.000000579
[epoch 000000170] loss=0.808937166 | avg=0.725459018 | rare=0.000000835
[epoch 000000171] loss=0.787526288 | avg=0.725685618 | rare=0.000000618
[epoch 000000172] loss=0.760891199 | avg=0.725623982 | rare=0.000000353
[epoch 000000173] loss=0.765402977 | avg=0.727470581 | rare=0.000000379
[epoch 000000174] loss=0.842731868 | avg=0.728965334 | rare=0.000001138
[epoch 000000175] loss=0.755156172 | avg=0.725709779 | rare=0.000000294
[epoch 000000176] loss=0.742235942 | avg=0.728765292 | rare=0.000000135
[epoch 000000177] loss=0.958488051 | avg=0.726240137 | rare=0.000002322
[epoch 000000178] loss=0.740847634 | avg=0.727053842 | rare=0.000000138
[epoch 000000179] loss=0.796803589 | avg=0.725501103 | rare=0.000000713
[epoch 000000180] loss=0.728528700 | avg=0.725832867 | rare=0.000000027
[epoch 000000181] loss=0.949647597 | avg=0.727761618 | rare=0.000002219
[epoch 000000182] loss=0.784137223 | avg=0.724484686 | rare=0.000000597
[epoch 000000183] loss=0.776374276 | avg=0.727910591 | rare=0.000000485
[epoch 000000184] loss=0.779703166 | avg=0.727344739 | rare=0.000000524
[epoch 000000185] loss=0.842460956 | avg=0.725101109 | rare=0.000001174
[epoch 000000186] loss=0.735704631 | avg=0.725009854 | rare=0.000000107
[epoch 000000187] loss=0.762573366 | avg=0.735836421 | rare=0.000000267
[epoch 000000188] loss=0.748622166 | avg=0.724574247 | rare=0.000000240
[epoch 000000189] loss=0.738185521 | avg=0.724834080 | rare=0.000000134
[epoch 000000190] loss=0.745719109 | avg=0.724343181 | rare=0.000000214
[epoch 000000191] loss=0.831600977 | avg=0.724568065 | rare=0.000001070
[epoch 000000192] loss=0.778154995 | avg=0.725260045 | rare=0.000000529
[epoch 000000193] loss=0.748110452 | avg=0.724093186 | rare=0.000000240
[epoch 000000194] loss=0.755708733 | avg=0.723706148 | rare=0.000000320
[epoch 000000195] loss=0.780652314 | avg=0.732823844 | rare=0.000000478
[epoch 000000196] loss=0.744062603 | avg=0.725477874 | rare=0.000000186
[epoch 000000197] loss=0.752698694 | avg=0.723494117 | rare=0.000000292
[epoch 000000198] loss=0.740059257 | avg=0.726801481 | rare=0.000000133
[epoch 000000199] loss=0.769131341 | avg=0.724376768 | rare=0.000000448
[epoch 000000200] loss=0.786675470 | avg=0.723079013 | rare=0.000000636

Training safe with adam...

Epochs:   0%|          | 0/200 [00:00<?, ?it/s]

[epoch 000000001] loss=142.039022991 | avg=50.119557244 | rare=0.000919195
[epoch 000000002] loss=13588.342041561 | avg=31.888240405 | rare=0.135564540
[epoch 000000003] loss=11682.030585970 | avg=38.714081900 | rare=0.116433166
[epoch 000000004] loss=2119.920813969 | avg=53.404009819 | rare=0.020665168
[epoch 000000005] loss=324.847011566 | avg=65.827477046 | rare=0.002590195
[epoch 000000006] loss=3543.725559780 | avg=31.890360423 | rare=0.035118352
[epoch 000000007] loss=2766.587456839 | avg=32.278489658 | rare=0.027343089
[epoch 000000008] loss=1876.330692836 | avg=32.109559740 | rare=0.018442212
[epoch 000000009] loss=3489.618344988 | avg=23.852538654 | rare=0.034657657
[epoch 000000010] loss=4735.617762974 | avg=17.219476427 | rare=0.047183983
[epoch 000000011] loss=4522.731070382 | avg=13.184278079 | rare=0.045095467
[epoch 000000012] loss=5054.889299665 | avg=11.549608026 | rare=0.050433397
[epoch 000000013] loss=3781.967407227 | avg=11.149029255 | rare=0.037708184
[epoch 000000014] loss=3893.360212054 | avg=11.494019985 | rare=0.038818662
[epoch 000000015] loss=2989.040352958 | avg=10.400624616 | rare=0.029786397
[epoch 000000016] loss=3322.625034877 | avg=10.600799016 | rare=0.033120242
[epoch 000000017] loss=4306.099068778 | avg=11.233310086 | rare=0.042948658
[epoch 000000018] loss=4079.161063058 | avg=10.376319885 | rare=0.040687847
[epoch 000000019] loss=3443.434029715 | avg=9.920892852 | rare=0.034335132
[epoch 000000020] loss=4767.174700056 | avg=9.372931242 | rare=0.047578019
[epoch 000000021] loss=3789.534737723 | avg=9.145842246 | rare=0.037803889
[epoch 000000022] loss=3433.046404157 | avg=8.805594683 | rare=0.034242408
[epoch 000000023] loss=3883.182843890 | avg=9.564502886 | rare=0.038736184
[epoch 000000024] loss=4013.856968471 | avg=8.637233394 | rare=0.040052197
[epoch 000000025] loss=2954.032409668 | avg=10.097116811 | rare=0.029439353
[epoch 000000026] loss=3145.547607422 | avg=10.565735340 | rare=0.031349819
[epoch 000000027] loss=3412.856794085 | avg=9.132170405 | rare=0.034037246
[epoch 000000028] loss=3932.801696777 | avg=9.572624888 | rare=0.039232290
[epoch 000000029] loss=3633.130658831 | avg=10.852485112 | rare=0.036222781
[epoch 000000030] loss=3194.194423131 | avg=10.001919746 | rare=0.031841925
[epoch 000000031] loss=3417.127842494 | avg=8.876877240 | rare=0.034082509
[epoch 000000032] loss=3257.745143345 | avg=8.823192222 | rare=0.032489220
[epoch 000000033] loss=4236.209926060 | avg=9.451994828 | rare=0.042267579
[epoch 000000034] loss=4103.497488839 | avg=9.884250879 | rare=0.040936133
[epoch 000000035] loss=3356.695059640 | avg=11.268159253 | rare=0.033454269
[epoch 000000036] loss=4011.519566127 | avg=11.084824562 | rare=0.040004347
[epoch 000000037] loss=4460.219063895 | avg=11.571078096 | rare=0.044486480
[epoch 000000038] loss=3920.307320731 | avg=10.150782313 | rare=0.039101565
[epoch 000000039] loss=3929.796813965 | avg=9.625118324 | rare=0.039201717
[epoch 000000040] loss=3476.385995047 | avg=9.489355155 | rare=0.034668967
[epoch 000000041] loss=3548.976335798 | avg=8.997420720 | rare=0.035399789
[epoch 000000042] loss=3190.084551130 | avg=13.006954806 | rare=0.031770776
[epoch 000000043] loss=1062.966975076 | avg=25.122862952 | rare=0.010378441
[epoch 000000044] loss=2856.681993757 | avg=17.997972761 | rare=0.028386840
[epoch 000000045] loss=4735.187569754 | avg=11.266521522 | rare=0.047239211
[epoch 000000046] loss=4124.848728725 | avg=10.211971964 | rare=0.041146367
[epoch 000000047] loss=4251.873936244 | avg=9.885125501 | rare=0.042419889
[epoch 000000048] loss=3973.822910854 | avg=9.642313957 | rare=0.039641806
[epoch 000000049] loss=2878.150233677 | avg=9.648541995 | rare=0.028685017
[epoch 000000050] loss=2938.779266357 | avg=10.130205257 | rare=0.029286490
[epoch 000000051] loss=3297.957528251 | avg=10.286575011 | rare=0.032876710
[epoch 000000052] loss=4833.492274693 | avg=11.114922728 | rare=0.048223773
[epoch 000000053] loss=3920.338692801 | avg=10.292766503 | rare=0.039100459
[epoch 000000054] loss=3415.774187360 | avg=9.556716578 | rare=0.034062175
[epoch 000000055] loss=3873.451747349 | avg=9.794178826 | rare=0.038636576
[epoch 000000056] loss=3594.256138393 | avg=9.646008968 | rare=0.035846101
[epoch 000000057] loss=3914.872855050 | avg=9.031333310 | rare=0.039058415
[epoch 000000058] loss=3796.001421247 | avg=9.463690281 | rare=0.037865378
[epoch 000000059] loss=4077.633693150 | avg=9.629238742 | rare=0.040680044
[epoch 000000060] loss=3807.153224400 | avg=10.112302235 | rare=0.037970409
[epoch 000000061] loss=4041.441833496 | avg=10.033793245 | rare=0.040314080
[epoch 000000062] loss=2895.197535924 | avg=10.912579605 | rare=0.028842849
[epoch 000000063] loss=3167.900861468 | avg=9.486712251 | rare=0.031584142
[epoch 000000064] loss=3128.686628069 | avg=9.436817510 | rare=0.031192498
[epoch 000000065] loss=2912.152500698 | avg=8.525986126 | rare=0.029036265
[epoch 000000066] loss=3140.913835798 | avg=8.372441326 | rare=0.031325414
[epoch 000000067] loss=3634.349714007 | avg=8.915628774 | rare=0.036254340
[epoch 000000068] loss=3582.049700056 | avg=9.353510244 | rare=0.035726962
[epoch 000000069] loss=3823.311401367 | avg=9.426401411 | rare=0.038138850
[epoch 000000070] loss=3516.609130859 | avg=9.458234991 | rare=0.035071508
[epoch 000000071] loss=3149.925707136 | avg=10.680625064 | rare=0.031392451
[epoch 000000072] loss=4084.169642857 | avg=9.512542656 | rare=0.040746571
[epoch 000000073] loss=3687.179251535 | avg=8.916672775 | rare=0.036782625
[epoch 000000074] loss=3270.351300921 | avg=8.737963608 | rare=0.032616134
[epoch 000000075] loss=3551.413687570 | avg=9.099242313 | rare=0.035423145
[epoch 000000076] loss=3741.090253557 | avg=9.139819758 | rare=0.037319504
[epoch 000000077] loss=3766.242701939 | avg=8.995357377 | rare=0.037572474
[epoch 000000078] loss=3212.395804269 | avg=9.449994428 | rare=0.032029458
[epoch 000000079] loss=3348.665719169 | avg=10.490808964 | rare=0.033381749
[epoch 000000080] loss=3551.621791295 | avg=9.824853897 | rare=0.035417969
[epoch 000000081] loss=3027.240199498 | avg=9.594383785 | rare=0.030176458
[epoch 000000082] loss=2833.884931292 | avg=9.360126019 | rare=0.028245248
[epoch 000000083] loss=3074.070704869 | avg=10.304137775 | rare=0.030637665
[epoch 000000084] loss=4013.055716378 | avg=11.391327994 | rare=0.040016644
[epoch 000000085] loss=3757.590637207 | avg=10.111768723 | rare=0.037474789
[epoch 000000086] loss=3776.122035435 | avg=8.937191520 | rare=0.037671849
[epoch 000000087] loss=3395.608782087 | avg=8.903623274 | rare=0.033867052
[epoch 000000088] loss=3050.942007882 | avg=9.409684386 | rare=0.030415323
[epoch 000000089] loss=3570.609244210 | avg=9.333761828 | rare=0.035612755
[epoch 000000090] loss=4175.561322893 | avg=9.956023625 | rare=0.041656053
[epoch 000000091] loss=3922.013235910 | avg=9.235310793 | rare=0.039127779
[epoch 000000092] loss=3379.504900251 | avg=8.737718480 | rare=0.033707672
[epoch 000000093] loss=2960.188807896 | avg=8.752678394 | rare=0.029514362
[epoch 000000094] loss=3408.361498152 | avg=12.949864115 | rare=0.033954117
[epoch 000000095] loss=4155.534476144 | avg=14.250169822 | rare=0.041412843
[epoch 000000096] loss=3873.160173689 | avg=12.262037686 | rare=0.038608981
[epoch 000000097] loss=4035.815534319 | avg=11.141700268 | rare=0.040246738
[epoch 000000098] loss=4133.498447963 | avg=10.688421999 | rare=0.041228100
[epoch 000000099] loss=3678.141854422 | avg=9.723801545 | rare=0.036684180
[epoch 000000100] loss=3778.734279088 | avg=8.997329780 | rare=0.037697369
[epoch 000000101] loss=3844.262067522 | avg=9.782660825 | rare=0.038344793
[epoch 000000102] loss=2668.336626325 | avg=12.041018350 | rare=0.026562956
[epoch 000000103] loss=3436.992684501 | avg=10.438448702 | rare=0.034265542
[epoch 000000104] loss=3318.389125279 | avg=8.653727361 | rare=0.033097353
[epoch 000000105] loss=3374.662649972 | avg=8.746373722 | rare=0.033659163
[epoch 000000106] loss=3298.936601911 | avg=9.431686435 | rare=0.032895049
[epoch 000000107] loss=3336.695460728 | avg=9.212147576 | rare=0.033274833
[epoch 000000108] loss=3598.310285296 | avg=9.352678299 | rare=0.035889576
[epoch 000000109] loss=3723.215393066 | avg=10.065959045 | rare=0.037131494
[epoch 000000110] loss=3859.485595703 | avg=10.542583466 | rare=0.038489430
[epoch 000000111] loss=4042.822300502 | avg=9.332747255 | rare=0.040334896
[epoch 000000112] loss=3959.988298689 | avg=9.166132927 | rare=0.039508221
[epoch 000000113] loss=3023.961260114 | avg=8.937360491 | rare=0.030150239
[epoch 000000114] loss=2278.749293736 | avg=9.679221937 | rare=0.022690701
[epoch 000000115] loss=3687.381888253 | avg=8.674124513 | rare=0.036787078
[epoch 000000116] loss=3691.941371373 | avg=9.077639512 | rare=0.036828637
[epoch 000000117] loss=3042.967817034 | avg=8.495246785 | rare=0.030344725
[epoch 000000118] loss=3273.283098493 | avg=8.449402537 | rare=0.032648337
[epoch 000000119] loss=3185.281947545 | avg=8.338604314 | rare=0.031769433
[epoch 000000120] loss=3097.442426409 | avg=8.406297105 | rare=0.030890361
[epoch 000000121] loss=3104.790849958 | avg=8.775168930 | rare=0.030960157
[epoch 000000122] loss=2847.852486747 | avg=8.051067012 | rare=0.028398014
[epoch 000000123] loss=3078.302647182 | avg=8.293571574 | rare=0.030700090
[epoch 000000124] loss=3341.189243862 | avg=8.436024870 | rare=0.033327532
[epoch 000000125] loss=3852.385951451 | avg=8.328861884 | rare=0.038440571
[epoch 000000126] loss=2552.363582066 | avg=8.942377056 | rare=0.025434212
[epoch 000000127] loss=3098.455540248 | avg=8.305900131 | rare=0.030901497
[epoch 000000128] loss=3338.047973633 | avg=10.517555203 | rare=0.033275304
[epoch 000000129] loss=3445.535452706 | avg=11.156785488 | rare=0.034343787
[epoch 000000130] loss=3836.591761998 | avg=9.992186751 | rare=0.038265995
[epoch 000000131] loss=3704.809186663 | avg=9.819989817 | rare=0.036949892
[epoch 000000132] loss=4421.439679827 | avg=9.476732118 | rare=0.044119629
[epoch 000000133] loss=3356.824445452 | avg=10.381758009 | rare=0.033464427
[epoch 000000134] loss=3756.318254743 | avg=9.973283495 | rare=0.037463450
[epoch 000000135] loss=3367.636178153 | avg=8.903930051 | rare=0.033587322
[epoch 000000136] loss=3040.117501395 | avg=8.081844091 | rare=0.030320356
[epoch 000000137] loss=2723.075064523 | avg=10.491337265 | rare=0.027125837
[epoch 000000138] loss=3197.577566964 | avg=9.042761666 | rare=0.031885348
[epoch 000000139] loss=3601.571611677 | avg=8.865469694 | rare=0.035927061
[epoch 000000140] loss=2975.446367536 | avg=10.024359090 | rare=0.029654220
[epoch 000000141] loss=3272.211059570 | avg=10.259033816 | rare=0.032619520
[epoch 000000142] loss=3371.780535017 | avg=9.934682301 | rare=0.033618459
[epoch 000000143] loss=4287.512363979 | avg=9.443776744 | rare=0.042780685
[epoch 000000144] loss=3469.392970494 | avg=9.493328231 | rare=0.034598996
[epoch 000000145] loss=4303.181501116 | avg=9.837711505 | rare=0.042933438
[epoch 000000146] loss=3595.405796596 | avg=9.439902067 | rare=0.035859659
[epoch 000000147] loss=4135.539498465 | avg=8.711585522 | rare=0.041268279
[epoch 000000148] loss=4104.387207031 | avg=9.914902960 | rare=0.040944723
[epoch 000000149] loss=3735.300354004 | avg=10.131652083 | rare=0.037251687
[epoch 000000150] loss=3653.613202776 | avg=10.224154949 | rare=0.036433890
[epoch 000000151] loss=3231.732883998 | avg=10.055924075 | rare=0.032216770
[epoch 000000152] loss=3418.925144741 | avg=9.828036070 | rare=0.034090972
[epoch 000000153] loss=746.373123169 | avg=22.456707818 | rare=0.007239164
[epoch 000000154] loss=1889.386653355 | avg=21.285415377 | rare=0.018681012
[epoch 000000155] loss=3297.941057478 | avg=14.335989543 | rare=0.032836051
[epoch 000000156] loss=4437.539908273 | avg=11.757100173 | rare=0.044257828
[epoch 000000157] loss=3426.501961844 | avg=11.982830388 | rare=0.034145192
[epoch 000000158] loss=4283.954816546 | avg=10.406216485 | rare=0.042735486
[epoch 000000159] loss=3340.303737095 | avg=10.772316320 | rare=0.033295314
[epoch 000000160] loss=3278.513558524 | avg=9.441933700 | rare=0.032690717
[epoch 000000161] loss=3481.134948730 | avg=8.917025157 | rare=0.034722179
[epoch 000000162] loss=2949.837934222 | avg=9.105939252 | rare=0.029407320
[epoch 000000163] loss=3328.931553432 | avg=10.091530800 | rare=0.033188401
[epoch 000000164] loss=1997.977458409 | avg=18.912145138 | rare=0.019790653
[epoch 000000165] loss=5103.660888672 | avg=10.564410755 | rare=0.050930964
[epoch 000000166] loss=3810.917585100 | avg=9.197646243 | rare=0.038017200
[epoch 000000167] loss=3747.077061244 | avg=8.854706253 | rare=0.037382223
[epoch 000000168] loss=3125.532732282 | avg=8.927871057 | rare=0.031166048
[epoch 000000169] loss=3670.199689593 | avg=8.312441826 | rare=0.036618873
[epoch 000000170] loss=3562.781790597 | avg=10.037864753 | rare=0.035527439
[epoch 000000171] loss=3879.210083008 | avg=10.598049845 | rare=0.038686120
[epoch 000000172] loss=4443.370326451 | avg=9.816785165 | rare=0.044335536
[epoch 000000173] loss=3168.323931013 | avg=8.811861174 | rare=0.031595120
[epoch 000000174] loss=3727.067173549 | avg=8.689406906 | rare=0.037183778
[epoch 000000175] loss=2930.213082450 | avg=8.900399412 | rare=0.029213126
[epoch 000000176] loss=3591.216901507 | avg=8.429107938 | rare=0.035827878
[epoch 000000177] loss=2967.334995815 | avg=9.567418541 | rare=0.029577676
[epoch 000000178] loss=3575.541285924 | avg=9.272197281 | rare=0.035662691
[epoch 000000179] loss=2783.581856864 | avg=10.355939422 | rare=0.027732260
[epoch 000000180] loss=3234.384826660 | avg=10.019692012 | rare=0.032243651
[epoch 000000181] loss=2826.852199009 | avg=10.806172780 | rare=0.028160460
[epoch 000000182] loss=3158.408708845 | avg=10.315580913 | rare=0.031480931
[epoch 000000183] loss=3018.960527693 | avg=10.518447263 | rare=0.030084421
[epoch 000000184] loss=2917.788774763 | avg=11.728467328 | rare=0.029060603
[epoch 000000185] loss=3163.624380929 | avg=10.227234909 | rare=0.031533971
[epoch 000000186] loss=3346.673309326 | avg=9.573786463 | rare=0.033370996
[epoch 000000187] loss=3762.120666504 | avg=9.330136163 | rare=0.037527906
[epoch 000000188] loss=1682.912411826 | avg=19.959719045 | rare=0.016629527
[epoch 000000189] loss=5403.560908726 | avg=16.629269600 | rare=0.053869317
[epoch 000000190] loss=5073.648158482 | avg=11.243455069 | rare=0.050624048
[epoch 000000191] loss=2720.389386858 | avg=12.635860443 | rare=0.027077535
[epoch 000000192] loss=3108.556971959 | avg=11.793656622 | rare=0.030967634
[epoch 000000193] loss=4639.274187360 | avg=10.102776119 | rare=0.046291715
[epoch 000000194] loss=3614.713997977 | avg=10.170561927 | rare=0.036045434
[epoch 000000195] loss=3590.759218488 | avg=11.237640653 | rare=0.035795215
[epoch 000000196] loss=3959.393048968 | avg=9.965628215 | rare=0.039494274
[epoch 000000197] loss=3882.051722935 | avg=9.272074291 | rare=0.038727797
[epoch 000000198] loss=3949.742170061 | avg=9.546076400 | rare=0.039401960
[epoch 000000199] loss=3626.134556362 | avg=9.648760830 | rare=0.036164858
[epoch 000000200] loss=2873.606009347 | avg=8.400084019 | rare=0.028652060
Accuracy: 64.06%  (CI 95%: [62.73%, 65.38%])
Robust Accuracy: 64.06262%  (CI 95%: [62.94050%, 65.50584%])
Conditional Robust Accuracy: 99.99567%  (CI 95%: [99.98702%, 100.00000%])
Accuracy: 79.68%  (CI 95%: [78.55%, 80.77%])
Robust Accuracy: 79.72273%  (CI 95%: [78.78666%, 80.81973%])
Conditional Robust Accuracy: 99.32920%  (CI 95%: [99.18501%, 99.46335%])

#################### lr: 0.01 ####################
  --> Running Seed: 42

Training naive with adam...

Epochs:   0%|          | 0/200 [00:00<?, ?it/s]

[epoch 000000001] loss=178608.407366071 | avg=0.319726129 | rare=1.786080871
[epoch 000000002] loss=178494.834821429 | avg=0.319935188 | rare=1.784945164
[epoch 000000003] loss=104795.570992606 | avg=3.910786814 | rare=1.047916578
[epoch 000000004] loss=12393.249720982 | avg=8.914255006 | rare=0.123843356
[epoch 000000005] loss=4227.331717355 | avg=7.897439275 | rare=0.042194343
[epoch 000000006] loss=2347.145315988 | avg=7.733521666 | rare=0.023394118
[epoch 000000007] loss=2950.772142683 | avg=6.005869252 | rare=0.029447663
[epoch 000000008] loss=3111.410888672 | avg=4.965868950 | rare=0.031064451
[epoch 000000009] loss=5712.361014230 | avg=3.484839133 | rare=0.057088762
[epoch 000000010] loss=4185.154471261 | avg=3.102424690 | rare=0.041820520
[epoch 000000011] loss=3403.459943499 | avg=3.132662416 | rare=0.034003272
[epoch 000000012] loss=3200.876360212 | avg=2.543915187 | rare=0.031983324
[epoch 000000013] loss=2377.729178292 | avg=2.335654335 | rare=0.023753935
[epoch 000000014] loss=2329.048871722 | avg=2.148878379 | rare=0.023269000
[epoch 000000015] loss=1723.211290632 | avg=1.962589221 | rare=0.017212487
[epoch 000000016] loss=1409.250601632 | avg=1.819509217 | rare=0.014074311
[epoch 000000017] loss=1486.260437012 | avg=1.415038411 | rare=0.014848454
[epoch 000000018] loss=1154.785361154 | avg=1.276668668 | rare=0.011535087
[epoch 000000019] loss=947.741891044 | avg=1.044893567 | rare=0.009466970
[epoch 000000020] loss=788.216249738 | avg=1.106902697 | rare=0.007871093
[epoch 000000021] loss=670.837593079 | avg=1.156153977 | rare=0.006696814
[epoch 000000022] loss=937.756243025 | avg=1.161519817 | rare=0.009365947
[epoch 000000023] loss=611.773843493 | avg=4.464844142 | rare=0.006073090
[epoch 000000024] loss=1625.207907540 | avg=3.187097907 | rare=0.016220208
[epoch 000000025] loss=685.625534058 | avg=5.725349111 | rare=0.006799002
[epoch 000000026] loss=1597.365887778 | avg=3.545144660 | rare=0.015938208
[epoch 000000027] loss=3146.014517648 | avg=1.922128081 | rare=0.031440924
[epoch 000000028] loss=2150.091029576 | avg=1.556869183 | rare=0.021485342
[epoch 000000029] loss=1542.905164446 | avg=1.278766849 | rare=0.015416264
[epoch 000000030] loss=961.634861537 | avg=1.027069024 | rare=0.009606078
[epoch 000000031] loss=835.312162127 | avg=0.931105154 | rare=0.008343811
[epoch 000000032] loss=708.477438790 | avg=1.127860550 | rare=0.007073496
[epoch 000000033] loss=895.731994629 | avg=1.015931032 | rare=0.008947161
[epoch 000000034] loss=675.744740077 | avg=0.940885148 | rare=0.006748039
[epoch 000000035] loss=716.999088832 | avg=0.853394423 | rare=0.007161457
[epoch 000000036] loss=594.410180228 | avg=0.861380556 | rare=0.005935488
[epoch 000000037] loss=634.856765747 | avg=0.998725201 | rare=0.006338580
[epoch 000000038] loss=762.118297032 | avg=1.013347800 | rare=0.007611050
[epoch 000000039] loss=474.857424055 | avg=1.004101813 | rare=0.004738533
[epoch 000000040] loss=679.583529881 | avg=0.904843739 | rare=0.006786787
[epoch 000000041] loss=550.080106463 | avg=0.975130345 | rare=0.005491050
[epoch 000000042] loss=692.753574916 | avg=0.828794794 | rare=0.006919248
[epoch 000000043] loss=565.465659005 | avg=0.992106910 | rare=0.005644736
[epoch 000000044] loss=581.934247698 | avg=0.811234747 | rare=0.005811230
[epoch 000000045] loss=595.379333496 | avg=0.807610559 | rare=0.005945717
[epoch 000000046] loss=532.380467006 | avg=0.789266505 | rare=0.005315912
[epoch 000000047] loss=545.097381592 | avg=0.803420105 | rare=0.005442940
[epoch 000000048] loss=599.507917132 | avg=0.794999970 | rare=0.005987129
[epoch 000000049] loss=534.625061035 | avg=0.919630357 | rare=0.005337054
[epoch 000000050] loss=580.412365505 | avg=0.889461624 | rare=0.005795229
[epoch 000000051] loss=640.843106951 | avg=0.840643695 | rare=0.006400025
[epoch 000000052] loss=675.814777919 | avg=0.844883306 | rare=0.006749699
[epoch 000000053] loss=704.474049159 | avg=1.527685259 | rare=0.007029464
[epoch 000000054] loss=765.505449568 | avg=1.388160867 | rare=0.007641173
[epoch 000000055] loss=839.855695452 | avg=1.110676289 | rare=0.008387450
[epoch 000000056] loss=690.053405762 | avg=1.073170189 | rare=0.006889802
[epoch 000000057] loss=745.018284389 | avg=1.067425749 | rare=0.007439509
[epoch 000000058] loss=808.702032907 | avg=0.900020812 | rare=0.008078020
[epoch 000000059] loss=741.475862776 | avg=1.023798845 | rare=0.007404521
[epoch 000000060] loss=938.349068778 | avg=0.975423851 | rare=0.009373736
[epoch 000000061] loss=697.197333200 | avg=0.841812981 | rare=0.006963555
[epoch 000000062] loss=591.880805969 | avg=0.843416618 | rare=0.005910374
[epoch 000000063] loss=595.142427717 | avg=0.847761227 | rare=0.005942947
[epoch 000000064] loss=670.785171509 | avg=0.744892342 | rare=0.006700403
[epoch 000000065] loss=565.985765730 | avg=0.758378097 | rare=0.005652274
[epoch 000000066] loss=505.924404689 | avg=0.730142257 | rare=0.005051943
[epoch 000000067] loss=503.221076965 | avg=0.737293725 | rare=0.005024838
[epoch 000000068] loss=402.720178332 | avg=0.756423584 | rare=0.004019638
[epoch 000000069] loss=495.673605783 | avg=0.700022255 | rare=0.004949736
[epoch 000000070] loss=538.337681362 | avg=0.656141392 | rare=0.005376815
[epoch 000000071] loss=450.210942950 | avg=0.680774254 | rare=0.004495302
[epoch 000000072] loss=427.054733276 | avg=0.684662730 | rare=0.004263701
[epoch 000000073] loss=420.938496181 | avg=0.683628376 | rare=0.004202549
[epoch 000000074] loss=424.807740348 | avg=0.626575402 | rare=0.004241812
[epoch 000000075] loss=478.831158229 | avg=0.723782786 | rare=0.004781074
[epoch 000000076] loss=571.358074733 | avg=0.830071879 | rare=0.005705280
[epoch 000000077] loss=670.478912354 | avg=0.675366683 | rare=0.006698035
[epoch 000000078] loss=469.654872349 | avg=0.666637957 | rare=0.004689882
[epoch 000000079] loss=427.294841221 | avg=0.649593226 | rare=0.004266452
[epoch 000000080] loss=562.762922015 | avg=0.678771717 | rare=0.005620842
[epoch 000000081] loss=571.972003392 | avg=0.608020778 | rare=0.005713640
[epoch 000000082] loss=406.965769087 | avg=0.626937372 | rare=0.004063388
[epoch 000000083] loss=439.010737828 | avg=0.673461882 | rare=0.004383373
[epoch 000000084] loss=439.645274571 | avg=0.612616995 | rare=0.004390327
[epoch 000000085] loss=457.656835284 | avg=0.612090643 | rare=0.004570447
[epoch 000000086] loss=464.821308681 | avg=0.606852493 | rare=0.004642145
[epoch 000000087] loss=441.373774937 | avg=0.605119428 | rare=0.004407687
[epoch 000000088] loss=437.251502991 | avg=0.635624566 | rare=0.004366159
[epoch 000000089] loss=450.085814340 | avg=0.662166868 | rare=0.004494236
[epoch 000000090] loss=530.673210144 | avg=0.606230284 | rare=0.005300670
[epoch 000000091] loss=447.821943011 | avg=0.581325948 | rare=0.004472406
[epoch 000000092] loss=482.125235421 | avg=0.581506699 | rare=0.004815437
[epoch 000000093] loss=401.742730822 | avg=0.584400858 | rare=0.004011583
[epoch 000000094] loss=523.679090227 | avg=0.558732899 | rare=0.005231204
[epoch 000000095] loss=374.360341753 | avg=0.601615395 | rare=0.003737587
[epoch 000000096] loss=502.204395839 | avg=0.579543714 | rare=0.005016248
[epoch 000000097] loss=419.920297895 | avg=0.613404240 | rare=0.004193069
[epoch 000000098] loss=475.753554208 | avg=0.602220344 | rare=0.004751513
[epoch 000000099] loss=462.398944310 | avg=0.565222725 | rare=0.004618337
[epoch 000000100] loss=373.107595171 | avg=0.583066172 | rare=0.003725245
[epoch 000000101] loss=457.193361555 | avg=0.595198478 | rare=0.004565981
[epoch 000000102] loss=407.925489153 | avg=0.585451392 | rare=0.004073400
[epoch 000000103] loss=421.661796570 | avg=0.601792761 | rare=0.004210600
[epoch 000000104] loss=432.669493539 | avg=0.588682315 | rare=0.004320808
[epoch 000000105] loss=348.919945853 | avg=0.566956179 | rare=0.003483530
[epoch 000000106] loss=414.632965088 | avg=0.548441233 | rare=0.004140845
[epoch 000000107] loss=385.596876962 | avg=0.562494804 | rare=0.003850344
[epoch 000000108] loss=427.346280779 | avg=0.537374088 | rare=0.004268089
[epoch 000000109] loss=384.404187884 | avg=0.531186430 | rare=0.003838730
[epoch 000000110] loss=355.804800306 | avg=0.552234441 | rare=0.003552526
[epoch 000000111] loss=351.461671012 | avg=0.546541306 | rare=0.003509151
[epoch 000000112] loss=475.322764805 | avg=0.527593966 | rare=0.004747952
[epoch 000000113] loss=394.564020429 | avg=0.571229081 | rare=0.003939928
[epoch 000000114] loss=356.865568978 | avg=0.535843547 | rare=0.003563297
[epoch 000000115] loss=327.205555507 | avg=0.508307374 | rare=0.003266972
[epoch 000000116] loss=365.278358459 | avg=0.536097646 | rare=0.003647423
[epoch 000000117] loss=387.360421317 | avg=0.546338660 | rare=0.003868141
[epoch 000000118] loss=357.655313764 | avg=0.553567180 | rare=0.003571017
[epoch 000000119] loss=339.045193263 | avg=0.539538420 | rare=0.003385057
[epoch 000000120] loss=409.954722813 | avg=0.501480816 | rare=0.004094532
[epoch 000000121] loss=310.955865043 | avg=0.502620263 | rare=0.003104532
[epoch 000000122] loss=331.398852757 | avg=0.506425581 | rare=0.003308924
[epoch 000000123] loss=300.619617462 | avg=0.516148542 | rare=0.003001035
[epoch 000000124] loss=274.384785243 | avg=0.515211146 | rare=0.002738696
[epoch 000000125] loss=322.848967416 | avg=0.517254932 | rare=0.003223317
[epoch 000000126] loss=301.017201015 | avg=0.524380841 | rare=0.003004928
[epoch 000000127] loss=369.736583165 | avg=0.503517749 | rare=0.003692331
[epoch 000000128] loss=349.871227809 | avg=0.595524371 | rare=0.003492757
[epoch 000000129] loss=398.590305873 | avg=0.526923880 | rare=0.003980634
[epoch 000000130] loss=335.246341160 | avg=0.510598615 | rare=0.003347357
[epoch 000000131] loss=280.859851292 | avg=0.512795808 | rare=0.002803471
[epoch 000000132] loss=378.135374887 | avg=0.509604816 | rare=0.003776258
[epoch 000000133] loss=248.450355530 | avg=0.497435687 | rare=0.002479529
[epoch 000000134] loss=293.221814837 | avg=0.493486360 | rare=0.002927283
[epoch 000000135] loss=241.161416190 | avg=0.502900315 | rare=0.002406585
[epoch 000000136] loss=311.430518014 | avg=0.494667685 | rare=0.003109358
[epoch 000000137] loss=248.747206007 | avg=0.497063030 | rare=0.002482501
[epoch 000000138] loss=356.443897792 | avg=0.479117317 | rare=0.003559648
[epoch 000000139] loss=283.217921666 | avg=0.483723051 | rare=0.002827342
[epoch 000000140] loss=307.568857465 | avg=0.499445511 | rare=0.003070694
[epoch 000000141] loss=258.521229335 | avg=0.517659253 | rare=0.002580036
[epoch 000000142] loss=342.331605094 | avg=0.515117662 | rare=0.003418165
[epoch 000000143] loss=304.613727025 | avg=0.522019748 | rare=0.003040917
[epoch 000000144] loss=251.289615086 | avg=0.495020128 | rare=0.002507946
[epoch 000000145] loss=253.792522975 | avg=0.485248862 | rare=0.002533073
[epoch 000000146] loss=259.085638864 | avg=0.481228379 | rare=0.002586044
[epoch 000000147] loss=289.735565186 | avg=0.487975180 | rare=0.002892476
[epoch 000000148] loss=250.855775016 | avg=0.478892686 | rare=0.002503769
[epoch 000000149] loss=266.275219509 | avg=0.501888420 | rare=0.002657733
[epoch 000000150] loss=275.187646048 | avg=0.497066581 | rare=0.002746906
[epoch 000000151] loss=271.804920741 | avg=0.480104804 | rare=0.002713248
[epoch 000000152] loss=250.509517125 | avg=0.474204617 | rare=0.002500353
[epoch 000000153] loss=294.278057643 | avg=0.472040734 | rare=0.002938060
[epoch 000000154] loss=244.768738338 | avg=0.480304622 | rare=0.002442884
[epoch 000000155] loss=264.634039743 | avg=0.483901926 | rare=0.002641501
[epoch 000000156] loss=280.987530300 | avg=0.467967906 | rare=0.002805196
[epoch 000000157] loss=258.457967486 | avg=0.476775059 | rare=0.002579812
[epoch 000000158] loss=297.913930620 | avg=0.466455875 | rare=0.002974475
[epoch 000000159] loss=221.312933786 | avg=0.494711857 | rare=0.002208182
[epoch 000000160] loss=248.501908439 | avg=0.473502894 | rare=0.002480284
[epoch 000000161] loss=252.613249643 | avg=0.464577794 | rare=0.002521487
[epoch 000000162] loss=273.367148263 | avg=0.462679561 | rare=0.002729045
[epoch 000000163] loss=210.415798187 | avg=0.463282792 | rare=0.002099525
[epoch 000000164] loss=210.031466893 | avg=0.481877161 | rare=0.002095496
[epoch 000000165] loss=283.347087315 | avg=0.485583337 | rare=0.002828615
[epoch 000000166] loss=275.644033704 | avg=0.522081428 | rare=0.002751220
[epoch 000000167] loss=293.477171762 | avg=0.480266241 | rare=0.002929969
[epoch 000000168] loss=247.296974182 | avg=0.513145651 | rare=0.002467838
[epoch 000000169] loss=284.329517909 | avg=0.513851219 | rare=0.002838157
[epoch 000000170] loss=223.092048645 | avg=0.529556817 | rare=0.002225625
[epoch 000000171] loss=257.578920637 | avg=0.504901722 | rare=0.002570740
[epoch 000000172] loss=228.510117122 | avg=0.502155136 | rare=0.002280080
[epoch 000000173] loss=239.246828352 | avg=0.509055314 | rare=0.002387378
[epoch 000000174] loss=308.465291704 | avg=0.510088084 | rare=0.003079552
[epoch 000000175] loss=234.684749058 | avg=0.493924333 | rare=0.002341908
[epoch 000000176] loss=211.770797729 | avg=0.487766230 | rare=0.002112830
[epoch 000000177] loss=233.844009399 | avg=0.511058916 | rare=0.002333330
[epoch 000000178] loss=276.190781730 | avg=0.488229055 | rare=0.002757026
[epoch 000000179] loss=213.456751687 | avg=0.508766472 | rare=0.002129480
[epoch 000000180] loss=269.277196067 | avg=0.494762380 | rare=0.002687824
[epoch 000000181] loss=286.602812631 | avg=0.488674396 | rare=0.002861141
[epoch 000000182] loss=235.746617453 | avg=0.487497494 | rare=0.002352591
[epoch 000000183] loss=205.781350817 | avg=0.486261306 | rare=0.002052951
[epoch 000000184] loss=260.328298296 | avg=0.486966744 | rare=0.002598413
[epoch 000000185] loss=261.527808053 | avg=0.490387957 | rare=0.002610374
[epoch 000000186] loss=221.911350250 | avg=0.474569953 | rare=0.002214368
[epoch 000000187] loss=222.236567906 | avg=0.489820559 | rare=0.002217467
[epoch 000000188] loss=279.909971510 | avg=0.499850060 | rare=0.002794101
[epoch 000000189] loss=299.130882263 | avg=0.482650133 | rare=0.002986482
[epoch 000000190] loss=232.147384644 | avg=0.500723115 | rare=0.002316467
[epoch 000000191] loss=246.989410400 | avg=0.479610569 | rare=0.002465098
[epoch 000000192] loss=243.036676679 | avg=0.473396659 | rare=0.002425633
[epoch 000000193] loss=217.539672852 | avg=0.479761999 | rare=0.002170599
[epoch 000000194] loss=227.269687653 | avg=0.466307555 | rare=0.002268034
[epoch 000000195] loss=199.708324432 | avg=0.477626596 | rare=0.001992307
[epoch 000000196] loss=213.741710663 | avg=0.474180709 | rare=0.002132675
[epoch 000000197] loss=266.345078060 | avg=0.471164141 | rare=0.002658739
[epoch 000000198] loss=288.004094260 | avg=0.501564515 | rare=0.002875025
[epoch 000000199] loss=247.562320164 | avg=0.479551220 | rare=0.002470828
[epoch 000000200] loss=249.881024497 | avg=0.479414391 | rare=0.002494016

Training safe with adam...

Epochs:   0%|          | 0/200 [00:00<?, ?it/s]

[epoch 000000001] loss=142.110842296 | avg=49.984584263 | rare=0.000921263
[epoch 000000002] loss=302.208787373 | avg=45.341320038 | rare=0.002568675
[epoch 000000003] loss=10644.672074999 | avg=30.105848994 | rare=0.106145663
[epoch 000000004] loss=13250.056030273 | avg=18.243470328 | rare=0.132318125
[epoch 000000005] loss=10148.659702846 | avg=13.713040556 | rare=0.101349467
[epoch 000000006] loss=7646.935232980 | avg=11.002566542 | rare=0.076359327
[epoch 000000007] loss=5695.051688058 | avg=8.743644135 | rare=0.056863081
[epoch 000000008] loss=4928.056902204 | avg=8.707561391 | rare=0.049193494
[epoch 000000009] loss=4400.881513323 | avg=8.553171737 | rare=0.043923284
[epoch 000000010] loss=5296.356061663 | avg=8.157447372 | rare=0.052881986
[epoch 000000011] loss=4241.127641950 | avg=8.459463937 | rare=0.042326682
[epoch 000000012] loss=3697.447431292 | avg=9.144278628 | rare=0.036883033
[epoch 000000013] loss=5368.402954102 | avg=8.487787076 | rare=0.053599153
[epoch 000000014] loss=4075.532366071 | avg=8.637692349 | rare=0.040668947
[epoch 000000015] loss=3624.665021624 | avg=8.593392338 | rare=0.036160717
[epoch 000000016] loss=4090.791521345 | avg=7.944996629 | rare=0.040828466
[epoch 000000017] loss=4639.128313337 | avg=8.579023974 | rare=0.046305493
[epoch 000000018] loss=4716.892926897 | avg=7.974021230 | rare=0.047089188
[epoch 000000019] loss=4163.487200056 | avg=8.020161186 | rare=0.041554670
[epoch 000000020] loss=4309.869594029 | avg=8.396384920 | rare=0.043014732
[epoch 000000021] loss=5549.184483119 | avg=7.786329133 | rare=0.055413982
[epoch 000000022] loss=4560.966587612 | avg=7.629922356 | rare=0.045533367
[epoch 000000023] loss=4778.581804548 | avg=7.576683862 | rare=0.047710050
[epoch 000000024] loss=5074.599155971 | avg=8.140760422 | rare=0.050664585
[epoch 000000025] loss=4255.976353237 | avg=7.583588498 | rare=0.042483928
[epoch 000000026] loss=4554.295026507 | avg=7.745383092 | rare=0.045465497
[epoch 000000027] loss=4735.315272740 | avg=7.343836921 | rare=0.047279714
[epoch 000000028] loss=4460.308768136 | avg=7.750363486 | rare=0.044525583
[epoch 000000029] loss=3528.420615060 | avg=8.186509575 | rare=0.035202341
[epoch 000000030] loss=3948.998674665 | avg=8.239922592 | rare=0.039407588
[epoch 000000031] loss=4355.620849609 | avg=7.885478565 | rare=0.043477353
[epoch 000000032] loss=4772.103846959 | avg=7.540798085 | rare=0.047645631
[epoch 000000033] loss=4960.746093750 | avg=7.658172641 | rare=0.049530879
[epoch 000000034] loss=5290.673950195 | avg=7.372064454 | rare=0.052833018
[epoch 000000035] loss=4308.337489537 | avg=7.964619875 | rare=0.043003729
[epoch 000000036] loss=4529.985299247 | avg=8.066367422 | rare=0.045219189
[epoch 000000037] loss=4778.061383929 | avg=8.074078492 | rare=0.047699873
[epoch 000000038] loss=4933.651123047 | avg=7.364166566 | rare=0.049262870
[epoch 000000039] loss=5544.108537946 | avg=7.179171732 | rare=0.055369294
[epoch 000000040] loss=4755.471139090 | avg=7.517584767 | rare=0.047479535
[epoch 000000041] loss=5042.377197266 | avg=7.266205141 | rare=0.050351111
[epoch 000000042] loss=5063.502598354 | avg=7.854442596 | rare=0.050556482
[epoch 000000043] loss=4721.685668945 | avg=8.425479991 | rare=0.047132602
[epoch 000000044] loss=4376.138392857 | avg=7.218887363 | rare=0.043689195
[epoch 000000045] loss=4164.213797433 | avg=7.053598847 | rare=0.041571602
[epoch 000000046] loss=4174.596435547 | avg=7.033126729 | rare=0.041675633
[epoch 000000047] loss=4526.290492467 | avg=7.275951692 | rare=0.045190146
[epoch 000000048] loss=4312.195905413 | avg=7.231079783 | rare=0.043049649
[epoch 000000049] loss=4040.251229422 | avg=7.588159834 | rare=0.040326630
[epoch 000000050] loss=4858.291564941 | avg=7.736436605 | rare=0.048505551
[epoch 000000051] loss=3729.696114676 | avg=7.275981631 | rare=0.037224201
[epoch 000000052] loss=5072.907741002 | avg=7.687208482 | rare=0.050652205
[epoch 000000053] loss=4578.594665527 | avg=7.902357953 | rare=0.045706924
[epoch 000000054] loss=4120.588509696 | avg=8.483932870 | rare=0.041121045
[epoch 000000055] loss=3918.698303223 | avg=8.134633575 | rare=0.039105636
[epoch 000000056] loss=4696.950282506 | avg=7.639035089 | rare=0.046893112
[epoch 000000057] loss=4370.849278041 | avg=8.040977444 | rare=0.043628082
[epoch 000000058] loss=4369.368268694 | avg=7.389959029 | rare=0.043619783
[epoch 000000059] loss=4878.366106306 | avg=7.070268495 | rare=0.048712958
[epoch 000000060] loss=4849.483084542 | avg=6.958200353 | rare=0.048425249
[epoch 000000061] loss=5355.016374860 | avg=6.981915406 | rare=0.053480344
[epoch 000000062] loss=4418.316057478 | avg=6.911087683 | rare=0.044114050
[epoch 000000063] loss=4864.858973912 | avg=6.702016660 | rare=0.048581569
[epoch 000000064] loss=4248.785871233 | avg=7.933695998 | rare=0.042408522
[epoch 000000065] loss=4642.981811523 | avg=7.674419369 | rare=0.046353073
[epoch 000000066] loss=4248.745605469 | avg=7.736094577 | rare=0.042410095
[epoch 000000067] loss=5251.680140904 | avg=7.753151315 | rare=0.052439270
[epoch 000000068] loss=4672.464808873 | avg=7.210489375 | rare=0.046652544
[epoch 000000069] loss=4916.084123884 | avg=7.434384448 | rare=0.049086497
[epoch 000000070] loss=5020.263305664 | avg=7.215948752 | rare=0.050130474
[epoch 000000071] loss=4417.188371931 | avg=7.326444762 | rare=0.044098619
[epoch 000000072] loss=4524.558959961 | avg=7.123556580 | rare=0.045174354
[epoch 000000073] loss=4427.949183873 | avg=7.055836780 | rare=0.044208933
[epoch 000000074] loss=4991.960344587 | avg=6.946665287 | rare=0.049850136
[epoch 000000075] loss=4291.288800921 | avg=7.345822777 | rare=0.042839430
[epoch 000000076] loss=5317.761805943 | avg=7.208671093 | rare=0.053105531
[epoch 000000077] loss=4749.332676479 | avg=7.142479590 | rare=0.047421902
[epoch 000000078] loss=4868.824148996 | avg=6.996985470 | rare=0.048618271
[epoch 000000079] loss=4705.821341378 | avg=7.081079415 | rare=0.046987402
[epoch 000000080] loss=5001.227975028 | avg=6.822636025 | rare=0.049944053
[epoch 000000081] loss=4902.128365653 | avg=7.871370452 | rare=0.048942570
[epoch 000000082] loss=3587.592119489 | avg=7.129442181 | rare=0.035804627
[epoch 000000083] loss=5019.051740374 | avg=6.835646221 | rare=0.050122161
[epoch 000000084] loss=4218.138270787 | avg=7.047056130 | rare=0.042110912
[epoch 000000085] loss=4701.563084194 | avg=7.593211276 | rare=0.046939698
[epoch 000000086] loss=3511.513889858 | avg=8.763502189 | rare=0.035027504
[epoch 000000087] loss=4360.917061942 | avg=7.282917534 | rare=0.043536340
[epoch 000000088] loss=5096.132568359 | avg=6.691137484 | rare=0.050894414
[epoch 000000089] loss=4676.862095424 | avg=6.875861270 | rare=0.046699863
[epoch 000000090] loss=4415.629220145 | avg=6.812530654 | rare=0.044088167
[epoch 000000091] loss=4503.119035993 | avg=6.956042801 | rare=0.044961630
[epoch 000000092] loss=4405.524815151 | avg=6.717113904 | rare=0.043988076
[epoch 000000093] loss=4121.515799386 | avg=6.845092263 | rare=0.041146707
[epoch 000000094] loss=5064.169677734 | avg=6.585098369 | rare=0.050575846
[epoch 000000095] loss=3200.159702846 | avg=7.547561066 | rare=0.031926122
[epoch 000000096] loss=3886.499476842 | avg=6.699523960 | rare=0.038797999
[epoch 000000097] loss=4829.572283064 | avg=6.910357543 | rare=0.048226619
[epoch 000000098] loss=5178.067853655 | avg=7.063082388 | rare=0.051710047
[epoch 000000099] loss=4786.294032506 | avg=7.449249744 | rare=0.047788448
[epoch 000000100] loss=3556.680873326 | avg=6.859124626 | rare=0.035498217
[epoch 000000101] loss=5096.964041574 | avg=6.778952735 | rare=0.050901851
[epoch 000000102] loss=3480.080897740 | avg=6.963054180 | rare=0.034731179
[epoch 000000103] loss=4834.540396554 | avg=6.745463712 | rare=0.048277950
[epoch 000000104] loss=4367.982857840 | avg=7.113189220 | rare=0.043608698
[epoch 000000105] loss=4712.230521066 | avg=6.835825375 | rare=0.047053946
[epoch 000000106] loss=4613.868425642 | avg=6.650456939 | rare=0.046072180
[epoch 000000107] loss=4480.441231864 | avg=6.703694548 | rare=0.044737376
[epoch 000000108] loss=4112.028390067 | avg=6.661019768 | rare=0.041053673
[epoch 000000109] loss=4267.658743722 | avg=6.830931323 | rare=0.042608278
[epoch 000000110] loss=4174.741524833 | avg=6.294406925 | rare=0.041684471
[epoch 000000111] loss=5608.762224470 | avg=7.039018801 | rare=0.056017231
[epoch 000000112] loss=3719.504193987 | avg=6.834815809 | rare=0.037126693
[epoch 000000113] loss=4531.461791992 | avg=6.724742992 | rare=0.045247370
[epoch 000000114] loss=4656.394670759 | avg=6.513096196 | rare=0.046498815
[epoch 000000115] loss=4928.589442662 | avg=7.516103915 | rare=0.049210734
[epoch 000000116] loss=4832.787789481 | avg=7.208299092 | rare=0.048255794
[epoch 000000117] loss=4319.028599330 | avg=6.703375919 | rare=0.043123252
[epoch 000000118] loss=3956.349522182 | avg=6.887793984 | rare=0.039494617
[epoch 000000119] loss=6068.288068499 | avg=6.819575548 | rare=0.060614684
[epoch 000000120] loss=4205.383108956 | avg=7.061586755 | rare=0.041983215
[epoch 000000121] loss=4685.107195173 | avg=6.915983643 | rare=0.046781913
[epoch 000000122] loss=4617.219543457 | avg=6.599439621 | rare=0.046106201
[epoch 000000123] loss=4666.531729562 | avg=6.540228537 | rare=0.046599916
[epoch 000000124] loss=4383.038051060 | avg=6.809537070 | rare=0.043762285
[epoch 000000125] loss=4659.993617467 | avg=6.981468882 | rare=0.046530122
[epoch 000000126] loss=4294.535714286 | avg=7.211471047 | rare=0.042873242
[epoch 000000127] loss=4041.631905692 | avg=6.562675510 | rare=0.040350692
[epoch 000000128] loss=3461.840593610 | avg=6.751704795 | rare=0.034550889
[epoch 000000129] loss=4315.852312360 | avg=6.734987804 | rare=0.043091173
[epoch 000000130] loss=5031.304024833 | avg=7.059125321 | rare=0.050242449
[epoch 000000131] loss=3952.028267997 | avg=6.827986411 | rare=0.039452003
[epoch 000000132] loss=4308.793230329 | avg=7.008127723 | rare=0.043017851
[epoch 000000133] loss=5565.834507533 | avg=7.085263968 | rare=0.055587493
[epoch 000000134] loss=3479.865740095 | avg=7.297066314 | rare=0.034725687
[epoch 000000135] loss=4477.721226283 | avg=6.914461817 | rare=0.044708068
[epoch 000000136] loss=3419.273995536 | avg=6.837890080 | rare=0.034124361
[epoch 000000137] loss=5088.905186244 | avg=6.574499266 | rare=0.050823307
[epoch 000000138] loss=4668.141688756 | avg=6.781520537 | rare=0.046613601
[epoch 000000139] loss=4427.906197684 | avg=6.698843377 | rare=0.044212073
[epoch 000000140] loss=4030.542131696 | avg=7.084562438 | rare=0.040234576
[epoch 000000141] loss=4565.734776088 | avg=7.106057542 | rare=0.045586286
[epoch 000000142] loss=4998.220807757 | avg=6.831158910 | rare=0.049913897
[epoch 000000143] loss=4695.837306431 | avg=7.510548047 | rare=0.046883267
[epoch 000000144] loss=5988.342302595 | avg=7.958953517 | rare=0.059803835
[epoch 000000145] loss=5057.012416295 | avg=7.102390119 | rare=0.050499100
[epoch 000000146] loss=4857.350254604 | avg=6.906858070 | rare=0.048504433
[epoch 000000147] loss=4063.274379185 | avg=6.786077636 | rare=0.040564883
[epoch 000000148] loss=4789.057390485 | avg=6.973210880 | rare=0.047820842
[epoch 000000149] loss=4673.138201032 | avg=6.770998001 | rare=0.046663673
[epoch 000000150] loss=4030.639997210 | avg=6.629801955 | rare=0.040240101
[epoch 000000151] loss=3839.083251953 | avg=6.618180241 | rare=0.038324650
[epoch 000000152] loss=4787.624720982 | avg=6.620776687 | rare=0.047810039
[epoch 000000153] loss=4956.137695312 | avg=6.449098076 | rare=0.049496886
[epoch 000000154] loss=4425.409772600 | avg=6.340836252 | rare=0.044190689
[epoch 000000155] loss=3967.261509487 | avg=6.634819133 | rare=0.039606267
[epoch 000000156] loss=4233.870413644 | avg=6.922572749 | rare=0.042269479
[epoch 000000157] loss=5571.548915318 | avg=6.673245839 | rare=0.055648757
[epoch 000000158] loss=3799.725821359 | avg=6.852443218 | rare=0.037928734
[epoch 000000159] loss=4823.247663225 | avg=6.716984987 | rare=0.048165308
[epoch 000000160] loss=5590.800397600 | avg=6.840863773 | rare=0.055839596
[epoch 000000161] loss=5016.622820173 | avg=6.628476177 | rare=0.050099943
[epoch 000000162] loss=4846.135079520 | avg=6.390683685 | rare=0.048397444
[epoch 000000163] loss=4770.298287528 | avg=6.529969624 | rare=0.047637684
[epoch 000000164] loss=4975.990478516 | avg=6.832586254 | rare=0.049691578
[epoch 000000165] loss=4891.129220145 | avg=6.346030406 | rare=0.048847832
[epoch 000000166] loss=3947.465541295 | avg=6.672867639 | rare=0.039407927
[epoch 000000167] loss=4198.191720145 | avg=6.340872015 | rare=0.041918509
[epoch 000000168] loss=4251.837158203 | avg=6.736040013 | rare=0.042451012
[epoch 000000169] loss=5208.154209682 | avg=6.291632414 | rare=0.052018626
[epoch 000000170] loss=4782.299891881 | avg=6.331724065 | rare=0.047759681
[epoch 000000171] loss=4324.348109654 | avg=6.517346723 | rare=0.043178308
[epoch 000000172] loss=5588.499372210 | avg=6.964678560 | rare=0.055815346
[epoch 000000173] loss=4822.320678711 | avg=6.778068406 | rare=0.048155426
[epoch 000000174] loss=4387.898925781 | avg=6.788276536 | rare=0.043811107
[epoch 000000175] loss=4535.197143555 | avg=6.648891211 | rare=0.045285483
[epoch 000000176] loss=4515.014997210 | avg=6.370171206 | rare=0.045086448
[epoch 000000177] loss=5278.273018973 | avg=6.357597624 | rare=0.052719155
[epoch 000000178] loss=4646.762721470 | avg=7.133513042 | rare=0.046396292
[epoch 000000179] loss=4652.238237653 | avg=7.153192077 | rare=0.046450851
[epoch 000000180] loss=4197.574358259 | avg=6.670873199 | rare=0.041909035
[epoch 000000181] loss=3914.165021624 | avg=6.982794659 | rare=0.039071823
[epoch 000000182] loss=4434.233450753 | avg=6.417823587 | rare=0.044278156
[epoch 000000183] loss=4073.757027762 | avg=6.611223357 | rare=0.040671458
[epoch 000000184] loss=3967.114432199 | avg=6.996835709 | rare=0.039601176
[epoch 000000185] loss=4152.983956473 | avg=6.606561695 | rare=0.041463774
[epoch 000000186] loss=4534.168247768 | avg=7.043536561 | rare=0.045271247
[epoch 000000187] loss=3496.666730608 | avg=7.004730838 | rare=0.034896620
[epoch 000000188] loss=5154.282941546 | avg=6.843759026 | rare=0.051474392
[epoch 000000189] loss=5586.903826032 | avg=6.422586918 | rare=0.055804811
[epoch 000000190] loss=4504.351693290 | avg=7.593179532 | rare=0.044967586
[epoch 000000191] loss=4946.142246791 | avg=6.572587490 | rare=0.049395697
[epoch 000000192] loss=4525.178885324 | avg=6.701241323 | rare=0.045184777
[epoch 000000193] loss=5074.002075195 | avg=7.093271732 | rare=0.050669088
[epoch 000000194] loss=5593.802246094 | avg=6.467487165 | rare=0.055873347
[epoch 000000195] loss=4722.180960519 | avg=6.837672370 | rare=0.047153433
[epoch 000000196] loss=4643.379847935 | avg=6.802436079 | rare=0.046365775
[epoch 000000197] loss=5571.018327985 | avg=6.803796019 | rare=0.055642145
[epoch 000000198] loss=4016.900408064 | avg=6.848268918 | rare=0.040100521
[epoch 000000199] loss=4566.547624860 | avg=6.629517930 | rare=0.045599180
[epoch 000000200] loss=5316.186349051 | avg=6.404653924 | rare=0.053097817
Accuracy: 82.77%  (CI 95%: [81.70%, 83.79%])
Robust Accuracy: 82.61443%  (CI 95%: [81.71911%, 83.64804%])
Conditional Robust Accuracy: 98.96555%  (CI 95%: [98.80016%, 99.12015%])
Accuracy: 82.87%  (CI 95%: [81.80%, 83.89%])
Robust Accuracy: 82.60823%  (CI 95%: [81.63075%, 83.66113%])
Conditional Robust Accuracy: 99.09391%  (CI 95%: [98.92420%, 99.26019%])
  --> Running Seed: 100

Training naive with adam...

Epochs:   0%|          | 0/200 [00:00<?, ?it/s]

[epoch 000000001] loss=178466.601562500 | avg=0.319753973 | rare=1.784662809
[epoch 000000002] loss=178522.145089286 | avg=0.320083375 | rare=1.785218264
[epoch 000000003] loss=104233.745535714 | avg=3.408576629 | rare=1.042303367
[epoch 000000004] loss=11057.002685547 | avg=7.978383098 | rare=0.110490243
[epoch 000000005] loss=4230.131626674 | avg=8.324299880 | rare=0.042218074
[epoch 000000006] loss=3216.947677612 | avg=7.407448462 | rare=0.032095402
[epoch 000000007] loss=1951.039498465 | avg=7.244064331 | rare=0.019437954
[epoch 000000008] loss=1663.755244664 | avg=6.139058692 | rare=0.016576162
[epoch 000000009] loss=2663.952213832 | avg=5.024819136 | rare=0.026589274
[epoch 000000010] loss=3655.814985003 | avg=4.239674807 | rare=0.036515753
[epoch 000000011] loss=3112.979326521 | avg=3.873437711 | rare=0.031091059
[epoch 000000012] loss=3400.834019252 | avg=3.163464699 | rare=0.033976706
[epoch 000000013] loss=2643.642438616 | avg=3.244977576 | rare=0.026403974
[epoch 000000014] loss=2564.180794852 | avg=3.011256967 | rare=0.025611695
[epoch 000000015] loss=2723.337620326 | avg=2.521757449 | rare=0.027208158
[epoch 000000016] loss=1998.445530483 | avg=2.473239030 | rare=0.019959723
[epoch 000000017] loss=2007.681893485 | avg=1.835925477 | rare=0.020058460
[epoch 000000018] loss=1615.012102400 | avg=1.839363064 | rare=0.016131727
[epoch 000000019] loss=1628.915823800 | avg=1.244966456 | rare=0.016276709
[epoch 000000020] loss=1127.893654960 | avg=1.006124786 | rare=0.011268875
[epoch 000000021] loss=818.793060303 | avg=0.879773796 | rare=0.008179133
[epoch 000000022] loss=898.232343401 | avg=1.286672924 | rare=0.008969457
[epoch 000000023] loss=738.280347552 | avg=1.066027692 | rare=0.007372143
[epoch 000000024] loss=647.577669416 | avg=0.977293283 | rare=0.006466004
[epoch 000000025] loss=805.435278756 | avg=0.916026179 | rare=0.008045193
[epoch 000000026] loss=847.103827340 | avg=0.895062281 | rare=0.008462088
[epoch 000000027] loss=632.793954032 | avg=0.926620330 | rare=0.006318673
[epoch 000000028] loss=577.902821132 | avg=0.806770861 | rare=0.005770961
[epoch 000000029] loss=600.689032418 | avg=0.741275204 | rare=0.005999477
[epoch 000000030] loss=586.692816598 | avg=0.717139836 | rare=0.005859757
[epoch 000000031] loss=420.561650957 | avg=0.718572072 | rare=0.004198431
[epoch 000000032] loss=411.590133667 | avg=0.730882240 | rare=0.004108593
[epoch 000000033] loss=468.033945356 | avg=0.718082343 | rare=0.004673159
[epoch 000000034] loss=401.710515703 | avg=0.713418671 | rare=0.004009971
[epoch 000000035] loss=470.790712629 | avg=0.670368348 | rare=0.004701203
[epoch 000000036] loss=495.630868094 | avg=0.863340650 | rare=0.004947675
[epoch 000000037] loss=839.279115949 | avg=1.034204262 | rare=0.008382449
[epoch 000000038] loss=655.709915161 | avg=0.834976971 | rare=0.006548749
[epoch 000000039] loss=559.318259103 | avg=0.750249352 | rare=0.005585680
[epoch 000000040] loss=488.692656381 | avg=0.658650420 | rare=0.004880340
[epoch 000000041] loss=463.576993670 | avg=0.677621556 | rare=0.004628994
[epoch 000000042] loss=399.998558044 | avg=0.993224821 | rare=0.003990053
[epoch 000000043] loss=703.871091570 | avg=0.931287731 | rare=0.007029398
[epoch 000000044] loss=606.682743617 | avg=0.744534940 | rare=0.006059382
[epoch 000000045] loss=480.050604684 | avg=0.660445941 | rare=0.004793902
[epoch 000000046] loss=444.151754107 | avg=0.694341783 | rare=0.004434574
[epoch 000000047] loss=509.066407340 | avg=0.758174058 | rare=0.005083082
[epoch 000000048] loss=446.021547590 | avg=0.716632294 | rare=0.004453049
[epoch 000000049] loss=453.072023664 | avg=0.632347350 | rare=0.004524397
[epoch 000000050] loss=446.026659829 | avg=0.615424961 | rare=0.004454112
[epoch 000000051] loss=436.196594238 | avg=0.629608120 | rare=0.004355670
[epoch 000000052] loss=385.219802856 | avg=0.687307503 | rare=0.003845325
[epoch 000000053] loss=396.558356149 | avg=0.677026383 | rare=0.003958813
[epoch 000000054] loss=463.728397914 | avg=0.683477708 | rare=0.004630449
[epoch 000000055] loss=371.568040030 | avg=0.671685836 | rare=0.003708964
[epoch 000000056] loss=443.796024867 | avg=0.623671962 | rare=0.004431724
[epoch 000000057] loss=361.117009844 | avg=0.621283416 | rare=0.003604957
[epoch 000000058] loss=382.909064157 | avg=0.639835890 | rare=0.003822692
[epoch 000000059] loss=415.505615234 | avg=0.637429199 | rare=0.004148682
[epoch 000000060] loss=369.559270586 | avg=0.752519161 | rare=0.003688067
[epoch 000000061] loss=366.765397208 | avg=0.857558063 | rare=0.003659078
[epoch 000000062] loss=679.466138567 | avg=0.795909515 | rare=0.006786702
[epoch 000000063] loss=548.044614519 | avg=0.823171841 | rare=0.005472214
[epoch 000000064] loss=533.247558594 | avg=0.777583761 | rare=0.005324700
[epoch 000000065] loss=559.589693342 | avg=0.672390742 | rare=0.005589173
[epoch 000000066] loss=450.121699742 | avg=0.667028393 | rare=0.004494547
[epoch 000000067] loss=422.946425302 | avg=0.610999431 | rare=0.004223354
[epoch 000000068] loss=427.409362793 | avg=0.601560167 | rare=0.004268078
[epoch 000000069] loss=383.170449393 | avg=0.583579108 | rare=0.003825869
[epoch 000000070] loss=325.018004281 | avg=0.657811765 | rare=0.003243602
[epoch 000000071] loss=485.783033098 | avg=0.647549719 | rare=0.004851355
[epoch 000000072] loss=357.614616394 | avg=0.637651916 | rare=0.003569770
[epoch 000000073] loss=470.022670201 | avg=0.592135749 | rare=0.004694305
[epoch 000000074] loss=400.725009373 | avg=0.559845039 | rare=0.004001652
[epoch 000000075] loss=368.379888262 | avg=0.567985064 | rare=0.003678119
[epoch 000000076] loss=414.000184195 | avg=0.680534574 | rare=0.004133196
[epoch 000000077] loss=327.019658770 | avg=0.712705570 | rare=0.003263070
[epoch 000000078] loss=591.385328020 | avg=0.572626872 | rare=0.005908127
[epoch 000000079] loss=469.595106942 | avg=0.575884977 | rare=0.004690192
[epoch 000000080] loss=507.100335257 | avg=0.561791810 | rare=0.005065385
[epoch 000000081] loss=399.095030648 | avg=0.603148558 | rare=0.003984919
[epoch 000000082] loss=316.167325701 | avg=0.605256515 | rare=0.003155621
[epoch 000000083] loss=464.028206961 | avg=0.556262157 | rare=0.004634719
[epoch 000000084] loss=354.567655291 | avg=0.560279608 | rare=0.003540074
[epoch 000000085] loss=392.571008955 | avg=0.532438340 | rare=0.003920386
[epoch 000000086] loss=364.699547359 | avg=0.573760686 | rare=0.003641258
[epoch 000000087] loss=470.856769017 | avg=0.564405603 | rare=0.004702924
[epoch 000000088] loss=407.711190360 | avg=0.555241523 | rare=0.004071559
[epoch 000000089] loss=411.247404916 | avg=0.527376954 | rare=0.004107200
[epoch 000000090] loss=402.406935556 | avg=0.560520596 | rare=0.004018464
[epoch 000000091] loss=385.969387599 | avg=0.559822785 | rare=0.003854096
[epoch 000000092] loss=456.560074942 | avg=0.525631677 | rare=0.004560344
[epoch 000000093] loss=441.820646014 | avg=0.535510976 | rare=0.004412851
[epoch 000000094] loss=387.629850115 | avg=0.545422712 | rare=0.003870844
[epoch 000000095] loss=383.778885978 | avg=0.524915676 | rare=0.003832540
[epoch 000000096] loss=325.458817618 | avg=0.526525382 | rare=0.003249323
[epoch 000000097] loss=350.672695705 | avg=0.523363592 | rare=0.003501493
[epoch 000000098] loss=332.648960658 | avg=0.508612941 | rare=0.003321403
[epoch 000000099] loss=315.334733146 | avg=0.529120305 | rare=0.003148056
[epoch 000000100] loss=337.079679217 | avg=0.513898907 | rare=0.003365658
[epoch 000000101] loss=364.083456857 | avg=0.513467665 | rare=0.003635700
[epoch 000000102] loss=356.167023795 | avg=0.499956284 | rare=0.003556671
[epoch 000000103] loss=271.416307722 | avg=0.491125492 | rare=0.002709252
[epoch 000000104] loss=325.467534746 | avg=0.483459339 | rare=0.003249841
[epoch 000000105] loss=296.769154140 | avg=0.489197671 | rare=0.002962800
[epoch 000000106] loss=285.500898089 | avg=0.490101833 | rare=0.002850108
[epoch 000000107] loss=288.391811916 | avg=0.488364556 | rare=0.002879034
[epoch 000000108] loss=314.396977016 | avg=0.511102293 | rare=0.003138859
[epoch 000000109] loss=373.203754970 | avg=0.494332831 | rare=0.003727094
[epoch 000000110] loss=359.278592791 | avg=0.498860736 | rare=0.003587797
[epoch 000000111] loss=292.170217242 | avg=0.530055150 | rare=0.002916402
[epoch 000000112] loss=285.754059928 | avg=0.576361284 | rare=0.002851777
[epoch 000000113] loss=346.016306196 | avg=0.512704228 | rare=0.003455036
[epoch 000000114] loss=339.118789673 | avg=0.514802469 | rare=0.003386040
[epoch 000000115] loss=354.270456587 | avg=0.537668124 | rare=0.003537328
[epoch 000000116] loss=402.861012050 | avg=0.516265761 | rare=0.004023447
[epoch 000000117] loss=306.231342861 | avg=0.489472200 | rare=0.003057419
[epoch 000000118] loss=289.606545585 | avg=0.489142109 | rare=0.002891174
[epoch 000000119] loss=290.656351362 | avg=0.511863968 | rare=0.002901445
[epoch 000000120] loss=416.191412789 | avg=0.518850648 | rare=0.004156726
[epoch 000000121] loss=382.278274536 | avg=0.591194970 | rare=0.003816871
[epoch 000000122] loss=339.790873936 | avg=0.517780649 | rare=0.003392731
[epoch 000000123] loss=330.537055969 | avg=0.494544874 | rare=0.003300425
[epoch 000000124] loss=343.684228080 | avg=0.490789213 | rare=0.003431934
[epoch 000000125] loss=355.242231097 | avg=0.492662083 | rare=0.003547496
[epoch 000000126] loss=347.878162929 | avg=0.519832515 | rare=0.003473583
[epoch 000000127] loss=268.730039324 | avg=0.504314927 | rare=0.002682257
[epoch 000000128] loss=275.888623919 | avg=0.496357924 | rare=0.002753923
[epoch 000000129] loss=312.455300467 | avg=0.502522305 | rare=0.003119528
[epoch 000000130] loss=279.965992519 | avg=0.492473196 | rare=0.002794735
[epoch 000000131] loss=259.497107370 | avg=0.474065678 | rare=0.002590230
[epoch 000000132] loss=291.161262512 | avg=0.478237271 | rare=0.002906830
[epoch 000000133] loss=262.001737322 | avg=0.503948725 | rare=0.002614978
[epoch 000000134] loss=281.866647993 | avg=0.489825813 | rare=0.002813768
[epoch 000000135] loss=305.253122602 | avg=0.501188536 | rare=0.003047519
[epoch 000000136] loss=250.163601467 | avg=0.511658081 | rare=0.002496519
[epoch 000000137] loss=277.589914594 | avg=0.514421538 | rare=0.002770755
[epoch 000000138] loss=280.186281477 | avg=0.486787958 | rare=0.002796995
[epoch 000000139] loss=250.946534293 | avg=0.486207839 | rare=0.002504603
[epoch 000000140] loss=266.167017256 | avg=0.471133798 | rare=0.002656959
[epoch 000000141] loss=295.602892194 | avg=0.464351520 | rare=0.002951385
[epoch 000000142] loss=245.116733006 | avg=0.461540905 | rare=0.002446552
[epoch 000000143] loss=271.122268677 | avg=0.460954549 | rare=0.002706613
[epoch 000000144] loss=245.980314527 | avg=0.497349635 | rare=0.002454830
[epoch 000000145] loss=287.809473310 | avg=0.537345699 | rare=0.002872721
[epoch 000000146] loss=352.136254447 | avg=0.471956804 | rare=0.003516643
[epoch 000000147] loss=266.933929443 | avg=0.494987173 | rare=0.002664389
[epoch 000000148] loss=247.188521249 | avg=0.476278910 | rare=0.002467122
[epoch 000000149] loss=190.705991473 | avg=0.474241934 | rare=0.001902317
[epoch 000000150] loss=230.272836413 | avg=0.477174031 | rare=0.002297957
[epoch 000000151] loss=254.345925467 | avg=0.467792913 | rare=0.002538781
[epoch 000000152] loss=227.117202214 | avg=0.474423683 | rare=0.002266428
[epoch 000000153] loss=265.704200745 | avg=0.449359685 | rare=0.002652548
[epoch 000000154] loss=247.555709839 | avg=0.442964122 | rare=0.002471128
[epoch 000000155] loss=239.138991220 | avg=0.477572992 | rare=0.002386614
[epoch 000000156] loss=273.293282645 | avg=0.496188909 | rare=0.002727971
[epoch 000000157] loss=302.310472761 | avg=0.456751826 | rare=0.003018537
[epoch 000000158] loss=246.110970633 | avg=0.473999070 | rare=0.002456370
[epoch 000000159] loss=260.706682478 | avg=0.458043665 | rare=0.002602486
[epoch 000000160] loss=284.276542664 | avg=0.446060025 | rare=0.002838305
[epoch 000000161] loss=260.041884831 | avg=0.464328095 | rare=0.002595776
[epoch 000000162] loss=204.272465570 | avg=0.466098592 | rare=0.002038064
[epoch 000000163] loss=231.615716117 | avg=0.445746916 | rare=0.002311700
[epoch 000000164] loss=224.481163025 | avg=0.452190014 | rare=0.002240290
[epoch 000000165] loss=240.857402257 | avg=0.442701195 | rare=0.002404147
[epoch 000000166] loss=204.514438084 | avg=0.443905807 | rare=0.002040705
[epoch 000000167] loss=232.877621787 | avg=0.455030235 | rare=0.002324226
[epoch 000000168] loss=265.804533822 | avg=0.451755089 | rare=0.002653528
[epoch 000000169] loss=237.001761845 | avg=0.475381883 | rare=0.002365264
[epoch 000000170] loss=213.503817422 | avg=0.450475993 | rare=0.002130533
[epoch 000000171] loss=240.286074502 | avg=0.449815180 | rare=0.002398363
[epoch 000000172] loss=220.711606162 | avg=0.455607116 | rare=0.002202560
[epoch 000000173] loss=201.355882917 | avg=0.450524864 | rare=0.002009054
[epoch 000000174] loss=188.373373304 | avg=0.458430603 | rare=0.001879149
[epoch 000000175] loss=208.419732775 | avg=0.453436726 | rare=0.002079663
[epoch 000000176] loss=252.786348615 | avg=0.441070382 | rare=0.002523453
[epoch 000000177] loss=196.000066485 | avg=0.452371295 | rare=0.001955477
[epoch 000000178] loss=231.296068464 | avg=0.436663059 | rare=0.002308594
[epoch 000000179] loss=179.966481073 | avg=0.449229519 | rare=0.001795173
[epoch 000000180] loss=201.711117336 | avg=0.434114735 | rare=0.002012770
[epoch 000000181] loss=171.893442971 | avg=0.439852548 | rare=0.001714536
[epoch 000000182] loss=206.870614733 | avg=0.438506595 | rare=0.002064321
[epoch 000000183] loss=177.720809392 | avg=0.434652490 | rare=0.001772862
[epoch 000000184] loss=189.132523673 | avg=0.443486299 | rare=0.001886890
[epoch 000000185] loss=172.742803846 | avg=0.444222661 | rare=0.001722986
[epoch 000000186] loss=194.136409760 | avg=0.442737718 | rare=0.001936937
[epoch 000000187] loss=232.973752703 | avg=0.434866550 | rare=0.002325389
[epoch 000000188] loss=196.437904903 | avg=0.446771920 | rare=0.001959911
[epoch 000000189] loss=169.671706063 | avg=0.432414066 | rare=0.001692393
[epoch 000000190] loss=185.692794800 | avg=0.432553459 | rare=0.001852602
[epoch 000000191] loss=185.331529890 | avg=0.435880985 | rare=0.001848957
[epoch 000000192] loss=186.590965816 | avg=0.430726171 | rare=0.001861602
[epoch 000000193] loss=181.664734977 | avg=0.427199787 | rare=0.001812375
[epoch 000000194] loss=175.336861202 | avg=0.435567945 | rare=0.001749013
[epoch 000000195] loss=164.197445461 | avg=0.428000075 | rare=0.001637694
[epoch 000000196] loss=176.363815308 | avg=0.427937471 | rare=0.001759359
[epoch 000000197] loss=170.274666377 | avg=0.432964089 | rare=0.001698417
[epoch 000000198] loss=200.023526873 | avg=0.429321994 | rare=0.001995942
[epoch 000000199] loss=169.935903277 | avg=0.437887977 | rare=0.001694980
[epoch 000000200] loss=145.630180904 | avg=0.439326829 | rare=0.001451909

Training safe with adam...

Epochs:   0%|          | 0/200 [00:00<?, ?it/s]

[epoch 000000001] loss=142.039022991 | avg=50.119557244 | rare=0.000919195
[epoch 000000002] loss=471.931176867 | avg=44.168428421 | rare=0.004277627
[epoch 000000003] loss=5566.660452706 | avg=30.177555357 | rare=0.055364830
[epoch 000000004] loss=9426.182512556 | avg=17.390475205 | rare=0.094087920
[epoch 000000005] loss=9862.253801618 | avg=13.586453506 | rare=0.098486673
[epoch 000000006] loss=5054.738002232 | avg=11.766544070 | rare=0.050429714
[epoch 000000007] loss=4652.188999721 | avg=9.889492512 | rare=0.046422995
[epoch 000000008] loss=5705.316144671 | avg=9.167842388 | rare=0.056961483
[epoch 000000009] loss=5141.277605329 | avg=8.285850695 | rare=0.051329918
[epoch 000000010] loss=5747.902413504 | avg=8.221469947 | rare=0.057396809
[epoch 000000011] loss=5698.705984933 | avg=8.614271641 | rare=0.056900917
[epoch 000000012] loss=5068.950596401 | avg=8.619566509 | rare=0.050603310
[epoch 000000013] loss=3381.272521973 | avg=9.094747271 | rare=0.033721778
[epoch 000000014] loss=3891.237295968 | avg=8.424423456 | rare=0.038828129
[epoch 000000015] loss=4340.952305385 | avg=8.306071963 | rare=0.043326463
[epoch 000000016] loss=3916.740264893 | avg=8.726754665 | rare=0.039080135
[epoch 000000017] loss=3256.640607561 | avg=9.253538166 | rare=0.032473871
[epoch 000000018] loss=4318.941057478 | avg=8.157506159 | rare=0.043107836
[epoch 000000019] loss=4649.773542132 | avg=8.371063198 | rare=0.046414024
[epoch 000000020] loss=3777.620204381 | avg=8.615692445 | rare=0.037690045
[epoch 000000021] loss=4159.247523717 | avg=8.059901987 | rare=0.041511877
[epoch 000000022] loss=4288.246756417 | avg=7.906691347 | rare=0.042803401
[epoch 000000023] loss=4022.485691616 | avg=8.012815033 | rare=0.040144729
[epoch 000000024] loss=3862.916085379 | avg=8.045802764 | rare=0.038548703
[epoch 000000025] loss=3670.380249023 | avg=8.659099954 | rare=0.036617212
[epoch 000000026] loss=4108.854745047 | avg=8.295886483 | rare=0.041005589
[epoch 000000027] loss=4594.101893834 | avg=7.729941845 | rare=0.045863720
[epoch 000000028] loss=4152.792951311 | avg=8.602228028 | rare=0.041441907
[epoch 000000029] loss=4373.997558594 | avg=7.741361073 | rare=0.043662562
[epoch 000000030] loss=3928.662876674 | avg=8.310769490 | rare=0.039203522
[epoch 000000031] loss=4865.960379464 | avg=7.675580502 | rare=0.048582848
[epoch 000000032] loss=4412.932390485 | avg=8.141598157 | rare=0.044047908
[epoch 000000033] loss=4806.522059849 | avg=8.063539233 | rare=0.047984586
[epoch 000000034] loss=4422.887765067 | avg=7.966740983 | rare=0.044149211
[epoch 000000035] loss=4297.886980329 | avg=7.838223594 | rare=0.042900487
[epoch 000000036] loss=3807.555114746 | avg=7.791308199 | rare=0.037997638
[epoch 000000037] loss=3323.757023403 | avg=9.131613220 | rare=0.033146254
[epoch 000000038] loss=4459.334211077 | avg=8.218375342 | rare=0.044511157
[epoch 000000039] loss=4800.082257952 | avg=8.032313858 | rare=0.047920499
[epoch 000000040] loss=3645.938764300 | avg=7.860560111 | rare=0.036380783
[epoch 000000041] loss=4703.091500419 | avg=7.439593213 | rare=0.046956519
[epoch 000000042] loss=4705.168265206 | avg=7.522249903 | rare=0.046976461
[epoch 000000043] loss=4862.116873605 | avg=7.359464986 | rare=0.048547574
[epoch 000000044] loss=4688.914114816 | avg=7.511471748 | rare=0.046814026
[epoch 000000045] loss=4327.629464286 | avg=7.579221998 | rare=0.043200502
[epoch 000000046] loss=3955.307094029 | avg=7.760337727 | rare=0.039475467
[epoch 000000047] loss=3659.531747001 | avg=8.002543109 | rare=0.036515293
[epoch 000000048] loss=4444.513767787 | avg=8.120441232 | rare=0.044363933
[epoch 000000049] loss=5437.748474121 | avg=8.890887397 | rare=0.054288576
[epoch 000000050] loss=5615.570643834 | avg=8.091902835 | rare=0.056074788
[epoch 000000051] loss=4601.328839983 | avg=8.034090723 | rare=0.045932947
[epoch 000000052] loss=4741.266374860 | avg=7.627600806 | rare=0.047336388
[epoch 000000053] loss=5753.461233956 | avg=7.564957857 | rare=0.057458963
[epoch 000000054] loss=4654.491542271 | avg=7.770207916 | rare=0.046467213
[epoch 000000055] loss=5121.688145229 | avg=7.546009472 | rare=0.051141421
[epoch 000000056] loss=4280.233660017 | avg=7.890413182 | rare=0.042723433
[epoch 000000057] loss=5539.804356166 | avg=7.423654693 | rare=0.055323807
[epoch 000000058] loss=4731.047869001 | avg=7.360888549 | rare=0.047236870
[epoch 000000059] loss=5167.722917829 | avg=7.519629649 | rare=0.051602033
[epoch 000000060] loss=4936.963413783 | avg=7.498518876 | rare=0.049294649
[epoch 000000061] loss=4661.373360770 | avg=7.560928106 | rare=0.046538124
[epoch 000000062] loss=4390.752511161 | avg=7.476394551 | rare=0.043832761
[epoch 000000063] loss=4884.709298270 | avg=7.324988570 | rare=0.048773843
[epoch 000000064] loss=4518.822657994 | avg=7.528063604 | rare=0.045112946
[epoch 000000065] loss=4867.630266462 | avg=7.430304459 | rare=0.048601999
[epoch 000000066] loss=4371.354893276 | avg=7.773981333 | rare=0.043635809
[epoch 000000067] loss=4326.698120117 | avg=7.455001763 | rare=0.043192432
[epoch 000000068] loss=3662.458365304 | avg=7.548667329 | rare=0.036549097
[epoch 000000069] loss=4878.245483398 | avg=7.142383303 | rare=0.048711031
[epoch 000000070] loss=4919.861938477 | avg=7.398754120 | rare=0.049124632
[epoch 000000071] loss=6294.383021763 | avg=6.767140150 | rare=0.062876158
[epoch 000000072] loss=4638.623168945 | avg=7.546813658 | rare=0.046310764
[epoch 000000073] loss=4241.223754883 | avg=7.299224888 | rare=0.042339245
[epoch 000000074] loss=5212.975027902 | avg=7.778046846 | rare=0.052051969
[epoch 000000075] loss=4695.678484235 | avg=7.662936006 | rare=0.046880155
[epoch 000000076] loss=5167.755597796 | avg=7.305874382 | rare=0.051604497
[epoch 000000077] loss=3979.549577985 | avg=7.765441043 | rare=0.039717841
[epoch 000000078] loss=4008.032871791 | avg=7.304289648 | rare=0.040007286
[epoch 000000079] loss=4255.811959403 | avg=7.211551973 | rare=0.042486004
[epoch 000000080] loss=3874.481846401 | avg=7.267047235 | rare=0.038672148
[epoch 000000081] loss=4619.855242048 | avg=7.219826460 | rare=0.046126354
[epoch 000000082] loss=4066.185076032 | avg=7.261173895 | rare=0.040589239
[epoch 000000083] loss=5171.475864955 | avg=7.288138662 | rare=0.051641877
[epoch 000000084] loss=4338.190935407 | avg=7.060010842 | rare=0.043311309
[epoch 000000085] loss=4510.011997768 | avg=7.230044774 | rare=0.045027819
[epoch 000000086] loss=4537.216727121 | avg=6.938966070 | rare=0.045302777
[epoch 000000087] loss=4090.377485003 | avg=7.856738840 | rare=0.040825208
[epoch 000000088] loss=4592.251552037 | avg=6.916266441 | rare=0.045853352
[epoch 000000089] loss=4163.386526925 | avg=7.370770727 | rare=0.041560158
[epoch 000000090] loss=4206.097115653 | avg=7.495811701 | rare=0.041986013
[epoch 000000091] loss=4130.332345145 | avg=7.210699694 | rare=0.041231217
[epoch 000000092] loss=4241.725830078 | avg=7.152810437 | rare=0.042345730
[epoch 000000093] loss=3602.753191267 | avg=7.460103103 | rare=0.035952931
[epoch 000000094] loss=5004.285086496 | avg=7.151726007 | rare=0.049971333
[epoch 000000095] loss=5173.910923549 | avg=7.150538002 | rare=0.051667604
[epoch 000000096] loss=4965.207676479 | avg=7.124510765 | rare=0.049580832
[epoch 000000097] loss=5141.718645368 | avg=7.018221753 | rare=0.051347004
[epoch 000000098] loss=4654.704833984 | avg=6.833911657 | rare=0.046478710
[epoch 000000099] loss=4263.619646345 | avg=6.971663441 | rare=0.042566480
[epoch 000000100] loss=4494.493373326 | avg=6.861893450 | rare=0.044876315
[epoch 000000101] loss=3860.948974609 | avg=7.290028470 | rare=0.038536590
[epoch 000000102] loss=4418.031677246 | avg=7.187937226 | rare=0.044108437
[epoch 000000103] loss=4114.884800502 | avg=7.337257896 | rare=0.041075476
[epoch 000000104] loss=4182.938092913 | avg=7.078196628 | rare=0.041758600
[epoch 000000105] loss=4517.799002511 | avg=7.383774076 | rare=0.045104152
[epoch 000000106] loss=4132.167951311 | avg=7.155282940 | rare=0.041250127
[epoch 000000107] loss=4570.229457310 | avg=7.467429365 | rare=0.045627620
[epoch 000000108] loss=4453.957938058 | avg=6.961988245 | rare=0.044469960
[epoch 000000109] loss=4198.499040876 | avg=6.858582667 | rare=0.041916404
[epoch 000000110] loss=3517.916216169 | avg=7.995477983 | rare=0.035099208
[epoch 000000111] loss=4946.069580078 | avg=6.888503517 | rare=0.049391811
[epoch 000000112] loss=4555.572910854 | avg=7.353634698 | rare=0.045482193
[epoch 000000113] loss=4362.126464844 | avg=7.793372597 | rare=0.043543331
[epoch 000000114] loss=4744.408238002 | avg=7.210411991 | rare=0.047371978
[epoch 000000115] loss=4192.425170898 | avg=7.577866486 | rare=0.041848474
[epoch 000000116] loss=4365.412039621 | avg=7.683298111 | rare=0.043577288
[epoch 000000117] loss=4240.718654088 | avg=7.262669631 | rare=0.042334560
[epoch 000000118] loss=4546.708635603 | avg=7.478742361 | rare=0.045392299
[epoch 000000119] loss=5988.023263114 | avg=7.064391749 | rare=0.059809589
[epoch 000000120] loss=5603.125976562 | avg=7.435669252 | rare=0.055956903
[epoch 000000121] loss=5214.550885882 | avg=6.953541551 | rare=0.052075973
[epoch 000000122] loss=4507.267421177 | avg=7.186351470 | rare=0.045000811
[epoch 000000123] loss=4593.383475167 | avg=7.280432258 | rare=0.045861030
[epoch 000000124] loss=4986.547912598 | avg=7.547691686 | rare=0.049790002
[epoch 000000125] loss=4816.223109654 | avg=7.345645223 | rare=0.048088774
[epoch 000000126] loss=4200.411010742 | avg=7.244802816 | rare=0.041931662
[epoch 000000127] loss=4372.488263811 | avg=6.891980682 | rare=0.043655963
[epoch 000000128] loss=4010.486589704 | avg=6.685576269 | rare=0.040038010
[epoch 000000129] loss=4554.457380022 | avg=6.698823827 | rare=0.045477585
[epoch 000000130] loss=4761.558192662 | avg=6.783353635 | rare=0.047547748
[epoch 000000131] loss=4770.067644392 | avg=7.235793522 | rare=0.047628318
[epoch 000000132] loss=4824.744646345 | avg=7.354040929 | rare=0.048173906
[epoch 000000133] loss=3956.759198870 | avg=7.703466620 | rare=0.039490557
[epoch 000000134] loss=5220.109575544 | avg=7.263930559 | rare=0.052128456
[epoch 000000135] loss=4587.322091239 | avg=7.299392291 | rare=0.045800227
[epoch 000000136] loss=5379.452619280 | avg=6.764912946 | rare=0.053726877
[epoch 000000137] loss=4538.011753627 | avg=7.032219921 | rare=0.045309795
[epoch 000000138] loss=4490.882097517 | avg=6.921113014 | rare=0.044839610
[epoch 000000139] loss=3981.805855887 | avg=7.305835792 | rare=0.039745000
[epoch 000000140] loss=4534.235020229 | avg=7.026512623 | rare=0.045272085
[epoch 000000141] loss=4385.910417829 | avg=7.803265469 | rare=0.043781071
[epoch 000000142] loss=4425.709542411 | avg=6.973978894 | rare=0.044187355
[epoch 000000143] loss=4649.600376674 | avg=6.843218565 | rare=0.046427571
[epoch 000000144] loss=4928.202270508 | avg=6.988630329 | rare=0.049212136
[epoch 000000145] loss=5058.235979353 | avg=6.892810447 | rare=0.050513432
[epoch 000000146] loss=3767.545244489 | avg=6.892786435 | rare=0.037606525
[epoch 000000147] loss=4775.697440011 | avg=6.971219710 | rare=0.047687263
[epoch 000000148] loss=3771.122855050 | avg=7.360939026 | rare=0.037637620
[epoch 000000149] loss=4949.813773019 | avg=6.680610895 | rare=0.049431332
[epoch 000000150] loss=4399.433140346 | avg=7.196808883 | rare=0.043922364
[epoch 000000151] loss=4069.852643694 | avg=7.100661448 | rare=0.040627519
[epoch 000000152] loss=4287.896292550 | avg=6.833694867 | rare=0.042810626
[epoch 000000153] loss=4342.601841518 | avg=7.020207405 | rare=0.043355815
[epoch 000000154] loss=4731.529942104 | avg=6.774477550 | rare=0.047247556
[epoch 000000155] loss=4247.105468750 | avg=6.923410722 | rare=0.042401821
[epoch 000000156] loss=4484.631399972 | avg=6.792136056 | rare=0.044778391
[epoch 000000157] loss=5407.620448521 | avg=6.773330791 | rare=0.054008471
[epoch 000000158] loss=4682.541521345 | avg=6.761314256 | rare=0.046757802
[epoch 000000159] loss=4783.110386440 | avg=6.655442340 | rare=0.047764549
[epoch 000000160] loss=4735.576886858 | avg=6.625248126 | rare=0.047289517
[epoch 000000161] loss=4564.286237444 | avg=6.605491332 | rare=0.045576808
[epoch 000000162] loss=5096.368687221 | avg=6.630292790 | rare=0.050897384
[epoch 000000163] loss=4638.538731166 | avg=6.808850561 | rare=0.046317300
[epoch 000000164] loss=4001.255249023 | avg=6.671172925 | rare=0.039945840
[epoch 000000165] loss=4186.889735631 | avg=6.726152250 | rare=0.041801636
[epoch 000000166] loss=4259.171334403 | avg=6.776731968 | rare=0.042523946
[epoch 000000167] loss=4093.632952009 | avg=7.177962439 | rare=0.040864550
[epoch 000000168] loss=4536.566162109 | avg=6.975589752 | rare=0.045295906
[epoch 000000169] loss=4655.027936663 | avg=6.810556889 | rare=0.046482173
[epoch 000000170] loss=4639.263026646 | avg=6.878089360 | rare=0.046323849
[epoch 000000171] loss=4322.073965890 | avg=7.193943875 | rare=0.043148800
[epoch 000000172] loss=4696.195783343 | avg=7.030351639 | rare=0.046891654
[epoch 000000173] loss=4752.572771345 | avg=7.203247683 | rare=0.047453695
[epoch 000000174] loss=3561.401698521 | avg=6.865144525 | rare=0.035545365
[epoch 000000175] loss=4052.391287667 | avg=6.720802069 | rare=0.040456704
[epoch 000000176] loss=4179.154715402 | avg=6.691823891 | rare=0.041724629
[epoch 000000177] loss=4312.873378209 | avg=6.620125157 | rare=0.043062532
[epoch 000000178] loss=3760.095947266 | avg=6.898967947 | rare=0.037531970
[epoch 000000179] loss=3601.948102679 | avg=6.848923036 | rare=0.035950992
[epoch 000000180] loss=4036.968296596 | avg=6.774045127 | rare=0.040301942
[epoch 000000181] loss=4427.357142857 | avg=6.682128327 | rare=0.044206750
[epoch 000000182] loss=4393.809762137 | avg=6.635784013 | rare=0.043871740
[epoch 000000183] loss=4143.766810826 | avg=6.783742973 | rare=0.041369831
[epoch 000000184] loss=3668.047328404 | avg=6.601761307 | rare=0.036614456
[epoch 000000185] loss=4208.618739537 | avg=6.476656437 | rare=0.042021420
[epoch 000000186] loss=3909.807059152 | avg=6.832453523 | rare=0.039029746
[epoch 000000187] loss=4132.243111747 | avg=6.684220791 | rare=0.041255589
[epoch 000000188] loss=4677.451084682 | avg=6.588778496 | rare=0.046708622
[epoch 000000189] loss=4389.970799037 | avg=6.697986671 | rare=0.043832728
[epoch 000000190] loss=4433.074881417 | avg=6.794397116 | rare=0.044262805
[epoch 000000191] loss=3859.796796526 | avg=7.137330770 | rare=0.038526595
[epoch 000000192] loss=3905.139317104 | avg=6.525539637 | rare=0.038986138
[epoch 000000193] loss=3950.518938337 | avg=6.773663861 | rare=0.039437453
[epoch 000000194] loss=3851.752406529 | avg=6.838396788 | rare=0.038449140
[epoch 000000195] loss=3941.737601144 | avg=6.727868250 | rare=0.039350097
[epoch 000000196] loss=4489.582606724 | avg=6.684111391 | rare=0.044828986
[epoch 000000197] loss=4285.467023577 | avg=6.562342610 | rare=0.042789047
[epoch 000000198] loss=4018.212053571 | avg=6.654619830 | rare=0.040115575
[epoch 000000199] loss=3648.657697405 | avg=6.983114447 | rare=0.036416745
[epoch 000000200] loss=4213.546875000 | avg=6.632957765 | rare=0.042069139
Accuracy: 81.79%  (CI 95%: [80.70%, 82.84%])
Robust Accuracy: 81.71052%  (CI 95%: [80.89088%, 82.75220%])
Conditional Robust Accuracy: 99.11545%  (CI 95%: [98.97028%, 99.25124%])
Accuracy: 82.97%  (CI 95%: [81.90%, 83.98%])
Robust Accuracy: 82.77786%  (CI 95%: [81.83784%, 83.73432%])
Conditional Robust Accuracy: 98.98906%  (CI 95%: [98.82628%, 99.14398%])

#################### lr: 0.001 ####################
  --> Running Seed: 42

Training naive with adam...

Epochs:   0%|          | 0/200 [00:00<?, ?it/s]

[epoch 000000001] loss=178608.407366071 | avg=0.319726129 | rare=1.786080871
[epoch 000000002] loss=178494.834821429 | avg=0.319935188 | rare=1.784945164
[epoch 000000003] loss=135888.295758929 | avg=0.587234919 | rare=1.358877063
[epoch 000000004] loss=13285.797398158 | avg=2.338515571 | rare=0.132834589
[epoch 000000005] loss=6358.067347935 | avg=2.468076672 | rare=0.063555992
[epoch 000000006] loss=6530.343680246 | avg=2.177806641 | rare=0.065281659
[epoch 000000007] loss=4558.309361049 | avg=2.447801335 | rare=0.045558616
[epoch 000000008] loss=4354.811436244 | avg=2.383139372 | rare=0.043524283
[epoch 000000009] loss=4001.539899554 | avg=2.399222902 | rare=0.039991406
[epoch 000000010] loss=3453.019165039 | avg=2.365917010 | rare=0.034506532
[epoch 000000011] loss=3292.905447824 | avg=2.220992335 | rare=0.032906844
[epoch 000000012] loss=3007.161673410 | avg=2.103005205 | rare=0.030050587
[epoch 000000013] loss=3181.988856724 | avg=1.932419436 | rare=0.031800564
[epoch 000000014] loss=3464.781668527 | avg=1.604699297 | rare=0.034631770
[epoch 000000015] loss=3286.626796177 | avg=1.445911501 | rare=0.032851808
[epoch 000000016] loss=5116.561907087 | avg=1.080768049 | rare=0.051154811
[epoch 000000017] loss=5068.099714007 | avg=0.871498206 | rare=0.050672281
[epoch 000000018] loss=4095.058122907 | avg=0.794253247 | rare=0.040942639
[epoch 000000019] loss=3378.295479911 | avg=0.760698348 | rare=0.033775348
[epoch 000000020] loss=2874.177577427 | avg=0.737582237 | rare=0.028734400
[epoch 000000021] loss=2627.640171596 | avg=0.698739269 | rare=0.026269414
[epoch 000000022] loss=2382.444658552 | avg=0.672571578 | rare=0.023817721
[epoch 000000023] loss=2110.488359724 | avg=0.647012719 | rare=0.021098413
[epoch 000000024] loss=1911.680838449 | avg=0.614457841 | rare=0.019110664
[epoch 000000025] loss=1721.802132743 | avg=0.584092898 | rare=0.017212180
[epoch 000000026] loss=1680.928850446 | avg=0.574625186 | rare=0.016803543
[epoch 000000027] loss=1642.018136161 | avg=0.539722230 | rare=0.016414784
[epoch 000000028] loss=1700.785156250 | avg=0.516584943 | rare=0.017002686
[epoch 000000029] loss=1564.012080601 | avg=0.508940407 | rare=0.015635031
[epoch 000000030] loss=1593.716151646 | avg=0.507550099 | rare=0.015932086
[epoch 000000031] loss=1263.683218820 | avg=0.505313158 | rare=0.012631779
[epoch 000000032] loss=1032.812600272 | avg=0.515989695 | rare=0.010322966
[epoch 000000033] loss=1286.966945103 | avg=0.482111637 | rare=0.012864848
[epoch 000000034] loss=1243.389774867 | avg=0.472502755 | rare=0.012429173
[epoch 000000035] loss=1294.393131801 | avg=0.477926808 | rare=0.012939152
[epoch 000000036] loss=1021.697256906 | avg=0.467963489 | rare=0.010212293
[epoch 000000037] loss=973.477255685 | avg=0.464635738 | rare=0.009730126
[epoch 000000038] loss=1042.071929932 | avg=0.460756240 | rare=0.010416112
[epoch 000000039] loss=875.114449637 | avg=0.461279003 | rare=0.008746532
[epoch 000000040] loss=742.738329206 | avg=0.466896579 | rare=0.007422714
[epoch 000000041] loss=833.163190569 | avg=0.455535644 | rare=0.008327076
[epoch 000000042] loss=713.156762259 | avg=0.459389480 | rare=0.007126974
[epoch 000000043] loss=717.274935041 | avg=0.455035657 | rare=0.007168199
[epoch 000000044] loss=635.846823556 | avg=0.456495489 | rare=0.006353903
[epoch 000000045] loss=622.304979597 | avg=0.460530662 | rare=0.006218444
[epoch 000000046] loss=573.647454398 | avg=0.461179457 | rare=0.005731863
[epoch 000000047] loss=571.486025129 | avg=0.454054256 | rare=0.005710320
[epoch 000000048] loss=567.957373483 | avg=0.455041468 | rare=0.005675023
[epoch 000000049] loss=667.037796021 | avg=0.455993312 | rare=0.006665818
[epoch 000000050] loss=581.284655980 | avg=0.481137550 | rare=0.005808035
[epoch 000000051] loss=525.942274911 | avg=0.482085798 | rare=0.005254602
[epoch 000000052] loss=508.657872881 | avg=0.481311287 | rare=0.005081766
[epoch 000000053] loss=589.918753488 | avg=0.454972144 | rare=0.005894638
[epoch 000000054] loss=504.849530901 | avg=0.479839240 | rare=0.005043697
[epoch 000000055] loss=464.718676976 | avg=0.481977490 | rare=0.004642367
[epoch 000000056] loss=549.739661080 | avg=0.461849377 | rare=0.005492778
[epoch 000000057] loss=427.679319109 | avg=0.462924827 | rare=0.004272164
[epoch 000000058] loss=445.683877128 | avg=0.466332172 | rare=0.004452176
[epoch 000000059] loss=430.632956369 | avg=0.455560884 | rare=0.004301774
[epoch 000000060] loss=440.136082241 | avg=0.458795362 | rare=0.004396773
[epoch 000000061] loss=407.961944580 | avg=0.463315855 | rare=0.004074986
[epoch 000000062] loss=406.982467651 | avg=0.469468517 | rare=0.004065130
[epoch 000000063] loss=499.632659912 | avg=0.459308524 | rare=0.004991733
[epoch 000000064] loss=447.991426740 | avg=0.464155674 | rare=0.004475273
[epoch 000000065] loss=388.338858468 | avg=0.470975016 | rare=0.003878679
[epoch 000000066] loss=424.705160958 | avg=0.454582446 | rare=0.004242506
[epoch 000000067] loss=385.644247872 | avg=0.454498700 | rare=0.003851897
[epoch 000000068] loss=365.988867623 | avg=0.456417156 | rare=0.003655325
[epoch 000000069] loss=376.898688180 | avg=0.458137329 | rare=0.003764406
[epoch 000000070] loss=409.638329642 | avg=0.451338019 | rare=0.004091870
[epoch 000000071] loss=350.215419224 | avg=0.482873621 | rare=0.003497325
[epoch 000000072] loss=438.471984863 | avg=0.450705326 | rare=0.004380213
[epoch 000000073] loss=373.780637469 | avg=0.462022415 | rare=0.003733186
[epoch 000000074] loss=312.426989964 | avg=0.460086744 | rare=0.003119669
[epoch 000000075] loss=378.606010437 | avg=0.463835663 | rare=0.003781422
[epoch 000000076] loss=400.615864345 | avg=0.455133432 | rare=0.004001607
[epoch 000000077] loss=358.978845869 | avg=0.465517789 | rare=0.003585133
[epoch 000000078] loss=362.686705453 | avg=0.461957214 | rare=0.003622248
[epoch 000000079] loss=325.709638323 | avg=0.468661015 | rare=0.003252410
[epoch 000000080] loss=345.359957014 | avg=0.457453755 | rare=0.003449025
[epoch 000000081] loss=359.617712838 | avg=0.463521783 | rare=0.003591542
[epoch 000000082] loss=340.737419128 | avg=0.475317008 | rare=0.003402621
[epoch 000000083] loss=345.155200413 | avg=0.465922556 | rare=0.003446893
[epoch 000000084] loss=361.086860657 | avg=0.482006744 | rare=0.003606049
[epoch 000000085] loss=365.116568429 | avg=0.462278500 | rare=0.003646543
[epoch 000000086] loss=284.168469020 | avg=0.463941772 | rare=0.002837045
[epoch 000000087] loss=330.204421997 | avg=0.457363110 | rare=0.003297471
[epoch 000000088] loss=335.972351074 | avg=0.452063418 | rare=0.003355203
[epoch 000000089] loss=338.982729231 | avg=0.457032674 | rare=0.003385257
[epoch 000000090] loss=368.872876848 | avg=0.447264465 | rare=0.003684256
[epoch 000000091] loss=337.059626988 | avg=0.451590406 | rare=0.003366080
[epoch 000000092] loss=301.048736572 | avg=0.460347861 | rare=0.003005884
[epoch 000000093] loss=334.391734532 | avg=0.463371441 | rare=0.003339284
[epoch 000000094] loss=340.551235744 | avg=0.456227892 | rare=0.003400950
[epoch 000000095] loss=336.087820871 | avg=0.453016801 | rare=0.003356348
[epoch 000000096] loss=281.256052290 | avg=0.460329680 | rare=0.002807957
[epoch 000000097] loss=285.677637373 | avg=0.474489963 | rare=0.002852031
[epoch 000000098] loss=308.704302107 | avg=0.469273603 | rare=0.003082350
[epoch 000000099] loss=273.257979257 | avg=0.462155312 | rare=0.002727958
[epoch 000000100] loss=304.161221095 | avg=0.461598211 | rare=0.003036996
[epoch 000000101] loss=289.439367022 | avg=0.469922345 | rare=0.002889694
[epoch 000000102] loss=274.747183664 | avg=0.460201206 | rare=0.002742870
[epoch 000000103] loss=246.797477722 | avg=0.487976430 | rare=0.002463095
[epoch 000000104] loss=362.718231201 | avg=0.459935765 | rare=0.003622583
[epoch 000000105] loss=305.958156041 | avg=0.458941160 | rare=0.003054992
[epoch 000000106] loss=297.182982309 | avg=0.458482185 | rare=0.002967245
[epoch 000000107] loss=298.638071333 | avg=0.454785404 | rare=0.002981833
[epoch 000000108] loss=254.218360901 | avg=0.476707940 | rare=0.002537417
[epoch 000000109] loss=311.230937958 | avg=0.460144281 | rare=0.003107708
[epoch 000000110] loss=326.630802699 | avg=0.457027169 | rare=0.003261738
[epoch 000000111] loss=272.425494603 | avg=0.455931930 | rare=0.002719696
[epoch 000000112] loss=284.469314575 | avg=0.453390273 | rare=0.002840159
[epoch 000000113] loss=257.812601362 | avg=0.457773315 | rare=0.002573548
[epoch 000000114] loss=244.698775155 | avg=0.460691124 | rare=0.002442381
[epoch 000000115] loss=306.925295149 | avg=0.449975970 | rare=0.003064753
[epoch 000000116] loss=252.629950387 | avg=0.464863500 | rare=0.002521651
[epoch 000000117] loss=271.934532166 | avg=0.462713891 | rare=0.002714718
[epoch 000000118] loss=283.029538836 | avg=0.468591826 | rare=0.002825609
[epoch 000000119] loss=327.275330680 | avg=0.460948427 | rare=0.003268144
[epoch 000000120] loss=297.701071603 | avg=0.460323163 | rare=0.002972407
[epoch 000000121] loss=297.074887957 | avg=0.460869429 | rare=0.002966140
[epoch 000000122] loss=286.347380502 | avg=0.455023968 | rare=0.002858924
[epoch 000000123] loss=241.739328657 | avg=0.461428638 | rare=0.002412779
[epoch 000000124] loss=232.963029044 | avg=0.455290392 | rare=0.002325077
[epoch 000000125] loss=272.263158526 | avg=0.455236980 | rare=0.002718079
[epoch 000000126] loss=286.185927255 | avg=0.451488058 | rare=0.002857344
[epoch 000000127] loss=288.532430376 | avg=0.454039295 | rare=0.002880784
[epoch 000000128] loss=289.103691101 | avg=0.454629532 | rare=0.002886491
[epoch 000000129] loss=262.313699995 | avg=0.459124180 | rare=0.002618546
[epoch 000000130] loss=276.164244516 | avg=0.462405901 | rare=0.002757018
[epoch 000000131] loss=250.572881426 | avg=0.463610496 | rare=0.002501093
[epoch 000000132] loss=233.231992449 | avg=0.468542640 | rare=0.002327635
[epoch 000000133] loss=262.501816886 | avg=0.459579696 | rare=0.002620422
[epoch 000000134] loss=277.951563154 | avg=0.456325493 | rare=0.002774952
[epoch 000000135] loss=258.733450753 | avg=0.458507312 | rare=0.002582749
[epoch 000000136] loss=253.078800746 | avg=0.469712983 | rare=0.002526091
[epoch 000000137] loss=265.810251508 | avg=0.455844123 | rare=0.002653544
[epoch 000000138] loss=259.479954311 | avg=0.456899492 | rare=0.002590231
[epoch 000000139] loss=298.797210693 | avg=0.450327037 | rare=0.002983469
[epoch 000000140] loss=261.289835249 | avg=0.473587115 | rare=0.002608162
[epoch 000000141] loss=270.563228062 | avg=0.466256997 | rare=0.002700970
[epoch 000000142] loss=231.493303571 | avg=0.503242899 | rare=0.002309901
[epoch 000000143] loss=301.262271336 | avg=0.454150621 | rare=0.003008081
[epoch 000000144] loss=305.177413940 | avg=0.451595194 | rare=0.003047258
[epoch 000000145] loss=251.743184771 | avg=0.453314977 | rare=0.002512899
[epoch 000000146] loss=250.809317998 | avg=0.453987792 | rare=0.002503553
[epoch 000000147] loss=300.207520621 | avg=0.461539002 | rare=0.002997460
[epoch 000000148] loss=254.178549630 | avg=0.475485221 | rare=0.002537031
[epoch 000000149] loss=281.709232875 | avg=0.467897000 | rare=0.002812413
[epoch 000000150] loss=258.863390241 | avg=0.492940520 | rare=0.002583704
[epoch 000000151] loss=280.482226236 | avg=0.556921659 | rare=0.002799253
[epoch 000000152] loss=242.173198700 | avg=0.490828540 | rare=0.002416824
[epoch 000000153] loss=299.420403617 | avg=0.461850679 | rare=0.002989586
[epoch 000000154] loss=287.327092852 | avg=0.465866046 | rare=0.002868612
[epoch 000000155] loss=301.378199986 | avg=0.454973613 | rare=0.003009232
[epoch 000000156] loss=285.416118077 | avg=0.451479454 | rare=0.002849646
[epoch 000000157] loss=316.754059928 | avg=0.445682909 | rare=0.003163084
[epoch 000000158] loss=257.144171579 | avg=0.449399163 | rare=0.002566948
[epoch 000000159] loss=240.225596837 | avg=0.452229611 | rare=0.002397734
[epoch 000000160] loss=237.551049369 | avg=0.457279797 | rare=0.002370938
[epoch 000000161] loss=293.937857492 | avg=0.458734851 | rare=0.002934791
[epoch 000000162] loss=279.517220633 | avg=0.451095756 | rare=0.002790661
[epoch 000000163] loss=241.882302420 | avg=0.456323839 | rare=0.002414260
[epoch 000000164] loss=243.674410139 | avg=0.449621692 | rare=0.002432248
[epoch 000000165] loss=255.995958601 | avg=0.448544140 | rare=0.002555474
[epoch 000000166] loss=208.488189152 | avg=0.454999817 | rare=0.002080332
[epoch 000000167] loss=234.518246242 | avg=0.464234150 | rare=0.002340540
[epoch 000000168] loss=215.219466073 | avg=0.465723670 | rare=0.002147537
[epoch 000000169] loss=235.334601266 | avg=0.454618837 | rare=0.002348800
[epoch 000000170] loss=273.408526829 | avg=0.450031989 | rare=0.002729585
[epoch 000000171] loss=282.854157584 | avg=0.447765540 | rare=0.002824064
[epoch 000000172] loss=224.309335981 | avg=0.452745961 | rare=0.002238566
[epoch 000000173] loss=240.999754769 | avg=0.446843526 | rare=0.002405529
[epoch 000000174] loss=279.831764221 | avg=0.447371855 | rare=0.002793844
[epoch 000000175] loss=239.465900966 | avg=0.448413811 | rare=0.002390175
[epoch 000000176] loss=209.100125994 | avg=0.465347497 | rare=0.002086348
[epoch 000000177] loss=258.070241656 | avg=0.452283883 | rare=0.002576180
[epoch 000000178] loss=231.444269453 | avg=0.467242445 | rare=0.002309770
[epoch 000000179] loss=221.161251613 | avg=0.450843249 | rare=0.002207104
[epoch 000000180] loss=220.940475464 | avg=0.455182501 | rare=0.002204853
[epoch 000000181] loss=226.986209324 | avg=0.478157537 | rare=0.002265081
[epoch 000000182] loss=282.324424744 | avg=0.480302498 | rare=0.002818441
[epoch 000000183] loss=278.094775609 | avg=0.505080457 | rare=0.002775897
[epoch 000000184] loss=279.792861938 | avg=0.477440977 | rare=0.002793154
[epoch 000000185] loss=197.660922459 | avg=0.471159920 | rare=0.001971898
[epoch 000000186] loss=261.024501256 | avg=0.448013063 | rare=0.002605765
[epoch 000000187] loss=243.004151481 | avg=0.456315024 | rare=0.002425478
[epoch 000000188] loss=213.446297237 | avg=0.456492558 | rare=0.002129898
[epoch 000000189] loss=257.483125959 | avg=0.454490919 | rare=0.002570286
[epoch 000000190] loss=218.019769941 | avg=0.460724679 | rare=0.002175590
[epoch 000000191] loss=266.616959708 | avg=0.455494898 | rare=0.002661615
[epoch 000000192] loss=251.459855216 | avg=0.461891179 | rare=0.002509980
[epoch 000000193] loss=275.286439623 | avg=0.464383662 | rare=0.002748221
[epoch 000000194] loss=203.573014941 | avg=0.458778341 | rare=0.002031142
[epoch 000000195] loss=228.444196974 | avg=0.454153112 | rare=0.002279900
[epoch 000000196] loss=255.854937962 | avg=0.456440576 | rare=0.002553985
[epoch 000000197] loss=238.836660658 | avg=0.455448734 | rare=0.002383812
[epoch 000000198] loss=203.607465472 | avg=0.468021618 | rare=0.002031394
[epoch 000000199] loss=206.200068883 | avg=0.461462981 | rare=0.002057386
[epoch 000000200] loss=237.002936227 | avg=0.454845116 | rare=0.002365481

Training safe with adam...

Epochs:   0%|          | 0/200 [00:00<?, ?it/s]

[epoch 000000001] loss=142.110842296 | avg=49.984584263 | rare=0.000921263
[epoch 000000002] loss=147.696747099 | avg=49.040500096 | rare=0.000986562
[epoch 000000003] loss=251.743070330 | avg=45.826668603 | rare=0.002059164
[epoch 000000004] loss=461.958191190 | avg=41.843075888 | rare=0.004201151
[epoch 000000005] loss=3968.947060721 | avg=35.883811542 | rare=0.039330632
[epoch 000000006] loss=9021.028982980 | avg=28.128732136 | rare=0.089929002
[epoch 000000007] loss=19271.093889509 | avg=19.717930249 | rare=0.192513762
[epoch 000000008] loss=13522.992850167 | avg=17.818716390 | rare=0.135051742
[epoch 000000009] loss=12219.516496931 | avg=15.806239809 | rare=0.122037103
[epoch 000000010] loss=9897.162597656 | avg=15.614900248 | rare=0.098815479
[epoch 000000011] loss=9081.801967076 | avg=14.570928914 | rare=0.090672310
[epoch 000000012] loss=8361.657226562 | avg=14.411844935 | rare=0.083472453
[epoch 000000013] loss=7143.378243583 | avg=13.817160130 | rare=0.071295611
[epoch 000000014] loss=8577.607770647 | avg=12.507369927 | rare=0.085651004
[epoch 000000015] loss=6797.786900112 | avg=12.638318675 | rare=0.067851486
[epoch 000000016] loss=9454.361990792 | avg=11.284354959 | rare=0.094430777
[epoch 000000017] loss=9508.259033203 | avg=9.816602366 | rare=0.094984423
[epoch 000000018] loss=8455.436209542 | avg=8.853057623 | rare=0.084465831
[epoch 000000019] loss=6425.606236049 | avg=9.120535782 | rare=0.064164858
[epoch 000000020] loss=6833.342424665 | avg=8.768757514 | rare=0.068245737
[epoch 000000021] loss=6047.213623047 | avg=8.821967806 | rare=0.060383917
[epoch 000000022] loss=5732.722464425 | avg=8.570429291 | rare=0.057241521
[epoch 000000023] loss=5705.149588449 | avg=8.365312508 | rare=0.056967843
[epoch 000000024] loss=5239.089878627 | avg=8.284739358 | rare=0.052308051
[epoch 000000025] loss=5648.419817243 | avg=8.247125489 | rare=0.056401726
[epoch 000000026] loss=4995.382254464 | avg=8.389948368 | rare=0.049869923
[epoch 000000027] loss=5805.521641323 | avg=8.171145848 | rare=0.057973505
[epoch 000000028] loss=4881.551164900 | avg=8.238815614 | rare=0.048733123
[epoch 000000029] loss=5047.098946708 | avg=8.072092397 | rare=0.050390268
[epoch 000000030] loss=4763.177071708 | avg=8.005710500 | rare=0.047551714
[epoch 000000031] loss=5063.379220145 | avg=7.890938112 | rare=0.050554883
[epoch 000000032] loss=5080.472481864 | avg=7.926703930 | rare=0.050725458
[epoch 000000033] loss=4833.115966797 | avg=7.910325766 | rare=0.048252057
[epoch 000000034] loss=4798.950631278 | avg=7.638221400 | rare=0.047913124
[epoch 000000035] loss=4866.051914760 | avg=7.596347707 | rare=0.048584555
[epoch 000000036] loss=4770.084647042 | avg=7.502289023 | rare=0.047625824
[epoch 000000037] loss=5030.569893973 | avg=7.420393671 | rare=0.050231495
[epoch 000000038] loss=5123.619716099 | avg=7.620487179 | rare=0.051159992
[epoch 000000039] loss=5320.042201451 | avg=7.599462543 | rare=0.053124427
[epoch 000000040] loss=5669.825195312 | avg=7.545478889 | rare=0.056622797
[epoch 000000041] loss=5054.138898577 | avg=7.510761295 | rare=0.050466282
[epoch 000000042] loss=4950.787981306 | avg=7.518551826 | rare=0.049432693
[epoch 000000043] loss=4874.306658064 | avg=7.507438557 | rare=0.048667992
[epoch 000000044] loss=4865.714024135 | avg=7.432739428 | rare=0.048582813
[epoch 000000045] loss=4577.704328265 | avg=7.598626205 | rare=0.045701057
[epoch 000000046] loss=4954.008108956 | avg=7.483716794 | rare=0.049465244
[epoch 000000047] loss=4466.883946010 | avg=7.759558575 | rare=0.044591244
[epoch 000000048] loss=4867.191179548 | avg=7.596696820 | rare=0.048595944
[epoch 000000049] loss=4609.563302176 | avg=7.707313674 | rare=0.046018559
[epoch 000000050] loss=4369.766270229 | avg=8.138583115 | rare=0.043616277
[epoch 000000051] loss=5093.372994559 | avg=7.655625105 | rare=0.050857173
[epoch 000000052] loss=4738.263357980 | avg=7.753460509 | rare=0.047305098
[epoch 000000053] loss=4364.807460240 | avg=7.755199092 | rare=0.043570522
[epoch 000000054] loss=4351.434273856 | avg=7.674362217 | rare=0.043437599
[epoch 000000055] loss=4173.655831473 | avg=7.780796187 | rare=0.041658750
[epoch 000000056] loss=4430.937709263 | avg=7.604947601 | rare=0.044233327
[epoch 000000057] loss=4357.080235073 | avg=7.573057038 | rare=0.043495072
[epoch 000000058] loss=4269.646920340 | avg=7.827639614 | rare=0.042618193
[epoch 000000059] loss=4379.797589983 | avg=7.667117153 | rare=0.043721305
[epoch 000000060] loss=4272.733224051 | avg=7.877867324 | rare=0.042648554
[epoch 000000061] loss=4520.801949637 | avg=7.744757278 | rare=0.045130572
[epoch 000000062] loss=4458.237043108 | avg=7.765390260 | rare=0.044504716
[epoch 000000063] loss=4473.657967704 | avg=7.722804240 | rare=0.044659352
[epoch 000000064] loss=4375.118164062 | avg=7.709270035 | rare=0.043674088
[epoch 000000065] loss=4716.276881627 | avg=7.717535257 | rare=0.047085594
[epoch 000000066] loss=4538.831874302 | avg=7.652215549 | rare=0.045311796
[epoch 000000067] loss=4659.363752093 | avg=7.478734425 | rare=0.046518850
[epoch 000000068] loss=4598.595755441 | avg=7.399461882 | rare=0.045911963
[epoch 000000069] loss=5244.074148996 | avg=7.073353291 | rare=0.052370008
[epoch 000000070] loss=4608.506365095 | avg=7.508339337 | rare=0.046009980
[epoch 000000071] loss=4664.554792132 | avg=7.523433004 | rare=0.046570315
[epoch 000000072] loss=4987.352329799 | avg=7.292819466 | rare=0.049800594
[epoch 000000073] loss=3760.823617118 | avg=7.994282893 | rare=0.037528293
[epoch 000000074] loss=4657.081909180 | avg=7.445431811 | rare=0.046496365
[epoch 000000075] loss=4393.193307059 | avg=7.519359452 | rare=0.043856739
[epoch 000000076] loss=5262.921892439 | avg=7.322457314 | rare=0.052555995
[epoch 000000077] loss=4072.694684710 | avg=7.944799185 | rare=0.040647499
[epoch 000000078] loss=4742.613019671 | avg=7.540158442 | rare=0.047350729
[epoch 000000079] loss=4371.687630790 | avg=7.494641304 | rare=0.043641930
[epoch 000000080] loss=4410.543753488 | avg=7.635867528 | rare=0.044029078
[epoch 000000081] loss=4230.549979074 | avg=7.499321801 | rare=0.042230506
[epoch 000000082] loss=4566.546264648 | avg=7.284766436 | rare=0.045592615
[epoch 000000083] loss=4466.025285993 | avg=7.663818870 | rare=0.044583615
[epoch 000000084] loss=5375.862304688 | avg=7.288270065 | rare=0.053685740
[epoch 000000085] loss=4681.632376535 | avg=7.393808603 | rare=0.046742387
[epoch 000000086] loss=4511.040693011 | avg=7.320480687 | rare=0.045037202
[epoch 000000087] loss=4339.642438616 | avg=7.267898287 | rare=0.043323746
[epoch 000000088] loss=4847.234095982 | avg=6.977216516 | rare=0.048402569
[epoch 000000089] loss=4811.420567104 | avg=7.345035860 | rare=0.048040755
[epoch 000000090] loss=4770.007899693 | avg=7.303417070 | rare=0.047627045
[epoch 000000091] loss=4228.005754743 | avg=7.366081170 | rare=0.042206396
[epoch 000000092] loss=4579.712733677 | avg=7.148059300 | rare=0.045725646
[epoch 000000093] loss=4567.078508650 | avg=7.063021081 | rare=0.045600155
[epoch 000000094] loss=4213.703927176 | avg=7.668668100 | rare=0.042060353
[epoch 000000095] loss=4712.842459542 | avg=7.301726818 | rare=0.047055408
[epoch 000000096] loss=5265.433471680 | avg=7.186753511 | rare=0.052582467
[epoch 000000097] loss=4707.507097517 | avg=7.614562477 | rare=0.046998924
[epoch 000000098] loss=4315.095842634 | avg=7.217891318 | rare=0.043078780
[epoch 000000099] loss=4320.515738351 | avg=7.275274175 | rare=0.043132405
[epoch 000000100] loss=4779.806745257 | avg=7.143809761 | rare=0.047726629
[epoch 000000101] loss=5068.199201311 | avg=7.197019543 | rare=0.050610023
[epoch 000000102] loss=4892.193062919 | avg=6.968145234 | rare=0.048852250
[epoch 000000103] loss=4769.823015485 | avg=6.933015721 | rare=0.047628899
[epoch 000000104] loss=4645.383632115 | avg=7.089199373 | rare=0.046382944
[epoch 000000105] loss=4641.772583008 | avg=6.944364820 | rare=0.046348282
[epoch 000000106] loss=4503.319649833 | avg=6.992294414 | rare=0.044963274
[epoch 000000107] loss=4690.325788225 | avg=6.993616922 | rare=0.046833321
[epoch 000000108] loss=4856.342633929 | avg=7.041133336 | rare=0.048493015
[epoch 000000109] loss=4423.627982003 | avg=7.100287608 | rare=0.044165277
[epoch 000000110] loss=4418.873570033 | avg=7.252884013 | rare=0.044116206
[epoch 000000111] loss=4699.250313895 | avg=7.134632928 | rare=0.046921157
[epoch 000000112] loss=4778.948346819 | avg=7.176753998 | rare=0.047717715
[epoch 000000113] loss=4895.347865513 | avg=7.088236673 | rare=0.048882596
[epoch 000000114] loss=3608.753173828 | avg=7.530689512 | rare=0.036012225
[epoch 000000115] loss=4713.092302595 | avg=7.138944183 | rare=0.047059533
[epoch 000000116] loss=4927.745099749 | avg=6.967834370 | rare=0.049207773
[epoch 000000117] loss=4982.404453823 | avg=6.984297616 | rare=0.049754202
[epoch 000000118] loss=4583.384190151 | avg=7.171928440 | rare=0.045762123
[epoch 000000119] loss=4649.195085798 | avg=7.090839420 | rare=0.046421042
[epoch 000000120] loss=4624.585850307 | avg=7.022052084 | rare=0.046175638
[epoch 000000121] loss=4816.945539202 | avg=7.074149404 | rare=0.048098714
[epoch 000000122] loss=4526.025303432 | avg=7.043563468 | rare=0.045189818
[epoch 000000123] loss=4568.152709961 | avg=7.029985189 | rare=0.045611228
[epoch 000000124] loss=4504.688023158 | avg=7.094536543 | rare=0.044975935
[epoch 000000125] loss=4228.321637835 | avg=6.917279857 | rare=0.042214043
[epoch 000000126] loss=5048.095023019 | avg=6.921340704 | rare=0.050411737
[epoch 000000127] loss=4525.990251814 | avg=7.125610862 | rare=0.045188646
[epoch 000000128] loss=5103.534755162 | avg=6.925804819 | rare=0.050966089
[epoch 000000129] loss=4545.693568638 | avg=6.950587205 | rare=0.045387430
[epoch 000000130] loss=4951.067330497 | avg=7.017025914 | rare=0.049440503
[epoch 000000131] loss=4154.853088379 | avg=7.478216001 | rare=0.041473748
[epoch 000000132] loss=5148.119210379 | avg=6.998554638 | rare=0.051411206
[epoch 000000133] loss=4655.925223214 | avg=6.939960616 | rare=0.046489853
[epoch 000000134] loss=4918.567173549 | avg=7.027159827 | rare=0.049115399
[epoch 000000135] loss=5084.124703544 | avg=7.079068082 | rare=0.050770456
[epoch 000000136] loss=4623.259225028 | avg=6.930650064 | rare=0.046163286
[epoch 000000137] loss=5368.051897321 | avg=6.945284333 | rare=0.053611067
[epoch 000000138] loss=4909.943568638 | avg=7.098489387 | rare=0.049028451
[epoch 000000139] loss=5174.080827985 | avg=6.917895215 | rare=0.051671630
[epoch 000000140] loss=5401.242239816 | avg=6.811105864 | rare=0.053944311
[epoch 000000141] loss=5202.874529157 | avg=6.797424112 | rare=0.051960771
[epoch 000000142] loss=4773.420671735 | avg=7.123528276 | rare=0.047662972
[epoch 000000143] loss=5096.439278739 | avg=6.979766437 | rare=0.050894594
[epoch 000000144] loss=5594.219813756 | avg=6.823255777 | rare=0.055873966
[epoch 000000145] loss=5479.475725446 | avg=6.903521265 | rare=0.054725722
[epoch 000000146] loss=5546.139526367 | avg=6.951304674 | rare=0.055391882
[epoch 000000147] loss=5860.736188616 | avg=6.782207523 | rare=0.058539539
[epoch 000000148] loss=5949.055629185 | avg=6.716296503 | rare=0.059423393
[epoch 000000149] loss=5365.309221540 | avg=6.829305819 | rare=0.053584800
[epoch 000000150] loss=5482.523786272 | avg=6.910422291 | rare=0.054756133
[epoch 000000151] loss=5246.327008929 | avg=6.818848031 | rare=0.052395081
[epoch 000000152] loss=5379.236188616 | avg=6.802162170 | rare=0.053724340
[epoch 000000153] loss=5336.020804269 | avg=6.862139634 | rare=0.053291587
[epoch 000000154] loss=5282.350411551 | avg=6.869735956 | rare=0.052754807
[epoch 000000155] loss=6013.223266602 | avg=6.699501276 | rare=0.060065237
[epoch 000000156] loss=6030.265241350 | avg=6.758165734 | rare=0.060235070
[epoch 000000157] loss=6205.926583426 | avg=6.711549214 | rare=0.061992151
[epoch 000000158] loss=6952.224155971 | avg=6.576239347 | rare=0.069456480
[epoch 000000159] loss=6005.501081194 | avg=6.746020658 | rare=0.059987552
[epoch 000000160] loss=6000.031075614 | avg=6.919816392 | rare=0.059931113
[epoch 000000161] loss=6177.221784319 | avg=6.763927732 | rare=0.061704579
[epoch 000000162] loss=6403.503923689 | avg=6.774186645 | rare=0.063967297
[epoch 000000163] loss=6161.062116350 | avg=6.796776056 | rare=0.061542654
[epoch 000000164] loss=6445.614571708 | avg=6.713502816 | rare=0.064389010
[epoch 000000165] loss=6463.298461914 | avg=6.777222054 | rare=0.064565213
[epoch 000000166] loss=6443.147042411 | avg=6.766427619 | rare=0.064363806
[epoch 000000167] loss=6715.038783482 | avg=6.661182778 | rare=0.067083777
[epoch 000000168] loss=6225.764334542 | avg=6.821796758 | rare=0.062189425
[epoch 000000169] loss=5865.980643136 | avg=6.789609296 | rare=0.058591911
[epoch 000000170] loss=7408.348911830 | avg=6.684370007 | rare=0.074016646
[epoch 000000171] loss=7522.163783482 | avg=6.864504984 | rare=0.075152992
[epoch 000000172] loss=6582.482596261 | avg=6.825351817 | rare=0.065756573
[epoch 000000173] loss=6249.971383231 | avg=6.857669592 | rare=0.062431137
[epoch 000000174] loss=6825.474400112 | avg=6.727994817 | rare=0.068187464
[epoch 000000175] loss=6542.877598354 | avg=6.743481159 | rare=0.065361341
[epoch 000000176] loss=6832.137241908 | avg=6.607978991 | rare=0.068255292
[epoch 000000177] loss=6325.476806641 | avg=6.731919765 | rare=0.063187449
[epoch 000000178] loss=6174.644165039 | avg=6.792883532 | rare=0.061678513
[epoch 000000179] loss=6171.233171735 | avg=6.924397298 | rare=0.061643087
[epoch 000000180] loss=6405.109549386 | avg=6.769031218 | rare=0.063983406
[epoch 000000181] loss=6487.939976283 | avg=6.709110873 | rare=0.064812309
[epoch 000000182] loss=5776.032435826 | avg=6.930703265 | rare=0.057691017
[epoch 000000183] loss=6924.552769252 | avg=6.730291333 | rare=0.069178225
[epoch 000000184] loss=6545.322335379 | avg=6.727320978 | rare=0.065385951
[epoch 000000185] loss=6455.093436105 | avg=6.707480465 | rare=0.064483859
[epoch 000000186] loss=6477.535208566 | avg=6.770473923 | rare=0.064707647
[epoch 000000187] loss=6828.745744978 | avg=6.680395637 | rare=0.068220654
[epoch 000000188] loss=6658.471348354 | avg=6.667003802 | rare=0.066518043
[epoch 000000189] loss=6978.956682478 | avg=6.953213181 | rare=0.069720034
[epoch 000000190] loss=6539.661621094 | avg=6.767168760 | rare=0.065328945
[epoch 000000191] loss=6982.923706055 | avg=6.723336560 | rare=0.069762003
[epoch 000000192] loss=6431.422781808 | avg=6.781370435 | rare=0.064246414
[epoch 000000193] loss=7058.791573661 | avg=6.709882668 | rare=0.070520818
[epoch 000000194] loss=6656.184814453 | avg=6.840092829 | rare=0.066493448
[epoch 000000195] loss=6733.778355190 | avg=6.691064937 | rare=0.067270873
[epoch 000000196] loss=6904.739676339 | avg=6.714723723 | rare=0.068980250
[epoch 000000197] loss=6874.978969029 | avg=6.682531323 | rare=0.068682964
[epoch 000000198] loss=5746.862897600 | avg=6.979846171 | rare=0.057398830
[epoch 000000199] loss=6723.205531529 | avg=6.826544183 | rare=0.067163790
[epoch 000000200] loss=6734.213169643 | avg=6.759088993 | rare=0.067274541
Accuracy: 82.41%  (CI 95%: [81.33%, 83.44%])
Robust Accuracy: 82.22415%  (CI 95%: [81.32282%, 83.32266%])
Conditional Robust Accuracy: 98.71969%  (CI 95%: [98.54573%, 98.89184%])
Accuracy: 82.91%  (CI 95%: [81.84%, 83.92%])
Robust Accuracy: 82.76660%  (CI 95%: [81.88021%, 83.76530%])
Conditional Robust Accuracy: 98.95123%  (CI 95%: [98.78163%, 99.09915%])
  --> Running Seed: 100

Training naive with adam...

Epochs:   0%|          | 0/200 [00:00<?, ?it/s]

[epoch 000000001] loss=178466.601562500 | avg=0.319753973 | rare=1.784662809
[epoch 000000002] loss=178522.145089286 | avg=0.320083375 | rare=1.785218264
[epoch 000000003] loss=133744.394531250 | avg=0.602276689 | rare=1.337437911
[epoch 000000004] loss=12189.759242467 | avg=2.664157646 | rare=0.121870950
[epoch 000000005] loss=5650.860107422 | avg=2.787568978 | rare=0.056480725
[epoch 000000006] loss=6533.599609375 | avg=2.320670826 | rare=0.065312790
[epoch 000000007] loss=5169.777675084 | avg=2.428375721 | rare=0.051673493
[epoch 000000008] loss=4210.869035993 | avg=2.503325343 | rare=0.042083658
[epoch 000000009] loss=4100.584333147 | avg=2.416922706 | rare=0.040981674
[epoch 000000010] loss=3453.689644950 | avg=2.440143704 | rare=0.034512495
[epoch 000000011] loss=3335.734357561 | avg=2.306573970 | rare=0.033334278
[epoch 000000012] loss=2762.754167829 | avg=2.265619516 | rare=0.027604885
[epoch 000000013] loss=3514.911167690 | avg=1.964211711 | rare=0.035129470
[epoch 000000014] loss=2951.719883510 | avg=1.862865031 | rare=0.029498570
[epoch 000000015] loss=3665.578665597 | avg=1.531410413 | rare=0.036640472
[epoch 000000016] loss=4150.807948521 | avg=1.340707566 | rare=0.041494672
[epoch 000000017] loss=5801.624825614 | avg=1.003161758 | rare=0.058006216
[epoch 000000018] loss=4849.605294364 | avg=0.859243120 | rare=0.048487461
[epoch 000000019] loss=3817.229823521 | avg=0.818338871 | rare=0.038164115
[epoch 000000020] loss=3058.826154436 | avg=0.797297657 | rare=0.030580288
[epoch 000000021] loss=2723.749084473 | avg=0.771108921 | rare=0.027229780
[epoch 000000022] loss=2459.266549247 | avg=0.746192064 | rare=0.024585203
[epoch 000000023] loss=2087.490173340 | avg=0.711390257 | rare=0.020867788
[epoch 000000024] loss=2002.229788644 | avg=0.684404041 | rare=0.020015454
[epoch 000000025] loss=1768.378941127 | avg=0.676784728 | rare=0.017677022
[epoch 000000026] loss=1706.611136300 | avg=0.676856935 | rare=0.017059343
[epoch 000000027] loss=1604.348885672 | avg=0.647066644 | rare=0.016037018
[epoch 000000028] loss=1481.480276925 | avg=0.621786164 | rare=0.014808585
[epoch 000000029] loss=1511.317574637 | avg=0.586195916 | rare=0.015107314
[epoch 000000030] loss=1467.520804269 | avg=0.565514066 | rare=0.014669553
[epoch 000000031] loss=1419.344011579 | avg=0.548277808 | rare=0.014187957
[epoch 000000032] loss=1265.310193743 | avg=0.536931815 | rare=0.012647733
[epoch 000000033] loss=1259.620269775 | avg=0.525742520 | rare=0.012590945
[epoch 000000034] loss=1579.453451974 | avg=0.517399441 | rare=0.015789361
[epoch 000000035] loss=1332.625030518 | avg=0.557412205 | rare=0.013320676
[epoch 000000036] loss=1198.683776855 | avg=0.532471425 | rare=0.011981513
[epoch 000000037] loss=1074.725899833 | avg=0.496826223 | rare=0.010742291
[epoch 000000038] loss=1121.177716936 | avg=0.516271082 | rare=0.011206614
[epoch 000000039] loss=1034.342891148 | avg=0.489318939 | rare=0.010338536
[epoch 000000040] loss=1058.742422921 | avg=0.473102533 | rare=0.010582693
[epoch 000000041] loss=1101.418657575 | avg=0.465520344 | rare=0.011009531
[epoch 000000042] loss=1042.120387486 | avg=0.469451811 | rare=0.010416509
[epoch 000000043] loss=852.075687953 | avg=0.474920914 | rare=0.008516008
[epoch 000000044] loss=873.012180873 | avg=0.459993196 | rare=0.008725522
[epoch 000000045] loss=826.487895421 | avg=0.457117432 | rare=0.008260308
[epoch 000000046] loss=784.869796753 | avg=0.461634229 | rare=0.007844082
[epoch 000000047] loss=784.752624512 | avg=0.448580031 | rare=0.007843040
[epoch 000000048] loss=733.561194284 | avg=0.455732284 | rare=0.007331055
[epoch 000000049] loss=633.894308908 | avg=0.460481891 | rare=0.006334338
[epoch 000000050] loss=561.460815430 | avg=0.464196124 | rare=0.005609966
[epoch 000000051] loss=696.536747524 | avg=0.460600855 | rare=0.006960761
[epoch 000000052] loss=660.583999634 | avg=0.450964255 | rare=0.006601330
[epoch 000000053] loss=640.829467773 | avg=0.459113466 | rare=0.006403704
[epoch 000000054] loss=582.012996129 | avg=0.463036150 | rare=0.005815499
[epoch 000000055] loss=576.965794155 | avg=0.460405077 | rare=0.005765054
[epoch 000000056] loss=551.130900792 | avg=0.450857950 | rare=0.005506800
[epoch 000000057] loss=464.011620658 | avg=0.459869587 | rare=0.004635518
[epoch 000000058] loss=491.741956438 | avg=0.457692587 | rare=0.004912843
[epoch 000000059] loss=562.950729370 | avg=0.460882034 | rare=0.005624898
[epoch 000000060] loss=574.819671631 | avg=0.453672362 | rare=0.005743660
[epoch 000000061] loss=430.399744306 | avg=0.461524118 | rare=0.004299382
[epoch 000000062] loss=451.161235264 | avg=0.458447476 | rare=0.004507028
[epoch 000000063] loss=401.039411272 | avg=0.472753925 | rare=0.004005667
[epoch 000000064] loss=478.590887887 | avg=0.459638464 | rare=0.004781313
[epoch 000000065] loss=462.372931344 | avg=0.466281384 | rare=0.004619066
[epoch 000000066] loss=411.268477304 | avg=0.457948795 | rare=0.004108105
[epoch 000000067] loss=411.118473598 | avg=0.457526633 | rare=0.004106609
[epoch 000000068] loss=399.640630450 | avg=0.462239891 | rare=0.003991784
[epoch 000000069] loss=415.216757638 | avg=0.463712931 | rare=0.004147530
[epoch 000000070] loss=447.544229780 | avg=0.468263445 | rare=0.004470760
[epoch 000000071] loss=422.750924247 | avg=0.487270723 | rare=0.004222637
[epoch 000000072] loss=376.161348615 | avg=0.485007829 | rare=0.003756763
[epoch 000000073] loss=451.171336583 | avg=0.468110804 | rare=0.004507032
[epoch 000000074] loss=417.283993312 | avg=0.470375110 | rare=0.004168136
[epoch 000000075] loss=438.531461443 | avg=0.460390925 | rare=0.004380711
[epoch 000000076] loss=436.667088100 | avg=0.451729193 | rare=0.004362154
[epoch 000000077] loss=358.372629438 | avg=0.466438296 | rare=0.003579062
[epoch 000000078] loss=388.427638463 | avg=0.458841232 | rare=0.003879688
[epoch 000000079] loss=390.702414376 | avg=0.460973652 | rare=0.003902414
[epoch 000000080] loss=359.390671866 | avg=0.462994343 | rare=0.003589277
[epoch 000000081] loss=368.546721322 | avg=0.459515414 | rare=0.003680872
[epoch 000000082] loss=364.327135359 | avg=0.470141860 | rare=0.003638570
[epoch 000000083] loss=391.038431440 | avg=0.462783105 | rare=0.003905756
[epoch 000000084] loss=421.787756784 | avg=0.458487485 | rare=0.004213293
[epoch 000000085] loss=405.942685808 | avg=0.450243018 | rare=0.004054925
[epoch 000000086] loss=371.312846592 | avg=0.451476989 | rare=0.003708614
[epoch 000000087] loss=308.876729693 | avg=0.464642463 | rare=0.003084121
[epoch 000000088] loss=362.319060189 | avg=0.451320244 | rare=0.003618677
[epoch 000000089] loss=330.439291818 | avg=0.458792310 | rare=0.003299805
[epoch 000000090] loss=350.706766401 | avg=0.461856897 | rare=0.003502449
[epoch 000000091] loss=357.072540283 | avg=0.468135148 | rare=0.003566044
[epoch 000000092] loss=348.696065630 | avg=0.467034338 | rare=0.003482290
[epoch 000000093] loss=339.607430594 | avg=0.456950769 | rare=0.003391505
[epoch 000000094] loss=364.388630458 | avg=0.459874370 | rare=0.003639288
[epoch 000000095] loss=335.454426357 | avg=0.466163178 | rare=0.003349883
[epoch 000000096] loss=319.888798305 | avg=0.455503036 | rare=0.003194333
[epoch 000000097] loss=315.332726615 | avg=0.455721798 | rare=0.003148770
[epoch 000000098] loss=372.281441825 | avg=0.446438117 | rare=0.003718350
[epoch 000000099] loss=278.742015839 | avg=0.475735130 | rare=0.002782663
[epoch 000000100] loss=298.957733154 | avg=0.464987661 | rare=0.002984927
[epoch 000000101] loss=287.807225909 | avg=0.463694794 | rare=0.002873435
[epoch 000000102] loss=295.581436157 | avg=0.457599474 | rare=0.002951238
[epoch 000000103] loss=313.894413539 | avg=0.468872332 | rare=0.003134255
[epoch 000000104] loss=324.586097717 | avg=0.454408380 | rare=0.003241317
[epoch 000000105] loss=293.955856323 | avg=0.460283045 | rare=0.002934956
[epoch 000000106] loss=273.329151699 | avg=0.458355625 | rare=0.002728708
[epoch 000000107] loss=291.630152021 | avg=0.460467962 | rare=0.002911697
[epoch 000000108] loss=407.870981489 | avg=0.450727016 | rare=0.004074203
[epoch 000000109] loss=312.817561558 | avg=0.447997898 | rare=0.003123696
[epoch 000000110] loss=294.653112139 | avg=0.459207026 | rare=0.002941939
[epoch 000000111] loss=318.631501334 | avg=0.449388700 | rare=0.003181821
[epoch 000000112] loss=280.250452314 | avg=0.456808175 | rare=0.002797936
[epoch 000000113] loss=256.688775199 | avg=0.465087882 | rare=0.002562237
[epoch 000000114] loss=301.017519270 | avg=0.449504559 | rare=0.003005680
[epoch 000000115] loss=338.298842294 | avg=0.453223371 | rare=0.003378456
[epoch 000000116] loss=282.273757935 | avg=0.453668139 | rare=0.002818201
[epoch 000000117] loss=272.287767683 | avg=0.451610985 | rare=0.002718362
[epoch 000000118] loss=269.580342974 | avg=0.450817791 | rare=0.002691295
[epoch 000000119] loss=264.548049927 | avg=0.454374690 | rare=0.002640937
[epoch 000000120] loss=218.492348262 | avg=0.509853342 | rare=0.002179825
[epoch 000000121] loss=311.608239310 | avg=0.453547037 | rare=0.003111547
[epoch 000000122] loss=278.326395852 | avg=0.458943803 | rare=0.002778675
[epoch 000000123] loss=286.638214111 | avg=0.455856847 | rare=0.002861824
[epoch 000000124] loss=288.382762364 | avg=0.463236581 | rare=0.002879195
[epoch 000000125] loss=263.455907549 | avg=0.459121640 | rare=0.002629968
[epoch 000000126] loss=256.563147409 | avg=0.460086805 | rare=0.002561031
[epoch 000000127] loss=321.127029419 | avg=0.453266548 | rare=0.003206738
[epoch 000000128] loss=295.659576416 | avg=0.459455011 | rare=0.002952001
[epoch 000000129] loss=289.075487409 | avg=0.464241424 | rare=0.002886112
[epoch 000000130] loss=252.857815334 | avg=0.496776102 | rare=0.002523610
[epoch 000000131] loss=259.627116612 | avg=0.471947368 | rare=0.002591552
[epoch 000000132] loss=265.630343846 | avg=0.462894303 | rare=0.002651674
[epoch 000000133] loss=292.863361904 | avg=0.469203387 | rare=0.002923942
[epoch 000000134] loss=260.281932286 | avg=0.462589017 | rare=0.002598193
[epoch 000000135] loss=328.410257612 | avg=0.461587455 | rare=0.003279487
[epoch 000000136] loss=310.763827188 | avg=0.468137022 | rare=0.003102957
[epoch 000000137] loss=278.141084943 | avg=0.470359807 | rare=0.002776707
[epoch 000000138] loss=254.686446054 | avg=0.464093198 | rare=0.002542224
[epoch 000000139] loss=218.915358407 | avg=0.458819549 | rare=0.002184565
[epoch 000000140] loss=259.403410775 | avg=0.453710258 | rare=0.002589497
[epoch 000000141] loss=253.710692269 | avg=0.465535043 | rare=0.002532452
[epoch 000000142] loss=274.926872253 | avg=0.458483106 | rare=0.002744684
[epoch 000000143] loss=236.019594465 | avg=0.458421460 | rare=0.002355612
[epoch 000000144] loss=261.908744812 | avg=0.460039394 | rare=0.002614487
[epoch 000000145] loss=276.445377895 | avg=0.460301214 | rare=0.002759851
[epoch 000000146] loss=258.043382917 | avg=0.459828183 | rare=0.002575836
[epoch 000000147] loss=239.565326146 | avg=0.466654113 | rare=0.002390987
[epoch 000000148] loss=278.634566171 | avg=0.469173619 | rare=0.002781654
[epoch 000000149] loss=273.194038391 | avg=0.457369193 | rare=0.002727367
[epoch 000000150] loss=231.466154916 | avg=0.456147705 | rare=0.002310100
[epoch 000000151] loss=266.869764056 | avg=0.453164050 | rare=0.002664166
[epoch 000000152] loss=201.507477352 | avg=0.511141796 | rare=0.002009963
[epoch 000000153] loss=246.245463235 | avg=0.469787928 | rare=0.002457757
[epoch 000000154] loss=213.930058071 | avg=0.494234973 | rare=0.002134358
[epoch 000000155] loss=245.912197113 | avg=0.475158012 | rare=0.002454370
[epoch 000000156] loss=256.165343148 | avg=0.471121582 | rare=0.002556942
[epoch 000000157] loss=275.254015241 | avg=0.452886573 | rare=0.002748011
[epoch 000000158] loss=253.612573896 | avg=0.451053994 | rare=0.002531615
[epoch 000000159] loss=243.342967442 | avg=0.459983713 | rare=0.002428830
[epoch 000000160] loss=212.552353995 | avg=0.457444774 | rare=0.002120949
[epoch 000000161] loss=196.384020124 | avg=0.468668987 | rare=0.001959154
[epoch 000000162] loss=246.530289241 | avg=0.453110963 | rare=0.002460772
[epoch 000000163] loss=271.286707197 | avg=0.452919338 | rare=0.002708338
[epoch 000000164] loss=250.515961783 | avg=0.456238725 | rare=0.002500597
[epoch 000000165] loss=241.310223171 | avg=0.462088683 | rare=0.002408481
[epoch 000000166] loss=286.396133968 | avg=0.459165318 | rare=0.002859370
[epoch 000000167] loss=248.100719997 | avg=0.459926486 | rare=0.002476408
[epoch 000000168] loss=292.156768799 | avg=0.456725340 | rare=0.002917000
[epoch 000000169] loss=243.446106502 | avg=0.470481996 | rare=0.002429756
[epoch 000000170] loss=293.782721383 | avg=0.460527716 | rare=0.002933222
[epoch 000000171] loss=241.274689266 | avg=0.503487112 | rare=0.002407712
[epoch 000000172] loss=273.978240967 | avg=0.473244993 | rare=0.002735050
[epoch 000000173] loss=247.430022103 | avg=0.465334247 | rare=0.002469647
[epoch 000000174] loss=223.565768106 | avg=0.475657414 | rare=0.002230901
[epoch 000000175] loss=259.007759094 | avg=0.487090454 | rare=0.002585207
[epoch 000000176] loss=270.451262338 | avg=0.476020313 | rare=0.002699752
[epoch 000000177] loss=266.719045367 | avg=0.482954436 | rare=0.002662361
[epoch 000000178] loss=286.206439427 | avg=0.462653422 | rare=0.002857438
[epoch 000000179] loss=218.228833880 | avg=0.465448752 | rare=0.002177634
[epoch 000000180] loss=266.048012325 | avg=0.463824266 | rare=0.002655842
[epoch 000000181] loss=272.746278490 | avg=0.485816391 | rare=0.002722605
[epoch 000000182] loss=312.373058864 | avg=0.506673381 | rare=0.003118664
[epoch 000000183] loss=244.700247628 | avg=0.466788073 | rare=0.002442335
[epoch 000000184] loss=230.476967403 | avg=0.463112069 | rare=0.002300139
[epoch 000000185] loss=243.575802394 | avg=0.461603690 | rare=0.002431142
[epoch 000000186] loss=238.141603742 | avg=0.454676222 | rare=0.002376869
[epoch 000000187] loss=230.408421108 | avg=0.453236376 | rare=0.002299552
[epoch 000000188] loss=220.665766035 | avg=0.460958875 | rare=0.002202048
[epoch 000000189] loss=237.875724792 | avg=0.458482791 | rare=0.002374172
[epoch 000000190] loss=257.000544957 | avg=0.457793449 | rare=0.002565428
[epoch 000000191] loss=241.420503889 | avg=0.449444635 | rare=0.002409711
[epoch 000000192] loss=211.968490056 | avg=0.459198339 | rare=0.002115093
[epoch 000000193] loss=256.573514121 | avg=0.450101980 | rare=0.002561234
[epoch 000000194] loss=221.022617885 | avg=0.453474053 | rare=0.002205691
[epoch 000000195] loss=251.035205296 | avg=0.454170376 | rare=0.002505810
[epoch 000000196] loss=253.501485552 | avg=0.468015637 | rare=0.002530335
[epoch 000000197] loss=288.385278974 | avg=0.471468053 | rare=0.002879138
[epoch 000000198] loss=237.029879434 | avg=0.461276069 | rare=0.002365686
[epoch 000000199] loss=214.421564920 | avg=0.462740100 | rare=0.002139588
[epoch 000000200] loss=264.161072867 | avg=0.450347249 | rare=0.002637107

Training safe with adam...

Epochs:   0%|          | 0/200 [00:00<?, ?it/s]

[epoch 000000001] loss=142.039022991 | avg=50.119557244 | rare=0.000919195
[epoch 000000002] loss=224.544947215 | avg=48.997990199 | rare=0.001755470
[epoch 000000003] loss=196.434282030 | avg=45.598670415 | rare=0.001508356
[epoch 000000004] loss=442.872177124 | avg=41.808252335 | rare=0.004010639
[epoch 000000005] loss=2098.550412859 | avg=36.781440735 | rare=0.020617689
[epoch 000000006] loss=9277.958496094 | avg=28.605061940 | rare=0.092493535
[epoch 000000007] loss=19819.272949219 | avg=19.790321895 | rare=0.197994822
[epoch 000000008] loss=12866.576660156 | avg=17.475337982 | rare=0.128491012
[epoch 000000009] loss=8351.292236328 | avg=16.608556952 | rare=0.083346837
[epoch 000000010] loss=9368.260742188 | avg=15.542611803 | rare=0.093527181
[epoch 000000011] loss=9409.096993583 | avg=14.554543836 | rare=0.093945425
[epoch 000000012] loss=8067.528145926 | avg=14.233589854 | rare=0.080532945
[epoch 000000013] loss=8446.421875000 | avg=13.189975398 | rare=0.084332320
[epoch 000000014] loss=10708.457310268 | avg=11.854491711 | rare=0.106966028
[epoch 000000015] loss=10517.570103237 | avg=11.108075823 | rare=0.105064623
[epoch 000000016] loss=9238.252580915 | avg=10.432011945 | rare=0.092278205
[epoch 000000017] loss=10568.107247489 | avg=8.851942982 | rare=0.105592554
[epoch 000000018] loss=9092.238455636 | avg=8.590114049 | rare=0.090836482
[epoch 000000019] loss=8153.059814453 | avg=8.407027483 | rare=0.081446528
[epoch 000000020] loss=6996.324846540 | avg=8.623269354 | rare=0.069877016
[epoch 000000021] loss=6266.364624023 | avg=8.769062996 | rare=0.062575955
[epoch 000000022] loss=6343.216727121 | avg=8.703050307 | rare=0.063345137
[epoch 000000023] loss=6283.478794643 | avg=8.534323829 | rare=0.062749445
[epoch 000000024] loss=5761.843854632 | avg=8.480695554 | rare=0.057533630
[epoch 000000025] loss=5650.492152623 | avg=8.441773449 | rare=0.056420504
[epoch 000000026] loss=5516.182599749 | avg=8.218478884 | rare=0.055079641
[epoch 000000027] loss=5560.694597517 | avg=8.185239962 | rare=0.055525094
[epoch 000000028] loss=5591.513654436 | avg=7.932614940 | rare=0.055835810
[epoch 000000029] loss=5659.333461217 | avg=7.931970188 | rare=0.056514015
[epoch 000000030] loss=5293.402605329 | avg=7.932518618 | rare=0.052854701
[epoch 000000031] loss=5248.105050223 | avg=7.761587926 | rare=0.052403434
[epoch 000000032] loss=4845.925223214 | avg=7.742610352 | rare=0.048381827
[epoch 000000033] loss=4852.914097377 | avg=7.670218127 | rare=0.048452438
[epoch 000000034] loss=4374.721819196 | avg=7.716353110 | rare=0.043670055
[epoch 000000035] loss=4422.651497977 | avg=7.663068465 | rare=0.044149884
[epoch 000000036] loss=4137.999215262 | avg=7.500968490 | rare=0.041304982
[epoch 000000037] loss=4461.469395229 | avg=7.575670549 | rare=0.044538938
[epoch 000000038] loss=4495.887137277 | avg=7.433479105 | rare=0.044884537
[epoch 000000039] loss=4232.901384626 | avg=7.450880698 | rare=0.042254505
[epoch 000000040] loss=4443.278390067 | avg=7.492402792 | rare=0.044357859
[epoch 000000041] loss=4540.755597796 | avg=7.554919583 | rare=0.045332006
[epoch 000000042] loss=4171.525163923 | avg=7.546093907 | rare=0.041639791
[epoch 000000043] loss=4685.100272042 | avg=7.402156591 | rare=0.046776982
[epoch 000000044] loss=4576.569231306 | avg=7.457968644 | rare=0.045691112
[epoch 000000045] loss=4903.813424247 | avg=7.514235973 | rare=0.048962991
[epoch 000000046] loss=4550.240966797 | avg=7.455742700 | rare=0.045427852
[epoch 000000047] loss=4676.742719378 | avg=7.503623145 | rare=0.046692391
[epoch 000000048] loss=4993.637241908 | avg=7.474755560 | rare=0.049861625
[epoch 000000049] loss=4434.990705218 | avg=7.692340340 | rare=0.044272983
[epoch 000000050] loss=4371.743495396 | avg=7.841843060 | rare=0.043639016
[epoch 000000051] loss=4487.310564314 | avg=7.494078193 | rare=0.044798165
[epoch 000000052] loss=4496.244437081 | avg=7.582384416 | rare=0.044886620
[epoch 000000053] loss=4423.992902483 | avg=7.525105408 | rare=0.044164677
[epoch 000000054] loss=4159.202950614 | avg=7.570878710 | rare=0.041516322
[epoch 000000055] loss=4096.702845982 | avg=7.644068718 | rare=0.040890588
[epoch 000000056] loss=4286.319545201 | avg=7.508306537 | rare=0.042788112
[epoch 000000057] loss=4113.392743792 | avg=7.439291818 | rare=0.041059535
[epoch 000000058] loss=4051.826572963 | avg=7.504513979 | rare=0.040443221
[epoch 000000059] loss=3947.389683315 | avg=7.506446838 | rare=0.039398832
[epoch 000000060] loss=4150.219220843 | avg=7.476948125 | rare=0.041427423
[epoch 000000061] loss=4674.642543248 | avg=7.528557198 | rare=0.046671140
[epoch 000000062] loss=4266.997218541 | avg=7.699133090 | rare=0.042592980
[epoch 000000063] loss=4324.911638532 | avg=7.665044648 | rare=0.043172466
[epoch 000000064] loss=4025.668090820 | avg=7.489869356 | rare=0.040181782
[epoch 000000065] loss=3957.697684152 | avg=7.475603989 | rare=0.039502221
[epoch 000000066] loss=4299.228341239 | avg=7.357852493 | rare=0.042918706
[epoch 000000067] loss=4414.122889927 | avg=7.654938493 | rare=0.044064680
[epoch 000000068] loss=4408.525512695 | avg=7.571436848 | rare=0.044009542
[epoch 000000069] loss=3997.507917132 | avg=7.475680794 | rare=0.039900322
[epoch 000000070] loss=3971.804914202 | avg=7.370309523 | rare=0.039644346
[epoch 000000071] loss=3950.423357282 | avg=7.309699059 | rare=0.039431136
[epoch 000000072] loss=4107.497052874 | avg=7.406020573 | rare=0.041000911
[epoch 000000073] loss=4788.207170759 | avg=7.389621803 | rare=0.047808176
[epoch 000000074] loss=4058.130824498 | avg=7.606669596 | rare=0.040505242
[epoch 000000075] loss=3840.918788365 | avg=7.452710935 | rare=0.038334660
[epoch 000000076] loss=4454.989292690 | avg=7.347225189 | rare=0.044476421
[epoch 000000077] loss=4439.885131836 | avg=7.367436988 | rare=0.044325177
[epoch 000000078] loss=4264.394705636 | avg=7.391508886 | rare=0.042570032
[epoch 000000079] loss=4080.276332310 | avg=7.316879136 | rare=0.040729594
[epoch 000000080] loss=4440.436070033 | avg=7.446762664 | rare=0.044329893
[epoch 000000081] loss=4192.651053292 | avg=7.304058654 | rare=0.041853470
[epoch 000000082] loss=4165.548095703 | avg=7.264440434 | rare=0.041582837
[epoch 000000083] loss=4448.577026367 | avg=7.265607595 | rare=0.044413114
[epoch 000000084] loss=4191.945678711 | avg=7.165103299 | rare=0.041847806
[epoch 000000085] loss=4163.003173828 | avg=7.385148048 | rare=0.041556181
[epoch 000000086] loss=4433.780587333 | avg=7.242524317 | rare=0.044265381
[epoch 000000087] loss=3973.313127790 | avg=7.212699788 | rare=0.039661004
[epoch 000000088] loss=3849.448678153 | avg=7.224066632 | rare=0.038422246
[epoch 000000089] loss=4247.318202427 | avg=7.367197820 | rare=0.042399510
[epoch 000000090] loss=4285.711425781 | avg=7.238455023 | rare=0.042784730
[epoch 000000091] loss=3981.140110561 | avg=7.143795558 | rare=0.039739963
[epoch 000000092] loss=4019.616489955 | avg=7.366762638 | rare=0.040122497
[epoch 000000093] loss=3739.814819336 | avg=7.227280923 | rare=0.037325876
[epoch 000000094] loss=3760.466971261 | avg=7.332963228 | rare=0.037531341
[epoch 000000095] loss=3972.183785575 | avg=7.289360489 | rare=0.039648944
[epoch 000000096] loss=3675.341831752 | avg=7.253099544 | rare=0.036680887
[epoch 000000097] loss=3978.092215402 | avg=7.196025814 | rare=0.039708962
[epoch 000000098] loss=3945.073381696 | avg=7.118062428 | rare=0.039379553
[epoch 000000099] loss=3651.419520787 | avg=7.348633085 | rare=0.036440708
[epoch 000000100] loss=4096.261544364 | avg=7.220176799 | rare=0.040890414
[epoch 000000101] loss=3715.176269531 | avg=7.078615495 | rare=0.037080977
[epoch 000000102] loss=3925.633231027 | avg=7.406441791 | rare=0.039182268
[epoch 000000103] loss=4018.536821638 | avg=7.254200152 | rare=0.040112827
[epoch 000000104] loss=3753.529314314 | avg=7.194676944 | rare=0.037463346
[epoch 000000105] loss=3571.565220424 | avg=7.264020545 | rare=0.035643012
[epoch 000000106] loss=3557.209856306 | avg=7.164575202 | rare=0.035500453
[epoch 000000107] loss=4251.100062779 | avg=7.079441513 | rare=0.042440206
[epoch 000000108] loss=3812.420724051 | avg=7.113126721 | rare=0.038053076
[epoch 000000109] loss=4093.201956613 | avg=7.149284942 | rare=0.040860527
[epoch 000000110] loss=3723.375191825 | avg=7.164137125 | rare=0.037162111
[epoch 000000111] loss=3827.160382952 | avg=7.106386491 | rare=0.038200540
[epoch 000000112] loss=4222.321969169 | avg=7.036751236 | rare=0.042152852
[epoch 000000113] loss=3926.489074707 | avg=7.261905091 | rare=0.039192272
[epoch 000000114] loss=3983.603027344 | avg=7.180713722 | rare=0.039764223
[epoch 000000115] loss=4223.256260463 | avg=7.049086060 | rare=0.042162072
[epoch 000000116] loss=3926.332214355 | avg=7.261579207 | rare=0.039190707
[epoch 000000117] loss=4160.595336914 | avg=7.088998624 | rare=0.041535063
[epoch 000000118] loss=4121.835501535 | avg=7.108077458 | rare=0.041147274
[epoch 000000119] loss=4093.172712054 | avg=7.159194504 | rare=0.040860135
[epoch 000000120] loss=3735.430960519 | avg=7.174587045 | rare=0.037282564
[epoch 000000121] loss=4056.560093471 | avg=7.190525021 | rare=0.040493696
[epoch 000000122] loss=3788.318036761 | avg=7.191325392 | rare=0.037811267
[epoch 000000123] loss=4586.673095703 | avg=7.116675820 | rare=0.045795565
[epoch 000000124] loss=4711.064592634 | avg=7.058671883 | rare=0.047040060
[epoch 000000125] loss=4388.988647461 | avg=7.089721680 | rare=0.043818990
[epoch 000000126] loss=4041.874546596 | avg=7.279008899 | rare=0.040345956
[epoch 000000127] loss=4715.336966378 | avg=7.277048281 | rare=0.047080600
[epoch 000000128] loss=4271.577218192 | avg=7.221203361 | rare=0.042643560
[epoch 000000129] loss=4609.480381557 | avg=7.027161189 | rare=0.046024533
[epoch 000000130] loss=4646.651994978 | avg=7.012700047 | rare=0.046396393
[epoch 000000131] loss=4957.711408343 | avg=7.019285543 | rare=0.049506921
[epoch 000000132] loss=4542.422310965 | avg=7.019314698 | rare=0.045354029
[epoch 000000133] loss=4727.261474609 | avg=7.365018572 | rare=0.047198964
[epoch 000000134] loss=4718.951485770 | avg=7.062051467 | rare=0.047118895
[epoch 000000135] loss=4928.203857422 | avg=7.209157807 | rare=0.049209947
[epoch 000000136] loss=4973.099923270 | avg=7.080576522 | rare=0.049660193
[epoch 000000137] loss=4704.095493862 | avg=7.031828301 | rare=0.046970636
[epoch 000000138] loss=4964.548688616 | avg=7.100727626 | rare=0.049574479
[epoch 000000139] loss=5385.098231724 | avg=7.227509737 | rare=0.053778707
[epoch 000000140] loss=5144.803588867 | avg=7.122971126 | rare=0.051376805
[epoch 000000141] loss=5012.023821150 | avg=7.158618144 | rare=0.050048652
[epoch 000000142] loss=4503.450910296 | avg=7.244035585 | rare=0.044962069
[epoch 000000143] loss=5389.636718750 | avg=7.042866809 | rare=0.053825938
[epoch 000000144] loss=4466.329101562 | avg=7.132582767 | rare=0.044591964
[epoch 000000145] loss=5290.302804129 | avg=7.029390165 | rare=0.052832734
[epoch 000000146] loss=4823.285627093 | avg=7.062445232 | rare=0.048162232
[epoch 000000147] loss=5162.598318917 | avg=7.080128057 | rare=0.051555182
[epoch 000000148] loss=5300.302908761 | avg=6.990781954 | rare=0.052933121
[epoch 000000149] loss=5185.260742188 | avg=6.974402870 | rare=0.051782863
[epoch 000000150] loss=4606.973249163 | avg=7.034778220 | rare=0.045999385
[epoch 000000151] loss=5318.492135184 | avg=6.970450367 | rare=0.053115217
[epoch 000000152] loss=5722.878906250 | avg=6.932958739 | rare=0.057159459
[epoch 000000153] loss=5186.944614955 | avg=6.955410072 | rare=0.051799892
[epoch 000000154] loss=5707.352748326 | avg=6.888034037 | rare=0.057004647
[epoch 000000155] loss=5714.761056083 | avg=6.936869349 | rare=0.057078240
[epoch 000000156] loss=5798.425763811 | avg=6.906842096 | rare=0.057915189
[epoch 000000157] loss=5617.946166992 | avg=6.895756790 | rare=0.056110503
[epoch 000000158] loss=5496.586948940 | avg=6.853606428 | rare=0.054897333
[epoch 000000159] loss=5354.062622070 | avg=6.971818515 | rare=0.053470909
[epoch 000000160] loss=5747.440534319 | avg=6.844213349 | rare=0.057405963
[epoch 000000161] loss=5569.537876674 | avg=6.887088094 | rare=0.055626507
[epoch 000000162] loss=5769.670619420 | avg=7.036228793 | rare=0.057626343
[epoch 000000163] loss=5526.324288504 | avg=7.133003473 | rare=0.055191914
[epoch 000000164] loss=6663.073451451 | avg=6.911594697 | rare=0.066561618
[epoch 000000165] loss=5870.131923131 | avg=6.839890480 | rare=0.058632920
[epoch 000000166] loss=5510.502144950 | avg=7.093938146 | rare=0.055034083
[epoch 000000167] loss=6331.582380022 | avg=6.791330406 | rare=0.063247910
[epoch 000000168] loss=5959.450892857 | avg=6.980352368 | rare=0.059524705
[epoch 000000169] loss=6172.760428292 | avg=6.860346624 | rare=0.061659001
[epoch 000000170] loss=6231.784702846 | avg=6.816494805 | rare=0.062249682
[epoch 000000171] loss=5744.811941964 | avg=7.027353934 | rare=0.057377846
[epoch 000000172] loss=6262.582101004 | avg=7.034970011 | rare=0.062555471
[epoch 000000173] loss=6293.464198521 | avg=6.836706945 | rare=0.062866276
[epoch 000000174] loss=6242.343296596 | avg=6.990474292 | rare=0.062353529
[epoch 000000175] loss=6154.139683315 | avg=6.931168727 | rare=0.061472085
[epoch 000000176] loss=5860.677629743 | avg=6.911174365 | rare=0.058537665
[epoch 000000177] loss=5712.037475586 | avg=6.907014166 | rare=0.057051304
[epoch 000000178] loss=6188.601597377 | avg=6.851140465 | rare=0.061817505
[epoch 000000179] loss=5582.991681780 | avg=6.867367540 | rare=0.055761242
[epoch 000000180] loss=6249.771868025 | avg=6.763121401 | rare=0.062430087
[epoch 000000181] loss=6285.343191964 | avg=6.997569799 | rare=0.062783456
[epoch 000000182] loss=6318.136265346 | avg=6.996577740 | rare=0.063111398
[epoch 000000183] loss=6705.267543248 | avg=6.808469670 | rare=0.066984591
[epoch 000000184] loss=6129.505580357 | avg=6.850283997 | rare=0.061226553
[epoch 000000185] loss=6396.536969866 | avg=6.847117049 | rare=0.063896899
[epoch 000000186] loss=5438.865042550 | avg=7.068837404 | rare=0.054317962
[epoch 000000187] loss=5792.390502930 | avg=6.975263527 | rare=0.057854152
[epoch 000000188] loss=6456.842250279 | avg=6.811871018 | rare=0.064500303
[epoch 000000189] loss=6005.523123605 | avg=6.870496137 | rare=0.059986527
[epoch 000000190] loss=5938.367327009 | avg=6.972280502 | rare=0.059313950
[epoch 000000191] loss=6280.740356445 | avg=6.946840014 | rare=0.062737935
[epoch 000000192] loss=6262.928065709 | avg=6.688983849 | rare=0.062562390
[epoch 000000193] loss=6388.035295759 | avg=6.903608867 | rare=0.063811316
[epoch 000000194] loss=6201.105085100 | avg=6.938907589 | rare=0.061941661
[epoch 000000195] loss=5986.718976702 | avg=6.832757677 | rare=0.059798862
[epoch 000000196] loss=5646.113490513 | avg=6.800617490 | rare=0.056393129
[epoch 000000197] loss=6219.651035854 | avg=6.738405057 | rare=0.062129127
[epoch 000000198] loss=6218.805140904 | avg=6.831222568 | rare=0.062119739
[epoch 000000199] loss=6422.554617746 | avg=6.722306694 | rare=0.064158323
[epoch 000000200] loss=5715.697230748 | avg=6.770852395 | rare=0.057089264
Accuracy: 82.79%  (CI 95%: [81.72%, 83.81%])
Robust Accuracy: 82.65736%  (CI 95%: [81.76534%, 83.67113%])
Conditional Robust Accuracy: 98.91620%  (CI 95%: [98.74240%, 99.08865%])
Accuracy: 83.17%  (CI 95%: [82.11%, 84.18%])
Robust Accuracy: 83.05365%  (CI 95%: [82.11479%, 84.04537%])
Conditional Robust Accuracy: 99.00482%  (CI 95%: [98.82555%, 99.16005%])

#################### lr: 0.0001 ####################
  --> Running Seed: 42

Training naive with adam...

Epochs:   0%|          | 0/200 [00:00<?, ?it/s]

[epoch 000000001] loss=178608.407366071 | avg=0.319726129 | rare=1.786080871
[epoch 000000002] loss=178494.834821429 | avg=0.319935188 | rare=1.784945164
[epoch 000000003] loss=174549.402901786 | avg=0.320809671 | rare=1.745490798
[epoch 000000004] loss=131936.979910714 | avg=0.420562035 | rare=1.319365587
[epoch 000000005] loss=89448.541294643 | avg=0.655244116 | rare=0.894478858
[epoch 000000006] loss=64188.244698661 | avg=0.886732749 | rare=0.641873594
[epoch 000000007] loss=49670.553850446 | avg=1.069770609 | rare=0.496694837
[epoch 000000008] loss=40443.987444196 | avg=1.203136538 | rare=0.404427843
[epoch 000000009] loss=34042.006556920 | avg=1.296147764 | rare=0.340407103
[epoch 000000010] loss=29287.563895089 | avg=1.368134303 | rare=0.292861956
[epoch 000000011] loss=25746.704938616 | avg=1.413839843 | rare=0.257452914
[epoch 000000012] loss=22495.373046875 | avg=1.446685663 | rare=0.224939265
[epoch 000000013] loss=20218.695033482 | avg=1.476215124 | rare=0.202172188
[epoch 000000014] loss=18210.426130022 | avg=1.499125915 | rare=0.182089269
[epoch 000000015] loss=16644.527622768 | avg=1.518696828 | rare=0.166430088
[epoch 000000016] loss=15295.407156808 | avg=1.552267364 | rare=0.152938549
[epoch 000000017] loss=14097.258789062 | avg=1.573049647 | rare=0.140956857
[epoch 000000018] loss=13214.944963728 | avg=1.587088449 | rare=0.132133578
[epoch 000000019] loss=12447.607352121 | avg=1.599784272 | rare=0.124460076
[epoch 000000020] loss=11578.682617188 | avg=1.619391603 | rare=0.115770632
[epoch 000000021] loss=10912.148088728 | avg=1.638798663 | rare=0.109105093
[epoch 000000022] loss=10252.767508371 | avg=1.665485118 | rare=0.102511020
[epoch 000000023] loss=9633.153459821 | avg=1.684304927 | rare=0.096314690
[epoch 000000024] loss=9129.493512835 | avg=1.703387661 | rare=0.091277900
[epoch 000000025] loss=8596.409737723 | avg=1.724692370 | rare=0.085946849
[epoch 000000026] loss=8251.800851004 | avg=1.745707716 | rare=0.082500551
[epoch 000000027] loss=7827.391287667 | avg=1.765148878 | rare=0.078256261
[epoch 000000028] loss=7469.409109933 | avg=1.790074570 | rare=0.074676191
[epoch 000000029] loss=7220.608363560 | avg=1.811873453 | rare=0.072187964
[epoch 000000030] loss=6917.035260882 | avg=1.827540168 | rare=0.069152076
[epoch 000000031] loss=6809.782366071 | avg=1.839333917 | rare=0.068079430
[epoch 000000032] loss=6596.697370257 | avg=1.857806453 | rare=0.065948396
[epoch 000000033] loss=6362.495361328 | avg=1.866232395 | rare=0.063606291
[epoch 000000034] loss=6207.966622489 | avg=1.874732545 | rare=0.062060919
[epoch 000000035] loss=6073.020228795 | avg=1.879999467 | rare=0.060711401
[epoch 000000036] loss=5889.473179408 | avg=1.886953047 | rare=0.058875863
[epoch 000000037] loss=5792.095214844 | avg=1.898491936 | rare=0.057901967
[epoch 000000038] loss=5602.906075614 | avg=1.896310559 | rare=0.056010098
[epoch 000000039] loss=5532.667340960 | avg=1.895900922 | rare=0.055307714
[epoch 000000040] loss=5409.292759487 | avg=1.893855350 | rare=0.054073989
[epoch 000000041] loss=5215.113734654 | avg=1.891586227 | rare=0.052132223
[epoch 000000042] loss=5052.037057059 | avg=1.909064353 | rare=0.050501281
[epoch 000000043] loss=4947.594342913 | avg=1.901540799 | rare=0.049456928
[epoch 000000044] loss=4956.296770368 | avg=1.889570219 | rare=0.049544072
[epoch 000000045] loss=4746.219412667 | avg=1.900252376 | rare=0.047443192
[epoch 000000046] loss=4620.046962193 | avg=1.898307707 | rare=0.046181486
[epoch 000000047] loss=4554.292672294 | avg=1.888117169 | rare=0.045524045
[epoch 000000048] loss=4466.301060268 | avg=1.886947112 | rare=0.044644141
[epoch 000000049] loss=4406.420148577 | avg=1.885983288 | rare=0.044045341
[epoch 000000050] loss=4439.522181920 | avg=1.876601381 | rare=0.044376456
[epoch 000000051] loss=4373.410173689 | avg=1.876087504 | rare=0.043715341
[epoch 000000052] loss=4371.427019392 | avg=1.863017482 | rare=0.043695640
[epoch 000000053] loss=4333.144269671 | avg=1.860988157 | rare=0.043312833
[epoch 000000054] loss=4344.795410156 | avg=1.835048880 | rare=0.043429604
[epoch 000000055] loss=4345.330618722 | avg=1.825655324 | rare=0.043435049
[epoch 000000056] loss=4275.399867467 | avg=1.805614301 | rare=0.042735943
[epoch 000000057] loss=4156.532226562 | avg=1.796734571 | rare=0.041547356
[epoch 000000058] loss=4081.998744420 | avg=1.798563472 | rare=0.040802002
[epoch 000000059] loss=3955.492972238 | avg=1.790122109 | rare=0.039537028
[epoch 000000060] loss=3943.095179967 | avg=1.778184210 | rare=0.039413170
[epoch 000000061] loss=3879.605730329 | avg=1.770275729 | rare=0.038778354
[epoch 000000062] loss=3846.929181780 | avg=1.755860610 | rare=0.038451733
[epoch 000000063] loss=3755.738996233 | avg=1.742237645 | rare=0.037539968
[epoch 000000064] loss=3622.860927037 | avg=1.748981876 | rare=0.036211119
[epoch 000000065] loss=3656.121547154 | avg=1.737075482 | rare=0.036543845
[epoch 000000066] loss=3495.964006696 | avg=1.723982062 | rare=0.034942401
[epoch 000000067] loss=3455.922729492 | avg=1.711206913 | rare=0.034542115
[epoch 000000068] loss=3434.167358398 | avg=1.690881320 | rare=0.034324765
[epoch 000000069] loss=3382.736502511 | avg=1.688154987 | rare=0.033810484
[epoch 000000070] loss=3279.524536133 | avg=1.683890062 | rare=0.032778406
[epoch 000000071] loss=3255.115652902 | avg=1.673041957 | rare=0.032534426
[epoch 000000072] loss=3357.370710100 | avg=1.651642680 | rare=0.033557191
[epoch 000000073] loss=3398.320364816 | avg=1.631765757 | rare=0.033966886
[epoch 000000074] loss=3348.081351144 | avg=1.615505610 | rare=0.033464658
[epoch 000000075] loss=3318.527465820 | avg=1.601176849 | rare=0.033169263
[epoch 000000076] loss=3364.637119838 | avg=1.575883627 | rare=0.033630612
[epoch 000000077] loss=3356.040701730 | avg=1.558279216 | rare=0.033544824
[epoch 000000078] loss=3267.810076032 | avg=1.547079504 | rare=0.032662630
[epoch 000000079] loss=3220.335257394 | avg=1.527016878 | rare=0.032188083
[epoch 000000080] loss=3250.130057199 | avg=1.497967482 | rare=0.032486321
[epoch 000000081] loss=3268.759817941 | avg=1.483202125 | rare=0.032672767
[epoch 000000082] loss=3134.660086496 | avg=1.472762644 | rare=0.031331873
[epoch 000000083] loss=3130.985508510 | avg=1.450961462 | rare=0.031295345
[epoch 000000084] loss=3294.150111607 | avg=1.420754024 | rare=0.032927294
[epoch 000000085] loss=3454.436802455 | avg=1.379733000 | rare=0.034530570
[epoch 000000086] loss=3205.327758789 | avg=1.383965909 | rare=0.032039438
[epoch 000000087] loss=3292.611912319 | avg=1.348944613 | rare=0.032912630
[epoch 000000088] loss=3520.347324916 | avg=1.303919213 | rare=0.035190434
[epoch 000000089] loss=3187.707170759 | avg=1.307166662 | rare=0.031864000
[epoch 000000090] loss=3285.002947126 | avg=1.280986897 | rare=0.032837219
[epoch 000000091] loss=3474.983607701 | avg=1.249171623 | rare=0.034737344
[epoch 000000092] loss=3665.132777623 | avg=1.207017481 | rare=0.036639258
[epoch 000000093] loss=3652.252580915 | avg=1.183294926 | rare=0.036510693
[epoch 000000094] loss=3641.133091518 | avg=1.162832728 | rare=0.036399703
[epoch 000000095] loss=3925.585989816 | avg=1.106258899 | rare=0.039244797
[epoch 000000096] loss=4196.372593471 | avg=1.066378772 | rare=0.041953062
[epoch 000000097] loss=4356.548618862 | avg=1.026284214 | rare=0.043555223
[epoch 000000098] loss=4438.934204102 | avg=0.990727872 | rare=0.044379435
[epoch 000000099] loss=4508.433593750 | avg=0.952314462 | rare=0.045074813
[epoch 000000100] loss=4604.566702706 | avg=0.916257948 | rare=0.046036504
[epoch 000000101] loss=4719.506399972 | avg=0.886741378 | rare=0.047186197
[epoch 000000102] loss=4762.791608538 | avg=0.854559562 | rare=0.047619370
[epoch 000000103] loss=4772.927769252 | avg=0.830272662 | rare=0.047720975
[epoch 000000104] loss=5101.975341797 | avg=0.808360215 | rare=0.051011669
[epoch 000000105] loss=5310.584716797 | avg=0.772299256 | rare=0.053098124
[epoch 000000106] loss=5284.512172154 | avg=0.748111299 | rare=0.052837641
[epoch 000000107] loss=5237.393903460 | avg=0.724017918 | rare=0.052366699
[epoch 000000108] loss=5141.017368862 | avg=0.710733235 | rare=0.051403067
[epoch 000000109] loss=5099.095075335 | avg=0.700645515 | rare=0.050983944
[epoch 000000110] loss=5328.763916016 | avg=0.670408798 | rare=0.053280935
[epoch 000000111] loss=5055.402343750 | avg=0.668577071 | rare=0.050547338
[epoch 000000112] loss=4894.548339844 | avg=0.654251827 | rare=0.048938940
[epoch 000000113] loss=4794.825160435 | avg=0.650278143 | rare=0.047941749
[epoch 000000114] loss=4808.002232143 | avg=0.631128324 | rare=0.048073712
[epoch 000000115] loss=4516.930350167 | avg=0.645677464 | rare=0.045162846
[epoch 000000116] loss=4633.581211635 | avg=0.620450846 | rare=0.046329607
[epoch 000000117] loss=4332.532034738 | avg=0.630599252 | rare=0.043319014
[epoch 000000118] loss=4184.424246652 | avg=0.626417828 | rare=0.041837978
[epoch 000000119] loss=4223.426042829 | avg=0.623831234 | rare=0.042228022
[epoch 000000120] loss=3952.751098633 | avg=0.621828135 | rare=0.039521292
[epoch 000000121] loss=3903.858660017 | avg=0.629992153 | rare=0.039032286
[epoch 000000122] loss=3887.965959821 | avg=0.615444877 | rare=0.038873505
[epoch 000000123] loss=3685.150024414 | avg=0.628716775 | rare=0.036845213
[epoch 000000124] loss=3700.093906948 | avg=0.619085742 | rare=0.036994748
[epoch 000000125] loss=3549.753191267 | avg=0.619853812 | rare=0.035491334
[epoch 000000126] loss=3363.404523577 | avg=0.628727990 | rare=0.033627758
[epoch 000000127] loss=3421.848371233 | avg=0.611000372 | rare=0.034212374
[epoch 000000128] loss=3127.043369838 | avg=0.637194812 | rare=0.031264062
[epoch 000000129] loss=2965.211983817 | avg=0.641641140 | rare=0.029645703
[epoch 000000130] loss=3031.651105608 | avg=0.627690307 | rare=0.030310234
[epoch 000000131] loss=2841.690098354 | avg=0.644725591 | rare=0.028410454
[epoch 000000132] loss=2670.816057478 | avg=0.650246693 | rare=0.026701658
[epoch 000000133] loss=2560.595179967 | avg=0.656208507 | rare=0.025599390
[epoch 000000134] loss=2692.806274414 | avg=0.642747406 | rare=0.026921635
[epoch 000000135] loss=2511.641671317 | avg=0.649041308 | rare=0.025109926
[epoch 000000136] loss=2555.689304897 | avg=0.638080865 | rare=0.025550512
[epoch 000000137] loss=2574.302533831 | avg=0.634009825 | rare=0.025736685
[epoch 000000138] loss=2495.616507394 | avg=0.632391321 | rare=0.024949841
[epoch 000000139] loss=2439.085484096 | avg=0.638070562 | rare=0.024384474
[epoch 000000140] loss=2575.847473145 | avg=0.617613030 | rare=0.025752299
[epoch 000000141] loss=2258.492736816 | avg=0.635377462 | rare=0.022578574
[epoch 000000142] loss=2468.646693638 | avg=0.616100584 | rare=0.024680306
[epoch 000000143] loss=2361.606549944 | avg=0.623764651 | rare=0.023609828
[epoch 000000144] loss=2440.082266671 | avg=0.610784841 | rare=0.024394715
[epoch 000000145] loss=2297.136369978 | avg=0.620588805 | rare=0.022965158
[epoch 000000146] loss=2407.717581613 | avg=0.607103876 | rare=0.024071105
[epoch 000000147] loss=2290.659232003 | avg=0.606618903 | rare=0.022900526
[epoch 000000148] loss=2304.233773368 | avg=0.603252434 | rare=0.023036305
[epoch 000000149] loss=2340.336931501 | avg=0.598339758 | rare=0.023397386
[epoch 000000150] loss=2207.075962612 | avg=0.601685175 | rare=0.022064742
[epoch 000000151] loss=2401.822736468 | avg=0.590039990 | rare=0.024012327
[epoch 000000152] loss=2147.138384138 | avg=0.600042305 | rare=0.021465383
[epoch 000000153] loss=2275.805585589 | avg=0.583353886 | rare=0.022752222
[epoch 000000154] loss=2205.108407157 | avg=0.589440878 | rare=0.022045190
[epoch 000000155] loss=2234.815717425 | avg=0.584629689 | rare=0.022342311
[epoch 000000156] loss=2084.557564872 | avg=0.592847909 | rare=0.020839647
[epoch 000000157] loss=2154.797075544 | avg=0.581809346 | rare=0.021542153
[epoch 000000158] loss=2053.088274275 | avg=0.586063579 | rare=0.020525022
[epoch 000000159] loss=2140.386823382 | avg=0.579853630 | rare=0.021398070
[epoch 000000160] loss=2008.095772879 | avg=0.582822072 | rare=0.020075130
[epoch 000000161] loss=2041.629316057 | avg=0.578186018 | rare=0.020410512
[epoch 000000162] loss=1986.254874093 | avg=0.579241088 | rare=0.019856756
[epoch 000000163] loss=1997.198460170 | avg=0.575647194 | rare=0.019966228
[epoch 000000164] loss=1880.041024344 | avg=0.583192242 | rare=0.018794578
[epoch 000000165] loss=1970.760402134 | avg=0.573466016 | rare=0.019701869
[epoch 000000166] loss=1875.603690011 | avg=0.577234162 | rare=0.018750264
[epoch 000000167] loss=1972.897853306 | avg=0.564500021 | rare=0.019723333
[epoch 000000168] loss=1812.496364049 | avg=0.577782552 | rare=0.018119186
[epoch 000000169] loss=1961.495108468 | avg=0.561236158 | rare=0.019609339
[epoch 000000170] loss=1817.169747489 | avg=0.569394601 | rare=0.018166003
[epoch 000000171] loss=1831.601361956 | avg=0.566095893 | rare=0.018310353
[epoch 000000172] loss=1783.134922573 | avg=0.565494065 | rare=0.017825694
[epoch 000000173] loss=1719.205993652 | avg=0.568236555 | rare=0.017186378
[epoch 000000174] loss=1877.875191825 | avg=0.555591400 | rare=0.018773196
[epoch 000000175] loss=1714.427455357 | avg=0.562059351 | rare=0.017138654
[epoch 000000176] loss=1791.865687779 | avg=0.550992170 | rare=0.017913147
[epoch 000000177] loss=1640.757437570 | avg=0.563488973 | rare=0.016401939
[epoch 000000178] loss=1807.721915109 | avg=0.550589212 | rare=0.018071713
[epoch 000000179] loss=1744.203325544 | avg=0.550836050 | rare=0.017436525
[epoch 000000180] loss=1797.264413016 | avg=0.546975766 | rare=0.017967174
[epoch 000000181] loss=1712.702174595 | avg=0.547665632 | rare=0.017121545
[epoch 000000182] loss=1699.078892299 | avg=0.546072062 | rare=0.016985328
[epoch 000000183] loss=1726.632489886 | avg=0.542930373 | rare=0.017260895
[epoch 000000184] loss=1711.161577497 | avg=0.540057057 | rare=0.017106215
[epoch 000000185] loss=1710.071184431 | avg=0.541147298 | rare=0.017095300
[epoch 000000186] loss=1857.325945173 | avg=0.529691749 | rare=0.018567963
[epoch 000000187] loss=1663.087594169 | avg=0.537656126 | rare=0.016625499
[epoch 000000188] loss=1763.149597168 | avg=0.530425050 | rare=0.017626192
[epoch 000000189] loss=1774.625566755 | avg=0.527923316 | rare=0.017740977
[epoch 000000190] loss=1736.711059570 | avg=0.525237028 | rare=0.017361858
[epoch 000000191] loss=1679.117684501 | avg=0.522250484 | rare=0.016785954
[epoch 000000192] loss=1649.408891950 | avg=0.522227871 | rare=0.016488867
[epoch 000000193] loss=1704.735961914 | avg=0.518927180 | rare=0.017042170
[epoch 000000194] loss=1616.863071987 | avg=0.518681098 | rare=0.016163444
[epoch 000000195] loss=1676.455976214 | avg=0.514032194 | rare=0.016759420
[epoch 000000196] loss=1633.384277344 | avg=0.509918253 | rare=0.016328744
[epoch 000000197] loss=1637.868007115 | avg=0.509393622 | rare=0.016373586
[epoch 000000198] loss=1621.314976283 | avg=0.511521073 | rare=0.016208035
[epoch 000000199] loss=1565.794076102 | avg=0.510150882 | rare=0.015652839
[epoch 000000200] loss=1605.289184570 | avg=0.506247529 | rare=0.016047829

Training safe with adam...

Epochs:   0%|          | 0/200 [00:00<?, ?it/s]

[epoch 000000001] loss=142.110842296 | avg=49.984584263 | rare=0.000921263
[epoch 000000002] loss=175.475879942 | avg=49.996451787 | rare=0.001254794
[epoch 000000003] loss=243.262245996 | avg=49.644343512 | rare=0.001936179
[epoch 000000004] loss=241.743893487 | avg=49.283812932 | rare=0.001924601
[epoch 000000005] loss=342.592698506 | avg=48.665621621 | rare=0.002939271
[epoch 000000006] loss=228.453587668 | avg=48.314925603 | rare=0.001801387
[epoch 000000007] loss=196.808471680 | avg=47.886293956 | rare=0.001489222
[epoch 000000008] loss=359.089089530 | avg=47.328586578 | rare=0.003117605
[epoch 000000009] loss=181.307391303 | avg=47.003247670 | rare=0.001343041
[epoch 000000010] loss=181.439096996 | avg=46.668434688 | rare=0.001347707
[epoch 000000011] loss=164.485794885 | avg=46.301535743 | rare=0.001181843
[epoch 000000012] loss=221.246253422 | avg=45.992899758 | rare=0.001752534
[epoch 000000013] loss=263.496685301 | avg=45.642826353 | rare=0.002178539
[epoch 000000014] loss=300.173101698 | avg=45.185595921 | rare=0.002549875
[epoch 000000015] loss=273.284543174 | avg=44.730085918 | rare=0.002285545
[epoch 000000016] loss=305.869296755 | avg=44.515475682 | rare=0.002613538
[epoch 000000017] loss=338.926009314 | avg=44.094347545 | rare=0.002948317
[epoch 000000018] loss=441.663476127 | avg=43.584886006 | rare=0.003980786
[epoch 000000019] loss=590.209266118 | avg=43.183934075 | rare=0.005470253
[epoch 000000020] loss=559.871374948 | avg=42.388742719 | rare=0.005174826
[epoch 000000021] loss=588.220364707 | avg=41.823218482 | rare=0.005463971
[epoch 000000022] loss=1202.186686380 | avg=40.964813777 | rare=0.011612219
[epoch 000000023] loss=1493.535948072 | avg=39.972073419 | rare=0.014535639
[epoch 000000024] loss=2800.144383022 | avg=38.857764108 | rare=0.027612866
[epoch 000000025] loss=3845.288362776 | avg=37.503292629 | rare=0.038077850
[epoch 000000026] loss=4666.960183280 | avg=35.994717734 | rare=0.046309654
[epoch 000000027] loss=5577.787431989 | avg=34.340145111 | rare=0.055434472
[epoch 000000028] loss=6929.363368443 | avg=32.851113047 | rare=0.068965124
[epoch 000000029] loss=9119.133056641 | avg=31.057946478 | rare=0.090880752
[epoch 000000030] loss=11501.629080636 | avg=29.280211994 | rare=0.114723488
[epoch 000000031] loss=11010.093758719 | avg=27.586509977 | rare=0.109825073
[epoch 000000032] loss=13065.795375279 | avg=26.125549861 | rare=0.130396699
[epoch 000000033] loss=15971.712960379 | avg=24.793111529 | rare=0.159469199
[epoch 000000034] loss=17424.202985491 | avg=23.773955209 | rare=0.174004293
[epoch 000000035] loss=19451.408551897 | avg=23.039477348 | rare=0.194283689
[epoch 000000036] loss=18975.268066406 | avg=22.348323141 | rare=0.189529196
[epoch 000000037] loss=17848.534946987 | avg=21.820792062 | rare=0.178267145
[epoch 000000038] loss=18115.242047991 | avg=21.181550843 | rare=0.180940603
[epoch 000000039] loss=16788.409737723 | avg=20.683178902 | rare=0.167677267
[epoch 000000040] loss=16438.202706473 | avg=20.192433085 | rare=0.164180104
[epoch 000000041] loss=15902.766950335 | avg=19.733586448 | rare=0.158830335
[epoch 000000042] loss=16212.028390067 | avg=19.482412883 | rare=0.161925462
[epoch 000000043] loss=14893.100097656 | avg=19.013588769 | rare=0.148740863
[epoch 000000044] loss=13688.065917969 | avg=18.736526489 | rare=0.136693294
[epoch 000000045] loss=13927.262904576 | avg=18.643646649 | rare=0.139086193
[epoch 000000046] loss=12722.038853237 | avg=18.461839880 | rare=0.127035772
[epoch 000000047] loss=12566.779436384 | avg=18.273597104 | rare=0.125485058
[epoch 000000048] loss=12034.434674944 | avg=18.183306830 | rare=0.120162513
[epoch 000000049] loss=12218.418701172 | avg=17.999678748 | rare=0.122004192
[epoch 000000050] loss=12026.041155134 | avg=17.794038568 | rare=0.120082473
[epoch 000000051] loss=11539.285191127 | avg=17.544242723 | rare=0.115217410
[epoch 000000052] loss=12038.008405413 | avg=17.186631066 | rare=0.120208217
[epoch 000000053] loss=12367.385253906 | avg=17.003675733 | rare=0.123503814
[epoch 000000054] loss=12262.767299107 | avg=16.855667046 | rare=0.122459118
[epoch 000000055] loss=12675.981305804 | avg=16.663095883 | rare=0.126593183
[epoch 000000056] loss=12209.526297433 | avg=16.449323518 | rare=0.121930771
[epoch 000000057] loss=12216.965332031 | avg=16.033698150 | rare=0.122009313
[epoch 000000058] loss=11853.512834821 | avg=15.820652962 | rare=0.118376921
[epoch 000000059] loss=11732.597202846 | avg=15.560455118 | rare=0.117170367
[epoch 000000060] loss=11440.616001674 | avg=15.587434769 | rare=0.114250287
[epoch 000000061] loss=11787.755371094 | avg=15.479278428 | rare=0.117722760
[epoch 000000062] loss=12214.738141741 | avg=15.186356817 | rare=0.121995516
[epoch 000000063] loss=12408.182582310 | avg=14.994909491 | rare=0.123931878
[epoch 000000064] loss=12642.011335100 | avg=14.876690865 | rare=0.126271348
[epoch 000000065] loss=12713.372488839 | avg=14.741303308 | rare=0.126986313
[epoch 000000066] loss=12137.056501116 | avg=14.519890104 | rare=0.121225366
[epoch 000000067] loss=12598.472063337 | avg=14.333335059 | rare=0.125841386
[epoch 000000068] loss=12438.748674665 | avg=14.131918090 | rare=0.124246168
[epoch 000000069] loss=12313.242606027 | avg=14.132482120 | rare=0.122991102
[epoch 000000070] loss=11803.413783482 | avg=14.103490761 | rare=0.117893105
[epoch 000000071] loss=11729.704345703 | avg=14.135102545 | rare=0.117155690
[epoch 000000072] loss=11463.809082031 | avg=14.047844682 | rare=0.114497613
[epoch 000000073] loss=11296.796630859 | avg=13.930208615 | rare=0.112828663
[epoch 000000074] loss=11215.901646205 | avg=13.857436657 | rare=0.112020443
[epoch 000000075] loss=10846.116803850 | avg=13.798075472 | rare=0.108323187
[epoch 000000076] loss=10989.485909598 | avg=13.724060944 | rare=0.109757618
[epoch 000000077] loss=11428.642752511 | avg=13.571694102 | rare=0.114150708
[epoch 000000078] loss=11725.020089286 | avg=13.451084954 | rare=0.117115688
[epoch 000000079] loss=11743.248814174 | avg=13.424435547 | rare=0.117298243
[epoch 000000080] loss=11563.520019531 | avg=13.235508374 | rare=0.115502847
[epoch 000000081] loss=11676.541538783 | avg=13.229484762 | rare=0.116633122
[epoch 000000082] loss=11623.711809431 | avg=13.084461689 | rare=0.116106272
[epoch 000000083] loss=11619.864013672 | avg=12.975162302 | rare=0.116068888
[epoch 000000084] loss=11456.047572545 | avg=12.897631032 | rare=0.114431499
[epoch 000000085] loss=11565.063755580 | avg=12.850708757 | rare=0.115522130
[epoch 000000086] loss=11393.361502511 | avg=12.774314199 | rare=0.113805871
[epoch 000000087] loss=11298.877894810 | avg=12.664260251 | rare=0.112862136
[epoch 000000088] loss=11285.697893415 | avg=12.595356941 | rare=0.112731025
[epoch 000000089] loss=11432.754813058 | avg=12.592360088 | rare=0.114201625
[epoch 000000090] loss=11316.797712054 | avg=12.500180721 | rare=0.113042975
[epoch 000000091] loss=10964.934500558 | avg=12.504595416 | rare=0.109524299
[epoch 000000092] loss=10857.216866629 | avg=12.411810330 | rare=0.108448050
[epoch 000000093] loss=10434.863420759 | avg=12.434290545 | rare=0.104224291
[epoch 000000094] loss=10022.932896205 | avg=12.451965673 | rare=0.100104809
[epoch 000000095] loss=9784.094831194 | avg=12.379012176 | rare=0.097717157
[epoch 000000096] loss=10354.911690848 | avg=12.253632001 | rare=0.103426581
[epoch 000000097] loss=10496.204764230 | avg=12.208118643 | rare=0.104839967
[epoch 000000098] loss=10450.918596540 | avg=12.169867788 | rare=0.104387488
[epoch 000000099] loss=10456.965297154 | avg=12.069069999 | rare=0.104448963
[epoch 000000100] loss=10411.024588449 | avg=11.998802049 | rare=0.103990259
[epoch 000000101] loss=10982.672746931 | avg=11.874713217 | rare=0.109707978
[epoch 000000102] loss=11076.072893415 | avg=11.750660624 | rare=0.110643222
[epoch 000000103] loss=10768.128731864 | avg=11.577982562 | rare=0.107565505
[epoch 000000104] loss=11067.974400112 | avg=11.508223329 | rare=0.110564662
[epoch 000000105] loss=11203.269531250 | avg=11.306452683 | rare=0.111919631
[epoch 000000106] loss=11621.970145089 | avg=11.069242886 | rare=0.116109008
[epoch 000000107] loss=11900.348423549 | avg=10.791471549 | rare=0.118895570
[epoch 000000108] loss=12859.879952567 | avg=10.450279713 | rare=0.128494299
[epoch 000000109] loss=12166.240652902 | avg=10.245178904 | rare=0.121559957
[epoch 000000110] loss=11613.931222098 | avg=10.063558919 | rare=0.116038675
[epoch 000000111] loss=11376.176339286 | avg=9.966916221 | rare=0.113662095
[epoch 000000112] loss=11535.929059710 | avg=9.770879337 | rare=0.115261582
[epoch 000000113] loss=10743.435651507 | avg=9.693350077 | rare=0.107337424
[epoch 000000114] loss=10968.357631138 | avg=9.595543385 | rare=0.109587620
[epoch 000000115] loss=11217.642020089 | avg=9.439083406 | rare=0.112082030
[epoch 000000116] loss=10685.985735212 | avg=9.334713970 | rare=0.106766510
[epoch 000000117] loss=10433.745814732 | avg=9.258017063 | rare=0.104244877
[epoch 000000118] loss=9941.445172991 | avg=9.274592672 | rare=0.099321706
[epoch 000000119] loss=10187.038853237 | avg=9.269657816 | rare=0.101777691
[epoch 000000120] loss=10147.323486328 | avg=9.136829649 | rare=0.101381868
[epoch 000000121] loss=9695.811174665 | avg=9.145080635 | rare=0.096866661
[epoch 000000122] loss=9741.774658203 | avg=9.018464667 | rare=0.097327562
[epoch 000000123] loss=9422.170793806 | avg=9.037501199 | rare=0.094131333
[epoch 000000124] loss=9011.906215123 | avg=9.013639620 | rare=0.090028926
[epoch 000000125] loss=9053.448800223 | avg=9.001597677 | rare=0.090444472
[epoch 000000126] loss=9081.534563337 | avg=8.939966066 | rare=0.090725947
[epoch 000000127] loss=8659.302315848 | avg=8.917026111 | rare=0.086503854
[epoch 000000128] loss=8620.637834821 | avg=8.929215908 | rare=0.086117085
[epoch 000000129] loss=8296.862304688 | avg=8.966391632 | rare=0.082878959
[epoch 000000130] loss=8802.470005580 | avg=8.883167267 | rare=0.087935870
[epoch 000000131] loss=9136.930664062 | avg=8.786292859 | rare=0.091281443
[epoch 000000132] loss=8543.212681362 | avg=8.809088298 | rare=0.085344037
[epoch 000000133] loss=8550.795375279 | avg=8.867494651 | rare=0.085419279
[epoch 000000134] loss=8551.718784877 | avg=8.839167629 | rare=0.085428795
[epoch 000000135] loss=8791.417201451 | avg=8.849405766 | rare=0.087825677
[epoch 000000136] loss=8830.104457310 | avg=8.812802621 | rare=0.088212916
[epoch 000000137] loss=8533.028878348 | avg=8.841584308 | rare=0.085241873
[epoch 000000138] loss=8444.851457868 | avg=8.816204888 | rare=0.084360353
[epoch 000000139] loss=8121.880231585 | avg=8.819747312 | rare=0.081130606
[epoch 000000140] loss=7987.992466518 | avg=8.838802065 | rare=0.079791535
[epoch 000000141] loss=7717.096261161 | avg=8.777584076 | rare=0.077083187
[epoch 000000142] loss=7462.068446568 | avg=8.807198559 | rare=0.074532613
[epoch 000000143] loss=7469.807250977 | avg=8.846123014 | rare=0.074609610
[epoch 000000144] loss=7396.993896484 | avg=8.823846681 | rare=0.073881700
[epoch 000000145] loss=7343.664411272 | avg=8.811776911 | rare=0.073348525
[epoch 000000146] loss=7353.914027623 | avg=8.830485344 | rare=0.073450836
[epoch 000000147] loss=7488.128941127 | avg=8.804437569 | rare=0.074793245
[epoch 000000148] loss=7333.556152344 | avg=8.776684761 | rare=0.073247795
[epoch 000000149] loss=7143.078055246 | avg=8.832981621 | rare=0.071342450
[epoch 000000150] loss=7408.432303292 | avg=8.801346438 | rare=0.073996311
[epoch 000000151] loss=7397.079903739 | avg=8.790191105 | rare=0.073882898
[epoch 000000152] loss=7097.529837472 | avg=8.766972201 | rare=0.070887629
[epoch 000000153] loss=7076.536376953 | avg=8.748734747 | rare=0.070677878
[epoch 000000154] loss=6851.994384766 | avg=8.723033258 | rare=0.068432714
[epoch 000000155] loss=6781.331560407 | avg=8.707288674 | rare=0.067726242
[epoch 000000156] loss=6804.036725725 | avg=8.691261394 | rare=0.067953455
[epoch 000000157] loss=6890.885288783 | avg=8.629437685 | rare=0.068822560
[epoch 000000158] loss=6629.765590123 | avg=8.669257368 | rare=0.066210964
[epoch 000000159] loss=6646.620012556 | avg=8.662297453 | rare=0.066379578
[epoch 000000160] loss=6600.610665458 | avg=8.626443420 | rare=0.065919842
[epoch 000000161] loss=6544.148542132 | avg=8.620103223 | rare=0.065355284
[epoch 000000162] loss=6380.727852958 | avg=8.627451965 | rare=0.063721004
[epoch 000000163] loss=6402.790108817 | avg=8.572316544 | rare=0.063942178
[epoch 000000164] loss=6319.620291574 | avg=8.618456261 | rare=0.063110019
[epoch 000000165] loss=6439.288085938 | avg=8.605417252 | rare=0.064306827
[epoch 000000166] loss=6266.629778181 | avg=8.570641960 | rare=0.062580591
[epoch 000000167] loss=6209.808558873 | avg=8.561681475 | rare=0.062012468
[epoch 000000168] loss=6203.747907366 | avg=8.588243348 | rare=0.061951598
[epoch 000000169] loss=6158.005824498 | avg=8.530138424 | rare=0.061494757
[epoch 000000170] loss=5970.193464007 | avg=8.559597492 | rare=0.059616338
[epoch 000000171] loss=5881.961495536 | avg=8.560610260 | rare=0.058734008
[epoch 000000172] loss=5728.139404297 | avg=8.571590151 | rare=0.057195678
[epoch 000000173] loss=5919.989414760 | avg=8.529209580 | rare=0.059114603
[epoch 000000174] loss=5870.980154855 | avg=8.524564573 | rare=0.058624555
[epoch 000000175] loss=5838.935511998 | avg=8.484968594 | rare=0.058304506
[epoch 000000176] loss=5732.379778181 | avg=8.483817918 | rare=0.057238960
[epoch 000000177] loss=5799.689976283 | avg=8.504538877 | rare=0.057911855
[epoch 000000178] loss=6105.688005720 | avg=8.480644907 | rare=0.060972074
[epoch 000000179] loss=5864.977469308 | avg=8.484887668 | rare=0.058564927
[epoch 000000180] loss=5894.375313895 | avg=8.474645955 | rare=0.058859006
[epoch 000000181] loss=5967.543526786 | avg=8.454178435 | rare=0.059590894
[epoch 000000182] loss=6033.374755859 | avg=8.477682965 | rare=0.060248970
[epoch 000000183] loss=5808.648123605 | avg=8.464401109 | rare=0.058001837
[epoch 000000184] loss=5910.707066127 | avg=8.423712901 | rare=0.059022834
[epoch 000000185] loss=5882.605486189 | avg=8.437663351 | rare=0.058741679
[epoch 000000186] loss=5581.818655831 | avg=8.441715683 | rare=0.055733770
[epoch 000000187] loss=5722.578386579 | avg=8.416853768 | rare=0.057141615
[epoch 000000188] loss=5507.317470006 | avg=8.440424953 | rare=0.054988770
[epoch 000000189] loss=5515.426199777 | avg=8.415815728 | rare=0.055070105
[epoch 000000190] loss=5645.892124721 | avg=8.424017463 | rare=0.056374682
[epoch 000000191] loss=5634.973301479 | avg=8.371428353 | rare=0.056266018
[epoch 000000192] loss=5569.822335379 | avg=8.369311299 | rare=0.055614530
[epoch 000000193] loss=5463.591500419 | avg=8.406914336 | rare=0.054551846
[epoch 000000194] loss=5477.039097377 | avg=8.385917630 | rare=0.054686531
[epoch 000000195] loss=5583.384678432 | avg=8.358562538 | rare=0.055750261
[epoch 000000196] loss=5757.786411830 | avg=8.307581595 | rare=0.057494788
[epoch 000000197] loss=5494.062552316 | avg=8.338677951 | rare=0.054857239
[epoch 000000198] loss=5461.330897740 | avg=8.323010717 | rare=0.054530079
[epoch 000000199] loss=5535.638497489 | avg=8.307525907 | rare=0.055273310
[epoch 000000200] loss=5363.229439872 | avg=8.282002517 | rare=0.053549474
Accuracy: 81.02%  (CI 95%: [79.91%, 82.08%])
Robust Accuracy: 80.54928%  (CI 95%: [79.69304%, 81.56774%])
Conditional Robust Accuracy: 97.54291%  (CI 95%: [97.30639%, 97.81757%])
Accuracy: 80.58%  (CI 95%: [79.46%, 81.65%])
Robust Accuracy: 80.52803%  (CI 95%: [79.54479%, 81.47798%])
Conditional Robust Accuracy: 99.02465%  (CI 95%: [98.87546%, 99.18839%])
  --> Running Seed: 100

Training naive with adam...

Epochs:   0%|          | 0/200 [00:00<?, ?it/s]

[epoch 000000001] loss=178466.601562500 | avg=0.319753973 | rare=1.784662809
[epoch 000000002] loss=178522.145089286 | avg=0.320083375 | rare=1.785218264
[epoch 000000003] loss=174698.250000000 | avg=0.320029031 | rare=1.746979305
[epoch 000000004] loss=132026.258370536 | avg=0.419843682 | rare=1.320258379
[epoch 000000005] loss=89036.989955357 | avg=0.657948617 | rare=0.890363331
[epoch 000000006] loss=64029.650669643 | avg=0.883995043 | rare=0.640287668
[epoch 000000007] loss=49837.272321429 | avg=1.064969208 | rare=0.498362079
[epoch 000000008] loss=41000.588448661 | avg=1.196645405 | rare=0.409993917
[epoch 000000009] loss=34372.459123884 | avg=1.296075021 | rare=0.343711627
[epoch 000000010] loss=29568.429966518 | avg=1.363646865 | rare=0.295670667
[epoch 000000011] loss=25944.537388393 | avg=1.413815209 | rare=0.259431240
[epoch 000000012] loss=23013.518833705 | avg=1.453919590 | rare=0.230120648
[epoch 000000013] loss=20468.212053571 | avg=1.468572055 | rare=0.204667433
[epoch 000000014] loss=18547.513950893 | avg=1.497589793 | rare=0.185460163
[epoch 000000015] loss=16798.709542411 | avg=1.517880772 | rare=0.167971914
[epoch 000000016] loss=15607.512625558 | avg=1.540314615 | rare=0.156059724
[epoch 000000017] loss=14343.998535156 | avg=1.566727936 | rare=0.143424317
[epoch 000000018] loss=13261.330775670 | avg=1.581116463 | rare=0.132597495
[epoch 000000019] loss=12498.030343192 | avg=1.596798624 | rare=0.124964338
[epoch 000000020] loss=11787.260532924 | avg=1.613574905 | rare=0.117856468
[epoch 000000021] loss=11073.841169085 | avg=1.636206491 | rare=0.110722050
[epoch 000000022] loss=10377.694056920 | avg=1.659739239 | rare=0.103760344
[epoch 000000023] loss=9878.191127232 | avg=1.678276190 | rare=0.098765128
[epoch 000000024] loss=9288.713762556 | avg=1.699745502 | rare=0.092870141
[epoch 000000025] loss=8733.137311663 | avg=1.721784404 | rare=0.087314154
[epoch 000000026] loss=8273.755126953 | avg=1.742232995 | rare=0.082720129
[epoch 000000027] loss=8025.449148996 | avg=1.762077715 | rare=0.080236871
[epoch 000000028] loss=7687.596051897 | avg=1.778995999 | rare=0.076858170
[epoch 000000029] loss=7293.020751953 | avg=1.797474010 | rare=0.072912231
[epoch 000000030] loss=7041.928780692 | avg=1.823662332 | rare=0.070401051
[epoch 000000031] loss=6880.583147321 | avg=1.824072233 | rare=0.068787591
[epoch 000000032] loss=6676.693777902 | avg=1.843236574 | rare=0.066748506
[epoch 000000033] loss=6449.930524554 | avg=1.864074562 | rare=0.064480665
[epoch 000000034] loss=6237.549316406 | avg=1.862758100 | rare=0.062356865
[epoch 000000035] loss=6105.141636440 | avg=1.880584478 | rare=0.061032611
[epoch 000000036] loss=5961.193289621 | avg=1.871901376 | rare=0.059593213
[epoch 000000037] loss=5795.306884766 | avg=1.882773357 | rare=0.057934240
[epoch 000000038] loss=5617.240478516 | avg=1.886908991 | rare=0.056153536
[epoch 000000039] loss=5560.931535993 | avg=1.888765880 | rare=0.055590427
[epoch 000000040] loss=5382.841971261 | avg=1.892226551 | rare=0.053809497
[epoch 000000041] loss=5268.662039621 | avg=1.893097426 | rare=0.052667689
[epoch 000000042] loss=5151.550606864 | avg=1.901388586 | rare=0.051496491
[epoch 000000043] loss=5079.541573661 | avg=1.896752375 | rare=0.050776449
[epoch 000000044] loss=4935.262712751 | avg=1.886787065 | rare=0.049333759
[epoch 000000045] loss=4821.101702009 | avg=1.889084535 | rare=0.048192126
[epoch 000000046] loss=4716.588099888 | avg=1.889528768 | rare=0.047146985
[epoch 000000047] loss=4575.972342355 | avg=1.889833272 | rare=0.045740826
[epoch 000000048] loss=4501.138549805 | avg=1.881256648 | rare=0.044992573
[epoch 000000049] loss=4436.908394950 | avg=1.884983488 | rare=0.044350235
[epoch 000000050] loss=4352.269810268 | avg=1.890218752 | rare=0.043503795
[epoch 000000051] loss=4316.366420201 | avg=1.877375807 | rare=0.043144890
[epoch 000000052] loss=4268.737322126 | avg=1.874416471 | rare=0.042668628
[epoch 000000053] loss=4313.380998884 | avg=1.857922758 | rare=0.043115231
[epoch 000000054] loss=4394.793265206 | avg=1.832433803 | rare=0.043929608
[epoch 000000055] loss=4367.682843890 | avg=1.817520814 | rare=0.043658653
[epoch 000000056] loss=4368.125069754 | avg=1.808772760 | rare=0.043663164
[epoch 000000057] loss=4179.884817941 | avg=1.798537169 | rare=0.041780863
[epoch 000000058] loss=4089.316877093 | avg=1.791728548 | rare=0.040875252
[epoch 000000059] loss=4002.278407506 | avg=1.789657388 | rare=0.040004886
[epoch 000000060] loss=3869.857892718 | avg=1.786676211 | rare=0.038680712
[epoch 000000061] loss=3891.764840262 | avg=1.767383226 | rare=0.038899975
[epoch 000000062] loss=3827.822283064 | avg=1.759098479 | rare=0.038260631
[epoch 000000063] loss=3823.682878767 | avg=1.741684582 | rare=0.038219412
[epoch 000000064] loss=3685.385131836 | avg=1.738468187 | rare=0.036836466
[epoch 000000065] loss=3594.259783064 | avg=1.738103952 | rare=0.035925217
[epoch 000000066] loss=3476.078979492 | avg=1.723908637 | rare=0.034743551
[epoch 000000067] loss=3448.996320452 | avg=1.709260898 | rare=0.034472870
[epoch 000000068] loss=3461.398367746 | avg=1.702242936 | rare=0.034596961
[epoch 000000069] loss=3387.937500000 | avg=1.692179382 | rare=0.033862453
[epoch 000000070] loss=3342.289219448 | avg=1.688972056 | rare=0.033406003
[epoch 000000071] loss=3267.583025251 | avg=1.666000477 | rare=0.032659170
[epoch 000000072] loss=3219.355242048 | avg=1.654493621 | rare=0.032177008
[epoch 000000073] loss=3214.996407645 | avg=1.645369606 | rare=0.032133511
[epoch 000000074] loss=3236.004333496 | avg=1.622095363 | rare=0.032343822
[epoch 000000075] loss=3204.613560268 | avg=1.617625798 | rare=0.032029959
[epoch 000000076] loss=3190.812744141 | avg=1.597873441 | rare=0.031892149
[epoch 000000077] loss=3359.142403739 | avg=1.564131337 | rare=0.033575783
[epoch 000000078] loss=3279.769670759 | avg=1.542345813 | rare=0.032782273
[epoch 000000079] loss=3212.760541643 | avg=1.534786216 | rare=0.032112258
[epoch 000000080] loss=3154.170724051 | avg=1.535011598 | rare=0.031526357
[epoch 000000081] loss=3390.977068220 | avg=1.481628307 | rare=0.033894955
[epoch 000000082] loss=3254.558105469 | avg=1.464650665 | rare=0.032530934
[epoch 000000083] loss=3129.957624163 | avg=1.460669662 | rare=0.031284969
[epoch 000000084] loss=3173.289149693 | avg=1.434827191 | rare=0.031718543
[epoch 000000085] loss=3234.261335100 | avg=1.403836089 | rare=0.032328575
[epoch 000000086] loss=3193.841203962 | avg=1.389834276 | rare=0.031924514
[epoch 000000087] loss=3296.535042899 | avg=1.366911726 | rare=0.032951681
[epoch 000000088] loss=3351.697230748 | avg=1.326158728 | rare=0.033503711
[epoch 000000089] loss=3262.006661551 | avg=1.311304552 | rare=0.032606954
[epoch 000000090] loss=3167.665143694 | avg=1.303941454 | rare=0.031663612
[epoch 000000091] loss=3379.025652204 | avg=1.269238864 | rare=0.033777564
[epoch 000000092] loss=3579.401384626 | avg=1.230884322 | rare=0.035781705
[epoch 000000093] loss=3918.546962193 | avg=1.185873381 | rare=0.039173611
[epoch 000000094] loss=3742.699096680 | avg=1.168771608 | rare=0.037415303
[epoch 000000095] loss=3880.468279157 | avg=1.128427531 | rare=0.038793399
[epoch 000000096] loss=4241.178553990 | avg=1.073947889 | rare=0.042401046
[epoch 000000097] loss=4163.596086775 | avg=1.054712619 | rare=0.041625414
[epoch 000000098] loss=4236.343662807 | avg=1.013260462 | rare=0.042353304
[epoch 000000099] loss=4459.058768136 | avg=0.970763109 | rare=0.044580879
[epoch 000000100] loss=4545.889822824 | avg=0.940973133 | rare=0.045449487
[epoch 000000101] loss=4721.332624163 | avg=0.903278623 | rare=0.047204295
[epoch 000000102] loss=4832.315150670 | avg=0.873064331 | rare=0.048314421
[epoch 000000103] loss=4581.217006138 | avg=0.858037127 | rare=0.045803589
[epoch 000000104] loss=4930.936907087 | avg=0.817628230 | rare=0.049301193
[epoch 000000105] loss=5414.943359375 | avg=0.781013416 | rare=0.054141623
[epoch 000000106] loss=5281.677455357 | avg=0.758052541 | rare=0.052809194
[epoch 000000107] loss=5201.967878069 | avg=0.735396734 | rare=0.052012325
[epoch 000000108] loss=5338.442034040 | avg=0.711121955 | rare=0.053377309
[epoch 000000109] loss=5252.221051897 | avg=0.695853582 | rare=0.052515252
[epoch 000000110] loss=5159.847760882 | avg=0.686625864 | rare=0.051591611
[epoch 000000111] loss=5142.101335798 | avg=0.662184209 | rare=0.051414392
[epoch 000000112] loss=5064.655953544 | avg=0.654474986 | rare=0.050640015
[epoch 000000113] loss=4912.015921456 | avg=0.646942403 | rare=0.049113689
[epoch 000000114] loss=4695.243756975 | avg=0.643392584 | rare=0.046946004
[epoch 000000115] loss=4739.976858956 | avg=0.625786304 | rare=0.047393510
[epoch 000000116] loss=4519.081996373 | avg=0.633618380 | rare=0.045184484
[epoch 000000117] loss=4461.373465402 | avg=0.622618109 | rare=0.044607509
[epoch 000000118] loss=4380.349434989 | avg=0.621807375 | rare=0.043797276
[epoch 000000119] loss=4160.765956334 | avg=0.625583380 | rare=0.041601404
[epoch 000000120] loss=4134.484130859 | avg=0.614059819 | rare=0.041338701
[epoch 000000121] loss=3943.875627790 | avg=0.626522754 | rare=0.039432491
[epoch 000000122] loss=3928.907836914 | avg=0.609914820 | rare=0.039282980
[epoch 000000123] loss=3809.963082450 | avg=0.623991179 | rare=0.038093390
[epoch 000000124] loss=3733.919869559 | avg=0.615654903 | rare=0.037333042
[epoch 000000125] loss=3690.687691825 | avg=0.612953940 | rare=0.036900747
[epoch 000000126] loss=3426.485264369 | avg=0.628240968 | rare=0.034258570
[epoch 000000127] loss=3543.755998884 | avg=0.610770489 | rare=0.035431453
[epoch 000000128] loss=3368.182355608 | avg=0.614466067 | rare=0.033675679
[epoch 000000129] loss=3255.593540737 | avg=0.617338768 | rare=0.032549762
[epoch 000000130] loss=3138.379429408 | avg=0.622423926 | rare=0.031377570
[epoch 000000131] loss=3022.964791434 | avg=0.632406345 | rare=0.030223324
[epoch 000000132] loss=2869.293579102 | avg=0.634468798 | rare=0.028686590
[epoch 000000133] loss=2625.235613142 | avg=0.649114324 | rare=0.026245865
[epoch 000000134] loss=2588.990801130 | avg=0.652544562 | rare=0.025883383
[epoch 000000135] loss=2569.245221819 | avg=0.641567213 | rare=0.025686037
[epoch 000000136] loss=2398.145961217 | avg=0.664096428 | rare=0.023974819
[epoch 000000137] loss=2460.503548758 | avg=0.642202624 | rare=0.024598613
[epoch 000000138] loss=2311.292210170 | avg=0.656217711 | rare=0.023106360
[epoch 000000139] loss=2313.909955706 | avg=0.649777200 | rare=0.023132601
[epoch 000000140] loss=2444.172284807 | avg=0.635599294 | rare=0.024435367
[epoch 000000141] loss=2296.647678920 | avg=0.642416937 | rare=0.022960053
[epoch 000000142] loss=2310.028974261 | avg=0.638354970 | rare=0.023093906
[epoch 000000143] loss=2417.393519810 | avg=0.624617662 | rare=0.024167689
[epoch 000000144] loss=2163.664925711 | avg=0.636537267 | rare=0.021630284
[epoch 000000145] loss=2289.850725446 | avg=0.624853722 | rare=0.022892259
[epoch 000000146] loss=2208.113176618 | avg=0.622640026 | rare=0.022074905
[epoch 000000147] loss=2315.185250419 | avg=0.614869612 | rare=0.023145704
[epoch 000000148] loss=2274.453674316 | avg=0.609062237 | rare=0.022738446
[epoch 000000149] loss=2203.017464774 | avg=0.603960612 | rare=0.022024135
[epoch 000000150] loss=2230.626194545 | avg=0.608810131 | rare=0.022300174
[epoch 000000151] loss=2270.229692732 | avg=0.593370842 | rare=0.022696363
[epoch 000000152] loss=2093.009486607 | avg=0.609962987 | rare=0.020923996
[epoch 000000153] loss=2298.976902553 | avg=0.588909579 | rare=0.022983880
[epoch 000000154] loss=2067.532287598 | avg=0.599074802 | rare=0.020669332
[epoch 000000155] loss=2179.626482282 | avg=0.589903827 | rare=0.021790365
[epoch 000000156] loss=2187.257638114 | avg=0.583779705 | rare=0.021866739
[epoch 000000157] loss=2067.393327985 | avg=0.589147589 | rare=0.020668041
[epoch 000000158] loss=2059.088213239 | avg=0.586568641 | rare=0.020585016
[epoch 000000159] loss=2007.696437291 | avg=0.591909179 | rare=0.020071045
[epoch 000000160] loss=2162.199340820 | avg=0.577658870 | rare=0.021616217
[epoch 000000161] loss=1986.513636998 | avg=0.585092553 | rare=0.019859285
[epoch 000000162] loss=2029.541887556 | avg=0.575492672 | rare=0.020289664
[epoch 000000163] loss=1972.534057617 | avg=0.577077759 | rare=0.019719570
[epoch 000000164] loss=1949.986790248 | avg=0.578320742 | rare=0.019494084
[epoch 000000165] loss=1953.387756348 | avg=0.572948494 | rare=0.019528148
[epoch 000000166] loss=1929.116367885 | avg=0.575463295 | rare=0.019285409
[epoch 000000167] loss=1933.341125488 | avg=0.567308888 | rare=0.019327739
[epoch 000000168] loss=1841.502476283 | avg=0.580297487 | rare=0.018409221
[epoch 000000169] loss=1916.790562221 | avg=0.561390483 | rare=0.019162292
[epoch 000000170] loss=1769.428248814 | avg=0.584580717 | rare=0.017688437
[epoch 000000171] loss=1880.298139300 | avg=0.563375473 | rare=0.018797347
[epoch 000000172] loss=1775.884268624 | avg=0.571829251 | rare=0.017753124
[epoch 000000173] loss=1762.613647461 | avg=0.566352295 | rare=0.017620473
[epoch 000000174] loss=1774.878914969 | avg=0.562131320 | rare=0.017743168
[epoch 000000175] loss=1711.551592146 | avg=0.563763806 | rare=0.017109878
[epoch 000000176] loss=1800.261919294 | avg=0.554045000 | rare=0.017997079
[epoch 000000177] loss=1730.311070033 | avg=0.558770963 | rare=0.017297523
[epoch 000000178] loss=1698.439287458 | avg=0.560795490 | rare=0.016978785
[epoch 000000179] loss=1696.684613909 | avg=0.557513735 | rare=0.016961271
[epoch 000000180] loss=1798.830967494 | avg=0.547343597 | rare=0.017982836
[epoch 000000181] loss=1625.125296456 | avg=0.552116579 | rare=0.016245732
[epoch 000000182] loss=1729.500924247 | avg=0.545521129 | rare=0.017289554
[epoch 000000183] loss=1689.415352958 | avg=0.549372839 | rare=0.016888660
[epoch 000000184] loss=1742.144182478 | avg=0.538918849 | rare=0.017416053
[epoch 000000185] loss=1675.541320801 | avg=0.540781496 | rare=0.016750005
[epoch 000000186] loss=1652.976867676 | avg=0.542293542 | rare=0.016524346
[epoch 000000187] loss=1643.359226772 | avg=0.538911828 | rare=0.016428203
[epoch 000000188] loss=1576.846670968 | avg=0.541655575 | rare=0.015763050
[epoch 000000189] loss=1782.935285296 | avg=0.526819314 | rare=0.017824084
[epoch 000000190] loss=1553.513724191 | avg=0.536841967 | rare=0.015529769
[epoch 000000191] loss=1676.864318848 | avg=0.525387479 | rare=0.016763389
[epoch 000000192] loss=1681.297930036 | avg=0.521256683 | rare=0.016807767
[epoch 000000193] loss=1679.519566127 | avg=0.517645206 | rare=0.016790019
[epoch 000000194] loss=1645.056457520 | avg=0.520319758 | rare=0.016445361
[epoch 000000195] loss=1681.394182478 | avg=0.512691404 | rare=0.016808815
[epoch 000000196] loss=1504.279654367 | avg=0.521359178 | rare=0.015037583
[epoch 000000197] loss=1615.847089495 | avg=0.509474780 | rare=0.016153376
[epoch 000000198] loss=1613.982596261 | avg=0.510937284 | rare=0.016134717
[epoch 000000199] loss=1566.765563965 | avg=0.507375196 | rare=0.015662582
[epoch 000000200] loss=1557.937037877 | avg=0.511562965 | rare=0.015574255

Training safe with adam...

Epochs:   0%|          | 0/200 [00:00<?, ?it/s]

[epoch 000000001] loss=142.039022991 | avg=50.119557244 | rare=0.000919195
[epoch 000000002] loss=179.133234024 | avg=49.917263848 | rare=0.001292160
[epoch 000000003] loss=158.249130522 | avg=49.450024741 | rare=0.001087991
[epoch 000000004] loss=296.055175236 | avg=49.075668335 | rare=0.002469795
[epoch 000000005] loss=297.425468172 | avg=48.682195118 | rare=0.002487433
[epoch 000000006] loss=247.133542197 | avg=48.134775707 | rare=0.001989988
[epoch 000000007] loss=270.617097037 | avg=47.676748276 | rare=0.002229403
[epoch 000000008] loss=362.404348101 | avg=47.221567699 | rare=0.003151828
[epoch 000000009] loss=230.662711825 | avg=46.903248378 | rare=0.001837595
[epoch 000000010] loss=276.112814767 | avg=46.653613227 | rare=0.002294592
[epoch 000000011] loss=171.107992990 | avg=46.260524477 | rare=0.001248475
[epoch 000000012] loss=111.109915597 | avg=46.020042419 | rare=0.000650899
[epoch 000000013] loss=279.457045691 | avg=45.558731352 | rare=0.002338983
[epoch 000000014] loss=184.287366322 | avg=45.467354366 | rare=0.001388200
[epoch 000000015] loss=237.827063424 | avg=45.102705547 | rare=0.001927244
[epoch 000000016] loss=244.615014757 | avg=44.674342292 | rare=0.001999407
[epoch 000000017] loss=289.531881605 | avg=44.364768982 | rare=0.002451671
[epoch 000000018] loss=399.604445321 | avg=43.896230425 | rare=0.003557082
[epoch 000000019] loss=466.798994882 | avg=43.361568996 | rare=0.004234374
[epoch 000000020] loss=537.176931654 | avg=42.755270004 | rare=0.004944217
[epoch 000000021] loss=465.678860801 | avg=42.134933744 | rare=0.004235439
[epoch 000000022] loss=680.937694550 | avg=41.469401768 | rare=0.006394683
[epoch 000000023] loss=1290.346972602 | avg=40.649029596 | rare=0.012496980
[epoch 000000024] loss=2298.464072091 | avg=39.608189174 | rare=0.022588559
[epoch 000000025] loss=3258.622217451 | avg=38.247171129 | rare=0.032203751
[epoch 000000026] loss=3863.571716309 | avg=36.560866220 | rare=0.038270108
[epoch 000000027] loss=5374.722891671 | avg=35.243665831 | rare=0.053394792
[epoch 000000028] loss=5546.583827427 | avg=33.698296956 | rare=0.055128855
[epoch 000000029] loss=7531.924909319 | avg=32.069589206 | rare=0.074998553
[epoch 000000030] loss=9578.241768973 | avg=30.348175185 | rare=0.095478934
[epoch 000000031] loss=11366.334402902 | avg=28.564972878 | rare=0.113377694
[epoch 000000032] loss=11258.342808315 | avg=26.908617701 | rare=0.112314341
[epoch 000000033] loss=14490.694475446 | avg=25.419025285 | rare=0.144652756
[epoch 000000034] loss=15454.622174944 | avg=24.200560434 | rare=0.154304216
[epoch 000000035] loss=19369.097167969 | avg=23.302453177 | rare=0.193457946
[epoch 000000036] loss=18359.283272879 | avg=22.557201658 | rare=0.183367261
[epoch 000000037] loss=18934.653599330 | avg=21.951719420 | rare=0.189127019
[epoch 000000038] loss=17902.563337054 | avg=21.160133634 | rare=0.178814032
[epoch 000000039] loss=17291.603236607 | avg=20.618286542 | rare=0.172709847
[epoch 000000040] loss=16226.819545201 | avg=20.227372578 | rare=0.162065918
[epoch 000000041] loss=16228.781529018 | avg=19.749403409 | rare=0.162090321
[epoch 000000042] loss=15887.363699777 | avg=19.406694004 | rare=0.158679570
[epoch 000000043] loss=15985.180873326 | avg=18.919353758 | rare=0.159662614
[epoch 000000044] loss=14505.230398996 | avg=18.654393196 | rare=0.144865760
[epoch 000000045] loss=14055.542480469 | avg=18.499585560 | rare=0.140370427
[epoch 000000046] loss=13353.870256696 | avg=18.318320138 | rare=0.133355519
[epoch 000000047] loss=12978.420584542 | avg=18.175193242 | rare=0.129602453
[epoch 000000048] loss=12365.291782924 | avg=17.905921732 | rare=0.123473857
[epoch 000000049] loss=11901.801199777 | avg=17.764327117 | rare=0.118840369
[epoch 000000050] loss=11460.280343192 | avg=17.675035340 | rare=0.114426051
[epoch 000000051] loss=11277.760672433 | avg=17.419845785 | rare=0.112603410
[epoch 000000052] loss=11298.033900670 | avg=17.215422630 | rare=0.112808183
[epoch 000000053] loss=11417.538434710 | avg=16.911778246 | rare=0.114006265
[epoch 000000054] loss=11926.203194754 | avg=16.592275688 | rare=0.119096110
[epoch 000000055] loss=11961.396484375 | avg=16.310209547 | rare=0.119450863
[epoch 000000056] loss=12022.565255301 | avg=15.967751435 | rare=0.120065974
[epoch 000000057] loss=12311.611572266 | avg=15.601846491 | rare=0.122960098
[epoch 000000058] loss=12121.810163225 | avg=15.480160509 | rare=0.121063298
[epoch 000000059] loss=12102.796561105 | avg=15.297279562 | rare=0.120874993
[epoch 000000060] loss=11843.071829660 | avg=15.079809938 | rare=0.118279920
[epoch 000000061] loss=11988.157296317 | avg=14.932423592 | rare=0.119732249
[epoch 000000062] loss=10962.338623047 | avg=14.846052510 | rare=0.109474925
[epoch 000000063] loss=11145.485456194 | avg=14.700217928 | rare=0.111307853
[epoch 000000064] loss=11135.634347098 | avg=14.689747674 | rare=0.111209447
[epoch 000000065] loss=10952.354910714 | avg=14.505847727 | rare=0.109378488
[epoch 000000066] loss=10804.625732422 | avg=14.408090251 | rare=0.107902176
[epoch 000000067] loss=11165.872174944 | avg=14.313640935 | rare=0.111515586
[epoch 000000068] loss=11064.795619420 | avg=14.267536231 | rare=0.110505281
[epoch 000000069] loss=10959.906598772 | avg=14.155620166 | rare=0.109457510
[epoch 000000070] loss=10916.045445033 | avg=14.108511993 | rare=0.109019370
[epoch 000000071] loss=11238.625104632 | avg=13.942630223 | rare=0.112246825
[epoch 000000072] loss=11289.668666295 | avg=13.858612606 | rare=0.112758100
[epoch 000000073] loss=11319.770926339 | avg=13.770385810 | rare=0.113060007
[epoch 000000074] loss=11632.737339565 | avg=13.700029850 | rare=0.116190373
[epoch 000000075] loss=12035.056431362 | avg=13.471559865 | rare=0.120215850
[epoch 000000076] loss=12190.155831473 | avg=13.361935888 | rare=0.121767938
[epoch 000000077] loss=12669.686593192 | avg=13.188578674 | rare=0.126564981
[epoch 000000078] loss=12982.441057478 | avg=13.026039873 | rare=0.129694149
[epoch 000000079] loss=13083.110212054 | avg=12.902018275 | rare=0.130702081
[epoch 000000080] loss=13090.702566964 | avg=12.956658636 | rare=0.130777460
[epoch 000000081] loss=13352.789620536 | avg=12.797033651 | rare=0.133399925
[epoch 000000082] loss=12689.397949219 | avg=12.765473775 | rare=0.126766326
[epoch 000000083] loss=12579.013113839 | avg=12.734343937 | rare=0.125662788
[epoch 000000084] loss=12395.716692243 | avg=12.674288750 | rare=0.123830427
[epoch 000000085] loss=12173.717215402 | avg=12.559356553 | rare=0.121611579
[epoch 000000086] loss=11823.175118583 | avg=12.591897488 | rare=0.118105834
[epoch 000000087] loss=11357.337472098 | avg=12.573598453 | rare=0.113447641
[epoch 000000088] loss=11314.196358817 | avg=12.549757140 | rare=0.113016466
[epoch 000000089] loss=11021.020472935 | avg=12.567534719 | rare=0.110084528
[epoch 000000090] loss=10566.102190290 | avg=12.563439165 | rare=0.105535387
[epoch 000000091] loss=10325.802594866 | avg=12.547093936 | rare=0.103132556
[epoch 000000092] loss=10136.917933873 | avg=12.517651899 | rare=0.101244002
[epoch 000000093] loss=10491.228201730 | avg=12.353630202 | rare=0.104788746
[epoch 000000094] loss=10250.518275670 | avg=12.309537683 | rare=0.102382087
[epoch 000000095] loss=10583.211739676 | avg=12.203868253 | rare=0.105710078
[epoch 000000096] loss=10443.073590960 | avg=12.081220627 | rare=0.104309923
[epoch 000000097] loss=10864.296770368 | avg=11.967020103 | rare=0.108523296
[epoch 000000098] loss=10640.413922991 | avg=11.920470987 | rare=0.106284937
[epoch 000000099] loss=10678.866594587 | avg=11.840562889 | rare=0.106670261
[epoch 000000100] loss=10497.167375837 | avg=11.662529673 | rare=0.104855047
[epoch 000000101] loss=10875.782505580 | avg=11.483945370 | rare=0.108642986
[epoch 000000102] loss=11306.596784319 | avg=11.215864795 | rare=0.112953810
[epoch 000000103] loss=11863.636648996 | avg=10.936927250 | rare=0.118526997
[epoch 000000104] loss=11823.779227121 | avg=10.597701481 | rare=0.118131815
[epoch 000000105] loss=11396.208844866 | avg=10.521623816 | rare=0.113856871
[epoch 000000106] loss=10981.868791853 | avg=10.431250027 | rare=0.109714375
[epoch 000000107] loss=11083.148995536 | avg=10.307575703 | rare=0.110728416
[epoch 000000108] loss=10694.591413225 | avg=10.199978624 | rare=0.106843914
[epoch 000000109] loss=10487.258754185 | avg=10.199606964 | rare=0.104770591
[epoch 000000110] loss=10018.526611328 | avg=10.065794604 | rare=0.100084608
[epoch 000000111] loss=10224.046142578 | avg=9.877105100 | rare=0.102141692
[epoch 000000112] loss=10416.758440290 | avg=9.782696724 | rare=0.104069757
[epoch 000000113] loss=9951.449183873 | avg=9.768484729 | rare=0.099416807
[epoch 000000114] loss=9478.612932478 | avg=9.685834817 | rare=0.094689272
[epoch 000000115] loss=9652.059116908 | avg=9.511558192 | rare=0.096425478
[epoch 000000116] loss=9202.812395368 | avg=9.395260947 | rare=0.091934172
[epoch 000000117] loss=9216.080705915 | avg=9.303924765 | rare=0.092067767
[epoch 000000118] loss=8940.599958147 | avg=9.292550768 | rare=0.089313073
[epoch 000000119] loss=8897.462995257 | avg=9.242170402 | rare=0.088882208
[epoch 000000120] loss=8787.231480190 | avg=9.183816399 | rare=0.087780476
[epoch 000000121] loss=8616.510637556 | avg=9.183812073 | rare=0.086073268
[epoch 000000122] loss=8358.215855190 | avg=9.104583263 | rare=0.083491113
[epoch 000000123] loss=7781.331054688 | avg=9.065563679 | rare=0.077722655
[epoch 000000124] loss=7731.947405134 | avg=9.074339730 | rare=0.077228729
[epoch 000000125] loss=7439.441301618 | avg=9.083256108 | rare=0.074303581
[epoch 000000126] loss=7345.254813058 | avg=9.057601520 | rare=0.073361971
[epoch 000000127] loss=7066.288085938 | avg=9.035501957 | rare=0.070572526
[epoch 000000128] loss=7053.068132673 | avg=9.008034842 | rare=0.070440600
[epoch 000000129] loss=8062.486240932 | avg=8.928322588 | rare=0.080535578
[epoch 000000130] loss=7788.451799665 | avg=8.840734346 | rare=0.077796111
[epoch 000000131] loss=7804.251081194 | avg=8.855369840 | rare=0.077953957
[epoch 000000132] loss=7704.254917690 | avg=8.749624729 | rare=0.076955053
[epoch 000000133] loss=7304.242292132 | avg=8.730934347 | rare=0.072955113
[epoch 000000134] loss=7146.254359654 | avg=8.673668691 | rare=0.071375807
[epoch 000000135] loss=7618.404471261 | avg=8.685436896 | rare=0.076097190
[epoch 000000136] loss=7406.634940011 | avg=8.710714817 | rare=0.073979242
[epoch 000000137] loss=7367.342110770 | avg=8.675166845 | rare=0.073586670
[epoch 000000138] loss=7174.704031808 | avg=8.733634676 | rare=0.071659704
[epoch 000000139] loss=7209.913434710 | avg=8.698215927 | rare=0.072012152
[epoch 000000140] loss=6985.165876116 | avg=8.675542048 | rare=0.069764904
[epoch 000000141] loss=6841.193254743 | avg=8.688443422 | rare=0.068325047
[epoch 000000142] loss=6841.895769392 | avg=8.674785818 | rare=0.068332210
[epoch 000000143] loss=6600.181291853 | avg=8.622571196 | rare=0.065915587
[epoch 000000144] loss=6204.709559849 | avg=8.638138737 | rare=0.061960715
[epoch 000000145] loss=6369.093366350 | avg=8.616020679 | rare=0.063604773
[epoch 000000146] loss=6440.070731027 | avg=8.600040095 | rare=0.064314706
[epoch 000000147] loss=6196.534737723 | avg=8.579140629 | rare=0.061879557
[epoch 000000148] loss=6391.642822266 | avg=8.578076363 | rare=0.063830648
[epoch 000000149] loss=6157.271222796 | avg=8.560694116 | rare=0.061487106
[epoch 000000150] loss=6031.847970145 | avg=8.543769973 | rare=0.060233042
[epoch 000000151] loss=5932.899414062 | avg=8.568204062 | rare=0.059243313
[epoch 000000152] loss=5983.429303850 | avg=8.602215733 | rare=0.059748272
[epoch 000000153] loss=6094.550676618 | avg=8.525497028 | rare=0.060860253
[epoch 000000154] loss=6022.051705497 | avg=8.518229042 | rare=0.060135334
[epoch 000000155] loss=5978.005702427 | avg=8.531465599 | rare=0.059694741
[epoch 000000156] loss=6192.017229353 | avg=8.478582723 | rare=0.061835386
[epoch 000000157] loss=6241.573957171 | avg=8.496449913 | rare=0.062330775
[epoch 000000158] loss=6379.429268973 | avg=8.475695644 | rare=0.063709536
[epoch 000000159] loss=6203.542288644 | avg=8.470384564 | rare=0.061950720
[epoch 000000160] loss=6168.292881557 | avg=8.483671631 | rare=0.061598091
[epoch 000000161] loss=6312.463466099 | avg=8.484599829 | rare=0.063039789
[epoch 000000162] loss=6162.467163086 | avg=8.468687500 | rare=0.061539984
[epoch 000000163] loss=6231.584542411 | avg=8.416567939 | rare=0.062231679
[epoch 000000164] loss=5950.109305246 | avg=8.468785967 | rare=0.059416405
[epoch 000000165] loss=5910.708461217 | avg=8.418415478 | rare=0.059022901
[epoch 000000166] loss=5854.258492606 | avg=8.460498197 | rare=0.058457980
[epoch 000000167] loss=5805.496459961 | avg=8.414484365 | rare=0.057970819
[epoch 000000168] loss=5736.786778041 | avg=8.470469611 | rare=0.057283163
[epoch 000000169] loss=5657.564697266 | avg=8.430596556 | rare=0.056491340
[epoch 000000170] loss=5538.888724191 | avg=8.409303972 | rare=0.055304795
[epoch 000000171] loss=5664.726492746 | avg=8.443172455 | rare=0.056562833
[epoch 000000172] loss=5715.704206194 | avg=8.438166823 | rare=0.057072661
[epoch 000000173] loss=5598.211233956 | avg=8.449317932 | rare=0.055897619
[epoch 000000174] loss=5386.351946150 | avg=8.452309711 | rare=0.053778996
[epoch 000000175] loss=5497.432965960 | avg=8.406773737 | rare=0.054890262
[epoch 000000176] loss=5381.014665876 | avg=8.438048192 | rare=0.053725766
[epoch 000000177] loss=5258.735961914 | avg=8.439033202 | rare=0.052502969
[epoch 000000178] loss=5442.369594029 | avg=8.377666405 | rare=0.054339919
[epoch 000000179] loss=5348.569562640 | avg=8.408672878 | rare=0.053401610
[epoch 000000180] loss=5385.696201869 | avg=8.415531363 | rare=0.053772806
[epoch 000000181] loss=5301.470947266 | avg=8.384825741 | rare=0.052930862
[epoch 000000182] loss=5292.973266602 | avg=8.426711593 | rare=0.052845465
[epoch 000000183] loss=5373.085867746 | avg=8.431798799 | rare=0.053646541
[epoch 000000184] loss=5522.325212751 | avg=8.401885339 | rare=0.055139233
[epoch 000000185] loss=5316.028669085 | avg=8.438178812 | rare=0.053075905
[epoch 000000186] loss=5384.252110073 | avg=8.401309899 | rare=0.053758508
[epoch 000000187] loss=5285.768519810 | avg=8.416211162 | rare=0.052773523
[epoch 000000188] loss=5271.557128906 | avg=8.369004999 | rare=0.052631882
[epoch 000000189] loss=5039.120797294 | avg=8.392555475 | rare=0.050307283
[epoch 000000190] loss=5048.254708426 | avg=8.403033631 | rare=0.050398517
[epoch 000000191] loss=5237.980486189 | avg=8.379774094 | rare=0.052296008
[epoch 000000192] loss=5141.193952288 | avg=8.378195899 | rare=0.051328158
[epoch 000000193] loss=5020.605712891 | avg=8.371291127 | rare=0.050122344
[epoch 000000194] loss=5080.340244838 | avg=8.379362243 | rare=0.050719608
[epoch 000000195] loss=4969.060442243 | avg=8.385494096 | rare=0.049606750
[epoch 000000196] loss=5142.141060965 | avg=8.378546919 | rare=0.051337626
[epoch 000000197] loss=5021.142177037 | avg=8.329114233 | rare=0.050128130
[epoch 000000198] loss=5050.803606306 | avg=8.400707211 | rare=0.050424029
[epoch 000000199] loss=5104.743774414 | avg=8.360441957 | rare=0.050963834
[epoch 000000200] loss=5139.244053432 | avg=8.356615714 | rare=0.051308874
Accuracy: 80.86%  (CI 95%: [79.74%, 81.92%])
Robust Accuracy: 80.59741%  (CI 95%: [79.75396%, 81.60575%])
Conditional Robust Accuracy: 97.47203%  (CI 95%: [97.21523%, 97.71570%])
Accuracy: 80.44%  (CI 95%: [79.32%, 81.51%])
Robust Accuracy: 80.25339%  (CI 95%: [79.27792%, 81.29147%])
Conditional Robust Accuracy: 98.97738%  (CI 95%: [98.80767%, 99.13477%])

Grid Search Complete!

In [ ]:
import numpy as np

# Automatically extract and sort learning rates descending (0.1 down to 1e-6)
lrs = sorted(list(final_results.keys()), reverse=True)
configs = [('naive', 'adam'), ('safe', 'adam')]

print("LaTeX Table Rows:\n")

for lr in lrs:
    # Format the learning rate beautifully for LaTeX (e.g., 0.1 -> 10^{-1})
    exponent = int(np.round(np.log10(lr)))
    row_string = f"$10^{{{exponent}}}$"

    for config in configs:
        # Extract the metrics for all 5 seeds and convert to percentages
        # Note: Using 'acc' instead of 'PA' based on your dictionary structure
        pa_scores = [res['acc'] * 100 for res in final_results[lr][config]]
        cra_scores = [res['CRA'] * 100 for res in final_results[lr][config]]

        # Calculate mean and standard deviation
        pa_mean, pa_std = np.mean(pa_scores), np.std(pa_scores)
        cra_mean, cra_std = np.mean(cra_scores), np.std(cra_scores)

        # Format the string: Mean (SD) / Mean (SD)
        cell_str = f"{pa_mean:.1f} ({pa_std:.1f}) / {cra_mean:.1f} ({cra_std:.1f})"

        # Apply LaTeX bolding if the configuration meets the success thresholds
        if pa_mean >= 80.0 and cra_mean >= 98.0:
            cell_str = f"\\textbf{{{cell_str}}}"

        # Append to the row string separated by the LaTeX column divider (&)
        row_string += f" & {cell_str}"

    # Cap off the row with the LaTeX line break (\\)
    row_string += " \\\\"

    print(row_string)

In [19]:
# ============================================================
# Safe-start criterion sweep for MAGIC (read-only: no training, no saving)
#   For each final-layer bias b: evaluate f(x0) = BCE and gamma * p(x0),
#   with p = _rare_event_margin_binary, on the full training set.
#   Paste as ONE new cell at the bottom, after pre_model and the data are loaded.
# ============================================================
import copy
import torch
import torch.nn as nn

# --- set these to the names used in your notebook ---
X_TRAIN   = X_train      # training features (the X you pass to train_all)
Y_TRAIN   = y_train      # training labels   (the y you pass to train_all)
PRE_MODEL = pre_model    # the pretrained (unsafe) model
GAMMA, SIGMA, J = 1e5, 2.0, 100          # same values as in the paper
BIASES = [None, 0, 5, 10, 15, 20, 25, 30,100,120,150,170,200]  # None = pretrained bias, unchanged (the unsafe start)
CHUNK = 1024

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

@torch.no_grad()
def evaluate_start(bias):
    model = copy.deepcopy(PRE_MODEL).to(device).eval()   # original model is untouched
    if bias is not None:
        model.fc_last.bias.fill_(bias)                    # same line as in joint_train

    bce = nn.BCEWithLogitsLoss(reduction="sum")
    torch.manual_seed(0)                                  # fixed noise, reproducible
    n = X_TRAIN.shape[0]
    f_sum = p_sum = 0.0
    for i in range(0, n, CHUNK):
        xb = X_TRAIN[i:i+CHUNK].to(device)
        yb = Y_TRAIN[i:i+CHUNK].to(device)
        logits = model(xb).squeeze(-1)
        f_sum += float(bce(logits, yb.squeeze(-1).float()))
        p_sum += float(_rare_event_margin_binary(model, xb, yb, sigma=SIGMA, J=J)) * xb.shape[0]
    return f_sum / n, p_sum / n

print(f"{'bias':>10} {'f(x0)':>10} {'p(x0)':>12} {'gamma*p(x0)':>14}  criterion (C=1)")
for b in BIASES:
    f0, p0 = evaluate_start(b)
    label = "pretrained" if b is None else f"{b}"
    ok = GAMMA * p0 <= f0
    print(f"{label:>10} {f0:10.4f} {p0:12.4g} {GAMMA*p0:14.4g}  {'SAFE' if ok else 'unsafe'}")

      bias      f(x0)        p(x0)    gamma*p(x0)  criterion (C=1)
pretrained     0.3194        1.786      1.786e+05  unsafe
         0     0.3697        1.779      1.779e+05  unsafe
         5     0.8901       0.5576      5.576e+04  unsafe
        10     2.2465       0.1034      1.034e+04  unsafe
        15     3.7979       0.0403           4030  unsafe
        20     5.4274      0.02057           2057  unsafe
        25     7.0901      0.01728           1728  unsafe
        30     8.7697      0.01414           1414  unsafe
       100    32.7416     0.002036          203.6  unsafe
       120    39.6525     0.002914          291.4  unsafe
       150    50.0565    0.0008977          89.77  unsafe
       170    57.0088    0.0004956          49.56  SAFE
       200    67.4525    0.0003745          37.45  SAFE